Made globals. Fixed UpdateGit and IsInstalledPackage.

diff --git a/bin/bashlib-dev b/bin/bashlib-dev
--- a/bin/bashlib-dev
+++ b/bin/bashlib-dev
@@ -248,7 +248,6 @@
         # </params>
 
         IsBool $2 &> /dev/null && bool_option_reinstall=true
-        IsInstalledPackage $1 && return 0
 
         # <remarks> Auto-update and auto-install selected packages </remarks>
         case "${str_package_manager}" in
@@ -282,7 +281,7 @@
                 ;;
 
             * )
-                echo -e "${str_fail}"
+                echo -e "${str_output_invalid_package_manager}"
                 return 1
                 ;;
         esac
@@ -302,22 +301,31 @@
         IsString $1 || return $?
 
         # <params>
-        local str_fail="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
+        local var_get_command=""
         # </params>
 
         # <remarks> Check if package is not installed </remarks>
         case "${str_package_manager}" in
             "apt" )
-                dpkg -s $1 &> /dev/null || InstallPackage $1 || return $?
+                var_get_command="dpkg -s $1" || return $?
                 ;;
 
             * )
-                echo -e "${str_fail}"
+                echo -e "${str_output_invalid_package_manager}"
                 return 1
                 ;;
         esac
 
-        return 0
+        declare -i int_delim=1
+
+        while true; do
+            local str_package=$( echo $1 | cut -d ' ' -f $int_delim )
+            IsString $str_package &> /dev/null || return 0
+            eval "${var_get_command}" &> /dev/null || break
+            (( int_delim++ ))
+        done
+
+        return 1
     }
 
     # <summary> Update GetInternetStatus </summary>
@@ -338,7 +346,6 @@
         # <params>
         local str_commands_to_execute=""
         local str_output="Uninstalling software packages..."
-        local str_fail="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
         # </params>
 
         # <remarks> Uninstall selected packages </remarks>
@@ -372,7 +379,7 @@
                 ;;
 
             * )
-                echo -e "${str_fail}"
+                echo -e "${str_output_invalid_package_manager}"
                 return 1
                 ;;
         esac
@@ -397,18 +404,20 @@
         # <summary> Update existing GitHub repository. </summary>
         if IsDir "$1$2"; then
             local var_command="git pull"
-
-            cd "$1$2" && StopEvalAfterThriceFail $( eval "${var_command}" ) &> /dev/null
-            return $?
+            cd "$1$2"
+            eval "${var_command}" &> /dev/null || return 1
+            return 0
 
         # <summary> Clone new GitHub repository. </summary>
         elif IsDir "$1$3"; then
             if ReadInput "Clone repo '$2'?"; then
                 local var_command="git clone https://github.com/$2"
-
-                cd "$1$3" && StopEvalAfterThriceFail $( eval "${var_command}" ) &> /dev/null
-                return $?
+                cd "$1$3"
+                eval "${var_command}" &> /dev/null || return 1
+                return 0
             fi
+
+            return 1
         else
             return 1
         fi
