Updating comments, undeclaring some variables.

diff --git a/bin/bashlib-files b/bin/bashlib-files
--- a/bin/bashlib-files
+++ b/bin/bashlib-files
@@ -21,12 +21,7 @@
     {
         IsFile $2 || return $?
         IsFile $1 || return $?
-
-        # <params>
-        local var_command='cmp -s $1 $2'
-        # </params>
-
-        eval "${var_command}" || return 1
+        [ cmp -s $1 $2 ] || return 1
         return 0
     }
 
@@ -70,12 +65,8 @@
             return 0
         }
 
-        # <params>
-        local str_output="Creating backup file...\t"
-        # </params>
-
         BackupFile_Main $1
-        PrintPassOrFail "${str_output}"
+        PrintPassOrFail "Creating backup file...\t"
         return "${int_exit_code}"
     }
 
@@ -86,13 +77,8 @@
         IsString $1 || return $?
         IsDir $1 &> /dev/null && return 0
 
-        # <params>
-        local str_fail="${var_prefix_fail} Could not create directory '$1'."
-        local var_command='mkdir -p $1 &> /dev/null'
-        # </params>
-
-        if ! eval "${var_command}"; then
-            echo -e "${str_fail}"
+        if ! mkdir -p $1 &> /dev/null; then
+            echo -e "${var_prefix_fail} Could not create directory '$1'."
             return 1
         fi
 
@@ -106,13 +92,8 @@
         IsString $1 || return $?
         IsFile $1 &> /dev/null && return 0
 
-        # <params>
-        local str_fail="${var_prefix_fail} Could not create file '$1'."
-        local var_command='touch '"$1"' &> /dev/null'
-        # </params>
-
-        if ! eval "${var_command}"; then
-            echo -e "${str_fail}"
+        if ! touch $1 &> /dev/null; then
+            echo -e "${var_prefix_fail} Could not create file '$1'."
             return 1
         fi
 
@@ -126,13 +107,8 @@
         IsString $1 || return $?
         IsDir $1 &> /dev/null || return 1
 
-        # <params>
-        local str_fail="${var_prefix_fail} Could not delete directory '$1'."
-        local var_command='rm -r '"$1"' &> /dev/null'
-        # </params>
-
-        if ! eval "${var_command}"; then
-            echo -e "${str_fail}"
+        if ! rm $1 &> /dev/null; then
+            echo -e "${var_prefix_fail} Could not delete directory '$1'."
             return 1
         fi
 
@@ -146,13 +122,8 @@
         IsString $1 || return $?
         IsFile $1 &> /dev/null || return 1
 
-        # <params>
-        local str_fail="${var_prefix_fail} Could not delete file '$1'."
-        local var_command='rm '"$1"' &> /dev/null'
-        # </params>
-
-        if ! eval "${var_command}"; then
-            echo -e "${str_fail}"
+        if ! rm $1 &> /dev/null; then
+            echo -e "${var_prefix_fail} Could not delete file '$1'."
             return 1
         fi
 
@@ -180,12 +151,8 @@
     {
         IsString $1 || return $?
 
-        # <params>
-        local str_fail="${var_prefix_error} File '$1' is not a directory."
-        # </params>
-
         if [[ ! -d $1 ]]; then
-            echo -e "${str_fail}"
+            echo -e "${var_prefix_error} File '$1' is not a directory."
             return "${int_code_dir_is_null}"
         fi
 
@@ -198,12 +165,8 @@
     {
         IsString $1 || return $?
 
-        # <params>
-        local str_fail="${var_prefix_error} '$1' is not a file."
-        # </params>
-
         if [[ ! -e $1 ]]; then
-            echo -e "${str_fail}"
+            echo -e "${var_prefix_error} '$1' is not a file."
             return "${int_code_dir_is_null}"
         fi
 
@@ -217,12 +180,7 @@
     {
         IsFile $2 || return $?
         IsFile $1 || return $?
-
-        # <params>
-        local var_command='$1 -nt $2'
-        # </params>
-
-        eval "${var_command}" || return 1
+        [ $1 -nt $2 ] || return 1
         return 0
     }
 
@@ -233,12 +191,7 @@
     {
         IsFile $2 || return $?
         IsFile $1 || return $?
-
-        # <params>
-        local var_command='$2 -nt $1'
-        # </params>
-
-        eval "${var_command}" || return 1
+        [ $2 -nt $1 ] || return 1
         return 0
     }
 
@@ -249,12 +202,8 @@
     {
         IsFile $1 || return $?
 
-        # <params>
-        local str_fail="${var_prefix_error} File '$1' is not executable."
-        # </params>
-
         if [[ ! -x $1 ]]; then
-            echo -e "${str_fail}"
+            echo -e "${var_prefix_error} File '$1' is not executable."
             return "${int_code_file_is_not_executable}"
         fi
 
@@ -267,12 +216,8 @@
     {
         IsFile $1 || return $?
 
-        # <params>
-        local str_fail="${var_prefix_error} File '$1' is not readable."
-        # </params>
-
         if [[ ! -r $1 ]]; then
-            echo -e "${str_fail}"
+            echo -e "${var_prefix_error} File '$1' is not readable."
             return "${int_code_file_is_not_readable}"
         fi
 
@@ -285,12 +230,8 @@
     {
         IsFile $1 || return $?
 
-        # <params>
-        local str_fail="${var_prefix_error} File '$1' is not writable."
-        # </params>
-
         if [[ ! -w $1 ]]; then
-            echo -e "${str_fail}"
+            echo -e "${var_prefix_error} File '$1' is not readable."
             return "${int_code_file_is_not_writable}"
         fi
 
@@ -318,7 +259,6 @@
         # <params>
         IFS=$'\n'
         declare -a arr_print_file=( )
-        local str_output="Contents for file ${var_yellow}'$1'${var_reset_color}:"
         # </params>
 
         ReadFile "arr_print_file" $1 || return $?
@@ -412,12 +352,11 @@
         IsArray $1 || return $?
 
         # <params>
-        local str_fail="${var_prefix_fail} Could not write to file '$1'."
         local var_set_param='printf "%s\n" "${'$1'[@]}" >> $2'
         # </params>
 
         if ! eval "${var_set_param}"; then
-            echo -e "${str_fail}"
+            echo -e "${var_prefix_fail} Could not write to file '$1'."
             return 1
         fi
 
diff --git a/bin/bashlib-vars b/bin/bashlib-vars
--- a/bin/bashlib-vars
+++ b/bin/bashlib-vars
@@ -14,8 +14,8 @@
 
 # <code>
     # <summary> Check if two given files are the same. If true, pass. </summary>
-    # <paramref name=$1> string: name of the array </paramref>
-    # <paramref name=$2> string: name of the array </paramref>
+    # <paramref name="1"> string: name of the array </paramref>
+    # <paramref name="2"> string: name of the array </paramref>
     function AreEqualArrays
     {
         IsArray $2 || return $?
@@ -39,8 +39,8 @@
     }
 
     # <summary> Find line in array. </summary>
-    # <paramref name=$1> string: the name of the array </paramref>
-    # <param name=$2> string: the line </param>
+    # <paramref name="1"> string: the name of the array </paramref>
+    # <param name="2"> string: the line </param>
     function FindLineInArray
     {
         IsString $2 || return $?
@@ -62,7 +62,7 @@
     }
 
     # <summary> Check if the array is empty. </summary>
-    # <paramref name=$1> string: name of the array </paramref>
+    # <paramref name="1"> string: name of the array </paramref>
     function IsArray
     {
         IsString $1 || return $?
@@ -77,7 +77,7 @@
         done
 
         if [[ $( eval "${var_get_param_len}" ) -eq 0 ]]; then
-            echo -e "${str_fail_var_is_empty_array}"
+            echo -e "${var_prefix_error} Empty array."
             return "${int_code_var_is_empty}"
         fi
 
@@ -85,11 +85,11 @@
     }
 
     # <summary> Check if the variable is not empty. If true, pass. </summary>
-    # <param name=$1> var: the variable </param>
+    # <param name="1"> var: the variable </param>
     function IsString
     {
         if [[ ${#1} -eq 0 && "${1}" == "" ]]; then
-            echo -e "${str_fail_var_is_empty_var}"
+            echo -e "${var_prefix_error} Empty string."
             return "${int_code_var_is_empty}"
         fi
 
@@ -97,7 +97,7 @@
     }
 
     # <summary> Check if the value is a valid bool. </summary>
-    # <param name=$1> var: the boolean </param>
+    # <param name="1"> var: the boolean </param>
     function IsBool
     {
         IsString $1 || return $?
@@ -108,20 +108,20 @@
                 ;;
 
             * )
-                echo -e "${str_fail_var_is_not_bool}"
+                echo -e "${var_prefix_error} Not a boolean."
                 return "${int_code_var_is_not_bool}"
                 ;;
         esac
     }
 
     # <summary> Check if the value is a valid number. If true, pass.</summary>
-    # <param name=$1> var: the number </param>
+    # <param name="1"> var: the number </param>
     function IsNum
     {
         IsString $1 || return $?
 
-        if ! [[ $1 =~ $str_regex_numbers ]]; then
-            echo -e "${str_fail_var_is_NAN}"
+        if ! [[ $1 =~ '^[0-9]+$' ]]; then
+            echo -e "${var_prefix_error} NaN."
             return "${int_code_var_is_NAN}"
         fi
 
@@ -129,7 +129,7 @@
     }
 
     # <summary> Check if the variable is writable. If true, pass. </summary>
-    # <paramref name=$1> string: the name of a variable </param>
+    # <paramref name="1"> string: the name of a variable </param>
     function IsVarWritable
     {
         IsString $1 || return $?
@@ -139,7 +139,7 @@
         # </params>
 
         if ! eval "${var_is_readonly_var}"; then
-            echo -e "${str_fail_var_is_RO}"
+            echo -e "${var_prefix_error} Readonly variable."
             return 1
         fi
 
@@ -147,7 +147,7 @@
     }
 
     # <summary> Output an array. Declare inherited params before calling this function. </summary>
-    # <paramref name=$1> string: name of the array </paramref>
+    # <paramref name="1"> string: name of the array </paramref>
     function PrintArray
     {
         IsString $1 || return $?
@@ -167,8 +167,8 @@
     }
 
     # <summary> Replace line in an array. </summary>
-    # <paramref name=$1> string: the name of the array </paramref>
-    # <param name=$2> string: the line </param>
+    # <paramref name="1"> string: the name of the array </paramref>
+    # <param name="2"> string: the line </param>
     # <param name=$3> string: the new line </param>
     function ReplaceLineInArray
     {
@@ -196,15 +196,3 @@
         return 0
     }
 # </code>
-
-# <params>
-    # <summary> Constants </summary>
-    declare -g str_regex_numbers='^[0-9]+$'
-
-    # <summary> Output statement </summary>
-    declare -g str_fail_var_is_empty_array="${var_prefix_error} Empty array."
-    declare -g str_fail_var_is_empty_var="${var_prefix_error} Empty string."
-    declare -g str_fail_var_is_not_bool="${var_prefix_error} Not a boolean."
-    declare -g str_fail_var_is_NAN="${var_prefix_error} NaN."
-    declare -g str_fail_var_is_RO="${var_prefix_error} Readonly variable."
-# </params>
