Update some locations of references. Unfinished.

diff --git a/bin/bashlib-vars b/bin/bashlib-vars
--- a/bin/bashlib-vars
+++ b/bin/bashlib-vars
@@ -19,11 +19,13 @@
     # <returns> the exit code </returns>
     function AreEqualArrays
     {
-        IsArray $2 || return $?
-        IsArray $1 || return $?
+        declare -an arr_are_equal_arrays_reference_2=$2
+        declare -an arr_are_equal_arrays_reference_1=$1
+        IsArray "arr_are_equal_arrays_reference_2" || return $?
+        IsArray "arr_are_equal_arrays_reference_1" || return $?
 
-        for int_key in $( eval '"${'$1'[@]}"' ); do
-            if [[ $( eval '"${'$1'[$int_key]}"' ) != $( eval '"${'$2'[$int_key]}"' ) ]]; then
+        for int_key in ${!arr_are_equal_arrays_reference_1[@]}; do
+            if [[ "${arr_are_equal_arrays_reference_1[$int_key]}" != "${arr_are_equal_arrays_reference_2[$int_key]}" ]]; then
                 return 1
             fi
         done
@@ -38,9 +40,10 @@
     function FindLineInArray
     {
         IsString $2 || return $?
-        IsArray $1 || return $?
+        declare -an arr_find_line_in_array_reference=$1
+        IsArray "arr_find_line_in_array_reference" || return $?
 
-        for var_element in $( eval '"${'$1'[@]}"' ); do
+        for var_element in ${arr_find_line_in_array_reference[@]}; do
             if [[ "${var_element}" == $2 ]]; then
                 return 0
             fi
@@ -57,13 +60,14 @@
         function Main
         {
             IsString $1 || return $?
+            declare -an arr_is_array_reference=$1
 
-            if [[ $( eval '"${#'$1'[@]}"' ) -eq 0 ]]; then
+            if [[ ${#arr_is_array_reference[@]} -eq 0 ]]; then
                 echo -e "${str_fail_array_is_empty}"
                 return $int_code_var_is_empty
             fi
 
-            for var_element in $( eval '"${'$1'[@]}"' ); do
+            for var_element in ${arr_is_array_reference[@]}; do
                 IsString "${var_element}" &> /dev/null && return 0
             done
 
@@ -76,21 +80,6 @@
         SaveExitCode
         unset IFS
         return $int_exit_code
-    }
-
-    # <summary> Check if the array is writable. If true, pass. </summary>
-    # <paramref name="1"> string: the name of a array </paramref>
-    # <returns> the exit code </returns>
-    function IsArrayWritable
-    {
-        IsArray $1 || return $?
-
-        if ! eval 'unset '$1' 2> /dev/null'; then
-            echo -e "${var_prefix_error} Readonly array."
-            return $int_code_var_is_readonly
-        fi
-
-        return 0
     }
 
     # <summary> Check if the variable is not empty. If true, pass. </summary>
@@ -140,16 +129,17 @@
         return 0
     }
 
-    # <summary> Check if the value is a pointer. If true, pass.</summary>
+    # <summary> Check if the value is a reference. If true, pass.</summary>
     # <paramref name="1"> var: the name of the variable </param>
     # <returns> the exit code </returns>
-    function IsPointer
+    function IsReference
     {
         IsString $1 || return $?
+        declare -n var_reference=$1
 
-        if ! IsString $( eval '$'"$1" ) &> /dev/null; then
-            echo -e "${var_prefix_error} Null pointer."
-            return $int_code_var_is_pointer
+        if ! IsString $var_reference &> /dev/null; then
+            echo -e "${var_prefix_error} Null reference."
+            return $int_code_var_is_not_a_reference
         fi
 
         return 0
@@ -178,14 +168,15 @@
     {
         function Main
         {
-            IsArray $1 || return $?
+            declare -an arr_print_array_reference=$1
+            IsArray "arr_print_array_reference" || return $?
             local bool_toggle_color=false
             IsBool $2 && bool_toggle_color=$2
 
             if $bool_toggle_color; then
-                eval 'echo -e "${var_yellow}${'$1'[*]}${var_reset_color}"' || return $?
+                echo -e "${var_yellow}${arr_print_array_reference[*]}${var_reset_color}" || return $?
             else
-                eval 'echo -e "${'$1'[*]}"' || return $?
+                echo "${arr_print_array_reference[*]}" || return $?
             fi
 
             return 0
@@ -208,21 +199,23 @@
         function Main
         {
             IsString $3 || return $?
-            IsArrayWritable $1 || return $?
-            FindLineInArray $1 $2 || return $?
+            declare -an arr_replace_line_in_array_reference=$1
+            IsArray "arr_replace_line_in_array_reference" || IsVarWritable "arr_replace_line_in_array_reference" || return $?
+            declare -a arr_replace_line_in_array_new="${arr_replace_line_in_array_reference[*]}"
+            FindLineInArray "arr_replace_line_in_array_new" $2 || return $?
 
-            for int_key in $( eval '${!'$1'[*]}' ); do
-                # case $( eval '"{'$1'[$int_key]}"' ) in
-                #     $2* )
-                #         eval "$1"'[$int_key]=$3'
-                #         ;;
-                # esac
+            for int_key in ${!arr_replace_line_in_array_new[@]}; do
+                local var_element="${arr_replace_line_in_array_new[$int_key]}"
 
-                if [[ $( eval '"{'$1'[$int_key]}"' ) ~= $2* ]]; then
-                    eval "$1"'[$int_key]=$3' || return $?
-                fi
+                case "${var_element}" in
+                    $2* )
+                        arr_replace_line_in_array_new[$int_key]=$3
+                        ;;
+                esac
             done
 
+            IsArray "arr_replace_line_in_array_new" || return $?
+            arr_replace_line_in_array_reference="${arr_replace_line_in_array_new[*]}" || return 1
             return 0
         }
 
@@ -241,20 +234,20 @@
     {
         function Main
         {
-            IsArrayWritable $1 || return $?
-
-            # <params>
+            declare -an arr_sort_array_reference=$1
+            IsArray "arr_sort_array_reference" || IsVarWritable "arr_sort_array_reference" || return $?
+            declare -a arr_sort_array_new=( )
             local bool_is_reverse_sort=false
-            # </params>
-
             IsBool $2 &> /dev/null && bool_is_reverse_sort=$2
 
             if $bool_is_reverse_sort; then
-                eval "$1"'=( $( sort -r <<< "${'"$1"'[*]}" ) )' || return $?
+                arr_sort_array_new=$( sort -r <<< "${arr_sort_array_reference[*]}" ) || return $?
             else
-                eval "$1"'=$( sort <<< "${'"$1"'[*]}" )' || return $?
+                arr_sort_array_new=$( sort <<< "${arr_sort_array_reference[*]}" ) || return $?
             fi
 
+            IsArray "arr_sort_array_new" || return $?
+            arr_sort_array_reference="${arr_sort_array_new[*]}" || return 1
             return 0
         }
 
@@ -272,24 +265,21 @@
     {
         function Main
         {
-            IsArray $1 || return $?
+            declare -an arr_trim_array_reference=$1
+            IsArray "arr_trim_array_reference" || IsVarWritable "arr_trim_array_reference" || return $?
+            declare -a arr_trim_array_new="${arr_trim_array_reference[*]}"
+            IsArray "arr_trim_array_new" || return $?
 
-            # <params>
-            declare -a arr_trim_array=( )
-            # </params>
+            for int_key in ${!arr_trim_array_new[@]}; do
+                local var_element="${arr_trim_array_new[$int_key]}"
 
-            for int_key in $( eval '${!'$1'[*]}' ); do
                 if IsString "${var_element}" &> /dev/null; then
-                    arr_trim_array+=( "${var_element}" )
+                    arr_trim_array_new[$int_key]=( "${var_element}" ) || return 1
                 fi
             done
 
-            if IsArray "arr_trim_array" &> /dev/null; then
-                eval "$1"'=( "${arr_trim_array[*]}" )' || return $?
-            else
-                eval "$1"'=( )' || return $?
-            fi
-
+            IsArray "arr_trim_array_new" || return $?
+            arr_trim_array_reference="${arr_trim_array_new[*]}" || return 1
             return 0
         }
 
