Fixed zram swap, and ModifyQEMU. Added function to select VFIO setup. Fixed calls to File functions, that use arrays.Removed debug. Organized functions by alphabet order.

diff --git a/bin/bashlib-dev b/bin/bashlib-dev
--- a/bin/bashlib-dev
+++ b/bin/bashlib-dev
@@ -71,113 +71,6 @@
         return 0
     }
 
-    # <summary> Check if system file is original or not. </summary>
-    # <parameter name=$1> string: the system file </parameter>
-    # <parameter name=$2> string: the software package(s) to install </parameter>
-    # <parameter name="${bool_is_connected_to_Internet}"> boolean: GetInternetStatus </parameter>
-    # <returns> exit code </returns>
-    function IsFileOriginal
-    {
-        IsString $2 || return $?
-        IsString $1 || return $?
-
-        # <params>
-        local bool_backup_file_exists=false
-        local bool_system_file_is_original=false
-        # </params>
-
-        # <remarks> Original system file does not exist. </remarks>
-        if $bool_is_connected_to_Internet && ! IsFile $1; then
-            InstallPackage $2 true && bool_system_file_is_original=true
-        fi
-
-        # <remarks> Backup system file. </remarks>
-        if BackupFile $1; then
-            bool_backup_file_exists=true
-        fi
-
-        # <remarks> Do no work. </remarks>
-        if ! $bool_backup_file_exists || ! $bool_system_file_is_original; then
-            return 1
-        fi
-
-        # <remarks> It is unknown if system file *is* original. </remarks>
-        if $bool_is_connected_to_Internet && $bool_backup_file_exists && ! $bool_system_file_is_original; then
-            DeleteFile $1
-            InstallPackage $2 true && bool_system_file_is_original=true
-        fi
-
-        # <remarks> System file *is not* original. Attempt to restore backup. </remarks>
-        if $bool_backup_file_exists && ! $bool_system_file_is_original; then
-            RestoreFile $1
-            return $?
-        fi
-
-        return 0
-    }
-
-    # <summary> Distro-agnostic, Install a software package. </summary>
-    # <param name=$1> string: the software package(s) </param>
-    # <param name=$2> boolean: true/false do/don't reinstall software package and configuration files (if possible) </param>
-    # <param name="${str_package_manager}"> string: the package manager </param>
-    # <returns> exit code </returns>
-    function InstallPackage
-    {
-        IsString "${str_package_manager}" || return $?
-        IsString $1 || return $?
-
-        # <params>
-        local bool_option_reinstall=false
-        local str_commands_to_execute=""
-        local readonly str_output="Installing software packages..."
-        local readonly str_fail="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
-        # </params>
-
-        IsBool $2 &> /dev/null && bool_option_reinstall=true
-
-        # <remarks> Auto-update and auto-install selected packages </remarks>
-        case "${str_package_manager}" in
-            "apt" )
-                local readonly str_option="--reinstall -o Dpkg::Options::=--force-confmiss"
-                str_commands_to_execute="apt update && apt full-upgrade -y && apt install ${str_option} -y ${1}"
-                ;;
-
-            "dnf" )
-                str_commands_to_execute="dnf upgrade && dnf install ${1}"
-                ;;
-
-            "pacman" )
-                str_commands_to_execute="pacman -Syu && pacman -S ${1}"
-                ;;
-
-            "gentoo" )
-                str_commands_to_execute="emerge -u @world && emerge ${1}"
-                ;;
-
-            "urpmi" )
-                str_commands_to_execute="urpmi --auto-update && urpmi ${1}"
-                ;;
-
-            "yum" )
-                str_commands_to_execute="yum update && yum install ${1}"
-                ;;
-
-            "zypper" )
-                str_commands_to_execute="zypper refresh && zypper in ${1}"
-                ;;
-
-            * )
-                echo -e "${str_fail}"
-                return 1
-                ;;
-        esac
-
-        echo "${str_output}"
-        eval "${str_commands_to_execute}" || ( return 1 )
-        PrintPassOrFail "${str_output}"
-        return $?
-    }
-
     # <summary> Test network connection to Internet. Ping DNS servers by address and name. </summary>
     # <param name=$1> boolean: true/false toggle verbosity </param>
     # <returns> exit code </returns>
@@ -297,6 +190,141 @@
         fi
 
         return 0
+    }
+
+    # <summary> Check if system file is original or not. </summary>
+    # <parameter name=$1> string: the system file </parameter>
+    # <parameter name=$2> string: the software package(s) to install </parameter>
+    # <parameter name="${bool_is_connected_to_Internet}"> boolean: GetInternetStatus </parameter>
+    # <returns> exit code </returns>
+    function IsFileOriginal
+    {
+        IsString $2 || return $?
+        IsString $1 || return $?
+
+        # <params>
+        local bool_backup_file_exists=false
+        local bool_system_file_is_original=false
+        # </params>
+
+        # <remarks> Original system file does not exist. </remarks>
+        if $bool_is_connected_to_Internet && ! IsFile $1; then
+            InstallPackage $2 true && bool_system_file_is_original=true
+        fi
+
+        # <remarks> Backup system file. </remarks>
+        if BackupFile $1; then
+            bool_backup_file_exists=true
+        fi
+
+        # <remarks> Do no work. </remarks>
+        if ! $bool_backup_file_exists && ! $bool_system_file_is_original; then
+            return 1
+        fi
+
+        # <remarks> It is unknown if system file *is* original. </remarks>
+        if $bool_is_connected_to_Internet && $bool_backup_file_exists && ! $bool_system_file_is_original; then
+            DeleteFile $1
+            InstallPackage $2 true && bool_system_file_is_original=true
+        fi
+
+        # <remarks> System file *is not* original. Attempt to restore backup. </remarks>
+        if $bool_backup_file_exists && ! $bool_system_file_is_original; then
+            RestoreFile $1
+            return $?
+        fi
+
+        return 0
+    }
+
+    # <summary> Distro-agnostic, check if package is installed. </summary>
+    # <param name=$1> string: the software package(s) </param>
+    # <param name="${str_package_manager}"> string: the package manager </param>
+    # <returns> exit code </returns>
+    function IsInstalledPackage
+    {
+        IsString "${str_package_manager}" || return $?
+        IsString $1 || return $?
+
+        # <params>
+        local readonly str_fail="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
+        # </params>
+
+        # <remarks> Check if package is not installed </remarks>
+        case "${str_package_manager}" in
+            "apt" )
+                dpkg -s $1 &> /dev/null || InstallPackage $1 || return $?
+                ;;
+
+            * )
+                echo -e "${str_fail}"
+                return 1
+                ;;
+        esac
+
+        return 0
+    }
+
+    # <summary> Distro-agnostic, Install a software package. </summary>
+    # <param name=$1> string: the software package(s) </param>
+    # <param name=$2> boolean: true/false do/don't reinstall software package and configuration files (if possible) </param>
+    # <param name="${str_package_manager}"> string: the package manager </param>
+    # <returns> exit code </returns>
+    function InstallPackage
+    {
+        IsString "${str_package_manager}" || return $?
+        IsString $1 || return $?
+
+        # <params>
+        local bool_option_reinstall=false
+        local str_commands_to_execute=""
+        local readonly str_output="Installing software packages..."
+        local readonly str_fail="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
+        # </params>
+
+        IsBool $2 &> /dev/null && bool_option_reinstall=true
+
+        # <remarks> Auto-update and auto-install selected packages </remarks>
+        case "${str_package_manager}" in
+            "apt" )
+                local readonly str_option="--reinstall -o Dpkg::Options::=--force-confmiss"
+                str_commands_to_execute="apt update && apt full-upgrade -y && apt install ${str_option} -y ${1}"
+                ;;
+
+            "dnf" )
+                str_commands_to_execute="dnf upgrade && dnf install ${1}"
+                ;;
+
+            "pacman" )
+                str_commands_to_execute="pacman -Syu && pacman -S ${1}"
+                ;;
+
+            "gentoo" )
+                str_commands_to_execute="emerge -u @world && emerge ${1}"
+                ;;
+
+            "urpmi" )
+                str_commands_to_execute="urpmi --auto-update && urpmi ${1}"
+                ;;
+
+            "yum" )
+                str_commands_to_execute="yum update && yum install ${1}"
+                ;;
+
+            "zypper" )
+                str_commands_to_execute="zypper refresh && zypper in ${1}"
+                ;;
+
+            * )
+                echo -e "${str_fail}"
+                return 1
+                ;;
+        esac
+
+        echo "${str_output}"
+        eval "${str_commands_to_execute}" || ( return 1 )
+        PrintPassOrFail "${str_output}"
+        return $?
     }
 
     # <summary> Update GetInternetStatus </summary>
diff --git a/bin/vfiolib-setup b/bin/vfiolib-setup
--- a/bin/vfiolib-setup
+++ b/bin/vfiolib-setup
@@ -343,19 +343,29 @@
         return 0
     }
 
-    # # <summary> ??? </summary>
-    # # <returns> exit code </returns>
-    # function Setup_VFIO
-    # {
-    #     # <params>
+    # <summary> ??? </summary>
+    # <returns> exit code </returns>
+    function Setup_VFIO
+    {
+        echo
+        ReadMultipleChoiceIgnoreCase "Setup VFIO? ${var_green}None / Multiboot / Static${var_reset_color}" "N" "M" "S"
 
-    #     # </params>
+        case "${var_input}" in
+            "M" )
+                Multiboot_VFIO || return $?
+                ;;
 
-    #     # diff between static and multiboot => static: all IOMMU for VFIO with PCI STUB devices will be binded to VFIO PCI driver? append only to GRUB and system files.
-    #     # multiboot: PCI STUB devices will use PCI STUB driver? append only GRUB and multiple GRUB entries
+            "S" )
+                Static_VFIO || return $?
+                ;;
 
-    #     return 0
-    # }
+            * )
+                return 1
+                ;;
+        esac
+
+        return 0
+    }
 
     # # <summary> ??? </summary>
     # # <returns> exit code </returns>
