Edited declarations of input params, arrays.

diff --git a/bin/bashlib-files b/bin/bashlib-files
--- a/bin/bashlib-files
+++ b/bin/bashlib-files
@@ -36,7 +36,7 @@
             # <params>
             local str_dir=$( dirname $1 )
             local str_suffix=".old"
-            declare -a arr_dir=( $( eval 'ls -t '"${str_dir}"' | grep '$1' | grep -i '"${str_suffix}"' | uniq' ) )
+            declare -a arr_dir=( $( eval 'ls -t '"${str_dir}"' | grep '${1}' | grep -i '"${str_suffix}"' | uniq' ) )
             # </params>
 
             # <remarks> If none exist, create backup. </remarks>
@@ -77,7 +77,7 @@
         IsDir $1 &> /dev/null && return 0
 
         if ! mkdir -p $1 &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not create directory '$1'."
+            echo -e "${var_prefix_fail} Could not create directory '${1}'."
             return 1
         fi
 
@@ -92,7 +92,7 @@
         IsFile $1 &> /dev/null && return 0
 
         if ! touch $1 &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not create file '$1'."
+            echo -e "${var_prefix_fail} Could not create file '${1}'."
             return 1
         fi
 
@@ -107,7 +107,7 @@
         IsDir $1 &> /dev/null || return 1
 
         if ! rm -r '"$1"' &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not delete directory '$1'."
+            echo -e "${var_prefix_fail} Could not delete directory '${1}'."
             return 1
         fi
 
@@ -122,7 +122,7 @@
         IsFile $1 &> /dev/null || return 1
 
         if ! rm '"$1"' &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not delete file '$1'."
+            echo -e "${var_prefix_fail} Could not delete file '${1}'."
             return 1
         fi
 
@@ -147,7 +147,7 @@
         IsString $1 || return $?
 
         if [[ ! -d $1 ]]; then
-            echo -e "${var_prefix_error} File '$1' is not a directory."
+            echo -e "${var_prefix_error} File '${1}' is not a directory."
             return $int_code_dir_is_null
         fi
 
@@ -161,7 +161,7 @@
         IsString $1 || return $?
 
         if [[ ! -e $1 ]]; then
-            echo -e "${var_prefix_error} '$1' is not a file."
+            echo -e "${var_prefix_error} '${1}' is not a file."
             return $int_code_dir_is_null
         fi
 
@@ -198,7 +198,7 @@
         IsFile $1 || return $?
 
         if [[ ! -x $1 ]]; then
-            echo -e "${var_prefix_error} File '$1' is not executable."
+            echo -e "${var_prefix_error} File '${1}' is not executable."
             return $int_code_file_is_not_executable
         fi
 
@@ -212,7 +212,7 @@
         IsFile $1 || return $?
 
         if [[ ! -r $1 ]]; then
-            echo -e "${var_prefix_error} File '$1' is not readable."
+            echo -e "${var_prefix_error} File '${1}' is not readable."
             return $int_code_file_is_not_readable
         fi
 
@@ -226,7 +226,7 @@
         IsFile $1 || return $?
 
         if [[ ! -w $1 ]]; then
-            echo -e "${var_prefix_error} File '$1' is not writable."
+            echo -e "${var_prefix_error} File '${1}' is not writable."
             return $int_code_file_is_not_writable
         fi
 
@@ -256,8 +256,8 @@
         declare -a arr_print_file=( )
         # </params>
 
-        ReadFile arr_print_file $1 || return $?
-        PrintArray arr_print_file
+        ReadFile "arr_print_file" $1 || return $?
+        PrintArray "arr_print_file"
         return $?
     }
 
@@ -274,7 +274,7 @@
         # </params>
 
         if ! mapfile -t < <( cat $2 ) || ! IsArray "MAPFILE" &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not read from file '$2'."
+            echo -e "${var_prefix_fail} Could not read from file '${2}'."
             return 1
         fi
 
@@ -294,8 +294,8 @@
         declare -a arr_replace_file=()
         # </params>
 
-        ReadFile arr_replace_file $1 || return $?
-        ReplaceLineInArray arr_replace_file $2 $3 || return $?
+        ReadFile "arr_replace_file" $1 || return $?
+        ReplaceLineInArray "arr_replace_file" $2 $3 || return $?
         return 0
     }
 
@@ -310,7 +310,7 @@
             # <params>
             local str_dir=$( dirname $1 )
             local str_suffix=".old"
-            declare -a arr_dir=( $( eval 'ls -t '"${str_dir}"' | grep '$1' | grep -i '"${str_suffix}"' | uniq' ) )
+            declare -a arr_dir=( $( eval 'ls -t '"${str_dir}"' | grep '${1}' | grep -i '"${str_suffix}"' | uniq' ) )
             # </params>
 
             # <remarks> If none exist, create backup. </remarks>
@@ -341,8 +341,8 @@
         IsFile $2 || return $?
         IsArray $1 || return $?
 
-        if ! printf "%s\n" "${'$1'[@]}" >> $2; then
-            echo -e "${var_prefix_fail} Could not write to file '$1'."
+        if ! printf "%s\n" "${'${1}'[@]}" >> $2; then
+            echo -e "${var_prefix_fail} Could not write to file '${1}'."
             return 1
         fi
 
