Disabled deletion of temp files. Multiboot setup works. Outputs delimited strings of drivers and hwid as expected.

diff --git a/bin/deploy-vfio_logic_main-setup b/bin/deploy-vfio_logic_main-setup
--- a/bin/deploy-vfio_logic_main-setup
+++ b/bin/deploy-vfio_logic_main-setup
@@ -106,18 +106,18 @@
   {
     if ! create_temp_files_for_main_setup \
       || ! do_try_main_setup; then
-      do_cleanup_main_setup
+      restore_temp_files_for_main_setup
       return 1
     fi
   }
 
-  function do_cleanup_main_setup
-  {
-    if ! restore_temp_files_for_main_setup \
-      || ! delete_temp_files_for_main_setup; then
-      print_prefix_error "Main setup: Cleanup failed."
-    fi
-  }
+  # function do_cleanup_main_setup
+  # {
+  #   if ! restore_temp_files_for_main_setup \
+  #     || ! delete_temp_files_for_main_setup; then
+  #     print_prefix_error "Main setup: Cleanup failed."
+  #   fi
+  # }
 
   function do_try_main_setup
   {
@@ -165,6 +165,7 @@
     {
       if ! get_output_for_multiboot_setup \
         || ! specify_grub_menu_entry_for_multiboot_setup \
+        || ! restore_source_files_for_main_setup \
         || ! write_output_for_multiboot_setup \
         || ! execute_update_after_main_setup; then
         print_prefix_fail "Multiboot VFIO setup has failed."
@@ -176,6 +177,7 @@
     {
       if ! specify_static_setup_prompt \
         || ! get_output_for_static_setup \
+        || ! restore_source_files_for_main_setup \
         || ! write_output_for_static_setup \
         || ! execute_update_after_main_setup; then
         print_prefix_fail "Static VFIO setup has failed."
@@ -209,15 +211,15 @@
       create_temp_file_of_file "${MODULES_DEST_PATH}" || return 1
     }
 
-    function delete_temp_files_for_main_setup
-    {
-      delete_temp_file_of_file "${GRUB_CUSTOM_DEST_PATH}" || return 1
-      delete_temp_file_of_file "${GRUB_DEST_PATH}" || return 1
-      delete_temp_file_of_file "${INITRAMFS_MODULES_DEST_PATH}" || return 1
-      delete_temp_file_of_file "${MODPROBE_BLACKLISTS_DEST_PATH}" || return 1
-      delete_temp_file_of_file "${MODPROBE_VFIO_DEST_PATH}" || return 1
-      delete_temp_file_of_file "${MODULES_DEST_PATH}" || return 1
-    }
+    # function delete_temp_files_for_main_setup
+    # {
+    #   delete_temp_file_of_file "${GRUB_CUSTOM_DEST_PATH}" || return 1
+    #   delete_temp_file_of_file "${GRUB_DEST_PATH}" || return 1
+    #   delete_temp_file_of_file "${INITRAMFS_MODULES_DEST_PATH}" || return 1
+    #   delete_temp_file_of_file "${MODPROBE_BLACKLISTS_DEST_PATH}" || return 1
+    #   delete_temp_file_of_file "${MODPROBE_VFIO_DEST_PATH}" || return 1
+    #   delete_temp_file_of_file "${MODULES_DEST_PATH}" || return 1
+    # }
 
     function restore_temp_files_for_main_setup
     {
@@ -231,7 +233,18 @@
 
     function restore_source_files_for_main_setup
     {
+      restore_source_files_for_multiboot_setup || return 1
+      restore_source_files_for_static_setup || return 1
+    }
+
+    function restore_source_files_for_multiboot_setup
+    {
       copy_this_file_to_other_file "${GRUB_CUSTOM_SRC_PATH}" "${GRUB_CUSTOM_DEST_PATH}" || return 1
+      copy_this_file_to_other_file "${GRUB_SRC_PATH}" "${GRUB_DEST_PATH}" || return 1
+    }
+
+    function restore_source_files_for_static_setup
+    {
       copy_this_file_to_other_file "${INITRAMFS_MODULES_SRC_PATH}" "${INITRAMFS_MODULES_DEST_PATH}" || return 1
       copy_this_file_to_other_file "${MODPROBE_BLACKLISTS_SRC_PATH}" "${MODPROBE_BLACKLISTS_DEST_PATH}" || return 1
       copy_this_file_to_other_file "${MODPROBE_VFIO_SRC_PATH}" "${MODPROBE_VFIO_DEST_PATH}" || return 1
@@ -242,6 +255,8 @@
   # <summary>Getters</summary>
     function get_grub_menu_entry_enum_for_multiboot_setup
     {
+      local -r prefix_grub_cmdline_temp="${1}"
+
       for this_iommu_group_id in ${IOMMU_GROUPS_FOR_VFIO_ENUM[@]}; do
         does_iommu_group_have_vga_device "${this_iommu_group_id}" &> /dev/null || continue
         local -a driver_enum=( )
@@ -261,7 +276,8 @@
         done
 
         get_name_for_first_vga_device_in_iommu_group "${this_iommu_group_id}" "this_iommu_group_vga_name" &> /dev/null
-        get_enums_for_selection "selection_without_this_group_enum" "driver_enum" "stub_hwid_enum" "vfio_hwid_enum" "driver_enum" "this_driver_delim"
+        get_enums_for_selection "selection_without_this_group_enum" "driver_enum" "stub_hwid_enum" "vfio_hwid_enum"
+        get_comma_delimited_string_from_enum "driver_enum" "this_driver_delim"
         get_comma_delimited_string_from_enum "stub_hwid_enum" "this_stub_hwid_delim"
         get_comma_delimited_string_from_enum "vfio_hwid_enum" "this_vfio_hwid_delim"
         grub_cmdline_temp+="modprobe.blacklist=${this_driver_delim} "
@@ -297,7 +313,7 @@
           "\tset root='/dev/disk/by-uuid/${system_uuid}'"
           "\t"'if [ x$feature_platform_search_hint = xy ]; then'"\n\t\t"'search --no-floppy --fs-uuid --set=root '"${system_uuid}\n\t"'fi'
           "\techo  'Loading ${system_os} ${kernel} ...'"
-          "\tlinux   /boot/vmlinuz-${kernel} root=UUID=${system_uuid} ${prefix_grub_cmdline_temp}"
+          "\tlinux   /boot/vmlinuz-${kernel} root=UUID=${system_uuid} ${grub_cmdline_temp}"
           "\tinitrd  /boot/initrd.img-${kernel}"
           "\techo  \"VFIO, w/o IOMMU '${iommu_group_id}' w/ '${this_iommu_group_vga_name}'\""
           "}"
@@ -324,7 +340,7 @@
     function get_output_for_multiboot_setup
     {
       local -ir max_parsed_kernels=3
-      local -a kernel_enum=( $( ls -1 /boot/vmli* | cut -d 'z' -f 2 | cut -c 2- | sort -r | head -n ${max_parsed_kernels} ) )
+      local -a kernel_enum=( $( ls -1 /boot/vmli* | cut -d 'z' -f 2 | cut -c 2- | sort -n | head -n ${max_parsed_kernels} ) )
       local -r system_disk=$( df / | grep -iv 'filesystem' | cut -d '/' -f3 | cut -d ' ' -f1 )
       local -r system_distro=$( lsb_release -i -s )
       local -r system_fstype=$( blkid -s TYPE | grep ${system_disk} | cut -d '"' -f2 )
@@ -349,7 +365,7 @@
       fi
 
       readonly prefix_grub_cmdline_temp
-      get_grub_menu_entry_enum_for_multiboot_setup
+      get_grub_menu_entry_enum_for_multiboot_setup "${prefix_grub_cmdline_temp}"
 
       if ! is_enum "GRUB_CUSTOM_FILE_CONTENTS"; then
         print_prefix_error "Multiboot setup output is empty."
