Added functions, traps.

diff --git a/bin/deploy-vfio_logic_common b/bin/deploy-vfio_logic_common
--- a/bin/deploy-vfio_logic_common
+++ b/bin/deploy-vfio_logic_common
@@ -7,6 +7,11 @@
 # Maintainer(s):  Alex Portell <github.com/portellam>
 #
 
+# <traps>
+  trap 'catch_error' SIGINT SIGTERM ERR
+  trap 'catch_exit' EXIT
+# </traps>
+
 # <functions>
   function declare_parameters
   {
@@ -16,8 +21,8 @@
 
     declare -g COMMON_ARE_PARAMS_SET=true
 
-    declare -gr REPO_NAME="deploy-vfio"
-    declare -gr DEPLOY_VFIO_NAME="deploy-vfio"
+    declare -gr REPO_NAME="portellam"
+    declare -gr SCRIPT_NAME="deploy-vfio"
 
     # <remarks>
     # Color coding
@@ -35,18 +40,18 @@
     declare -gr PREFIX_PASS="${SET_COLOR_GREEN}Success:${RESET_COLOR}"
     declare -gr SUFFIX_FAIL="${SET_COLOR_RED}[Failure]${RESET_COLOR}"
     declare -gr SUFFIX_PASS="${SET_COLOR_GREEN}[Success]${RESET_COLOR}"
-    declare -gr SUFFIX_SKIP="${SET_COLOR_YELLOW}[Skipped]${RESET_COLOR}"
-    declare -gr SUFFIX_WORK="${SET_COLOR_YELLOW}[Working]${RESET_COLOR}"
+    # declare -gr SUFFIX_SKIP="${SET_COLOR_YELLOW}[Skipped]${RESET_COLOR}"
+    # declare -gr SUFFIX_WORK="${SET_COLOR_YELLOW}[Working]${RESET_COLOR}"
 
     declare -g PREFIX_COMMENT="#" # <note>Added this var, to prevent IDE from showing visual errors when a string contains a comment variable.</note>
 
-    declare -gr BIN_PATH="/usr/local/bin/${DEPLOY_VFIO_NAME}.d/"
-    declare -gr ETC_BACKUPS_PATH="/usr/local/etc/${DEPLOY_VFIO_NAME}.d/"
+    declare -gr BIN_PATH="/usr/local/bin/${SCRIPT_NAME}.d/"
+    declare -gr ETC_BACKUPS_PATH="/usr/local/etc/${SCRIPT_NAME}.d/"
 
     # <remarks>File templates.</remarks>
     declare -gar DISCLAIMER_FILE_CONTENTS=(
-      "${PREFIX_COMMENT} Generated by '${REPO_NAME}/${DEPLOY_VFIO_NAME}'"
-      "${PREFIX_COMMENT} WARNING: Any modifications to this file will be modified by '${DEPLOY_VFIO_NAME}'"
+      "${PREFIX_COMMENT} Generated by '${REPO_NAME}/${SCRIPT_NAME}'"
+      "${PREFIX_COMMENT} WARNING: Any modifications to this file will be modified by '${SCRIPT_NAME}'"
       "${PREFIX_COMMENT}"
     )
 
@@ -61,71 +66,73 @@
     declare -gr LOGIN_USER=$( who am i | awk '{print $1}' )
   }
 
-  function is_user_superuser
-  {
-    if [[ $( whoami ) != "root" ]]; then
-      print_prefix_error "User is not sudo or root."
-      exit 1
-    fi
-  }
-
-  function reverse_array
-  {
-    is_enum "${1}" || return 1
-    local -n reference="${1}"
-    reference="$( printf '%s\n' "${reference[@]}" | tac | tr '\n' ' '; echo )"
-  }
-
-  function set_ifs_to_newline
-  {
-    IFS=$'\n'
-  }
-
-  function unset_ifs
-  {
-    unset IFS
-  }
-
-  # <summary>GitHub</summary>
-    function clone_git_repo
+  # <summary>Clean-up</summary>
+    function reset_ifs
     {
-      local -r full_repo="${1}"
+      IFS="${SAVEIFS}"
+    }
 
-      if ! git clone "https://github.com/${full_repo}" &> /dev/null; then
-        print_prefix_error "Failed to download repository."
+  # <summary>Data-type manipulation</summary>
+    function reverse_array
+    {
+      is_enum "${1}" || return 1
+      local -n this_enum="${1}"
+      this_enum="$( printf '%s\n' "${this_enum[@]}" | tac | tr '\n' ' '; echo )"
+    }
+
+  # <summary>Data-type validation</summary>
+    function get_comma_delimited_string_from_enum
+    {
+      local -n this_enum="${1}"
+      local -n this_delimited_string="${2}"
+
+      for value in ${this_enum[@]}; do
+        this_delimited_string+="${value},"
+      done
+
+      if [[ ${this_delimited_string: -1} == "," ]]; then
+        this_delimited_string="${this_delimited_string::-1}"
+      fi
+    }
+
+    function is_enum
+    {
+      local -n this_enum="${1}"
+
+      if ! [[ "${#this_enum[@]}" -gt 0 ]]; then
+        print_to_error_log "Invalid enum."
         return 1
       fi
     }
 
-    function update_git_repo
+    function is_enum_not_empty
     {
-      if ! git pull &> /dev/null; then
-        print_prefix_error "Failed to update repository."
+      is_enum "${1}" || return 1
+      local -n this_enum="${1}"
+
+      for value in "${this_enum[@]}"; do
+        if is_string "${value}" &> /dev/null; then
+          return 0
+        fi
+      done
+
+      print_to_error_log "Empty enum."
+      return 1
+    }
+
+    function is_int
+    {
+      if ! [[ "${1}" =~ ^[0-9]+$ ]] \
+        && ! [[ "${1}" =~ ^[-][0-9]+$ ]]; then
+        print_to_error_log "Invalid integer."
         return 1
       fi
     }
 
-    function update_or_clone_git_repo
+    function is_string
     {
-      local -r full_repo="${1}"
-      local -r user_name="${2}"
-      local -r full_path="${BIN_PATH}${full_repo}"
-      local -r user_path="${BIN_PATH}${user_name}"
-
-      if [[ ! -d "${user_path}" ]] \
-        && ! sudo mkdir --parents "${user_path}" &> /dev/null; then
-        print_prefix_error "Failed to create directory '${user_path}'."
-        return 1
-      fi
-
-      if [[ ! -d "${full_path}" ]]; then
-        cd "${full_path}"
-        update_git_repo
-
-      elif [[ -d "${user_path}" ]]; then
-        clone_git_repo "${full_repo}"
-
-      else
+      if [[ "${1}" == "" ]]; then
+        print_to_error_log "Empty string."
         return 1
       fi
     }
@@ -139,7 +146,7 @@
       local -r temp_file="${file}.tmp"
 
       if ! cp --force "${file}" "${temp_file}"; then
-        print_prefix_error "Failed to create temp file of '${file}'."
+        print_error_to_log "Failed to create temp file of '${file}'."
         return 1
       fi
     }
@@ -154,7 +161,7 @@
       is_file "${temp_file}" || return 1
 
       if ! cp --force "${temp_file}" "${file}"; then
-        print_prefix_error "Failed to overwrite file '${file}'."
+        print_error_to_log "Failed to overwrite file '${file}'."
         return 1
       fi
     }
@@ -179,7 +186,7 @@
       is_file "${temp_file}" &> /dev/null || return 0
 
       if ! rm --force --recursive "${temp_file}"; then
-        print_prefix_error "Failed to delete temp file '${temp_file}'."
+        print_error_to_log "Failed to delete temp file '${temp_file}'."
         return 1
       fi
     }
@@ -196,10 +203,91 @@
 
       for line in ${reference[*]}; do
         if ! sudo echo -e "${line}" >> "${file}"; then
-          print_prefix_error "Could not append to file."
+          print_error_to_log "Could not append to file."
           return 1
         fi
       done
+    }
+
+  # <summary>File validation</summary>
+    function is_file
+    {
+      if [[ -z "${1}" ]] \
+        || [[ ! -e "${1}" ]]; then
+        print_error_to_log "File does not exist."
+        return 1
+      fi
+    }
+
+    function is_file_not_empty
+    {
+      if [[ -z "${1}" ]] \
+        || [[ ! -s "${1}" ]]; then
+        print_error_to_log "File is empty."
+        return 1
+      fi
+    }
+
+   # <summary>GitHub</summary>
+    function clone_git_repo
+    {
+      local -r full_repo="${1}"
+
+      if ! git clone "https://github.com/${full_repo}" &> /dev/null; then
+        print_error_to_log "Failed to download repository."
+        return 1
+      fi
+    }
+
+    function update_git_repo
+    {
+      if ! git pull &> /dev/null; then
+        print_error_to_log "Failed to update repository."
+        return 1
+      fi
+    }
+
+    function update_or_clone_git_repo
+    {
+      local -r full_repo="${1}"
+      local -r user_name="${2}"
+      local -r full_path="${BIN_PATH}${full_repo}"
+      local -r user_path="${BIN_PATH}${user_name}"
+
+      if [[ ! -d "${user_path}" ]] \
+        && ! sudo mkdir --parents "${user_path}" &> /dev/null; then
+        print_error_to_log "Failed to create directory '${user_path}'."
+        return 1
+      fi
+
+      if [[ ! -d "${full_path}" ]]; then
+        cd "${full_path}"
+        update_git_repo
+
+      elif [[ -d "${user_path}" ]]; then
+        clone_git_repo "${full_repo}"
+
+      else
+        return 1
+      fi
+    }
+
+  # <summary>Handlers</summary>
+    function catch_error {
+      exit 255
+    }
+
+    function catch_exit {
+      print_pass_or_fail_to_log
+      reset_ifs
+    }
+
+    function is_user_superuser
+    {
+      if [[ $( whoami ) != "root" ]]; then
+        print_to_error_log "User is not sudo or root."
+        return 1
+      fi
     }
 
   # <summary>Interaction</summary>
@@ -230,43 +318,36 @@
       return 1
     }
 
+  # <summary>Loggers/summary>
+    function print_error_to_log
+    {
+       echo -e "${PREFIX_ERROR} ${1}" >&2
+    }
+
+    function print_fail_to_log
+    {
+      echo -e "${PREFIX_FAIL} ${1}" >&2
+    }
+
+    function print_pass_or_fail_to_log
+    {
+      if [[ "${?}" -ne 0 ]]; then
+        print_to_output_log "${PREFIX_FAIL}Setup incomplete."
+        return 1
+      fi
+
+      print_to_output_log "${PREFIX_PASS}Setup complete."
+    }
+
+    function print_pass_to_log
+    {
+      echo -e "${PREFIX_PASS} ${1}" >&1
+    }
+
   # <summary>Presentation/summary>
-    function is_file
-    {
-      if [[ -z "${1}" ]] \
-        || [[ ! -e "${1}" ]]; then
-        print_prefix_error "File does not exist."
-        return 1
-      fi
-    }
-
-    function is_file_not_empty
-    {
-      if [[ -z "${1}" ]] \
-        || [[ ! -s "${1}" ]]; then
-        print_prefix_error "File is empty."
-        return 1
-      fi
-    }
-
-    function print_prefix_error
-    {
-       echo -e "${PREFIX_ERROR} ${1}"
-    }
-
-    function print_prefix_fail
-    {
-      echo -e "${PREFIX_FAIL} ${1}"
-    }
-
-    function print_prefix_note
+    function print_note
     {
       echo -e "${PREFIX_NOTE} ${1}"
-    }
-
-    function print_prefix_pass
-    {
-      echo -e "${PREFIX_PASS} ${1}"
     }
 
     function print_suffix_error
@@ -287,50 +368,6 @@
     function print_suffix_pass
     {
       echo -e "${1} ${SUFFIX_PASS}"
-    }
-
-  # <summary>Variable data-type validation</summary>
-    function get_comma_delimited_string_from_enum
-    {
-      local -n enum_reference="${1}"
-      local -n delim_reference="${2}"
-
-      for value in ${enum_reference[@]}; do
-        delim_reference+="${value},"
-      done
-
-      if [[ ${delim_reference: -1} == "," ]]; then
-        delim_reference="${delim_reference::-1}"
-      fi
-    }
-
-    function is_enum
-    {
-      local -n reference="${1}"
-
-      if ! [[ "${#reference[@]}" -gt 0 ]]; then
-        return 1
-      fi
-    }
-
-    function is_enum_empty
-    {
-      is_enum "${1}" || return 1
-      local -n reference="${1}"
-
-      for value in "${reference[@]}"; do
-        if ! [[ ! -z "${value}" ]]; then
-          return 1
-        fi
-      done
-    }
-
-    function is_int
-    {
-      if ! [[ "${1}" =~ ^[0-9]+$ ]] \
-        && ! [[ "${1}" =~ ^[-][0-9]+$ ]]; then
-        return 1
-      fi
     }
 
   # <summary>System validation</summary>
