Added prefix params to loggers. Updated comments. Updated usecases of loggers.

diff --git a/bin/deploy-vfio_logic_common b/bin/deploy-vfio_logic_common
--- a/bin/deploy-vfio_logic_common
+++ b/bin/deploy-vfio_logic_common
@@ -24,44 +24,45 @@
     declare -gr REPO_NAME="portellam"
     declare -gr SCRIPT_NAME="deploy-vfio"
 
-    # <remarks>
+    # <summary>
     # Color coding
     # Reference URL: 'https://www.shellhacks.com/bash-colors'
-    # </remarks>
-    declare -gr SET_COLOR_GREEN='\033[0;32m'
-    declare -gr SET_COLOR_RED='\033[0;31m'
-    declare -gr SET_COLOR_YELLOW='\033[0;33m'
-    declare -gr RESET_COLOR='\033[0m'
+    # </summary>
+      declare -gr SET_COLOR_GREEN='\033[0;32m'
+      declare -gr SET_COLOR_RED='\033[0;31m'
+      declare -gr SET_COLOR_YELLOW='\033[0;33m'
+      declare -gr RESET_COLOR='\033[0m'
 
-    # <remarks>Append output</remarks>
-    declare -gr PREFIX_NOTE="${SET_COLOR_YELLOW}Note:${RESET_COLOR}"
-    declare -gr PREFIX_ERROR="${SET_COLOR_YELLOW}An error occurred:${RESET_COLOR}"
-    declare -gr PREFIX_FAIL="${SET_COLOR_RED}Failure:${RESET_COLOR}"
-    declare -gr PREFIX_PASS="${SET_COLOR_GREEN}Success:${RESET_COLOR}"
-    declare -gr SUFFIX_FAIL="${SET_COLOR_RED}[Failure]${RESET_COLOR}"
-    declare -gr SUFFIX_PASS="${SET_COLOR_GREEN}[Success]${RESET_COLOR}"
-    # declare -gr SUFFIX_SKIP="${SET_COLOR_YELLOW}[Skipped]${RESET_COLOR}"
-    # declare -gr SUFFIX_WORK="${SET_COLOR_YELLOW}[Working]${RESET_COLOR}"
+    # <summary>Append output</summary>
+      declare -gr PREFIX_PROMPT="${SCRIPT_NAME}: "
+      declare -gr PREFIX_NOTE="${PREFIX_PROMPT}${SET_COLOR_YELLOW}Note:${RESET_COLOR} "
+      declare -gr PREFIX_ERROR="${PREFIX_PROMPT}${SET_COLOR_YELLOW}An error occurred:${RESET_COLOR} "
+      declare -gr PREFIX_FAIL="${PREFIX_PROMPT}${SET_COLOR_RED}Failure:${RESET_COLOR} "
+      declare -gr PREFIX_PASS="${PREFIX_PROMPT}${SET_COLOR_GREEN}Success:${RESET_COLOR} "
+      declare -gr SUFFIX_FAIL="${SET_COLOR_RED}[Failure]${RESET_COLOR}"
+      declare -gr SUFFIX_PASS="${SET_COLOR_GREEN}[Success]${RESET_COLOR}"
+      # declare -gr SUFFIX_SKIP="${SET_COLOR_YELLOW}[Skipped]${RESET_COLOR}"
+      # declare -gr SUFFIX_WORK="${SET_COLOR_YELLOW}[Working]${RESET_COLOR}"
 
     declare -g PREFIX_COMMENT="#" # <note>Added this var, to prevent IDE from showing visual errors when a string contains a comment variable.</note>
 
     declare -gr BIN_PATH="/usr/local/bin/${SCRIPT_NAME}.d/"
     declare -gr ETC_BACKUPS_PATH="/usr/local/etc/${SCRIPT_NAME}.d/"
 
-    # <remarks>File templates.</remarks>
-    declare -gar DISCLAIMER_FILE_CONTENTS=(
-      "${PREFIX_COMMENT} Generated by '${REPO_NAME}/${SCRIPT_NAME}'"
-      "${PREFIX_COMMENT} WARNING: Any modifications to this file will be modified by '${SCRIPT_NAME}'"
-      "${PREFIX_COMMENT}"
-    )
+    # <summary>File templates.</summary>
+      declare -gar DISCLAIMER_FILE_CONTENTS=(
+        "${PREFIX_COMMENT} Generated by '${REPO_NAME}/${SCRIPT_NAME}'"
+        "${PREFIX_COMMENT} WARNING: Any modifications to this file will be modified by '${SCRIPT_NAME}'"
+        "${PREFIX_COMMENT}"
+      )
 
-    # <remarks>Memory</remarks>
-    declare -gi AVAILABLE_MEMORY=0
-    declare -gir ONE_GIB_IN_KIB=1048576
-    declare -gir TWO_MIB_IN_KIB=2048
-    declare -gir MAX_MEMORY=$( cat /proc/meminfo | grep MemTotal | cut -d ":" -f 2 | awk 'END {print $1}' )
-    declare -gir MIN_MEMORY=$(( 8 * ${ONE_GIB_IN_KIB} ))
-    set_free_memory
+    # <summary>Memory</summary>
+      declare -gi AVAILABLE_MEMORY=0
+      declare -gir ONE_GIB_IN_KIB=1048576
+      declare -gir TWO_MIB_IN_KIB=2048
+      declare -gir MAX_MEMORY=$( cat /proc/meminfo | grep MemTotal | cut -d ":" -f 2 | awk 'END {print $1}' )
+      declare -gir MIN_MEMORY=$(( 8 * ${ONE_GIB_IN_KIB} ))
+      set_free_memory
 
     declare -gr LOGIN_USER=$( who am i | awk '{print $1}' )
   }
@@ -321,33 +322,38 @@
   # <summary>Loggers/summary>
     function print_error_to_log
     {
-       echo -e "${PREFIX_ERROR} ${1}" >&2
+       echo -e "${PREFIX_ERROR}${1}" >&2
     }
 
     function print_fail_to_log
     {
-      echo -e "${PREFIX_FAIL} ${1}" >&2
+      echo -e "${PREFIX_FAIL}${1}" >&2
+    }
+
+    function print_output_to_log
+    {
+      echo -e "${PREFIX_PROMPT}${1}" >&1
     }
 
     function print_pass_or_fail_to_log
     {
       if [[ "${?}" -ne 0 ]]; then
-        print_to_output_log "${PREFIX_FAIL}Setup incomplete."
+        print_fail_to_log "Setup incomplete."
         return 1
       fi
 
-      print_to_output_log "${PREFIX_PASS}Setup complete."
+      print_output_to_log "Setup complete."
     }
 
     function print_pass_to_log
     {
-      echo -e "${PREFIX_PASS} ${1}" >&1
+      echo -e "${PREFIX_PASS}${1}" >&1
     }
 
   # <summary>Presentation/summary>
     function print_note
     {
-      echo -e "${PREFIX_NOTE} ${1}"
+      echo -e "${PREFIX_NOTE}${1}"
     }
 
     function print_suffix_error
