Revised null string checks. Added functionality to not exit script on skip execution.  Added function to prefix pass or fail to statement.

diff --git a/bin/vfiolib-common b/bin/vfiolib-common
--- a/bin/vfiolib-common
+++ b/bin/vfiolib-common
@@ -41,8 +41,8 @@
 
     function FindPackage
     {
-        if [[ "$1" == "" ]] \
-            || [[ "$_PACKAGE_MANAGER" == "" ]]; then
+        if [[ -z "$1" ]] \
+            || [[ -z "$_PACKAGE_MANAGER" ]]; then
             echo -e "$_PREFIX_ERROR Input values are empty."
             return 1
         fi
@@ -118,7 +118,7 @@
 
         if "$_IS_VERBOSE"; then
             ( return "$_LAST_EXIT_CODE" )
-            PrintPassOrFail
+            PrintSuffixPassOrFail
             echo -en "Testing connection to DNS...\t"
         fi
 
@@ -130,7 +130,7 @@
 
         if "$_IS_VERBOSE"; then
             ( return "$_LAST_EXIT_CODE" )
-            PrintPassOrFail
+            PrintSuffixPassOrFail
         fi
 
         if [[ "$_LAST_EXIT_CODE" -ne 0 ]]; then
@@ -173,7 +173,7 @@
                 _PACKAGE_MANAGER=""
             fi
 
-            if ! command -v "$_PACKAGE_MANAGER"; then
+            if ! command -v "$_PACKAGE_MANAGER" &> /dev/null; then
                 return 1
             fi
 
@@ -188,7 +188,7 @@
         local _OS_WITH_URPMI="opensuse"
         local _OS_WITH_ZYPPER="mandriva mageia"
 
-        if [[ "$_KERNEL" == "" || "$_OPERATING_SYSTEM" == "" ]]; then
+        if [[ -z "$_KERNEL" || -z "$_OPERATING_SYSTEM" ]]; then
             echo -e "$_PREFIX_ERROR Null values."
             return 1
         fi
@@ -208,8 +208,8 @@
 
     function InstallPackage
     {
-        if [[ "$_PACKAGE_MANAGER" == "" ]] \
-            || [[ "$1" == "" ]]; then
+        if [[ -z "$_PACKAGE_MANAGER" ]] \
+            || [[ -z "$1" ]]; then
             echo -e "$_PREFIX_ERROR Input values are empty."
             return 1
         fi
@@ -253,14 +253,14 @@
                 false ;;
         esac
 
-        PrintPassOrFail "Installing software packages..."
+        PrintSuffixPassOrFail "Installing software packages..."
         return "$?"
     }
 
     function IsInstalledPackage
     {
-        if [[ "$_PACKAGE_MANAGER" == "" ]] \
-            || [[ "$1" == "" ]]; then
+        if [[ -z "$_PACKAGE_MANAGER" ]] \
+            || [[ -z "$1" ]]; then
             echo -e "$_PREFIX_ERROR Input values are empty."
             return 1
         fi
@@ -298,11 +298,35 @@
         return 0
     }
 
-    function PrintPassOrFail
+    function PrintPrefixPassOrFail
     {
         SaveExitCode
 
-        if [[ "$1" != "" ]]; then
+        case "$_LAST_EXIT_CODE" in
+            0 )
+                echo -en "$_PREFIX_PASS" ;;
+
+            255 )
+                echo -en "$_PREFIX_SKIP" ;;
+
+            * )
+                echo -en "$_PREFIX_FAIL" ;;
+        esac
+
+        if [[ -z "$1" ]]; then
+            echo
+        else
+            echo -e " $1"
+        fi
+
+        return "$_LAST_EXIT_CODE"
+    }
+
+    function PrintSuffixPassOrFail
+    {
+        SaveExitCode
+
+        if [[ ! -z "$1" ]]; then
             echo -en "$1\t"
         fi
 
@@ -327,8 +351,8 @@
 
     function UninstallPackage
     {
-        if [[ "$_PACKAGE_MANAGER" == "" ]] \
-            || [[ "$1" == "" ]]; then
+        if [[ -z "$_PACKAGE_MANAGER" ]] \
+            || [[ -z "$1" ]]; then
             echo -e "$_PREFIX_ERROR Input values are empty."
             return 1
         fi
@@ -361,7 +385,7 @@
                 false ;;
         esac
 
-        PrintPassOrFail "Uninstalling software packages..."
+        PrintSuffixPassOrFail "Uninstalling software packages..."
         return "$?"
     }
 
@@ -373,9 +397,9 @@
             _AUTO_ANSWER_YES=true
         fi
 
-        if [[ "$3" == "" ]] \
-            || [[ "$2" == "" ]] \
-            || [[ "$1" == "" ]]; then
+        if [[ -z "$3" ]] \
+            || [[ -z "$2" ]] \
+            || [[ -z "$1" ]]; then
             echo -e "$_PREFIX_ERROR Input values are empty."
             return 1
         fi
@@ -437,8 +461,6 @@
     declare -g _OUTPUT_INVALID_PACKAGE_MANAGER="$_PREFIX_ERROR Command '$_PACKAGE_MANAGER' is not supported."
 
     # <remarks> System validation </remarks>
-    declare -gl _PACKAGE_MANAGER=""
+    declare -gl _PACKAGE_MANAGER
     declare -gl _OPERATING_SYSTEM="$( lsb_release -is )"
-    # declare -gl _LINUX_FAMILY=""
-    GetLinuxDistro
 # </params>
diff --git a/bin/vfiolib-extras b/bin/vfiolib-extras
--- a/bin/vfiolib-extras
+++ b/bin/vfiolib-extras
@@ -109,6 +109,7 @@
 		local -r _REPO_NAME="zram-swap"
 		local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
 		local _HAS_SKIPPED=false
+        echo
 
 		if ! "$_EXECUTE_ZRAM_SWAP" \
 			&& ! AskToExecuteOrSkip "Install zram-swap?"; then
@@ -127,51 +128,62 @@
 			( return 255 )
 		fi
 
-		PrintPassOrFail "Allocating RAM to swap..."
+		PrintSuffixPassOrFail "Allocating RAM to swap..."
 		return "$_LAST_EXIT_CODE"
 	}
 
 	function ExecuteExtras
 	{
-		if "$_EXECUTE_ALL_EXTRA_SETUPS"; then
-			Allocate_RAM_ToSwap
-			SetVideoOutput
-			LibvirtHooks
-			GuestAudioLoopback
-			# NOTE: these functions always fail at build stage.
-			# TODO: fix!
-			# GuestAudioStream
-			# GuestVideoCapture
-			return 0
-		fi
+        function Main
+        {
+            while [[ "$?" -ne 1 ]]; do
+                if "$_EXECUTE_ALL_EXTRA_SETUPS"; then
+                    Allocate_RAM_ToSwap
+                    SetVideoOutput
+                    LibvirtHooks
+                    GuestAudioLoopback
+                    # NOTE: these functions always fail at build stage.
+                    # TODO: fix!
+                    # GuestAudioStream
+                    # GuestVideoCapture
+                    break
+                fi
 
-		if "$_EXECUTE_ZRAM_SWAP"; then
-			Allocate_RAM_ToSwap || return 1
-		fi
+                if "$_EXECUTE_ZRAM_SWAP"; then
+                    Allocate_RAM_ToSwap
+                fi
 
-		if "$_EXECUTE_AUTO_XORG_SETUP"; then
-			SetVideoOutput || return 1
-		fi
+                if "$_EXECUTE_AUTO_XORG_SETUP"; then
+                    SetVideoOutput
+                fi
 
-		if "$_EXECUTE_LIBVIRT_HOOKS"; then
-			LibvirtHooks || return 1
-		fi
+                if "$_EXECUTE_LIBVIRT_HOOKS"; then
+                    LibvirtHooks
+                fi
 
-		if "$_EXECUTE_AUDIO_LOOPBACK_SETUP"; then
-			GuestAudioLoopback || return 1
-		fi
+                if "$_EXECUTE_AUDIO_LOOPBACK_SETUP"; then
+                    GuestAudioLoopback
+                fi
 
-		# NOTE: these functions always fail at build stage.
-		# TODO: fix!
-		# if "$_EXECUTE_SCREAM"; then
-		#     GuestAudioStream || return 1
-		# fi
+                # NOTE: these functions always fail at build stage.
+                # TODO: fix!
+                # if "$_EXECUTE_SCREAM"; then
+                #     GuestAudioStream
+                # fi
 
-		# if "$_EXECUTE_LOOKING_GLASS"; then
-		#     GuestVideoCapture || return 1
-		# fi
+                # if "$_EXECUTE_LOOKING_GLASS"; then
+                #     GuestVideoCapture
+                # fi
 
-		return 0
+                break
+            done
+
+            return "$?"
+        }
+
+        Main
+        PrintSuffixPassOrFail "Executing post-install..."
+		return "$?"
 	}
 
 	# <summary>
@@ -235,7 +247,7 @@
 		}
 
 		Main
-		PrintPassOrFail "Installing audio drivers..." && _IS_AUDIO_CAPTURE_SETUP=true
+		PrintSuffixPassOrFail "Installing audio drivers..." && _IS_AUDIO_CAPTURE_SETUP=true
 		return "$_LAST_EXIT_CODE"
 	}
 
@@ -276,6 +288,7 @@
 		}
 
 		local _HAS_SKIPPED=false
+        echo
 
 		if ! "$_EXECUTE_AUDIO_LOOPBACK_SETUP" \
 			&& ! AskToExecuteOrSkip "Install audio loopback service?"; then
@@ -291,7 +304,7 @@
 			( return 255 )
 		fi
 
-		PrintPassOrFail "Creating audio loopback..."
+		PrintSuffixPassOrFail "Creating audio loopback..."
 		return "$_LAST_EXIT_CODE"
 	}
 
@@ -370,7 +383,7 @@
 				esac
 
 			else
-				return 1Rneamed fi
+				return 1
 			fi
 
 			# <remarks> Get dependencies. </remarks>
@@ -466,6 +479,7 @@
 		}
 
 		local _HAS_SKIPPED=false
+        echo
 
 		if ! "$_EXECUTE_SCREAM" \
 			&& ! AskToExecuteOrSkip "Install Scream?"; then
@@ -477,10 +491,10 @@
 				false
 			else
 				Get
-				PrintPassOrFail "Updating Scream..."
+				PrintSuffixPassOrFail "Updating Scream..."
 
 				if Build; then
-					PrintPassOrFail "Building Scream..."
+					PrintSuffixPassOrFail "Building Scream..."
 					Install && Modify
 				fi
 			fi
@@ -490,7 +504,7 @@
 			( return 255 )
 		fi
 
-		PrintPassOrFail "Installing Scream...\t" && _IS_SCREAM_SETUP=true
+		PrintSuffixPassOrFail "Installing Scream...\t" && _IS_SCREAM_SETUP=true
 		return "$_LAST_EXIT_CODE"
 	}
 
@@ -602,6 +616,7 @@
 		}
 
 		local _HAS_SKIPPED=false
+        echo
 
 		if ! "$_EXECUTE_LOOKING_GLASS" \
 			&& ! AskToExecuteOrSkip "Install Looking Glass?"; then
@@ -610,7 +625,7 @@
 
 		if ! "$_HAS_SKIPPED"; then
 			Get
-			PrintPassOrFail "Updating Looking Glass..."
+			PrintSuffixPassOrFail "Updating Looking Glass..."
 			Install && Modify
 		fi
 
@@ -618,7 +633,7 @@
 			( return 255 )
 		fi
 
-		PrintPassOrFail "Installing Looking Glass..."
+		PrintSuffixPassOrFail "Installing Looking Glass..."
 		return "$_LAST_EXIT_CODE"
 	}
 
@@ -680,6 +695,7 @@
 		}
 
 		local _HAS_SKIPPED=false
+        echo
 
 		if ! "$_EXECUTE_LIBVIRT_HOOKS" \
 			&& ! AskToExecuteOrSkip "Install Libvirt hooks?"; then
@@ -694,7 +710,7 @@
 			( return 255 )
 		fi
 
-		PrintPassOrFail "Installing Libvirt hooks..."
+		PrintSuffixPassOrFail "Installing Libvirt hooks..."
 		return "$_LAST_EXIT_CODE"
 	}
 
@@ -740,6 +756,7 @@
 		local -r _REPO_NAME="auto-Xorg"
 		local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
 		local _HAS_SKIPPED=false
+        echo
 
 		if ! "$_EXECUTE_AUTO_XORG_SETUP" \
 			&& ! AskToExecuteOrSkip "Install auto-Xorg?"; then
@@ -755,7 +772,7 @@
 			( return 255 )
 		fi
 
-		PrintPassOrFail "Installing auto-Xorg...\t"
+		PrintSuffixPassOrFail "Installing auto-Xorg...\t"
 		return "$_LAST_EXIT_CODE"
 	}
 # </code>
diff --git a/bin/vfiolib-setup b/bin/vfiolib-setup
--- a/bin/vfiolib-setup
+++ b/bin/vfiolib-setup
@@ -128,53 +128,62 @@
     {
         function Main
         {
-            if ! "$_EXECUTE_MULTIBOOT_SETUP" \
-                && ! "$_EXECUTE_STATIC_SETUP" \
-                && ! "$_EXECUTE_UNINSTALL_SETUP"; then
-                for _TRIES_COUNT in $( seq 0 2 ); do
-                    read -r -p "Execute VFIO setup? [(M)ultiboot/(S)tatic/(U)ninstall/(N)o]: " _ANSWER
+            while [[ "$?" -ne 1 ]]; do
+                if ! "$_EXECUTE_MULTIBOOT_SETUP" \
+                    && ! "$_EXECUTE_STATIC_SETUP" \
+                    && ! "$_EXECUTE_UNINSTALL_SETUP"; then
+                    for _TRIES_COUNT in $( seq 0 2 ); do
+                        read -r -p "Execute VFIO setup? [(M)ultiboot/(S)tatic/(U)ninstall/(N)o]: " _ANSWER
 
-                    case "$_ANSWER" in
-                        [Mm]* )
-                            _EXECUTE_MULTIBOOT_SETUP=true
-                            break ;;
+                        case "$_ANSWER" in
+                            [Mm]* )
+                                _EXECUTE_MULTIBOOT_SETUP=true
+                                break ;;
 
-                        [Ss]* )
-                            _EXECUTE_STATIC_SETUP=true
-                            break ;;
+                            [Ss]* )
+                                _EXECUTE_STATIC_SETUP=true
+                                break ;;
 
-                        [Uu]* )
-                            _EXECUTE_UNINSTALL_SETUP=true
-                            break ;;
+                            [Uu]* )
+                                _EXECUTE_UNINSTALL_SETUP=true
+                                break ;;
 
-                        [Nn]* )
-                            return 255 ;;
+                            [Nn]* )
+                                return 255 ;;
 
-                        * )
-                            echo "Please answer \"M\", \"S\", \"U\", or \"N\"." ;;
-                    esac
-                done
+                            * )
+                                echo "Please answer \"M\", \"S\", \"U\", or \"N\"." ;;
+                        esac
+                    done
 
-                if ! [[ "$_ANSWER" =~ [MmSsUuNn] ]]; then
-                    echo -e "$_PREFIX_ERROR Failed to answer."
-                    return 1
+                    if ! [[ "$_ANSWER" =~ [MmSsUuNn] ]]; then
+                        echo -e "$_PREFIX_ERROR Failed to answer."
+                        return 1
+                    fi
                 fi
-            fi
 
-            case true in
-                "$_EXECUTE_MULTIBOOT_SETUP" )
-                    ExecuteMultibootSetup || return 1 ;;
+                case true in
+                    "$_EXECUTE_MULTIBOOT_SETUP" )
+                        ExecuteParse || return 1
+                        ExecuteMultibootSetup || return 1 ;;
 
-                "$_EXECUTE_STATIC_SETUP" )
-                    ExecuteStaticSetup || return 1 ;;
+                    "$_EXECUTE_STATIC_SETUP" )
+                        ExecuteParse || return 1
+                        ExecuteStaticSetup || return 1 ;;
 
-                "$_EXECUTE_UNINSTALL_SETUP" )
-                    ExecuteUninstallSetup || return 1 ;;
-            esac
+                    "$_EXECUTE_UNINSTALL_SETUP" )
+                        ExecuteUninstallSetup || return 1 ;;
+                esac
+
+                break
+            done
+
+            return "$?"
         }
 
+        echo
         Main
-        PrintPassOrFail "Deploying VFIO setup...\t"
+        PrintSuffixPassOrFail "Executing VFIO setup...\t"
         return "$_LAST_EXIT_CODE"
     }
 
