Working before the weekend.

diff --git a/bin/vfiolib-common b/bin/vfiolib-common
--- a/bin/vfiolib-common
+++ b/bin/vfiolib-common
@@ -12,217 +12,218 @@
 # </sources>
 
 # <functions>
-    # <summary> Public getters </summary>
-        function GetInternetStatus
-        {
-            function PingServer
+    # <summary> Public </summary>
+        # <summary> Global getters </summary>
+            function GetInternetStatus
             {
-                IsString $1 || return 1
-                ping -q -c 1 $1 &> /dev/null
-                return "$?"
-            }
+                function PingServer
+                {
+                    IsString $1 || return 1
+                    ping -q -c 1 $1 &> /dev/null
+                    return "$?"
+                }
 
-            local _IS_VERBOSE=false
+                local _IS_VERBOSE=false
 
-            if [[ "$1" == true ]]; then
-                _IS_VERBOSE=true
-            fi
-
-            if "$_IS_VERBOSE"; then
-                echo -en "Testing Internet connection...\t"
-            fi
-
-            if ! PingServer "8.8.8.8" || ! PingServer "1.1.1.1"; then
-                false
-            fi
-
-            SaveExitCode
-
-            if "$_IS_VERBOSE"; then
-                ( return "$_LAST_EXIT_CODE" )
-                PrintSuffixPassOrFail
-                echo -en "Testing connection to DNS...\t"
-            fi
-
-            if ! PingServer "www.google.com" || ! PingServer "www.yandex.com"; then
-                false
-            fi
-
-            SaveExitCode
-
-            if "$_IS_VERBOSE"; then
-                ( return "$_LAST_EXIT_CODE" )
-                PrintSuffixPassOrFail
-            fi
-
-            if [[ "$_LAST_EXIT_CODE" -ne 0 ]]; then
-                echo -e "Failed to ping Internet/DNS servers. Check network settings or firewall, and try again."
-            fi
-
-            return "$_LAST_EXIT_CODE"
-        }
-
-        function GetLinuxDistro
-        {
-            # <summary> Check if current Operating System matches Package Manager, and Check if PM is installed. </summary>
-            function GetPackageManagerBy_OS
-            {
-                if [[ "$_OS_WITH_APT" =~ .*${_OPERATING_SYSTEM}.* ]]; then
-                    _PACKAGE_MANAGER="apt"
-
-                elif [[ "$_OS_WITH_DNF_OR_YUM" =~ .*${_OPERATING_SYSTEM}.* ]]; then
-                    _PACKAGE_MANAGER="dnf"
-
-                    if command -v "$_PACKAGE_MANAGER"; then
-                        return 0
-                    fi
-
-                    _PACKAGE_MANAGER="yum"
-
-                elif [[ "$_OS_WITH_PACMAN" =~ .*${_OPERATING_SYSTEM}.* ]]; then
-                    _PACKAGE_MANAGER="pacman"
-
-                elif [[ "$_OS_WITH_PORTAGE" =~ .*${_OPERATING_SYSTEM}.* ]]; then
-                    _PACKAGE_MANAGER="portage"
-
-                elif [[ "$_OS_WITH_URPMI" =~ .*${_OPERATING_SYSTEM}.* ]]; then
-                    _PACKAGE_MANAGER="urpmi"
-
-                elif [[ "$_OS_WITH_ZYPPER" =~ .*${_OPERATING_SYSTEM}.* ]]; then
-                    _PACKAGE_MANAGER="zypper"
-
-                else
-                    _PACKAGE_MANAGER=""
+                if [[ "$1" == true ]]; then
+                    _IS_VERBOSE=true
                 fi
 
-                if ! command -v "$_PACKAGE_MANAGER" &> /dev/null; then
+                if "$_IS_VERBOSE"; then
+                    echo -en "Testing Internet connection...\t"
+                fi
+
+                if ! PingServer "8.8.8.8" || ! PingServer "1.1.1.1"; then
+                    false
+                fi
+
+                SaveExitCode
+
+                if "$_IS_VERBOSE"; then
+                    ( return "$_LAST_EXIT_CODE" )
+                    PrintSuffixPassOrFail
+                    echo -en "Testing connection to DNS...\t"
+                fi
+
+                if ! PingServer "www.google.com" || ! PingServer "www.yandex.com"; then
+                    false
+                fi
+
+                SaveExitCode
+
+                if "$_IS_VERBOSE"; then
+                    ( return "$_LAST_EXIT_CODE" )
+                    PrintSuffixPassOrFail
+                fi
+
+                if [[ "$_LAST_EXIT_CODE" -ne 0 ]]; then
+                    echo -e "Failed to ping Internet/DNS servers. Check network settings or firewall, and try again."
+                fi
+
+                return "$_LAST_EXIT_CODE"
+            }
+
+            function GetLinuxDistro
+            {
+                # <summary> Check if current Operating System matches Package Manager, and Check if PM is installed. </summary>
+                function GetPackageManagerBy_OS
+                {
+                    if [[ "$_OS_WITH_APT" =~ .*${_OPERATING_SYSTEM}.* ]]; then
+                        _PACKAGE_MANAGER="apt"
+
+                    elif [[ "$_OS_WITH_DNF_OR_YUM" =~ .*${_OPERATING_SYSTEM}.* ]]; then
+                        _PACKAGE_MANAGER="dnf"
+
+                        if command -v "$_PACKAGE_MANAGER"; then
+                            return 0
+                        fi
+
+                        _PACKAGE_MANAGER="yum"
+
+                    elif [[ "$_OS_WITH_PACMAN" =~ .*${_OPERATING_SYSTEM}.* ]]; then
+                        _PACKAGE_MANAGER="pacman"
+
+                    elif [[ "$_OS_WITH_PORTAGE" =~ .*${_OPERATING_SYSTEM}.* ]]; then
+                        _PACKAGE_MANAGER="portage"
+
+                    elif [[ "$_OS_WITH_URPMI" =~ .*${_OPERATING_SYSTEM}.* ]]; then
+                        _PACKAGE_MANAGER="urpmi"
+
+                    elif [[ "$_OS_WITH_ZYPPER" =~ .*${_OPERATING_SYSTEM}.* ]]; then
+                        _PACKAGE_MANAGER="zypper"
+
+                    else
+                        _PACKAGE_MANAGER=""
+                    fi
+
+                    if ! command -v "$_PACKAGE_MANAGER" &> /dev/null; then
+                        return 1
+                    fi
+
+                    return 0
+                }
+
+                local _KERNEL="$( uname -o | tr '[:upper:]' '[:lower:]' )"
+                local _OS_WITH_APT="debian bodhi deepin knoppix mint peppermint pop ubuntu kubuntu lubuntu xubuntu"
+                local _OS_WITH_DNF_OR_YUM="redhat alma berry centos cern clearos elastix fedora fermi frameos mageia opensuse oracle scientific suse"
+                local _OS_WITH_PACMAN="arch manjaro"
+                local _OS_WITH_PORTAGE="gentoo"
+                local _OS_WITH_URPMI="opensuse"
+                local _OS_WITH_ZYPPER="mandriva mageia"
+
+                if [[ -z "$_KERNEL" || -z "$_OPERATING_SYSTEM" ]]; then
+                    echo -e "$_PREFIX_ERROR Null values."
+                    return 1
+                fi
+
+                if [[ "$_KERNEL" != *"linux"* ]]; then
+                    echo -e "$_PREFIX_ERROR Kernel '$( uname -o )' is not supported."
+                    return 1
+                fi
+
+                if ! GetPackageManagerBy_OS; then
+                    echo -e "$_PREFIX_ERROR Distribution '$( lsb_release -is )' is not supported."
                     return 1
                 fi
 
                 return 0
             }
 
-            local _KERNEL="$( uname -o | tr '[:upper:]' '[:lower:]' )"
-            local _OS_WITH_APT="debian bodhi deepin knoppix mint peppermint pop ubuntu kubuntu lubuntu xubuntu"
-            local _OS_WITH_DNF_OR_YUM="redhat alma berry centos cern clearos elastix fedora fermi frameos mageia opensuse oracle scientific suse"
-            local _OS_WITH_PACMAN="arch manjaro"
-            local _OS_WITH_PORTAGE="gentoo"
-            local _OS_WITH_URPMI="opensuse"
-            local _OS_WITH_ZYPPER="mandriva mageia"
+        # <summary> Global setters </summary>
+            function SetParameters
+            {
+                declare -g _OUTPUT_INVALID_PACKAGE_MANAGER="$_PREFIX_ERROR Command '$_PACKAGE_MANAGER' is not supported."
 
-            if [[ -z "$_KERNEL" || -z "$_OPERATING_SYSTEM" ]]; then
-                echo -e "$_PREFIX_ERROR Null values."
+                # <remarks> System validation </remarks>
+                declare -gl _PACKAGE_MANAGER
+                declare -gl _OPERATING_SYSTEM="$( lsb_release -is )"
+            }
+
+        # <summary> Interaction </summary>
+            function AskToExecuteOrSkip
+            {
+                local OUTPUT=""
+
+                if [[ ! -z "$1" ]]; then
+                    OUTPUT="$1 "
+                fi
+
+                for TRY_COUNT in $( seq 0 2 ); do
+                    read -r -p "$OUTPUT[Y/n]: " ANSWER
+
+                    case "$ANSWER" in
+                        [Yy]* )
+                            return 0 ;;
+
+                        [Nn]* )
+                            return 255 ;;
+
+                        * )
+                            echo "Please answer 'Y' or 'N'." ;;
+                    esac
+                done
+
                 return 1
-            fi
+            }
 
-            if [[ "$_KERNEL" != *"linux"* ]]; then
-                echo -e "$_PREFIX_ERROR Kernel '$( uname -o )' is not supported."
-                return 1
-            fi
+        # <summary> Presentation </summary>
+            function PrintPrefixPassOrFail
+            {
+                SaveExitCode
 
-            if ! GetPackageManagerBy_OS; then
-                echo -e "$_PREFIX_ERROR Distribution '$( lsb_release -is )' is not supported."
-                return 1
-            fi
+                case "$_LAST_EXIT_CODE" in
+                    0 )
+                        echo -en "$_PREFIX_PASS" ;;
 
-            return 0
-        }
-
-    # <summary> Public setters </summary>
-        function SetParameters
-        {
-            declare -g _OUTPUT_INVALID_PACKAGE_MANAGER="$_PREFIX_ERROR Command '$_PACKAGE_MANAGER' is not supported."
-
-            # <remarks> System validation </remarks>
-            declare -gl _PACKAGE_MANAGER
-            declare -gl _OPERATING_SYSTEM="$( lsb_release -is )"
-        }
-
-    # <summary> Interaction </summary>
-        function AskToExecuteOrSkip
-        {
-            local OUTPUT=""
-
-            if [[ ! -z "$1" ]]; then
-                OUTPUT="$1 "
-            fi
-
-            for TRY_COUNT in $( seq 0 2 ); do
-                read -r -p "$OUTPUT[Y/n]: " ANSWER
-
-                case "$ANSWER" in
-                    [Yy]* )
-                        return 0 ;;
-
-                    [Nn]* )
-                        return 255 ;;
+                    255 )
+                        echo -en "$_PREFIX_SKIP" ;;
 
                     * )
-                        echo "Please answer 'Y' or 'N'." ;;
+                        echo -en "$_PREFIX_FAIL" ;;
                 esac
-            done
 
-            return 1
-        }
+                if [[ -z "$1" ]]; then
+                    echo
+                else
+                    echo -e " $1"
+                fi
 
-    # <summary> Presentation </summary>
-        function PrintPrefixPassOrFail
-        {
-            SaveExitCode
+                return "$_LAST_EXIT_CODE"
+            }
 
-            case "$_LAST_EXIT_CODE" in
-                0 )
-                    echo -en "$_PREFIX_PASS" ;;
+            function PrintSuffixPassOrFail
+            {
+                SaveExitCode
 
-                255 )
-                    echo -en "$_PREFIX_SKIP" ;;
+                if [[ ! -z "$1" ]]; then
+                    echo -en "$1\t"
+                fi
 
-                * )
-                    echo -en "$_PREFIX_FAIL" ;;
-            esac
+                case "$_LAST_EXIT_CODE" in
+                    0 )
+                        echo -e "$_SUFFIX_PASS" ;;
 
-            if [[ -z "$1" ]]; then
-                echo
-            else
-                echo -e " $1"
-            fi
+                    255 )
+                        echo -e "$_SUFFIX_SKIP" ;;
 
-            return "$_LAST_EXIT_CODE"
-        }
+                    * )
+                        echo -e "$_SUFFIX_FAIL" ;;
+                esac
 
-        function PrintSuffixPassOrFail
-        {
-            SaveExitCode
+                return "$_LAST_EXIT_CODE"
+            }
 
-            if [[ ! -z "$1" ]]; then
-                echo -en "$1\t"
-            fi
+            function PrintSuffixWait
+            {
+                if [[ ! -z "$1" ]]; then
+                    echo -en "$1\t"
+                fi
 
-            case "$_LAST_EXIT_CODE" in
-                0 )
-                    echo -e "$_SUFFIX_PASS" ;;
+                echo -e "$_SUFFIX_WORK"
+                return 0
+            }
 
-                255 )
-                    echo -e "$_SUFFIX_SKIP" ;;
-
-                * )
-                    echo -e "$_SUFFIX_FAIL" ;;
-            esac
-
-            return "$_LAST_EXIT_CODE"
-        }
-
-        function PrintSuffixWait
-        {
-            if [[ ! -z "$1" ]]; then
-                echo -en "$1\t"
-            fi
-
-            echo -e "$_SUFFIX_WORK"
-            return 0
-        }
-
-    # <summary> Unnamed </summary>
+        # <summary> Unnamed </summary>
         function FindPackage
         {
             if [[ -z "$1" ]] \
