Saving my work.

diff --git a/bin/vfiolib-setup b/bin/vfiolib-setup
--- a/bin/vfiolib-setup
+++ b/bin/vfiolib-setup
@@ -107,6 +107,8 @@
     {
         local -r _PRINT_FAIL="$_PREFIX_ERROR Static setup has failed."
 
+        # RemoveProblemFilesForStaticSetup || return 1
+
         if "$_ASK_TO_SELECT_TYPE_OF_STATIC_SETUP"; then
             AskToSpecifyStaticSetup || return 1
         fi
@@ -218,6 +220,17 @@
         return 0
     }
 
+    function RemoveProblemFilesForStaticSetup
+    {
+        if [[ -d $( dirname "$_CUSTOM_GRUB_DEST_PATH" ) ]] \
+            && ! sudo rm -rf $( dirname "$_CUSTOM_GRUB_DEST_PATH" ); then
+            echo -e "$_PREFIX_ERROR Failed to delete directory '"$( dirname "$_CUSTOM_GRUB_DEST_PATH" )"'."
+            return 1
+        fi
+
+        return 0
+    }
+
     function SetParamsForGRUBStaticSetup
     {
         IFS=$'\n'
@@ -272,20 +285,21 @@
     {
         GetParamsForSetup || return 1
         IFS=$'\n'
-        local -a _FILE_CONTENTS_LIST=( )
-        local -a _STATIC_DRIVER_LIST=( "${_DRIVER_LIST_VFIOPCI[@]}" "${_DRIVER_LIST_VFIOPCI_WITH_VGA[@]}" )
-        local -a _STATIC_HWID_LIST=( "${_HWID_LIST_PCISTUB[@]}" "${_HWID_LIST_VFIOPCI[@]}" "${_HWID_LIST_VFIOPCI_WITH_VGA[@]}" )
+        declare -ag _FILE_CONTENTS_LIST=( )
+        declare -ag _STATIC_DRIVER_LIST=( "${_DRIVER_LIST_VFIOPCI[@]}" "${_DRIVER_LIST_VFIOPCI_WITH_VGA[@]}" )
+        declare -ag _STATIC_HWID_LIST=( "${_HWID_LIST_PCISTUB[@]}" "${_HWID_LIST_VFIOPCI[@]}" "${_HWID_LIST_VFIOPCI_WITH_VGA[@]}" )
         _STATIC_DRIVER_LIST=( $( sort --uniq <<<"${_STATIC_DRIVER_LIST[*]}" ) )
         _STATIC_HWID_LIST=( $( sort --uniq <<<"${_STATIC_HWID_LIST[*]}" ) )
-        local -a _BLACKLISTS_LIST=()
-        local -a _INITRAMFS_LIST=()
-        local -a _MODULES_LIST=()
+        declare -ag _BLACKLISTS_LIST=( )
+        declare -ag _INITRAMFS_LIST=( )
+        declare -ag _MODULES_LIST=( )
         declare -g _DRIVER_DELIM=""
         declare -g _HWID_DELIM=""
         unset IFS
 
         for _DRIVER in ${_STATIC_DRIVER_LIST[@]}; do
-            if [[ "$_DRIVER" != "" ]]; then
+            if [[ "$_DRIVER" != "" ]] \
+                && [[ "$_DRIVER" != "N/A" ]]; then
                 _DRIVER_DELIM+="$_DRIVER,"
 
                 _BLACKLISTS_LIST+=(
@@ -396,6 +410,7 @@
 
             _NO_VGA_DRIVER_DELIM="${_NO_VGA_DRIVER_DELIM::-1}"
             _NO_VGA_HWID_DELIM="${_NO_VGA_HWID_DELIM::-1}"
+
             echo "_NO_VGA_DRIVER_DELIM == '$_NO_VGA_DRIVER_DELIM'"
             echo "_NO_VGA_HWID_DELIM == '$_NO_VGA_HWID_DELIM'"
 
@@ -455,14 +470,51 @@
         _LINE_GRUB_CMDLINE_TEMP="${_LINE_GRUB_CMDLINE_TEMP::-1}"
         local -r _LINE_GRUB_CMDLINE_DEFAULT="GRUB_CMDLINE_LINUX_DEFAULT=\"$_LINE_GRUB_CMDLINE_TEMP\""
 
-        # TODO: find line to start at, then output array at that line.
+        # <remarks> Write to new file. </remarks>
+        local -i _KEY=$(( "${#_INITRAMFS_LIST[@]}" - 1 ))
+        local -i _NUM_LINE=23
 
+        while [[ "$_KEY" -ge 0 ]]; do
+            _LINE="${_INITRAMFS_LIST[$_KEY]}"
+
+            if ! sed -i "23i $_LINE" "$_INITRAMFS_MODULES_DEST_PATH"; then
+                echo -e "$_PREFIX_ERROR Failed to overwrite target lines of files."
+                return 1
+            fi
+
+            (( --_KEY ))
+        done
+
+        if [[ "$?" -ne 0 ]]; then
+            echo -e "$_PREFIX_ERROR Failed to overwrite target lines of files."
+            return 1
+        fi
+
+        # <remarks> Write to new file. </remarks>
+        local -i _KEY=$(( "${#_MODULES_LIST[@]}" - 1 ))
+        local -i _NUM_LINE=7
+
+        while [[ "$_KEY" -ge 0 ]]; do
+            _LINE="${_MODULES_LIST[$_KEY]}"
+
+            if ! sed -i "7i $_LINE" "$_MODPROBE_VFIO_DEST_PATH"; then
+                echo -e "$_PREFIX_ERROR Failed to overwrite target lines of files."
+                return 1
+            fi
+
+            (( --_KEY ))
+        done
+
+        if [[ "$?" -ne 0 ]]; then
+            echo -e "$_PREFIX_ERROR Failed to overwrite target lines of files."
+            return 1
+        fi
+
+        # <remarks> Write to new files. </remarks>
         if ! sed -i '/'$_LINE_TO_MATCH'/c\'"$_LINE_GRUB_CMDLINE_DEFAULT" "$_GRUB_DEST_PATH_1" \
-            || ! sed -i '/## REPLACE_THIS_LINE*/c\'"${_INITRAMFS_LIST[*]}" "$_INITRAMFS_MODULES_DEST_PATH" \
             || ! sed -i "/options vfio_pci ids=*/c\options vfio_pci_ids=\"$_HWID_DELIM\"" "$_INITRAMFS_MODULES_DEST_PATH" \
             || ! sed -i "/vfio_pci ids=*/c\vfio_pci_ids=\"$_HWID_DELIM\"" "$_INITRAMFS_MODULES_DEST_PATH" \
             || ! echo "${_BLACKLISTS_LIST[*]}" >> "$_MODPROBE_BLACKLISTS_DEST_PATH" \
-            || ! sed -i '/## REPLACE_THIS_LINE*/c\'"${_MODULES_LIST[*]}" "$_MODPROBE_VFIO_DEST_PATH" \
             || ! sed -i "/options vfio_pci ids=*/c\vfio_pci_ids=\"$_HWID_DELIM\"" "$_MODPROBE_VFIO_DEST_PATH" \
             || ! sed -i "/vfio_pci ids=*/c\vfio_pci_ids=\"$_HWID_DELIM\"" "$_MODULES_DEST_PATH"; then
             echo -e "$_PREFIX_ERROR Failed to overwrite target lines of files."
@@ -501,6 +553,12 @@
     {
         "$_HAS_EXECUTED_BACKUPS" || return 1
         IFS=$'\n'
+
+        if [[ -d $( dirname "$_CUSTOM_GRUB_DEST_PATH" ) ]] \
+            && ! sudo mkdir -p $( dirname "$_CUSTOM_GRUB_DEST_PATH" ); then
+            echo -e "$_PREFIX_ERROR Failed to create directory '"$( dirname "$_CUSTOM_GRUB_DEST_PATH" )"'."
+            return 1
+        fi
 
         if ! echo -e "\n${_FILE_CONTENTS_LIST[*]}" >> "$_CUSTOM_GRUB_DEST_PATH"; then
             echo -e "$_PREFIX_ERROR Failed to overwrite target lines of files."
