Added commands. Fixed error in conditional. Made code blocks in subfunctions.

diff --git a/bin/vfiolib-setup b/bin/vfiolib-setup
--- a/bin/vfiolib-setup
+++ b/bin/vfiolib-setup
@@ -86,7 +86,7 @@
                 local str_IOMMU="${arr_IOMMU[$int_key]}"
 
                 # <remarks> Add IOMMU group if it is not in the VGA list or if it does not match the given IOMMU group, and if it not in the current VFIO list. </remarks>
-                if ( ! FindLineInArray "arr_IOMMU_VFIO_PCI_with_VGA" "${str_IOMMU}" || [[ "${str_IOMMU} != $1" ]] ) ! [[ "${str_multiboot_drivers}" ~= *"${str_driver}"* ]]; then
+                if ( ! FindLineInArray "arr_IOMMU_VFIO_PCI_with_VGA" "${str_IOMMU}" || [[ "${str_IOMMU} != $1" ]] ) && ! [[ "${str_multiboot_drivers}" ~= *"${str_driver}"* ]]; then
                     str_multiboot_drivers+="${str_driver}"
                 fi
 
@@ -156,11 +156,12 @@
             return "$?"
         fi
 
-        # <remarks> GRUB </remarks>
+        # <remarks> Write to files. </remarks>
         Multiboot_VFIO_GRUB || return $?
-
-        # <remarks> Custom GRUB entries </remarks>
         Multiboot_VFIO_Custom_GRUB || return $?
+
+        # <remarks> Update system configuration </remarks>
+        eval "${var_update_grub}" || return 1
 
         return 0
     }
@@ -204,35 +205,10 @@
             OverwriteFile "arr_file1" "${str_file1}" || return $?
         }
 
-        # <params>
-            # <remarks> File contents </remarks>
-            declare -a arr_file1_contents arr_file2_contents arr_file3_contents arr_file4_contents arr_file5_contents
-
-            # <remarks> Filenames </remarks>
-            local readonly str_file1="/etc/default/grub"
-            local readonly str_file2="/etc/initramfs-tools/modules"
-            local readonly str_file3="/etc/modprobe.d/pci-blacklists.conf"
-            local readonly str_file4="/etc/modprobe.d/vfio.conf"
-            local readonly str_file5="/etc/modules"
-
-            # <remarks> Evaluations </remarks>
-            local readonly var_get_softdep='softdep ${str_driver} pre: vfio-pci'
-        # </params>
-
-        # <remarks> Check if backup files exist. </remarks>
-        GoToScriptDir && cd "${str_files_dir}"
-
-        # <remarks> Backup existing system files. </remarks>
-        BackupFile "${str_file1}"
-        BackupFile "${str_file2}"
-        BackupFile "${str_file3}"
-        BackupFile "${str_file4}"
-        BackupFile "${str_file5}"
-
-        # <remarks> GRUB </remarks>
-        Static_VFIO_GRUB || return $?
-
-        # <summary> Initramfs and Modules </summary>
+        # <summary> Write to Modules. </summary>
+        # <returns> exit code </returns>
+        function Static_VFIO_ModulesInitramfs
+        {
             # <remarks> Organize new lines. </remarks>
             declare -a arr_file2=( "${arr_static_initramfs_file_template[@]}" )
             declare -a arr_file5=( "${arr_static_modules_file_template[@]}" )
@@ -290,30 +266,73 @@
             OverwriteFile "arr_file2" "${str_file2}" || return $?
             OverwriteFile "arr_file5" "${str_file5}" || return $?
 
-        # <summary> Modprobe: blacklists </summary>
-            # <remarks> Organize new lines. </remarks>
-            declare -a arr_file3=( "${arr_static_modprobe_blacklist_file_template[@]}" )
+            return 0
+        }
 
-            # <remarks> Set new lines. </remarks>
-            for var_driver in "${arr_drivers_VFIO_PCI[@]}"; do      # TODO: change to valid array
-                arr_file3+=( "${str_modprobe_blacklist}${var_driver}" )
-            done
+        # <summary> Write to Modprobe. </summary>
+        # <returns> exit code </returns>
+        function Static_VFIO_Modprobe
+        {
+            # <summary> Modprobe: blacklists </summary>
+                # <remarks> Organize new lines. </remarks>
+                declare -a arr_file3=( "${arr_static_modprobe_blacklist_file_template[@]}" )
 
-            readonly arr_file3
+                # <remarks> Set new lines. </remarks>
+                for var_driver in "${arr_drivers_VFIO_PCI[@]}"; do
+                    arr_file3+=( "${str_modprobe_blacklist}${var_driver}" )
+                done
 
-            # <remarks> Write new lines to file. </remarks>
-            OverwriteFile "arr_file3" "${str_file3}" || return $?
+                readonly arr_file3
 
-        # <remarks> Modprobe: conf </remarks>
-            # <remarks> Organize new lines. </remarks>
-            declare -ar arr_file4=(
-                "${arr_static_modprobe_vfio_file_template[@]}"
-                "${arr_softdep[@]}"
-                "${str_initramfs_modules_VFIO_PCI}${str_new_line_VFIO_temp}"
-            )
+                # <remarks> Write new lines to file. </remarks>
+                OverwriteFile "arr_file3" "${str_file3}" || return $?
 
-            # <remarks> Write new lines to file. </remarks>
-            OverwriteFile "arr_file4" "${str_file4}" || return $?
+            # <summary> Modprobe: conf </summary>
+                # <remarks> Organize new lines. </remarks>
+                declare -ar arr_file4=(
+                    "${arr_static_modprobe_vfio_file_template[@]}"
+                    "${arr_softdep[@]}"
+                    "${str_initramfs_modules_VFIO_PCI}${str_new_line_VFIO_temp}"
+                )
+
+                # <remarks> Write new lines to file. </remarks>
+                OverwriteFile "arr_file4" "${str_file4}" || return $?
+
+            return 0
+        }
+
+        # <params>
+            # <remarks> File contents </remarks>
+            declare -a arr_file1_contents arr_file2_contents arr_file3_contents arr_file4_contents arr_file5_contents
+
+            # <remarks> Filenames </remarks>
+            local readonly str_file1="/etc/default/grub"
+            local readonly str_file2="/etc/initramfs-tools/modules"
+            local readonly str_file3="/etc/modprobe.d/pci-blacklists.conf"
+            local readonly str_file4="/etc/modprobe.d/vfio.conf"
+            local readonly str_file5="/etc/modules"
+
+            # <remarks> Evaluations </remarks>
+            local readonly var_get_softdep='softdep ${str_driver} pre: vfio-pci'
+        # </params>
+
+        # <remarks> Check if backup files exist. </remarks>
+        GoToScriptDir && cd "${str_files_dir}"
+
+        # <remarks> Backup existing system files. </remarks>
+        BackupFile "${str_file1}"
+        BackupFile "${str_file2}"
+        BackupFile "${str_file3}"
+        BackupFile "${str_file4}"
+        BackupFile "${str_file5}"
+
+        # <remarks> Write to files. </remarks>
+        Static_VFIO_GRUB || return $?
+        Static_VFIO_ModulesInitramfs || return $?
+        Static_VFIO_Modprobe || return $?
+
+        # <remarks> Update system configuration </remarks>
+        eval "${var_update_grub}" && eval "${var_update_initramfs}" || return 1
 
         return 0
     }
@@ -341,6 +360,10 @@
 # </code>
 
 # <params>
+    # <remarks> Commands </remarks>
+    declare -gr var_update_grub='update-grub'
+    declare -gr var_update_initramfs='update-initramfs -u -k all'
+
     # <remarks> GRUB templates </remarks>
     declare -gr str_GRUB_template="GRUB_CMDLINE_LINUX_DEFAULT="
     declare -gr str_GRUB_required="iommu=1,pt amd_iommu=on intel_iommu=on "
