Worked thru the weekend.

diff --git a/bin/vfiolib-post-setup b/bin/vfiolib-post-setup
--- a/bin/vfiolib-post-setup
+++ b/bin/vfiolib-post-setup
@@ -8,7 +8,6 @@
 #
 
 # <sources>
-	source vfiolib-calcs
 	source vfiolib-common
 	source vfiolib-files
 	source vfiolib-usage
@@ -24,7 +23,7 @@
 					if "$_ASK_TO_EXECUTE_POST_SETUPS"; then
 						LibvirtHooks
 						GuestAudioLoopback
-						Allocate_RAM_ToSwap
+						AllocateRAMToSwap
 						SetVideoOutput
 						break
 					fi
@@ -38,7 +37,7 @@
 					fi
 
 					if "$_EXECUTE_POST_SETUP_ZRAM_SWAP"; then
-						Allocate_RAM_ToSwap
+						AllocateRAMToSwap
 					fi
 
 					if "$_EXECUTE_POST_SETUP_AUTO_XORG"; then
@@ -73,144 +72,197 @@
 		# zramswap: Setup a swap partition in host memory.
 		# Reduce swapiness to existing host swap partition(s)/file(s), and reduce chances of memory exhaustion as host over-allocates memory.
 		# </summary>
-		function Allocate_RAM_ToSwap
-		{
-			function Get
-			{
-				UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" "$_EXECUTE_POST_SETUP_ZRAM_SWAP" || return 1
-				return 0
-			}
+            function AllocateRAMToSwap
+            {
+                function Get
+                {
+                    UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" "$_EXECUTE_POST_SETUP_ZRAM_SWAP" || return 1
+                    return 0
+                }
 
-			function Install
-			{
-				local -r _SCRIPT_NAME="install.sh"
+                function Install
+                {
+                    local -r _SCRIPT_NAME="install.sh"
 
-				if ! cd "$_GIT_PATH$_FULL_REPO"; then
-					echo -e "$_PREFIX_ERROR Failed to find build directory."
-					return 1
-				fi
+                    if ! cd "$_GIT_PATH$_FULL_REPO"; then
+                        echo -e "$_PREFIX_ERROR Failed to find build directory."
+                        return 1
+                    fi
 
-				if [[ ! -e "$_SCRIPT_NAME" ]]; then
-					echo -e "$_PREFIX_ERROR Failed to find script '$_SCRIPT_NAME'."
-					return 1
-				fi
+                    if [[ ! -e "$_SCRIPT_NAME" ]]; then
+                        echo -e "$_PREFIX_ERROR Failed to find script '$_SCRIPT_NAME'."
+                        return 1
+                    fi
 
-				if ! echo "i" | sudo bash "$_SCRIPT_NAME" &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to execute script '$_SCRIPT_NAME'."
-					return 1
-				fi
+                    if ! echo "i" | sudo bash "$_SCRIPT_NAME" &> /dev/null; then
+                        echo -e "$_PREFIX_ERROR Failed to execute script '$_SCRIPT_NAME'."
+                        return 1
+                    fi
 
-				return 0
-			}
+                    return 0
+                }
 
-			function Modify
-			{
-				local -r _FILE="/etc/default/zram-swap"
-				local -r _LINE_TO_MATCH="_zram_fraction="
-				local _FRACTION="$_ARGS_FOR_ZRAM_SWAP_FRACTION"
+                function Modify
+                {
+                    local -r _FILE="/etc/default/zram-swap"
+                    local -r _LINE_TO_MATCH="_zram_fraction="
+                    local _FRACTION="$_ARGS_FOR_ZRAM_SWAP_FRACTION"
 
-				if ! "$_HAS_ARG_ZRAM_SWAP_DEFAULTS" \
-					&& ! "$_HAS_ARG_ZRAM_SWAP_SET_FRACTION"; then
-					local -ir _MAX_TRIES=2
+                    if ! "$_HAS_ARG_ZRAM_SWAP_DEFAULTS" \
+                        && ! "$_HAS_ARG_ZRAM_SWAP_SET_FRACTION"; then
+                        local -ir _MAX_TRIES=2
 
-					for _TRIES_COUNT in $( seq 0 "$_MAX_TRIES" ); do
-						read -r -p "Set fraction of total memory for zram-swap to use (to calculate default, enter 'default'): " _ANSWER
+                        for TRY_COUNT in $( seq 0 "$_MAX_TRIES" ); do
+                            read -r -p "Set fraction of total memory for zram-swap to use (to calculate default, enter 'default'): " _ANSWER
 
-						if Get_ZRAM_SwapSize "$_ANSWER"; then
-							_FRACTION="$_ANSWER"
-							break
-						fi
+                            if GetZRAMSwapSize "$_ANSWER"; then
+                                _FRACTION="$_ANSWER"
+                                break
+                            fi
 
-						if [[ "$?" -ne 0 ]] \
-							&& [[ $_TRIES_COUNT -eq "$_MAX_TRIES" ]]; then
-							return 1
-						fi
-					done
-				fi
+                            if [[ "$?" -ne 0 ]] \
+                                && [[ $TRY_COUNT -eq "$_MAX_TRIES" ]]; then
+                                return 1
+                            fi
+                        done
+                    fi
 
-				if "$_HAS_ARG_ZRAM_SWAP_DEFAULTS" \
-					&& ! "$_HAS_ARG_ZRAM_SWAP_SET_FRACTION"; then
-					local -i _ZRAM_SWAP_AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY / 2 ))
-					local -i _DENOMINATOR=$( printf "%.0f" $( echo "scale=2;$_INT_MAX_MEMORY/$_ZRAM_SWAP_AVAILABLE_MEMORY" | bc ) )
+                    if "$_HAS_ARG_ZRAM_SWAP_DEFAULTS" \
+                        && ! "$_HAS_ARG_ZRAM_SWAP_SET_FRACTION"; then
+                        local -i _ZRAM_SWAP_AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY / 2 ))
+                        local -i _DENOMINATOR=$( printf "%.0f" $( echo "scale=2;$_INT_MAX_MEMORY/$_ZRAM_SWAP_AVAILABLE_MEMORY" | bc ) )
 
-					# <remarks> Round down to nearest even number. </remarks>
-					if [[ $( expr $_DENOMINATOR % 2 ) -eq 1 ]]; then
-						(( _DENOMINATOR-- ))
-					fi
+                        # <remarks> Round down to nearest even number. </remarks>
+                        if [[ $( expr $_DENOMINATOR % 2 ) -eq 1 ]]; then
+                            (( _DENOMINATOR-- ))
+                        fi
 
-					# <remarks> Is fraction positive non-zero and not equal to one. </remarks>
-					if [[ "$_DENOMINATOR" -le 0 ]]; then
-						echo -e "$_PREFIX_ERROR Denominator is negative or zero."
-					fi
+                        # <remarks> Is fraction positive non-zero and not equal to one. </remarks>
+                        if [[ "$_DENOMINATOR" -le 0 ]]; then
+                            echo -e "$_PREFIX_ERROR Denominator is negative or zero."
+                        fi
 
-					_FRACTION="1/$_DENOMINATOR"
-				fi
+                        _FRACTION="1/$_DENOMINATOR"
+                    fi
 
-				if ! sed -i '/'$_LINE_TO_MATCH'"*"/c\'$_LINE_TO_MATCH'"'$_FRACTION'"' "$_FILE"; then
-					echo -e "$_PREFIX_ERROR Failed to write output to zram-swap file."
-					return 1
-				fi
+                    if ! sed -i '/'$_LINE_TO_MATCH'"*"/c\'$_LINE_TO_MATCH'"'$_FRACTION'"' "$_FILE"; then
+                        echo -e "$_PREFIX_ERROR Failed to write output to zram-swap file."
+                        return 1
+                    fi
 
-				if ! "$_HAS_ARG_ZRAM_SWAP_FORCE" \
-					&& sudo swapon -v | grep zram &> /dev/null \
-					&& sudo swapon -v | grep zram &> /dev/null \
-					&& ! sudo swapon -v | grep zram | grep 0B &> /dev/null; then
-					echo -e "$_PREFIX_NOTE zram-swap device(s) already in use. Restart system to save changes."
-					return 0
-				fi
+                    if ! "$_HAS_ARG_ZRAM_SWAP_FORCE" \
+                        && sudo swapon -v | grep zram &> /dev/null \
+                        && sudo swapon -v | grep zram &> /dev/null \
+                        && ! sudo swapon -v | grep zram | grep 0B &> /dev/null; then
+                        echo -e "$_PREFIX_NOTE zram-swap device(s) already in use. Restart system to save changes."
+                        return 0
+                    fi
 
-				if sudo swapon -v | grep zram &> /dev/null \
-					&& ! sudo swapoff /dev/zram* &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to disable zram-swap device(s)."
-					return 1
-				fi
+                    if sudo swapon -v | grep zram &> /dev/null \
+                        && ! sudo swapoff /dev/zram* &> /dev/null; then
+                        echo -e "$_PREFIX_ERROR Failed to disable zram-swap device(s)."
+                        return 1
+                    fi
 
-				if ! sudo systemctl daemon-reload &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to update systemd."
-					return 1
-				fi
+                    if ! sudo systemctl daemon-reload &> /dev/null; then
+                        echo -e "$_PREFIX_ERROR Failed to update systemd."
+                        return 1
+                    fi
 
-				if ! sudo systemctl restart zram-swap &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to restart zram-swap service."
-					return 1
-				fi
+                    if ! sudo systemctl restart zram-swap &> /dev/null; then
+                        echo -e "$_PREFIX_ERROR Failed to restart zram-swap service."
+                        return 1
+                    fi
 
-				if ! sudo swapon -v | grep zram &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to enable zram-swap device."
-					return 1
-				fi
+                    if ! sudo swapon -v | grep zram &> /dev/null; then
+                        echo -e "$_PREFIX_ERROR Failed to enable zram-swap device."
+                        return 1
+                    fi
 
-				return 0
-			}
+                    return 0
+                }
 
-			local -r _USER_NAME="foundObjects"
-			local -r _REPO_NAME="zram-swap"
-			local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
-			local _HAS_SKIPPED=false
+                local -r _USER_NAME="foundObjects"
+                local -r _REPO_NAME="zram-swap"
+                local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
+                local _HAS_SKIPPED=false
 
-			if ! "$_EXECUTE_POST_SETUP_ZRAM_SWAP"; then
-				echo
+                if ! "$_EXECUTE_POST_SETUP_ZRAM_SWAP"; then
+                    echo
 
-				if ! AskToExecuteOrSkip "Install zram-swap?"; then
-					_HAS_SKIPPED=true
-				fi
-			fi
+                    if ! AskToExecuteOrSkip "Install zram-swap?"; then
+                        _HAS_SKIPPED=true
+                    fi
+                fi
 
-			if ! "$_HAS_SKIPPED" \
-				&& ( ! IsHostMemorySufficientForZramSwap \
-				|| ! Get \
-				|| ! Install \
-				|| ! Modify ); then
-				false
-			fi
+                if ! "$_HAS_SKIPPED" \
+                    && ( ! IsHostMemorySufficientForZramSwap \
+                    || ! Get \
+                    || ! Install \
+                    || ! Modify ); then
+                    false
+                fi
 
-			if "$_HAS_SKIPPED"; then
-				( return 255 )
-			fi
+                if "$_HAS_SKIPPED"; then
+                    ( return 255 )
+                fi
 
-			PrintSuffixPassOrFail "Allocating RAM to swap..."
-			return "$_LAST_EXIT_CODE"
-		}
+                PrintSuffixPassOrFail "Allocating RAM to swap..."
+                return "$_LAST_EXIT_CODE"
+            }
+
+            function GetZRAMSwapSize
+            {
+                IsHostMemorySufficientForZramSwap || return 1
+
+                case "$1" in
+                    *"/"* )
+                        local -i _NUMERATOR=$( echo $1 | cut -d '/' -f1 )
+                        local -i _DENOMINATOR=$( echo $1 | cut -d '/' -f2 ) ;;
+
+                    "default" )
+                        _HAS_ARG_ZRAM_SWAP_DEFAULTS=true
+                        return 0 ;;
+
+                    * )
+                        echo -e "$_PREFIX_ERROR Not a fraction."
+                        return 1 ;;
+                esac
+
+                if ! [[ "$_NUMERATOR" =~ ^[0-9]+$ ]] \
+                    || ! [[ "$_DENOMINATOR" =~ ^[0-9]+$ ]]; then
+                    echo -e "$_PREFIX_ERROR Values are not numbers."
+                    return 1
+                fi
+
+                if [[ "$_NUMERATOR" -lt "$_DENOMINATOR" ]] || [[ "$_DENOMINATOR" -gt 1 ]]; then
+                    declare -g _ARGS_FOR_ZRAM_SWAP_FRACTION="$1"
+                    _HAS_ARG_ZRAM_SWAP_SET_FRACTION=true
+                    return 0
+
+                elif [[ "$_DENOMINATOR" -eq 0 ]]; then
+                    return 1
+
+                else
+                    echo -e "$_PREFIX_ERROR Invalid fraction."
+                fi
+
+                return 1
+            }
+
+            function IsHostMemorySufficientForZramSwap
+            {
+                if "$_IS_HUGEPAGES_SETUP"; then
+                    _AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY - _HUGEPAGES_ALLOCATED_MEMORY ))
+                fi
+
+                if ! GetFreeMemory; then
+                    echo -e "$_PREFIX_ERROR Insufficient Host memory for zram-swap."
+                    return 1
+                fi
+
+                return 0
+            }
 
 		# <summary>
 		# Install necessary depenencies to setup an audio capture from guest emulated audio device to host audio backend.
diff --git a/bin/vfiolib-pre-setup b/bin/vfiolib-pre-setup
--- a/bin/vfiolib-pre-setup
+++ b/bin/vfiolib-pre-setup
@@ -8,8 +8,8 @@
 #
 
 # <sources>
-    source vfiolib-calcs
     source vfiolib-common
+    source vfiolib-checks
     source vfiolib-files
     source vfiolib-parse
     source vfiolib-usage
@@ -25,26 +25,26 @@
                     AddUserToGroups
 
                     if "$_ASK_TO_EXECUTE_PRE_SETUP_ALL"; then
-                        StaticAllocateRAMToGuest
-                        StaticAllocateCPUToGuest
-                        Virtual_KVM
-                        Modify_QEMU
+                        ExecuteHugepagesSetup
+                        ExecuteStaticCPUIsolation
+                        ExecuteVirtualKVMSetup
+                        ExecuteModifyQEMUConfiguration
                         break
                     fi
 
                     if "$_EXECUTE_PRE_SETUP_HUGEPAGES"; then
-                        StaticAllocateRAMToGuest
+                        ExecuteHugepagesSetup
                     fi
 
                     if "$_EXECUTE_PRE_SETUP_STATIC_ISOLCPU"; then
-                        StaticAllocateCPUToGuest
+                        ExecuteStaticCPUIsolation
                     fi
 
                     if "$_EXECUTE_PRE_SETUP_EVDEV"; then
-                        Virtual_KVM
+                        ExecuteVirtualKVMSetup
                     fi
 
-                    Modify_QEMU
+                    ExecuteModifyQEMUConfiguration
                     break
                 done
 
@@ -61,7 +61,16 @@
         # <summary> Global setters </summary>
         function SetParameters
         {
+            declare -g _REGEX_FOR_NUM='^[0-9]+$'
+
             declare -gi _HUGEPAGES_ALLOCATED_MEMORY=0
+            declare -gi _HUGEPAGES_COUNT=0
+            declare -gu _HUGEPAGES_BYTE_SUFFIX
+            declare -gi _HUGEPAGES_MAX_SIZE=0
+            declare -gi _HUGEPAGES_MAX_SIZE_IN_KBIT=$( cat /proc/meminfo | grep MemTotal | cut -d ":" -f 2 | cut -d "k" -f 1 )
+            declare -gi _HUGEPAGES_MIN_SIZE=0
+            declare -gi _HUGEPAGES_MIN_SIZE_IN_KBIT=4194304
+            declare -gi _HUGEPAGES_SIZE_IN_KBIT=0
 
             # <remarks> Flag progress of setups </remarks>
             declare -g _IS_EVDEV_SETUP=false
@@ -69,6 +78,162 @@
         }
 
     # <summary> Private </summary>
+        # <summary>
+        # Hugepages: Allocate host memory (RAM) to 'hugepages'.
+        # Eliminate the need to defragement memory, reduce host overhead, and improve both host and guest performance.
+        # </summary
+            function ExecuteHugepagesSetup
+            {
+                function AskForHugepageByteSize
+                {
+                    if "$_IS_HUGEPAGES_SIZE_SET"; then
+                        return 0
+                    fi
+
+                    for TRY_COUNT in $( seq 0 2 ); do
+                        read -r -p "Enter size of Hugepages [2M/1G]: " _HUGEPAGES_BYTE_SUFFIX
+                        GetHugepageByteSize "$_HUGEPAGES_BYTE_SUFFIX" && return 0
+                    done
+
+                    echo -e "$_OUTPUT_INVALID_ANSWER"
+                    return 1
+                }
+
+                function AskForHugepageCount
+                {
+
+                    if "$_IS_HUGEPAGES_COUNT_SET"; then
+                        return 0
+                    fi
+
+                    for TRY_COUNT in $( seq 0 2 ); do
+                        read -r -p "Enter count of Hugepages [$_HUGEPAGES_MIN_SIZE-$_HUGEPAGES_MAX_SIZE]: " _HUGEPAGES_COUNT
+                        GetHugepageCount "$_HUGEPAGES_COUNT" && return 0
+                    done
+
+                    echo -e "$_OUTPUT_INVALID_ANSWER"
+                    return 1
+                }
+
+                function Main
+                {
+                    if ! "$_EXECUTE_PRE_SETUP_HUGEPAGES"; then
+                        echo
+                    fi
+
+                    _IS_HUGEPAGES_SETUP=false
+
+                    if ! [[ "$_INT_MAX_MEMORY" =~ ^[0-9]+$ ]]; then
+                        echo -e "$_PREFIX_ERROR Could not parse system memory."
+                        return 1
+                    fi
+
+                    if ! "$_EXECUTE_PRE_SETUP_HUGEPAGES"; then
+                        if ! "$_IS_QUIET"; then
+                            echo -e "Hugepages is a feature which statically allocates system memory to pagefiles.\nGuest(s) can use Hugepages to a peformance benefit.\nThe greater the Hugepage size, the less fragmentation of memory, and the less latency/overhead of system memory-access.\n${var_yellow}NOTE:${var_reset_color} It is recommended to use a size which is a multiple of an individual memory channel/stick.\n${var_yellow}Example:${var_reset_color} Four (4) channels of 8 GB each, use 1x, 2x, or 3x (8 GB, 16 GB, or 24 GB).\n"
+                        fi
+
+                        AskToExecuteOrSkip "Setup Hugepages?" || return "$?"
+                    fi
+
+                    if ! "$_IS_HUGEPAGES_SIZE_SET"; then
+                        AskForHugepageByteSize || return 1
+                    fi
+
+                    GetHugepageMinAndMaxSizes || return 1
+
+                    if ! "$_IS_HUGEPAGES_COUNT_SET"; then
+                        AskForHugepageCount || return 1
+                    fi
+
+                    GetMemoryAllocatedToHugepages || return 1
+                    IsHostMemorySufficientForHugepages || return 1
+                    declare -g _OUTPUT_GRUB_CMDLINE_HUGEPAGES="default_hugepagesz=$_HUGEPAGES_BYTE_SUFFIX hugepagesz=$_HUGEPAGES_BYTE_SUFFIX hugepages=$_HUGEPAGES_COUNT"
+                    _IS_HUGEPAGES_SETUP=true
+                    return 0
+                }
+
+                Main
+                PrintSuffixPassOrFail "Allocating RAM to pages..."
+                return "$_LAST_EXIT_CODE"
+            }
+
+            function GetMemoryAllocatedToHugepages
+            {
+                _HUGEPAGES_ALLOCATED_MEMORY=$(( $_HUGEPAGES_COUNT * $_HUGEPAGES_SIZE_IN_KBIT ))
+                return 0
+            }
+
+            function GetHugepageByteSize
+            {
+                local -u ANSWER="$1"
+
+                case "$ANSWER" in
+                    "1G" | "2M" )
+                        _HUGEPAGES_BYTE_SUFFIX="$ANSWER"
+                        _IS_HUGEPAGES_SIZE_SET=true
+                        return 0 ;;
+
+                    * )
+                        echo -e "Please a enter valid Hugepages size, '2M' or '1G'."
+                        return 1 ;;
+                esac
+            }
+
+            function GetHugepageCount
+            {
+                if [[ -z "$1" ]]; then
+                    echo -e "$_PREFIX_ERROR Hugepage count is empty."
+                    return 1
+                fi
+
+                GetHugepageMinAndMaxSizes || return 1
+
+                if ! echo "$1" | grep -E -q "$_REGEX_FOR_NUM" \
+                    || [[ "$1" -lt "$_HUGEPAGES_MIN_SIZE" ]] \
+                    || [[ "$1" -gt "$_HUGEPAGES_MAX_SIZE" ]]; then
+                    echo -e "$_PREFIX_ERROR Please enter a valid Hugepages amount, between $_HUGEPAGES_MIN_SIZE or $_HUGEPAGES_MAX_SIZE."
+                    return 1
+                fi
+
+                _IS_HUGEPAGES_COUNT_SET=true
+                _HUGEPAGES_COUNT="$1"
+                return 0
+            }
+
+            function GetHugepageMinAndMaxSizes
+            {
+                case "$_HUGEPAGES_BYTE_SUFFIX" in
+                    "2M" )
+                        _HUGEPAGES_SIZE_IN_KBIT=2048
+                        _HUGEPAGES_MIN_SIZE=2 ;;
+
+                    "1G" )
+                        _HUGEPAGES_SIZE_IN_KBIT=1048576
+                        _HUGEPAGES_MIN_SIZE=1 ;;
+
+                    * )
+                        echo -e "$_PREFIX_ERROR Failed to calculate minimum or maximum values for Hugepages."
+                        return 1 ;;
+                esac
+
+                _HUGEPAGES_MAX_SIZE=$(( "$_HUGEPAGES_MAX_SIZE_IN_KBIT" - "$_HUGEPAGES_MIN_SIZE_IN_KBIT" ))
+                _HUGEPAGES_MAX_SIZE=$(( "$_HUGEPAGES_MAX_SIZE" / "$_HUGEPAGES_SIZE_IN_KBIT" ))
+                return 0
+            }
+
+
+            function IsHostMemorySufficientForHugepages
+            {
+                if ! GetFreeMemory; then
+                    echo -e "$_PREFIX_ERROR Insufficient Host memory for Hugepages."
+                    return 1
+                fi
+
+                return 0
+            }
+
+
         # <summary>
         # Add user to necessary user groups.
         # </summary>
@@ -86,7 +251,7 @@
         # <summary>
         # isolcpus: Allocate host CPU cores (and/or threads), to reduce host overhead, and improve both host and guest performance.
         # </summary
-        function StaticAllocateCPUToGuest
+        function ExecuteStaticCPUIsolation
         {
             function GetThreadByCoreAnd_SMT
             {
@@ -233,93 +398,9 @@
         }
 
         # <summary>
-        # Hugepages: Allocate host memory (RAM) to 'hugepages'.
-        # Eliminate the need to defragement memory, reduce host overhead, and improve both host and guest performance.
-        # </summary
-        function StaticAllocateRAMToGuest
-        {
-            function AskForHugepageByteSize
-            {
-                if "$_IS_HUGEPAGES_SIZE_SET"; then
-                    return 0
-                fi
-
-                declare -gu _HUGEPAGES_BYTE_SUFFIX=""
-
-                for _TRIES_COUNT in $( seq 0 2 ); do
-                    read -r -p "Enter size of Hugepages [2M/1G]: " _HUGEPAGES_BYTE_SUFFIX
-                    GetHugepageByteSize "$_HUGEPAGES_BYTE_SUFFIX" && return 0
-                done
-
-                echo -e "$_OUTPUT_INVALID_ANSWER"
-                return 1
-            }
-
-            function AskForHugepageCount
-            {
-
-                if "$_IS_HUGEPAGES_COUNT_SET"; then
-                    return 0
-                fi
-
-                declare -gi _HUGEPAGES_COUNT=""
-
-                for _TRIES_COUNT in $( seq 0 2 ); do
-                    read -r -p "Enter count of Hugepages [$_HUGEPAGES_MIN_SIZE-$_HUGEPAGES_MAX_SIZE]: " _HUGEPAGES_COUNT
-                    GetHugepageCount "$_HUGEPAGES_COUNT" && return 0
-                done
-
-                echo -e "$_OUTPUT_INVALID_ANSWER"
-                return 1
-            }
-
-            function Main
-            {
-                if ! "$_EXECUTE_PRE_SETUP_HUGEPAGES"; then
-                    echo
-                fi
-
-                _IS_HUGEPAGES_SETUP=false
-
-                if ! [[ "$_INT_MAX_MEMORY" =~ ^[0-9]+$ ]]; then
-                    echo -e "$_PREFIX_ERROR Could not parse system memory."
-                    return 1
-                fi
-
-                if ! "$_EXECUTE_PRE_SETUP_HUGEPAGES"; then
-                    if ! "$_IS_QUIET"; then
-                        echo -e "Hugepages is a feature which statically allocates system memory to pagefiles.\nGuest(s) can use Hugepages to a peformance benefit.\nThe greater the Hugepage size, the less fragmentation of memory, and the less latency/overhead of system memory-access.\n${var_yellow}NOTE:${var_reset_color} It is recommended to use a size which is a multiple of an individual memory channel/stick.\n${var_yellow}Example:${var_reset_color} Four (4) channels of 8 GB each, use 1x, 2x, or 3x (8 GB, 16 GB, or 24 GB).\n"
-                    fi
-
-                    AskToExecuteOrSkip "Setup Hugepages?" || return "$?"
-                fi
-
-                if ! "$_IS_HUGEPAGES_SIZE_SET"; then
-                    AskForHugepageByteSize || return 1
-                fi
-
-                GetHugepageMinAndMaxSizes || return 1
-
-                if ! "$_IS_HUGEPAGES_COUNT_SET"; then
-                    AskForHugepageCount || return 1
-                fi
-
-                GetMemoryAllocatedToHugepages || return 1
-                IsHostMemorySufficientForHugepages || return 1
-                declare -g _OUTPUT_GRUB_CMDLINE_HUGEPAGES="default_hugepagesz=$_HUGEPAGES_BYTE_SUFFIX hugepagesz=$_HUGEPAGES_BYTE_SUFFIX hugepages=$_HUGEPAGES_COUNT"
-                _IS_HUGEPAGES_SETUP=true
-                return 0
-            }
-
-            Main
-            PrintSuffixPassOrFail "Allocating RAM to pages..."
-            return "$_LAST_EXIT_CODE"
-        }
-
-        # <summary>
         # libvirt-qemu: Append necessary changes to QEMU system file, including user groups, Evdev, Hugepages, and NVRAM (for UEFI guest(s)).
         # </summary>
-        function Modify_QEMU
+        function ExecuteModifyQEMUConfiguration
         {
             function Main
             {
@@ -451,7 +532,7 @@
         # Evdev: Setup a virtual Keyboard-Video-Mouse switch (excluding the Video).
         # Will allow a user to swap between active guest(s) and host, with the use of a pre-defined macro (example: 'L-CTRL' + 'R-CTRL').
         # </summary>
-        function Virtual_KVM
+        function ExecuteVirtualKVMSetup
         {
             function Main
             {
