Update vfiolib-post-setup

diff --git a/bin/vfiolib-post-setup b/bin/vfiolib-post-setup
--- a/bin/vfiolib-post-setup
+++ b/bin/vfiolib-post-setup
@@ -76,26 +76,26 @@
             {
                 function Get
                 {
-                    UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" "$_EXECUTE_POST_SETUP_ZRAM_SWAP" || return 1
+                    UpdateOrCloneGitRepo "$_GIT_PATH" "$FULL_REPO" "$USER_NAME" "$_EXECUTE_POST_SETUP_ZRAM_SWAP" || return 1
                     return 0
                 }
 
                 function Install
                 {
-                    local -r _SCRIPT_NAME="install.sh"
+                    local -r SCRIPT_NAME="install.sh"
 
-                    if ! cd "$_GIT_PATH$_FULL_REPO"; then
+                    if ! cd "$_GIT_PATH$FULL_REPO"; then
                         echo -e "$_PREFIX_ERROR Failed to find build directory."
                         return 1
                     fi
 
-                    if [[ ! -e "$_SCRIPT_NAME" ]]; then
-                        echo -e "$_PREFIX_ERROR Failed to find script '$_SCRIPT_NAME'."
+                    if [[ ! -e "$SCRIPT_NAME" ]]; then
+                        echo -e "$_PREFIX_ERROR Failed to find script '$SCRIPT_NAME'."
                         return 1
                     fi
 
-                    if ! echo "i" | sudo bash "$_SCRIPT_NAME" &> /dev/null; then
-                        echo -e "$_PREFIX_ERROR Failed to execute script '$_SCRIPT_NAME'."
+                    if ! echo "i" | sudo bash "$SCRIPT_NAME" &> /dev/null; then
+                        echo -e "$_PREFIX_ERROR Failed to execute script '$SCRIPT_NAME'."
                         return 1
                     fi
 
@@ -120,8 +120,8 @@
                         return 1
                     }
 
-                    local -r _FILE="/etc/default/zram-swap"
-                    local -r _LINE_TO_MATCH="_zram_fraction="
+                    local -r FILE="/etc/default/zram-swap"
+                    local -r LINE_TO_MATCH="_zram_fraction="
                     local FRACTION="$_ARGS_FOR_ZRAM_SWAP_FRACTION"
 
                     if ! "$_HAS_ARG_ZRAM_SWAP_DEFAULTS" \
@@ -147,7 +147,7 @@
                         FRACTION="1/$DENOMINATOR"
                     fi
 
-                    if ! sed -i '/'$_LINE_TO_MATCH'"*"/c\'$_LINE_TO_MATCH'"'$FRACTION'"' "$_FILE"; then
+                    if ! sed -i '/'$LINE_TO_MATCH'"*"/c\'$LINE_TO_MATCH'"'$FRACTION'"' "$FILE"; then
                         echo -e "$_PREFIX_ERROR Failed to write output to zram-swap file."
                         return 1
                     fi
@@ -184,9 +184,9 @@
                     return 0
                 }
 
-                local -r _USER_NAME="foundObjects"
-                local -r _REPO_NAME="zram-swap"
-                local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
+                local -r USER_NAME="foundObjects"
+                local -r REPO_NAME="zram-swap"
+                local -r FULL_REPO="$USER_NAME/$REPO_NAME"
                 local HAS_SKIPPED=false
 
                 if ! "$_EXECUTE_POST_SETUP_ZRAM_SWAP"; then
@@ -475,7 +475,7 @@
 		{
 			function Get
 			{
-				UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" "$_EXECUTE_POST_SETUP_AUTO_XORG" || return 1
+				UpdateOrCloneGitRepo "$_GIT_PATH" "$FULL_REPO" "$USER_NAME" "$_EXECUTE_POST_SETUP_AUTO_XORG" || return 1
 				return 0
 			}
 
@@ -500,35 +500,35 @@
 
 			function Install
 			{
-				local -r _SCRIPT_NAME="installer.bash"
+				local -r SCRIPT_NAME="installer.bash"
 
-				if ! cd "$_GIT_PATH$_FULL_REPO"; then
+				if ! cd "$_GIT_PATH$FULL_REPO"; then
 					echo -e "$_PREFIX_ERROR Failed to find build directory."
 					return 1
 				fi
 
-				if [[ ! -e "$_SCRIPT_NAME" ]]; then
-					echo -e "$_PREFIX_ERROR Failed to find script '$_SCRIPT_NAME'."
+				if [[ ! -e "$SCRIPT_NAME" ]]; then
+					echo -e "$_PREFIX_ERROR Failed to find script '$SCRIPT_NAME'."
 					return 1
 				fi
 
-				if ! sudo bash $_SCRIPT_NAME $_ARGS_FOR_AUTO_XORG &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to execute script '$_SCRIPT_NAME'."
+				if ! sudo bash $SCRIPT_NAME $_ARGS_FOR_AUTO_XORG &> /dev/null; then
+					echo -e "$_PREFIX_ERROR Failed to execute script '$SCRIPT_NAME'."
 					return 1
 				fi
 
 				return 0
 			}
 
-			local -r _USER_NAME="portellam"
-			local -r _REPO_NAME="auto-Xorg"
-			local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
+			local -r USER_NAME="portellam"
+			local -r REPO_NAME="auto-Xorg"
+			local -r FULL_REPO="$USER_NAME/$REPO_NAME"
 			local HAS_SKIPPED=false
 
 			if ! "$_EXECUTE_POST_SETUP_AUTO_XORG"; then
 				echo
 
-				if ! AskToExecuteOrSkip "Install $_REPO_NAME?"; then
+				if ! AskToExecuteOrSkip "Install $REPO_NAME?"; then
 					HAS_SKIPPED=true
 				fi
 			fi
@@ -560,7 +560,7 @@
 				( return 255 )
 			fi
 
-			PrintSuffixPassOrFail "Installing $_REPO_NAME...\t"
+			PrintSuffixPassOrFail "Installing $REPO_NAME...\t"
 			return "$_LAST_EXIT_CODE"
 		}
 # </functions>
