Added functionality to ask user method of parsing (which database and if a file, enter a filename).

diff --git a/bin/vfiolib-parse b/bin/vfiolib-parse
--- a/bin/vfiolib-parse
+++ b/bin/vfiolib-parse
@@ -21,7 +21,7 @@
     declare -gA _IOMMU_GROUP_DEVICE_LIST
     declare -ga _IOMMU_GROUP_ID_LIST=$( ls -1v /sys/kernel/iommu_groups/ | sort -h )
     declare -ga _IOMMU_GROUP_ID_LIST_FOR_VFIO _IOMMU_GROUP_ID_LIST_WITH_VGA_FOR_HOST _IOMMU_GROUP_ID_LIST_WITH_VGA_FOR_VFIO
-    declare -g _PARSE_IOMMU_DATABASE_DEFAULT_PATH="/usr/local/etc/vfiolib_lspci_database"
+    declare -g _DEFAULT_FILE_DATABASE="/usr/local/etc/vfiolib_lspci_database"
     declare -g _PARSE_OPTIONS=""
 # </params>
 
@@ -126,6 +126,7 @@
 
     function ExecuteParse
     {
+        SelectMethodToParseDatabase || return 1
         ParseDatabaseFirstTimeAndSaveToFile || return 1
         SetOptionsForParsingDatabase || return 1
         GetDevicesForEachIOMMUGroup || return 1
@@ -200,14 +201,11 @@
 
     function ParseDatabaseFirstTimeAndSaveToFile
     {
-        local _FILE="$_PARSE_IOMMU_DATABASE_FILENAME"
-
-        if [[ -z "$_PARSE_IOMMU_DATABASE_FILENAME" ]]; then
-            _FILE="$_PARSE_IOMMU_DATABASE_DEFAULT_PATH"
-
+        if "$_DO_PARSE_DATABASE_FROM_FILE"; then
+            return 0
         fi
 
-        readonly _FILE
+        local _FILE="$_DEFAULT_FILE_DATABASE"
 
         if [[ ! -z "$_FILE" ]] \
             && [[ ! -e "$_FILE" ]] \
@@ -370,21 +368,75 @@
         return 0
     }
 
+    function SelectMethodToParseDatabase
+    {
+        case true in
+            "$_DO_PARSE_DATABASE_FROM_CACHE" | "$_DO_PARSE_DATABASE_FROM_FILE" | "$_DO_PARSE_DATABASE_FROM_INTERNET" )
+                return 0 ;;
+        esac
+
+        for _TRIES_COUNT in $( seq 0 2 ); do
+            read -r -p "Select method of parsing IOMMU groups? [(F)ile/(I)nternal/(O)nline]: " _ANSWER
+
+            case "$_ANSWER" in
+                [Ff]* )
+                    _DO_PARSE_DATABASE_FROM_FILE=true
+                    SelectFileToParseDatabase || return 1
+                    return 0 ;;
+
+                [Ii]* )
+                    _DO_PARSE_DATABASE_FROM_CACHE=true
+                    return 0 ;;
+
+                [Oo]* )
+                    _DO_PARSE_DATABASE_FROM_INTERNET=true
+                    return 0 ;;
+
+                * )
+                    echo "Please answer \"F\", \"I\", or \"O\"." ;;
+            esac
+        done
+
+        echo -e "$_PREFIX_ERROR Failed to answer."
+        return 1
+    }
+
+    function SelectFileToParseDatabase
+    {
+        for _TRIES_COUNT in $( seq 0 2 ); do
+            read -r -p "Enter filename (leave blank for default): " _ANSWER
+
+            if [[ ! -e "$_ANSWER" ]]; then
+                echo -e "File does not exist."
+            fi
+
+            if [[ ! -s "$_ANSWER" ]]; then
+                echo -e "File is empty."
+            fi
+
+            if [[ -e "$_ANSWER" ]] \
+                && [[ -s "$_ANSWER" ]]; then
+                _FILE_DATABASE="$_ANSWER"
+                return 0
+            fi
+        done
+
+        echo -e "$_PREFIX_ERROR Failed to answer."
+        return 1
+    }
+
     function SetOptionsForParsingDatabase
     {
         _PARSE_OPTIONS=""
-        local _FILE="$_PARSE_IOMMU_DATABASE_FILENAME"
+        local _FILE=""
 
-        if [[ -z "$_PARSE_IOMMU_DATABASE_FILENAME" ]]; then
-            _FILE="$_PARSE_IOMMU_DATABASE_DEFAULT_PATH"
-
+        if "$_DO_PARSE_DATABASE_FROM_FILE"; then
+            _FILE="$_FILE_DATABASE"
+        else
+            _FILE="$_DEFAULT_FILE_DATABASE"
         fi
 
-        readonly _FILE
-
-        if ( "$_DO_PARSE_ONLINE_DATABASE" \
-            || "$_DO_PARSE_FILE_DATABASE" ) \
-            && [[ ! -s "$_FILE" ]]; then
+        if [[ ! -s "$_FILE" ]]; then
             echo -e "$_PREFIX_ERROR Database file is empty."
             return 1
         fi
