Update param calls (using brackets). vfiolib-setup has been combed thru.

diff --git a/bin/vfiolib-common b/bin/vfiolib-common
--- a/bin/vfiolib-common
+++ b/bin/vfiolib-common
@@ -14,14 +14,14 @@
             {
                 function PingServer
                 {
-                    [ ! -z "$1" ] || return 1
-                    ping -q -c 1 $1 &> /dev/null
-                    return "$?"
+                    [ ! -z "${1}" ] || return 1
+                    ping -q -c 1 ${1} &> /dev/null
+                    return "${?}"
                 }
 
                 local IS_VERBOSE=false
 
-                if [[ "$1" == true ]]; then
+                if [[ "${1}" == true ]]; then
                     IS_VERBOSE=true
                 fi
 
@@ -108,22 +108,22 @@
                 local OS_WITH_ZYPPER="mandriva mageia"
 
                 if [[ -z "$KERNEL" ]]; then
-                    echo -e "$_PREFIX_ERROR Failed to parse system kernel."
+                    echo -e "${_PREFIX_ERROR} Failed to parse system kernel."
                     return 1
                 fi
 
                 if [[ -z "$_OPERATING_SYSTEM" ]]; then
-                    echo -e "$_PREFIX_ERROR Failed to parse operating system."
+                    echo -e "${_PREFIX_ERROR} Failed to parse operating system."
                     return 1
                 fi
 
                 if [[ "$KERNEL" != *"linux"* ]]; then
-                    echo -e "$_PREFIX_ERROR Kernel '$( uname -o )' is not supported."
+                    echo -e "${_PREFIX_ERROR} Kernel '$( uname -o )' is not supported."
                     return 1
                 fi
 
                 if ! GetPackageManagerByOS; then
-                    echo -e "$_PREFIX_ERROR Distribution '$( lsb_release -is )' is not supported."
+                    echo -e "${_PREFIX_ERROR} Distribution '$( lsb_release -is )' is not supported."
                     return 1
                 fi
 
@@ -133,7 +133,7 @@
         # <summary> Global setters </summary>
             function SetExitCode
             {
-                _LAST_EXIT_CODE="$?"
+                _LAST_EXIT_CODE="${?}"
             }
 
             function SetParameters
@@ -180,7 +180,7 @@
                 declare -gi _MIN_MEMORY=8
 
                 # <remarks> System validation </remarks>
-                declare -g _OUTPUT_INVALID_PACKAGE_MANAGER="$_PREFIX_ERROR Command '$_PACKAGE_MANAGER' is not supported."
+                declare -g _OUTPUT_INVALID_PACKAGE_MANAGER="${_PREFIX_ERROR} Command '$_PACKAGE_MANAGER' is not supported."
                 declare -gl _PACKAGE_MANAGER
                 declare -gl _OPERATING_SYSTEM="$( lsb_release -is )"
             }
@@ -188,15 +188,15 @@
         # <summary> Variable data-type validaiton </summary>
             function IsEnum
             {
-                local -n REFERENCE="$1"
+                local -n REFERENCE="${1}"
                 [ "${#REFERENCE[@]}" -gt 0 ]
-                return "$?"
+                return "${?}"
             }
 
             function IsEmptyEnum
             {
-                IsEnum "$1" || return "$?"
-                local -n REFERENCE="$1"
+                IsEnum "${1}" || return "${?}"
+                local -n REFERENCE="${1}"
 
                 for VALUE in "${REFERENCE[@]}"; do
                     [ ! -z "$VALUE" ] || return 1
@@ -207,9 +207,9 @@
 
             function IsInt
             {
-                [[ "$1" =~ ^[0-9]+$ ]] \
-                || [[ "$1" =~ ^[-][0-9]+$ ]]
-                return "$?"
+                [[ "${1}" =~ ^[0-9]+$ ]] \
+                || [[ "${1}" =~ ^[-][0-9]+$ ]]
+                return "${?}"
             }
 
         # <summary> Interaction </summary>
@@ -217,14 +217,14 @@
             {
                 local OUTPUT=""
 
-                if [[ ! -z "$1" ]]; then
-                    OUTPUT="$1 "
+                if [[ ! -z "${1}" ]]; then
+                    OUTPUT="${1} "
                 fi
 
                 for COUNT in $( seq 0 2 ); do
-                    read -r -p "$OUTPUT[Y/n]: " ANSWER
+                    read -r -p "${OUTPUT}[Y/n]: " ANSWER
 
-                    case "$ANSWER" in
+                    case "${ANSWER}" in
                         [Yy]* )
                             return 0 ;;
 
@@ -255,10 +255,10 @@
                         echo -en "$_PREFIX_FAIL" ;;
                 esac
 
-                if [[ -z "$1" ]]; then
+                if [[ -z "${1}" ]]; then
                     echo
                 else
-                    echo -e " $1"
+                    echo -e " ${1}"
                 fi
 
                 return "$_LAST_EXIT_CODE"
@@ -268,8 +268,8 @@
             {
                 SetExitCode
 
-                if [[ ! -z "$1" ]]; then
-                    echo -en "$1\t"
+                if [[ ! -z "${1}" ]]; then
+                    echo -en "${1}\t"
                 fi
 
                 case "$_LAST_EXIT_CODE" in
@@ -288,8 +288,8 @@
 
             function PrintSuffixWait
             {
-                if [[ ! -z "$1" ]]; then
-                    echo -en "$1\t"
+                if [[ ! -z "${1}" ]]; then
+                    echo -en "${1}\t"
                 fi
 
                 echo -e "$_SUFFIX_WORK"
@@ -311,33 +311,33 @@
         # <summary> Unnamed </summary>
         function FindPackage
         {
-            if [[ -z "$1" ]] \
+            if [[ -z "${1}" ]] \
                 || [[ -z "$_PACKAGE_MANAGER" ]]; then
-                echo -e "$_PREFIX_ERROR Input values are empty."
+                echo -e "${_PREFIX_ERROR} Input values are empty."
                 return 1
             fi
 
             case "$_PACKAGE_MANAGER" in
                 "apt" )
-                    apt list "$1" ;;
+                    apt list "${1}" ;;
 
                 "dnf" )
-                    dnf search "$1" ;;
+                    dnf search "${1}" ;;
 
                 "pacman" )
-                    pacman -Ss "$1" ;;
+                    pacman -Ss "${1}" ;;
 
                 "gentoo" )
-                    emerge --search "$1" ;;
+                    emerge --search "${1}" ;;
 
                 "urpmi" )
-                    urpmq "$1" ;;
+                    urpmq "${1}" ;;
 
                 "yum" )
-                    yum search "$1" ;;
+                    yum search "${1}" ;;
 
                 "zypper" )
-                    zypper se "$1" ;;
+                    zypper se "${1}" ;;
 
                 * )
                     echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
@@ -349,10 +349,10 @@
             if [[ "$_LAST_EXIT_CODE" -ne 0 ]]; then
                 case "$_PACKAGE_MANAGER" in
                     *" "* )
-                        echo -e "$_PREFIX_ERROR Packages '$_PACKAGE_MANAGER' were not found." ;;
+                        echo -e "${_PREFIX_ERROR} Packages '$_PACKAGE_MANAGER' were not found." ;;
 
                     * )
-                        echo -e "$_PREFIX_ERROR Package '$_PACKAGE_MANAGER' was not found." ;;
+                        echo -e "${_PREFIX_ERROR} Package '$_PACKAGE_MANAGER' was not found." ;;
                 esac
 
                 return 1
@@ -364,15 +364,15 @@
         function InstallPackage
         {
             if [[ -z "$_PACKAGE_MANAGER" ]] \
-                || [[ -z "$1" ]]; then
-                echo -e "$_PREFIX_ERROR Input values are empty."
+                || [[ -z "${1}" ]]; then
+                echo -e "${_PREFIX_ERROR} Input values are empty."
                 return 1
             fi
 
             local DO_REINSTALL=false
             local OPTION=""
 
-            if [[ "$2" == true ]]; then
+            if [[ "${2}" == true ]]; then
                 DO_REINSTALL=true
             fi
 
@@ -383,25 +383,25 @@
                         OPTION="--reinstall -o Dpkg::Options::=--force-confmiss"
                     fi
 
-                    apt update && apt full-upgrade -y && apt install -y "$OPTION" "$1" || return 1 ;;
+                    apt update && apt full-upgrade -y && apt install -y "$OPTION" "${1}" || return 1 ;;
 
                 "dnf" )
-                    dnf upgrade && dnf install "$1" ;;
+                    dnf upgrade && dnf install "${1}" ;;
 
                 "pacman" )
-                    pacman -Syu && pacman -S "$1" ;;
+                    pacman -Syu && pacman -S "${1}" ;;
 
                 "gentoo" )
-                    emerge -u @world && emerge "$1" ;;
+                    emerge -u @world && emerge "${1}" ;;
 
                 "urpmi" )
-                    urpmi --auto-update && urpmi "$1" ;;
+                    urpmi --auto-update && urpmi "${1}" ;;
 
                 "yum" )
-                    yum update && yum install "$1" ;;
+                    yum update && yum install "${1}" ;;
 
                 "zypper" )
-                    zypper refresh && zypper in "$1" ;;
+                    zypper refresh && zypper in "${1}" ;;
 
                 * )
                     echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
@@ -409,14 +409,14 @@
             esac
 
             PrintSuffixPassOrFail "Installing software packages..."
-            return "$?"
+            return "${?}"
         }
 
         function IsInstalledPackage
         {
             if [[ -z "$_PACKAGE_MANAGER" ]] \
-                || [[ -z "$1" ]]; then
-                echo -e "$_PREFIX_ERROR Input values are empty."
+                || [[ -z "${1}" ]]; then
+                echo -e "${_PREFIX_ERROR} Input values are empty."
                 return 1
             fi
 
@@ -432,8 +432,8 @@
                     return 1 ;;
             esac
 
-            local -i COUNT_DELIM=$( echo "$1" | wc -w )
-            local GET_PACKAGE='echo "$1" | cut -d ' ' -f "$COUNT_DELIM"'
+            local -i COUNT_DELIM=$( echo "${1}" | wc -w )
+            local GET_PACKAGE='echo "${1}" | cut -d ' ' -f "$COUNT_DELIM"'
 
             while [[ ! -z "$PACKAGE" ]]; do
                 local PACKAGE=$( eval "$GET_PACKAGE" )
@@ -447,7 +447,7 @@
         function IsSudoUser
         {
             if [[ $( whoami ) != "root" ]]; then
-                echo -e "$_PREFIX_ERROR User is not sudo/root."
+                echo -e "${_PREFIX_ERROR} User is not sudo/root."
                 return 1
             fi
 
@@ -457,33 +457,33 @@
         function UninstallPackage
         {
             if [[ -z "$_PACKAGE_MANAGER" ]] \
-                || [[ -z "$1" ]]; then
-                echo -e "$_PREFIX_ERROR Input values are empty."
+                || [[ -z "${1}" ]]; then
+                echo -e "${_PREFIX_ERROR} Input values are empty."
                 return 1
             fi
 
             # <remarks> Uninstall selected packages </remarks>
             case "$_PACKAGE_MANAGER" in
                 "apt" )
-                    apt uninstall "$1" ;;
+                    apt uninstall "${1}" ;;
 
                 "dnf" )
-                    dnf remove "$1" ;;
+                    dnf remove "${1}" ;;
 
                 "pacman" )
-                    pacman -R "$1" ;;
+                    pacman -R "${1}" ;;
 
                 "gentoo" )
-                    emerge -Cv "$1" ;;
+                    emerge -Cv "${1}" ;;
 
                 "urpmi" )
-                    urpme "$1" ;;
+                    urpme "${1}" ;;
 
                 "yum" )
-                    yum remove "$1" ;;
+                    yum remove "${1}" ;;
 
                 "zypper" )
-                    zypper remove "$1" ;;
+                    zypper remove "${1}" ;;
 
                 * )
                     echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
@@ -491,56 +491,56 @@
             esac
 
             PrintSuffixPassOrFail "Uninstalling software packages..."
-            return "$?"
+            return "${?}"
         }
 
         function UpdateOrCloneGitRepo
         {
             local DO_AUTO_ANSWER_YES=false
 
-            if [[ "$4" == true ]]; then
+            if [[ "${4}" == true ]]; then
                 DO_AUTO_ANSWER_YES=true
             fi
 
-            if [[ -z "$3" ]] \
-                || [[ -z "$2" ]] \
-                || [[ -z "$1" ]]; then
-                echo -e "$_PREFIX_ERROR Input values are empty."
+            if [[ -z "${3}" ]] \
+                || [[ -z "${2}" ]] \
+                || [[ -z "${1}" ]]; then
+                echo -e "${_PREFIX_ERROR} Input values are empty."
                 return 1
             fi
 
-            if [[ ! -d "$1$2" ]] \
-                && ! sudo mkdir -p "$1$3"; then
-                echo -e "$_PREFIX_ERROR Failed to create directory '$1$3'."
+            if [[ ! -d "${1}${2}" ]] \
+                && ! sudo mkdir -p "${1}${3}"; then
+                echo -e "${_PREFIX_ERROR} Failed to create directory '${1}${3}'."
                 return 1
             fi
 
             # <remarks> Update existing GitHub repository. </remarks>
-            if [[ -d "$1$2" ]]; then
-                cd "$1$2"
+            if [[ -d "${1}${2}" ]]; then
+                cd "${1}${2}"
 
                 if ! git pull &> /dev/null; then
-                    echo -e "$_PREFIX_ERROR Failed to update repository."
+                    echo -e "${_PREFIX_ERROR} Failed to update repository."
                     return 1
                 fi
 
                 return 0
 
             # <remarks> Clone new GitHub repository. </remarks>
-            elif [[ -d "$1$3" ]]; then
+            elif [[ -d "${1}${3}" ]]; then
                 for COUNT in $( seq 0 2 ); do
                     if ! "$DO_AUTO_ANSWER_YES"; then
-                        read -r -p "Clone repo '$2'? [Y/n]: " ANSWER
+                        read -r -p "Clone repo '${2}'? [Y/n]: " ANSWER
                     else
                         ANSWER="Y"
                     fi
 
-                    case "$ANSWER" in
+                    case "${ANSWER}" in
                         [Yy]* )
-                            cd "$1$3"
+                            cd "${1}${3}"
 
-                            if ! git clone "https://github.com/$2" &> /dev/null; then
-                                echo -e "$_PREFIX_ERROR Failed to download repository."
+                            if ! git clone "https://github.com/${2}" &> /dev/null; then
+                                echo -e "${_PREFIX_ERROR} Failed to download repository."
                                 return 1
                             fi
 
diff --git a/bin/vfiolib-files b/bin/vfiolib-files
--- a/bin/vfiolib-files
+++ b/bin/vfiolib-files
@@ -15,10 +15,10 @@
     # <summary> Public </summary>
         function ExecuteBackups
         {
-            SetWorkingDirToBackupsFolder || return "$?"
-            GetFiles || return "$?"
-            SetFiles || return "$?"
-            CopyFilesToPaths || return "$?"
+            SetWorkingDirToBackupsFolder || return "${?}"
+            GetFiles || return "${?}"
+            SetFiles || return "${?}"
+            CopyFilesToPaths || return "${?}"
             _HAS_EXECUTED_BACKUPS=true
             return 0
         }
@@ -97,14 +97,14 @@
     # <summary> Private </summary>
         function BackupFile
         {
-            if [[ -e "$1" ]] \
-                && cmp -s "$1" "$1$_SUFFIX_BACKUP"; then
+            if [[ -e "${1}" ]] \
+                && cmp -s "${1}" "${1}$_SUFFIX_BACKUP"; then
                 return 0
             fi
 
-            if ( [[ -e "$1" ]] \
-                && ! sudo cp -rv "$1" "$1$_SUFFIX_BACKUP" &> /dev/null ); then
-                echo -e "$_PREFIX_ERROR Failed to backup file '$1'."
+            if ( [[ -e "${1}" ]] \
+                && ! sudo cp -rv "${1}" "${1}$_SUFFIX_BACKUP" &> /dev/null ); then
+                echo -e "${_PREFIX_ERROR} Failed to backup file '${1}'."
                 return 1
             fi
 
@@ -114,12 +114,12 @@
         function BackupFiles
         {
             BackupFile "$_APPARMOR_QEMU_DEST_PATH" || return 1
-            BackupFile "$_CUSTOM_GRUB_DEST_PATH" || return 1
-            BackupFile "$_GRUB_DEST_PATH_1" || return 1
-            BackupFile "$_INITRAMFS_MODULES_DEST_PATH" || return 1
-            BackupFile "$_MODPROBE_BLACKLISTS_DEST_PATH" || return 1
-            BackupFile "$_MODPROBE_VFIO_DEST_PATH" || return 1
-            BackupFile "$_MODULES_DEST_PATH" || return 1
+            BackupFile "${_CUSTOM_GRUB_DEST_PATH}" || return 1
+            BackupFile "${_GRUB_DEST_PATH_1}" || return 1
+            BackupFile "${_INITRAMFS_MODULES_DEST_PATH}" || return 1
+            BackupFile "${_MODPROBE_BLACKLISTS_DEST_PATH}" || return 1
+            BackupFile "${_MODPROBE_VFIO_DEST_PATH}" || return 1
+            BackupFile "${_MODULES_DEST_PATH}" || return 1
             BackupFile "$_QEMU_DEST_PATH" || return 1
             return 0
         }
@@ -127,47 +127,47 @@
         function CopyFilesToPaths
         {
             if ! sudo mkdir -p $( dirname "$_APPARMOR_QEMU_DEST_PATH" ) \
-                || ! sudo mkdir -p $( dirname "$_CUSTOM_GRUB_DEST_PATH" ) \
+                || ! sudo mkdir -p $( dirname "${_CUSTOM_GRUB_DEST_PATH}" ) \
                 || ! sudo mkdir -p $( dirname "$_QEMU_DEST_PATH" ); then
-                echo -e "$_PREFIX_ERROR Failed to create directories."
+                echo -e "${_PREFIX_ERROR} Failed to create directories."
                 return 1
             fi
 
             if [[ -e "$_APPARMOR_QEMU_DEST_PATH" ]] \
                 && ! sudo rm "$_APPARMOR_QEMU_DEST_PATH" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to delete file '$_APPARMOR_QEMU_DEST_PATH'."
+                echo -e "${_PREFIX_ERROR} Failed to delete file '$_APPARMOR_QEMU_DEST_PATH'."
                 return 1
             fi
 
             if ! sudo touch "$_APPARMOR_QEMU_DEST_PATH" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to create file '$_APPARMOR_QEMU_DEST_PATH'."
+                echo -e "${_PREFIX_ERROR} Failed to create file '$_APPARMOR_QEMU_DEST_PATH'."
                 return 1
             fi
 
-            if ! sudo cp -rv "$_CUSTOM_GRUB_SRC_PATH" "$_CUSTOM_GRUB_DEST_PATH" &> /dev/null \
-                || ! sudo cp -rv "$_INITRAMFS_MODULES_SRC_PATH" "$_INITRAMFS_MODULES_DEST_PATH" &> /dev/null \
-                || ! sudo cp -rv "$_MODPROBE_BLACKLISTS_SRC_PATH" "$_MODPROBE_BLACKLISTS_DEST_PATH" &> /dev/null \
-                || ! sudo cp -rv "$_MODPROBE_VFIO_SRC_PATH" "$_MODPROBE_VFIO_DEST_PATH" &> /dev/null \
-                || ! sudo cp -rv "$_MODULES_SRC_PATH" "$_MODULES_DEST_PATH" &> /dev/null \
+            if ! sudo cp -rv "$_CUSTOM_GRUB_SRC_PATH" "${_CUSTOM_GRUB_DEST_PATH}" &> /dev/null \
+                || ! sudo cp -rv "$_INITRAMFS_MODULES_SRC_PATH" "${_INITRAMFS_MODULES_DEST_PATH}" &> /dev/null \
+                || ! sudo cp -rv "$_MODPROBE_BLACKLISTS_SRC_PATH" "${_MODPROBE_BLACKLISTS_DEST_PATH}" &> /dev/null \
+                || ! sudo cp -rv "$_MODPROBE_VFIO_SRC_PATH" "${_MODPROBE_VFIO_DEST_PATH}" &> /dev/null \
+                || ! sudo cp -rv "$_MODULES_SRC_PATH" "${_MODULES_DEST_PATH}" &> /dev/null \
                 || ! sudo cp -rv "$_QEMU_SRC_PATH" "$_QEMU_DEST_PATH" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to copy files."
+                echo -e "${_PREFIX_ERROR} Failed to copy files."
                 return 1
             fi
 
             if ! sudo chown root:root "$_APPARMOR_QEMU_DEST_PATH" &> /dev/null \
-                || ! sudo chown root:root "$_CUSTOM_GRUB_DEST_PATH" &> /dev/null \
-                || ! sudo chmod +x "$_CUSTOM_GRUB_DEST_PATH" &> /dev/null \
-                || ! sudo chown root:root "$_INITRAMFS_MODULES_DEST_PATH" &> /dev/null \
-                || ! sudo chown root:root "$_MODPROBE_BLACKLISTS_DEST_PATH" &> /dev/null \
-                || ! sudo chown root:root "$_MODPROBE_VFIO_DEST_PATH" &> /dev/null \
-                || ! sudo chown root:root "$_MODULES_DEST_PATH" &> /dev/null \
+                || ! sudo chown root:root "${_CUSTOM_GRUB_DEST_PATH}" &> /dev/null \
+                || ! sudo chmod +x "${_CUSTOM_GRUB_DEST_PATH}" &> /dev/null \
+                || ! sudo chown root:root "${_INITRAMFS_MODULES_DEST_PATH}" &> /dev/null \
+                || ! sudo chown root:root "${_MODPROBE_BLACKLISTS_DEST_PATH}" &> /dev/null \
+                || ! sudo chown root:root "${_MODPROBE_VFIO_DEST_PATH}" &> /dev/null \
+                || ! sudo chown root:root "${_MODULES_DEST_PATH}" &> /dev/null \
                 || ! sudo chown root:root "$_QEMU_DEST_PATH" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to set permissions for files."
+                echo -e "${_PREFIX_ERROR} Failed to set permissions for files."
                 return 1
             fi
 
             if ! sudo chmod 644 "$_APPARMOR_QEMU_DEST_PATH" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to set permissions for file '$_APPARMOR_QEMU_DEST_PATH'."
+                echo -e "${_PREFIX_ERROR} Failed to set permissions for file '$_APPARMOR_QEMU_DEST_PATH'."
                 return 1
             fi
         }
@@ -182,7 +182,7 @@
                 || [[ ! -e "$_MODPROBE_BLACKLISTS_SRC_PATH" ]] \
                 || [[ ! -e "$_MODPROBE_VFIO_SRC_PATH" ]] \
                 || [[ ! -e "$_MODULES_SRC_PATH" ]]; then
-                echo -e "$_PREFIX_ERROR Failed to find backup files."
+                echo -e "${_PREFIX_ERROR} Failed to find backup files."
                 return 1
             fi
 
@@ -195,19 +195,19 @@
 
         function GetFilesForGRUB
         {
-            if [[ -e "$_GRUB_DEST_PATH_1" ]]; then
+            if [[ -e "${_GRUB_DEST_PATH_1}" ]]; then
                 return 0
             fi
 
             if [[ ! -e "$_GRUB_DEST_PATH_2" ]] \
                 && [[ ! -e "$_GRUB_SRC_PATH" ]]; then
-                echo -e "$_PREFIX_ERROR Failed to find GRUB source file."
+                echo -e "${_PREFIX_ERROR} Failed to find GRUB source file."
                 return 1
             fi
 
             if [[ ! -e "$_GRUB_DEST_PATH_BACKUP" ]]; then
                 if ! sudo cp "$_GRUB_DEST_PATH_2" "$_GRUB_SRC_PATH"; then
-                    echo -e "$_PREFIX_ERROR Failed to backup GRUB source file."
+                    echo -e "${_PREFIX_ERROR} Failed to backup GRUB source file."
                     return 1
                 fi
             fi
@@ -217,20 +217,20 @@
 
         function RestoreFile
         {
-            if [[ -e "$1$_SUFFIX_BACKUP" ]] \
-                && cmp -s "$1" "$1$_SUFFIX_BACKUP"; then
+            if [[ -e "${1}$_SUFFIX_BACKUP" ]] \
+                && cmp -s "${1}" "${1}$_SUFFIX_BACKUP"; then
                 return 0
             fi
 
-            if ( [[ -e "$1$_SUFFIX_BACKUP" ]] \
-                && ! sudo cp -rv "$1$_SUFFIX_BACKUP" "$1" &> /dev/null ); then
-                echo -e "$_PREFIX_ERROR Failed to restore file '$1'."
+            if ( [[ -e "${1}$_SUFFIX_BACKUP" ]] \
+                && ! sudo cp -rv "${1}$_SUFFIX_BACKUP" "${1}" &> /dev/null ); then
+                echo -e "${_PREFIX_ERROR} Failed to restore file '${1}'."
                 return 1
             fi
 
-            if [[ -e "$1$_SUFFIX_BACKUP" ]] \
-                && ! sudo rm -f "$1$_SUFFIX_BACKUP" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to delete file '$1'."
+            if [[ -e "${1}$_SUFFIX_BACKUP" ]] \
+                && ! sudo rm -f "${1}$_SUFFIX_BACKUP" &> /dev/null; then
+                echo -e "${_PREFIX_ERROR} Failed to delete file '${1}'."
                 return 1
             fi
 
@@ -240,12 +240,12 @@
         function RestoreFiles
         {
             RestoreFile "$_APPARMOR_QEMU_DEST_PATH" || return 1
-            RestoreFile "$_CUSTOM_GRUB_DEST_PATH" || return 1
-            RestoreFile "$_GRUB_DEST_PATH_1" || return 1
-            RestoreFile "$_INITRAMFS_MODULES_DEST_PATH" || return 1
-            RestoreFile "$_MODPROBE_BLACKLISTS_DEST_PATH" || return 1
-            RestoreFile "$_MODPROBE_VFIO_DEST_PATH" || return 1
-            RestoreFile "$_MODULES_DEST_PATH" || return 1
+            RestoreFile "${_CUSTOM_GRUB_DEST_PATH}" || return 1
+            RestoreFile "${_GRUB_DEST_PATH_1}" || return 1
+            RestoreFile "${_INITRAMFS_MODULES_DEST_PATH}" || return 1
+            RestoreFile "${_MODPROBE_BLACKLISTS_DEST_PATH}" || return 1
+            RestoreFile "${_MODPROBE_VFIO_DEST_PATH}" || return 1
+            RestoreFile "${_MODULES_DEST_PATH}" || return 1
             RestoreFile "$_QEMU_DEST_PATH" || return 1
             return 0
         }
@@ -257,21 +257,21 @@
             fi
 
             if [[ ! -e "$_QEMU_SRC_PATH" ]]; then
-                echo -e "$_PREFIX_ERROR Failed to find QEMU source file. Attempting to download."
+                echo -e "${_PREFIX_ERROR} Failed to find QEMU source file. Attempting to download."
 
                 if ! command -v curl &> /dev/null; then
-                    echo -e "$_PREFIX_ERROR Required command 'curl' is not installed."
+                    echo -e "${_PREFIX_ERROR} Required command 'curl' is not installed."
                     return 1
                 fi
 
                 if ! curl -v "$_QEMU_FILE_URL" -o "$_QEMU_SRC_PATH" &> /dev/null; then
-                    echo -e "$_PREFIX_ERROR Failed to find backup QEMU source file."
+                    echo -e "${_PREFIX_ERROR} Failed to find backup QEMU source file."
                     return 1
                 fi
             fi
 
             if ! sudo cp $_QEMU_SRC_PATH $_QEMU_DEST_PATH &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to restore QEMU backup file."
+                echo -e "${_PREFIX_ERROR} Failed to restore QEMU backup file."
                 return 1
             fi
 
@@ -281,7 +281,7 @@
         function SetWorkingDirToBackupsFolder
         {
             if ! cd "$_BACKUPS_PATH" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to set working directory."
+                echo -e "${_PREFIX_ERROR} Failed to set working directory."
                 return 1
             fi
 
@@ -298,7 +298,7 @@
         function SetFilesForGRUB
         {
             if ! sudo cp "$_GRUB_SRC_PATH" "$_GRUB_SRC_BACKUP_PATH" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to copy GRUB backup file."
+                echo -e "${_PREFIX_ERROR} Failed to copy GRUB backup file."
                 return 1
             fi
 
@@ -306,21 +306,21 @@
             local -r LINE_GRUB_DISTRIBUTOR="GRUB_DISTRIBUTOR=\`lsb_release -i -s 2> /dev/null || echo "$( lsb_release -i -s )"\`"
             local -r LINE_GRUB_CMDLINE_DEFAULT="GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash\""
 
-            if ! sed -i '/GRUB_DISTRIBUTOR=*/c\'"$LINE_GRUB_DISTRIBUTOR" "$_GRUB_SRC_BACKUP_PATH" \
-                || ! sed -i '/GRUB_CMDLINE_LINUX_DEFAULT=*/c\'"$LINE_GRUB_CMDLINE_DEFAULT" "$_GRUB_SRC_BACKUP_PATH"; then
-                echo -e "$_PREFIX_ERROR Failed to clear target lines of GRUB backup file."
+            if ! sed -i '/GRUB_DISTRIBUTOR=*/c\'"${LINE_GRUB_DISTRIBUTOR}" "$_GRUB_SRC_BACKUP_PATH" \
+                || ! sed -i '/GRUB_CMDLINE_LINUX_DEFAULT=*/c\'"${LINE_GRUB_CMDLINE_DEFAULT}" "$_GRUB_SRC_BACKUP_PATH"; then
+                echo -e "${_PREFIX_ERROR} Failed to clear target lines of GRUB backup file."
                 return 1
             fi
 
-            if [[ -z $( grep "$LINE_GRUB_DISTRIBUTOR" "$_GRUB_SRC_BACKUP_PATH" ) ]] \
-                || [[ -z $( grep "$LINE_GRUB_CMDLINE_DEFAULT" "$_GRUB_SRC_BACKUP_PATH" ) ]]; then
-                echo -e "$_PREFIX_ERROR Failed to overwrite target lines of GRUB backup file."
+            if [[ -z $( grep "${LINE_GRUB_DISTRIBUTOR}" "$_GRUB_SRC_BACKUP_PATH" ) ]] \
+                || [[ -z $( grep "${LINE_GRUB_CMDLINE_DEFAULT}" "$_GRUB_SRC_BACKUP_PATH" ) ]]; then
+                echo -e "${_PREFIX_ERROR} Failed to overwrite target lines of GRUB backup file."
                 return 1
             fi
 
             # <remarks> Note: this must be the second file (that is the overwritten copy) </remarks>
-            if ! sudo cp "$_GRUB_SRC_BACKUP_PATH" "$_GRUB_DEST_PATH_1" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to restore GRUB backup file."
+            if ! sudo cp "$_GRUB_SRC_BACKUP_PATH" "${_GRUB_DEST_PATH_1}" &> /dev/null; then
+                echo -e "${_PREFIX_ERROR} Failed to restore GRUB backup file."
                 return 1
             fi
 
diff --git a/bin/vfiolib-post-setup b/bin/vfiolib-post-setup
--- a/bin/vfiolib-post-setup
+++ b/bin/vfiolib-post-setup
@@ -19,7 +19,7 @@
 		{
 			function Main
 			{
-				while [[ "$?" -ne 1 ]]; do
+				while [[ "${?}" -ne 1 ]]; do
 					if "$_ASK_TO_EXECUTE_POST_SETUPS"; then
 						LibvirtHooks
 						GuestAudioLoopback
@@ -47,14 +47,14 @@
 					break
 				done
 
-				return "$?"
+				return "${?}"
 			}
 
 			local OUTPUT="Executing post-setup...\t"
-			PrintSuffixWait "$OUTPUT"
+			PrintSuffixWait "${OUTPUT}"
 			Main
-			PrintSuffixPassOrFail "$OUTPUT"
-			return "$?"
+			PrintSuffixPassOrFail "${OUTPUT}"
+			return "${?}"
 		}
 
         # <summary> Global setters </summary>
@@ -85,17 +85,17 @@
                     local -r SCRIPT_NAME="install.sh"
 
                     if ! cd "$_GIT_PATH$FULL_REPO"; then
-                        echo -e "$_PREFIX_ERROR Failed to find build directory."
+                        echo -e "${_PREFIX_ERROR} Failed to find build directory."
                         return 1
                     fi
 
                     if [[ ! -e "$SCRIPT_NAME" ]]; then
-                        echo -e "$_PREFIX_ERROR Failed to find script '$SCRIPT_NAME'."
+                        echo -e "${_PREFIX_ERROR} Failed to find script '$SCRIPT_NAME'."
                         return 1
                     fi
 
                     if ! echo "i" | sudo bash "$SCRIPT_NAME" &> /dev/null; then
-                        echo -e "$_PREFIX_ERROR Failed to execute script '$SCRIPT_NAME'."
+                        echo -e "${_PREFIX_ERROR} Failed to execute script '$SCRIPT_NAME'."
                         return 1
                     fi
 
@@ -106,13 +106,13 @@
                 {
                     function AskToContinue
                     {
-                        local -n REFERENCE="$1"
+                        local -n REFERENCE="${1}"
 
                         for COUNT in $( seq 0 2 ); do
                             read -r -p "Set fraction of total memory for zram-swap to use (to calculate default, enter 'default'): " ANSWER
 
-                            if GetZRAMSwapSize "$ANSWER"; then
-                                REFERENCE="$ANSWER"
+                            if GetZRAMSwapSize "${ANSWER}"; then
+                                REFERENCE="${ANSWER}"
                                 return 0
                             fi
                         done
@@ -126,7 +126,7 @@
 
                     if ! "$_HAS_ARG_ZRAM_SWAP_DEFAULTS" \
                         && ! "$_HAS_ARG_ZRAM_SWAP_SET_FRACTION"; then
-                        AskToContinue "$FRACTION" || return "$?"
+                        AskToContinue "$FRACTION" || return "${?}"
                     fi
 
                     if "$_HAS_ARG_ZRAM_SWAP_DEFAULTS" \
@@ -141,14 +141,14 @@
 
                         # <remarks> Is fraction positive non-zero and not equal to one. </remarks>
                         if [[ "$DENOMINATOR" -le 0 ]]; then
-                            echo -e "$_PREFIX_ERROR Denominator is negative or zero."
+                            echo -e "${_PREFIX_ERROR} Denominator is negative or zero."
                         fi
 
                         FRACTION="1/$DENOMINATOR"
                     fi
 
-                    if ! sed -i '/'$LINE_TO_MATCH'"*"/c\'$LINE_TO_MATCH'"'$FRACTION'"' "$FILE"; then
-                        echo -e "$_PREFIX_ERROR Failed to write output to zram-swap file."
+                    if ! sed -i '/'${LINE_TO_MATCH}'"*"/c\'${LINE_TO_MATCH}'"'$FRACTION'"' "${FILE}"; then
+                        echo -e "${_PREFIX_ERROR} Failed to write output to zram-swap file."
                         return 1
                     fi
 
@@ -162,22 +162,22 @@
 
                     if sudo swapon -v | grep zram &> /dev/null \
                         && ! sudo swapoff /dev/zram* &> /dev/null; then
-                        echo -e "$_PREFIX_ERROR Failed to disable zram-swap device(s)."
+                        echo -e "${_PREFIX_ERROR} Failed to disable zram-swap device(s)."
                         return 1
                     fi
 
                     if ! sudo systemctl daemon-reload &> /dev/null; then
-                        echo -e "$_PREFIX_ERROR Failed to update systemd."
+                        echo -e "${_PREFIX_ERROR} Failed to update systemd."
                         return 1
                     fi
 
                     if ! sudo systemctl restart zram-swap &> /dev/null; then
-                        echo -e "$_PREFIX_ERROR Failed to restart zram-swap service."
+                        echo -e "${_PREFIX_ERROR} Failed to restart zram-swap service."
                         return 1
                     fi
 
                     if ! sudo swapon -v | grep zram &> /dev/null; then
-                        echo -e "$_PREFIX_ERROR Failed to enable zram-swap device."
+                        echo -e "${_PREFIX_ERROR} Failed to enable zram-swap device."
                         return 1
                     fi
 
@@ -217,28 +217,28 @@
             {
                 IsHostMemorySufficientForZRAMSwap || return 1
 
-                case "$1" in
+                case "${1}" in
                     *"/"* )
-                        local -i NUMERATOR=$( echo $1 | cut -d '/' -f1 )
-                        local -i DENOMINATOR=$( echo $1 | cut -d '/' -f2 ) ;;
+                        local -i NUMERATOR=$( echo ${1} | cut -d '/' -f1 )
+                        local -i DENOMINATOR=$( echo ${1} | cut -d '/' -f2 ) ;;
 
                     "default" )
                         _HAS_ARG_ZRAM_SWAP_DEFAULTS=true
                         return 0 ;;
 
                     * )
-                        echo -e "$_PREFIX_ERROR Not a fraction."
+                        echo -e "${_PREFIX_ERROR} Not a fraction."
                         return 1 ;;
                 esac
 
                 if ! [[ "$NUMERATOR" =~ ^[0-9]+$ ]] \
                     || ! [[ "$DENOMINATOR" =~ ^[0-9]+$ ]]; then
-                    echo -e "$_PREFIX_ERROR Values are not numbers."
+                    echo -e "${_PREFIX_ERROR} Values are not numbers."
                     return 1
                 fi
 
                 if [[ "$NUMERATOR" -lt "$DENOMINATOR" ]] || [[ "$DENOMINATOR" -gt 1 ]]; then
-                    declare -g _ARGS_FOR_ZRAM_SWAP_FRACTION="$1"
+                    declare -g _ARGS_FOR_ZRAM_SWAP_FRACTION="${1}"
                     _HAS_ARG_ZRAM_SWAP_SET_FRACTION=true
                     return 0
 
@@ -246,7 +246,7 @@
                     return 1
 
                 else
-                    echo -e "$_PREFIX_ERROR Invalid fraction."
+                    echo -e "${_PREFIX_ERROR} Invalid fraction."
                 fi
 
                 return 1
@@ -259,7 +259,7 @@
                 fi
 
                 if ! GetFreeMemory; then
-                    echo -e "$_PREFIX_ERROR Insufficient Host memory for zram-swap."
+                    echo -e "${_PREFIX_ERROR} Insufficient Host memory for zram-swap."
                     return 1
                 fi
 
@@ -323,7 +323,7 @@
 				fi
 
 				IsInstalledPackage "$DEPENDENCIES" &> /dev/null || InstallPackage "$DEPENDENCIES" &> /dev/null
-				return "$?"
+				return "${?}"
 			}
 
 			Main
@@ -340,27 +340,27 @@
 			function Main
 			{
 				if ! command -v "pulseaudio" &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Required audio backend 'PulseAudio' is missing."
+					echo -e "${_PREFIX_ERROR} Required audio backend 'PulseAudio' is missing."
 					return 1
 				fi
 
 				if ! sudo cp "$_AUDIO_LOOPBACK_SRC_PATH" "$_AUDIO_LOOPBACK_DEST_PATH"; then
-					echo -e "$_PREFIX_ERROR Failed to copy file."
+					echo -e "${_PREFIX_ERROR} Failed to copy file."
 					return 1
 				fi
 
 				if ! sudo systemctl daemon-reload &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to update systemd with new daemon/service."
+					echo -e "${_PREFIX_ERROR} Failed to update systemd with new daemon/service."
 					return 1
 				fi
 
 				if ! sudo systemctl start "$_AUDIO_LOOPBACK_FILENAME"; then
-					echo -e "$_PREFIX_ERROR Failed to start audio loopback service."
+					echo -e "${_PREFIX_ERROR} Failed to start audio loopback service."
 					return 1
 				fi
 
 				if ! sudo systemctl enable "$_AUDIO_LOOPBACK_FILENAME"; then
-					echo -e "$_PREFIX_ERROR Failed to enable audio loopback service."
+					echo -e "${_PREFIX_ERROR} Failed to enable audio loopback service."
 					return 1
 				fi
 
@@ -401,7 +401,7 @@
 					|| ! sudo cp "$_LIBVIRT_HOOK_NOSLEEP_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_NOSLEEP_HOOK_DEST_PATH" &> /dev/null \
 					|| ! sudo cp "$_LIBVIRT_HOOK_NOSLEEP_SERVICE_SRC_PATH" "$_LIBVIRT_HOOK_NOSLEEP_SERVICE_DEST_PATH" &> /dev/null \
 					|| ! sudo cp "$_LIBVIRT_HOOK_UPDATE_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_UPDATE_HOOK_DEST_PATH" &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to copy file(s)."
+					echo -e "${_PREFIX_ERROR} Failed to copy file(s)."
 					return 1
 				fi
 
@@ -411,18 +411,18 @@
 					|| ! sudo chmod +x "$_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH" &> /dev/null \
 					|| ! sudo chmod +x "$_LIBVIRT_HOOK_NOSLEEP_HOOK_DEST_PATH" &> /dev/null \
 					|| ! sudo chmod +x "$_LIBVIRT_HOOK_UPDATE_HOOK_DEST_PATH" &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to set file permissions."
+					echo -e "${_PREFIX_ERROR} Failed to set file permissions."
 					return 1
 				fi
 
 				if ! "$_HAS_EXECUTED_PRE_SETUP_STATIC_ISOLCPU"; then
 					if ! sudo cp "$_LIBVIRT_HOOK_ISOLCPU_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH" &> /dev/null; then
-						echo -e "$_PREFIX_ERROR Failed to copy file(s)."
+						echo -e "${_PREFIX_ERROR} Failed to copy file(s)."
 						return 1
 					fi
 
 					if ! sudo chmod +x "$_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH" &> /dev/null; then
-						echo -e "$_PREFIX_ERROR Failed to set file permissions."
+						echo -e "${_PREFIX_ERROR} Failed to set file permissions."
 						return 1
 					fi
 				fi
@@ -433,13 +433,13 @@
 					|| ! sudo echo -e "source \"$_LIBVIRT_HOOK_NOSLEEP_HOOK_DEST_PATH\"" >> "$_LIBVIRT_HOOK_DEST_PATH" \
 					|| ! sudo echo -e "source \"$_LIBVIRT_HOOK_UPDATE_HOOK_DEST_PATH\"" >> "$_LIBVIRT_HOOK_DEST_PATH" \
                     || ! sudo echo -e "# </sources>" >> "$_LIBVIRT_HOOK_DEST_PATH"; then
-					echo -e "$_PREFIX_ERROR Failed to append filenames as sources to Libvirt hooks file."
+					echo -e "${_PREFIX_ERROR} Failed to append filenames as sources to Libvirt hooks file."
 					return 1
 				fi
 
 				if ! sudo systemctl daemon-reload &> /dev/null \
 					|| ! sudo systemctl restart libvirtd &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to update systemd with new daemon/service."
+					echo -e "${_PREFIX_ERROR} Failed to update systemd with new daemon/service."
 					return 1
 				fi
 
@@ -505,17 +505,17 @@
 				local -r SCRIPT_NAME="installer.bash"
 
 				if ! cd "$_GIT_PATH$FULL_REPO"; then
-					echo -e "$_PREFIX_ERROR Failed to find build directory."
+					echo -e "${_PREFIX_ERROR} Failed to find build directory."
 					return 1
 				fi
 
 				if [[ ! -e "$SCRIPT_NAME" ]]; then
-					echo -e "$_PREFIX_ERROR Failed to find script '$SCRIPT_NAME'."
+					echo -e "${_PREFIX_ERROR} Failed to find script '$SCRIPT_NAME'."
 					return 1
 				fi
 
 				if ! sudo bash $SCRIPT_NAME $_ARGS_FOR_AUTO_XORG &> /dev/null; then
-					echo -e "$_PREFIX_ERROR Failed to execute script '$SCRIPT_NAME'."
+					echo -e "${_PREFIX_ERROR} Failed to execute script '$SCRIPT_NAME'."
 					return 1
 				fi
 
@@ -547,9 +547,9 @@
 
 					for _COUNT in $( seq 1 "$COUNT_OF_VALID_ARGS" ); do
 						read -r -p "Enter argument (to skip, leave blank): " ANSWER
-						GetArgsForAutoXorg "$ANSWER" || return 1
+						GetArgsForAutoXorg "${ANSWER}" || return 1
 
-						if [[ -z "$ANSWER" ]]; then
+						if [[ -z "${ANSWER}" ]]; then
 							break
 						fi
 					done
diff --git a/bin/vfiolib-pre-setup b/bin/vfiolib-pre-setup
--- a/bin/vfiolib-pre-setup
+++ b/bin/vfiolib-pre-setup
@@ -21,7 +21,7 @@
         {
             function Main
             {
-                while [[ "$?" -ne 1 ]]; do
+                while [[ "${?}" -ne 1 ]]; do
                     AddUserToGroups
 
                     if "$_ASK_TO_EXECUTE_PRE_SETUP_ALL"; then
@@ -48,14 +48,14 @@
                     break
                 done
 
-                return "$?"
+                return "${?}"
             }
 
             local OUTPUT="Executing pre-setup...\t"
-            PrintSuffixWait "$OUTPUT"
+            PrintSuffixWait "${OUTPUT}"
             Main
-            PrintSuffixPassOrFail "$OUTPUT"
-            return "$?"
+            PrintSuffixPassOrFail "${OUTPUT}"
+            return "${?}"
         }
 
         # <summary> Global setters </summary>
@@ -124,7 +124,7 @@
                     _IS_HUGEPAGES_SETUP=false
 
                     if ! [[ "$_INT_MAX_MEMORY" =~ ^[0-9]+$ ]]; then
-                        echo -e "$_PREFIX_ERROR Could not parse system memory."
+                        echo -e "${_PREFIX_ERROR} Could not parse system memory."
                         return 1
                     fi
 
@@ -133,7 +133,7 @@
                             echo -e "Hugepages is a feature which statically allocates system memory to pagefiles.\nGuest(s) can use Hugepages to a peformance benefit.\nThe greater the Hugepage size, the less fragmentation of memory, and the less latency/overhead of system memory-access.\n${var_yellow}NOTE:${var_reset_color} It is recommended to use a size which is a multiple of an individual memory channel/stick.\n${var_yellow}Example:${var_reset_color} Four (4) channels of 8 GB each, use 1x, 2x, or 3x (8 GB, 16 GB, or 24 GB).\n"
                         fi
 
-                        AskToExecuteOrSkip "Setup Hugepages?" || return "$?"
+                        AskToExecuteOrSkip "Setup Hugepages?" || return "${?}"
                     fi
 
                     if ! "$_IS_HUGEPAGES_SIZE_SET"; then
@@ -166,11 +166,11 @@
 
             function GetHugepageByteSize
             {
-                local -u ANSWER="$1"
+                local -u ANSWER="${1}"
 
-                case "$ANSWER" in
+                case "${ANSWER}" in
                     "1G" | "2M" )
-                        _HUGEPAGES_BYTE_SUFFIX="$ANSWER"
+                        _HUGEPAGES_BYTE_SUFFIX="${ANSWER}"
                         _IS_HUGEPAGES_SIZE_SET=true
                         return 0 ;;
 
@@ -182,22 +182,22 @@
 
             function GetHugepageCount
             {
-                if [[ -z "$1" ]]; then
-                    echo -e "$_PREFIX_ERROR Hugepage count is empty."
+                if [[ -z "${1}" ]]; then
+                    echo -e "${_PREFIX_ERROR} Hugepage count is empty."
                     return 1
                 fi
 
                 GetHugepageMinAndMaxSizes || return 1
 
-                if ! echo "$1" | grep -E -q "$_REGEX_FOR_NUM" \
-                    || [[ "$1" -lt "$_HUGEPAGES_MIN_SIZE" ]] \
-                    || [[ "$1" -gt "$_HUGEPAGES_MAX_SIZE" ]]; then
-                    echo -e "$_PREFIX_ERROR Please enter a valid Hugepages amount, between $_HUGEPAGES_MIN_SIZE or $_HUGEPAGES_MAX_SIZE."
+                if ! echo "${1}" | grep -E -q "$_REGEX_FOR_NUM" \
+                    || [[ "${1}" -lt "$_HUGEPAGES_MIN_SIZE" ]] \
+                    || [[ "${1}" -gt "$_HUGEPAGES_MAX_SIZE" ]]; then
+                    echo -e "${_PREFIX_ERROR} Please enter a valid Hugepages amount, between $_HUGEPAGES_MIN_SIZE or $_HUGEPAGES_MAX_SIZE."
                     return 1
                 fi
 
                 _IS_HUGEPAGES_COUNT_SET=true
-                _HUGEPAGES_COUNT="$1"
+                _HUGEPAGES_COUNT="${1}"
                 return 0
             }
 
@@ -213,7 +213,7 @@
                         _HUGEPAGES_MIN_SIZE=1 ;;
 
                     * )
-                        echo -e "$_PREFIX_ERROR Failed to calculate minimum or maximum values for Hugepages."
+                        echo -e "${_PREFIX_ERROR} Failed to calculate minimum or maximum values for Hugepages."
                         return 1 ;;
                 esac
 
@@ -226,7 +226,7 @@
             function IsHostMemorySufficientForHugepages
             {
                 if ! GetFreeMemory; then
-                    echo -e "$_PREFIX_ERROR Insufficient Host memory for Hugepages."
+                    echo -e "${_PREFIX_ERROR} Insufficient Host memory for Hugepages."
                     return 1
                 fi
 
@@ -241,7 +241,7 @@
         {
             if ! sudo adduser "$_USER" "input" &> /dev/null \
                 || ! sudo adduser "$_USER" "libvirt" &> /dev/null; then
-                echo -e "$_PREFIX_ERROR Failed to add user '$_USER' to groups."
+                echo -e "${_PREFIX_ERROR} Failed to add user '$_USER' to groups."
                 return 1
             fi
 
@@ -391,7 +391,7 @@
                     Main
                 fi
 
-                # ( return "$?" )
+                # ( return "${?}" )
             fi
 
             PrintSuffixPassOrFail "Allocating CPU threads..." && _HAS_EXECUTED_PRE_SETUP_STATIC_ISOLCPU=true
@@ -512,11 +512,11 @@
 
                 # <remarks> Append changes to file(s). </remarks>
                 if ! sudo echo -e "${FILE_1_CONTENTS[*]}" >> "$_QEMU_DEST_PATH"; then
-                    echo -e "$_PREFIX_ERROR Failed to write to file '$_QEMU_DEST_PATH'."
+                    echo -e "${_PREFIX_ERROR} Failed to write to file '$_QEMU_DEST_PATH'."
                 fi
 
                 if ! sudo echo -e "${FILE_2_CONTENTS[*]}" >> "$_APPARMOR_QEMU_DEST_PATH"; then
-                    echo -e "$_PREFIX_ERROR Failed to write to file '$_APPARMOR_QEMU_DEST_PATH'."
+                    echo -e "${_PREFIX_ERROR} Failed to write to file '$_APPARMOR_QEMU_DEST_PATH'."
                 fi
 
                 return 0
@@ -543,7 +543,7 @@
                 if [[ "${#_EVENT_DEVICES_LIST[@]}" -eq 0 ]] \
                     ||[[ "${#_INPUT_DEVICES_LIST[@]}" -eq 0 ]]; then
                     _IS_EVDEV_SETUP=false
-                    echo -e "$_PREFIX_ERROR Cannot parse input devices (by ID)."
+                    echo -e "${_PREFIX_ERROR} Cannot parse input devices (by ID)."
                     return 1
                 fi
 
@@ -558,7 +558,7 @@
                     echo -e "Evdev (Event Devices) is a method of creating a virtual KVM (Keyboard-Video-Mouse) switch between Host and Guest(s).\n${_SET_COLOR_YELLOW}HOW-TO:${_RESET_COLOR} Press 'L-CTRL' and 'R-CTRL' simultaneously.\n"
                 fi
 
-                AskToExecuteOrSkip "Setup Evdev?" || return "$?"
+                AskToExecuteOrSkip "Setup Evdev?" || return "${?}"
             fi
 
             Main
diff --git a/bin/vfiolib-usage b/bin/vfiolib-usage
--- a/bin/vfiolib-usage
+++ b/bin/vfiolib-usage
@@ -21,9 +21,9 @@
     # <summary> Public </summary>
         function ExecuteUsage
         {
-            if ! GetOption "$@"; then
+            if ! GetOption "${@}"; then
                 GetHelp
-                return "$?"
+                return "${?}"
             fi
 
             return 0
@@ -37,8 +37,8 @@
                 declare -g _ARGS_FOR_AUTO_XORG=""
 
                 # <remarks> Statements </remarks
-                declare -g _OUTPUT_INVALIDANSWER="$_PREFIX_ERROR Failed to answer."
-                declare -g _OUTPUT_INVALID_OPTION="$_PREFIX_ERROR Invalid option."
+                declare -g _OUTPUT_INVALIDANSWER="${_PREFIX_ERROR} Failed to answer."
+                declare -g _OUTPUT_INVALID_OPTION="${_PREFIX_ERROR} Invalid option."
 
                 # <remarks> Flags </remarks
                 declare -g _ASK_TO_EXECUTE_POST_SETUPS=true
@@ -78,12 +78,12 @@
         # <summary> Argument getters </summary>
             function GetArgsForAutoXorg
             {
-                if [[ -z "$1" ]]; then
+                if [[ -z "${1}" ]]; then
                     return 0
                 fi
 
-                while [[ ! -z "$1" ]]; do
-                    case "$1" in
+                while [[ ! -z "${1}" ]]; do
+                    case "${1}" in
                         "first" | "last" )
                             if "$_HAS_ARG_AUTO_XORG_SORT_ORDER"; then
                                 return 1
@@ -99,11 +99,11 @@
                             _HAS_ARG_AUTO_XORG_PREFERRED_VENDOR=true ;;
 
                         * )
-                            PrintStatementInvalidArgument "$1"
+                            PrintStatementInvalidArgument "${1}"
                             return 1 ;;
                     esac
 
-                    _ARGS_FOR_AUTO_XORG+=" --$1"
+                    _ARGS_FOR_AUTO_XORG+=" --${1}"
                     shift
                 done
 
@@ -112,22 +112,22 @@
 
             function GetArgsForParseSelection
             {
-                if [[ -z "$1" ]]; then
-                    IsIOMMUGroupIDValid "$1"
+                if [[ -z "${1}" ]]; then
+                    IsIOMMUGroupIDValid "${1}"
                     return 1
                 fi
 
-                local -i COUNT_DELIM=$( echo "$1" | grep -o "," | wc -l )
+                local -i COUNT_DELIM=$( echo "${1}" | grep -o "," | wc -l )
                 (( COUNT_DELIM++ ))
 
                 while [[ "$COUNT_DELIM" -gt 0 ]] \
                     && ! "$_HAS_ARG_PARSE_IOMMU_SELECT_ALL"; do
-                    local ARG=$( echo "$1" | cut -d ',' -f "$COUNT_DELIM" )
+                    local ARG=$( echo "${1}" | cut -d ',' -f "$COUNT_DELIM" )
 
                     if [[ ! -z "$ARG" ]] \
-                        && ( ! "$_DO_PARSE_DATABASE_FROM_FILE" \
-                            || ( "$_DO_PARSE_DATABASE_FROM_FILE" \
-                            && [[ "$ARG" != "$_DATABASE_FILE" ]] )); then
+                        && ( ! "${_DO_PARSE_DATABASE_FROM_FILE}" \
+                            || ( "${_DO_PARSE_DATABASE_FROM_FILE}" \
+                            && [[ "$ARG" != "${_DATABASE_FILE}" ]] )); then
                         case "$ARG" in
                             "all" )
                                 _HAS_ARG_PARSE_IOMMU_SELECT_ALL=true
@@ -153,7 +153,7 @@
 
             function GetArgsForMultibootVFIO
             {
-                case "$1" in
+                case "${1}" in
                     "default" )
                         _EXECUTE_VFIO_SETUP_MULTIBOOT_PREFER_DEFAULT=true
                         return 0 ;;
@@ -167,14 +167,14 @@
                         return 0 ;;
 
                     * )
-                        if DoesIOMMUGroupHaveVGADevice "$1" \
-                            && SetPreferredIOMMUGroupForMultiboot "$1"; then
+                        if DoesIOMMUGroupHaveVGADevice "${1}" \
+                            && SetPreferredIOMMUGroupForMultiboot "${1}"; then
                             return 0
                         fi ;;
                 esac
 
-                if [[ ! -z "$1" ]]; then
-                    PrintStatementInvalidArgument "$1"
+                if [[ ! -z "${1}" ]]; then
+                    PrintStatementInvalidArgument "${1}"
                 fi
 
                 return 1
@@ -182,11 +182,11 @@
 
             function GetArgsForStaticVFIO
             {
-                if [[ -z "$1" ]]; then
+                if [[ -z "${1}" ]]; then
                     return 0
                 fi
 
-                case "$1" in
+                case "${1}" in
                     "grub" )
                         _EXECUTE_VFIO_SETUP_STATIC_WITH_GRUB=true
                         return 0 ;;
@@ -196,21 +196,21 @@
                         return 0 ;;
                 esac
 
-                PrintStatementInvalidArgument "$1"
+                PrintStatementInvalidArgument "${1}"
                 return 1
             }
 
             function GetArgsForHugepages
             {
-                if [[ ! -z "$1" ]] \
-                    && ! GetHugepageByteSize "$1"; then
-                    PrintStatementInvalidArgument "$1"
+                if [[ ! -z "${1}" ]] \
+                    && ! GetHugepageByteSize "${1}"; then
+                    PrintStatementInvalidArgument "${1}"
                     return 1
                 fi
 
-                if [[ ! -z "$2" ]] \
-                    && ! GetHugepageCount "$2"; then
-                    PrintStatementInvalidArgument "$2"
+                if [[ ! -z "${2}" ]] \
+                    && ! GetHugepageCount "${2}"; then
+                    PrintStatementInvalidArgument "${2}"
                     return 1
                 fi
 
@@ -219,12 +219,12 @@
 
             function GetArgsForZRAMSwap
             {
-                if [[ ! -z "$1" ]]; then
-                    GetZRAMSwapSize "$1" || GetOverrideArgsForZRAMSwap "$1" || return 1
+                if [[ ! -z "${1}" ]]; then
+                    GetZRAMSwapSize "${1}" || GetOverrideArgsForZRAMSwap "${1}" || return 1
                 fi
 
-                if [[ ! -z "$2" ]]; then
-                    GetZRAMSwapSize "$2" || GetOverrideArgsForZRAMSwap "$2" || return 1
+                if [[ ! -z "${2}" ]]; then
+                    GetZRAMSwapSize "${2}" || GetOverrideArgsForZRAMSwap "${2}" || return 1
                 fi
 
                 return 0
@@ -232,12 +232,12 @@
 
             function GetOverrideArgsForZRAMSwap
             {
-                case "$1" in
+                case "${1}" in
                     "force" )
                         _HAS_ARG_ZRAM_SWAP_FORCE=true ;;
 
                     * )
-                        PrintStatementInvalidArgument "$1"
+                        PrintStatementInvalidArgument "${1}"
                         return 1 ;;
                 esac
 
@@ -247,7 +247,7 @@
         # <summary> Argument validation </summary>
             function ShiftInputIfOptionHasArgument
             {
-                while [[ ! -z "$1" ]]; do
+                while [[ ! -z "${1}" ]]; do
                     shift
                     (( ARGS_COUNT++ ))
                 done
@@ -258,15 +258,15 @@
         # <summary> Options getters </summary>
             function GetOption
             {
-                if [[ -z "$@" ]]; then
+                if [[ -z "${@}" ]]; then
                     return 0
                 fi
 
-                while [[ "$1" =~ ^- ]] \
-                    || [[ "$1" =~ ^-- ]]; do
+                while [[ "${1}" =~ ^- ]] \
+                    || [[ "${1}" =~ ^-- ]]; do
                     local -i ARGS_COUNT=0
 
-                    if ! GetThisOption "$@"; then
+                    if ! GetThisOption "${@}"; then
                         return 1
                     fi
 
@@ -280,7 +280,7 @@
 
             function GetThisOption
             {
-                case "$1" in
+                case "${1}" in
                     "-h" | "--help" )
                         PrintUsage
                         exit 1 ;;
@@ -291,7 +291,7 @@
                     # <remarks> Parse PCI for VFIO setup </remarks>
                     "-f" | "--file" )
                         shift
-                        SetFileForParseSelection "$1" || return 1 ;;
+                        SetFileForParseSelection "${1}" || return 1 ;;
 
                     "-i" | "--internal" )
                         _DO_PARSE_DATABASE_FROM_CACHE=true ;;
@@ -302,8 +302,8 @@
                     "-p" | "--parse" )
                         shift
                         SetParseParameters
-                        GetArgsForParseSelection "$1" || return 1
-                        ShiftInputIfOptionHasArgument "$1" ;;
+                        GetArgsForParseSelection "${1}" || return 1
+                        ShiftInputIfOptionHasArgument "${1}" ;;
 
                     # <remarks> Pre-setup </remarks>
                     "-c" | "--cpu" )
@@ -318,12 +318,12 @@
 
                     "-H" | "--hugepages" )
                         shift
-                        GetArgsForHugepages "$1" "$2" || return 1
+                        GetArgsForHugepages "${1}" "${2}" || return 1
                         IsHostMemorySufficientForHugepages || return 1
                         _ASK_TO_EXECUTE_PRE_SETUP_ALL=false
                         _EXECUTE_PRE_SETUP_SKIP_ALL=false
                         _EXECUTE_PRE_SETUP_HUGEPAGES=true
-                        ShiftInputIfOptionHasArgument "$1" "$2" ;;
+                        ShiftInputIfOptionHasArgument "${1}" "${2}" ;;
 
                     "--uninstall-pre-setup" )
                         _ASK_TO_EXECUTE_PRE_SETUP_ALL=false
@@ -333,17 +333,17 @@
                     # <remarks> VFIO setup </remarks>
                     "-m" | "--multiboot" )
                         shift
-                        GetArgsForMultibootVFIO "$1" || return 1
+                        GetArgsForMultibootVFIO "${1}" || return 1
                         _ASK_TO_EXECUTE_VFIO_SETUP=false
                         _EXECUTE_VFIO_SETUP_MULTIBOOT_WITH_GRUB=true
-                        ShiftInputIfOptionHasArgument "$1" ;;
+                        ShiftInputIfOptionHasArgument "${1}" ;;
 
                     "-s" | "--static" )
                         shift
-                        GetArgsForStaticVFIO "$1" || return 1
+                        GetArgsForStaticVFIO "${1}" || return 1
                         _ASK_TO_EXECUTE_VFIO_SETUP=false
                         _ASK_TO_EXECUTE_VFIO_SETUP_STATIC=false
-                        ShiftInputIfOptionHasArgument "$1" ;;
+                        ShiftInputIfOptionHasArgument "${1}" ;;
 
                     "--uninstall-vfio-setup" )
                         _ASK_TO_EXECUTE_VFIO_SETUP=false
@@ -362,23 +362,23 @@
                         shift
                         _ASK_TO_EXECUTE_POST_SETUPS=false
                         _EXECUTE_POST_SETUP_AUTO_XORG=true
-                        GetArgsForAutoXorg "$1" "$2" || return 1
-                        ShiftInputIfOptionHasArgument "$1" "$2" ;;
+                        GetArgsForAutoXorg "${1}" "${2}" || return 1
+                        ShiftInputIfOptionHasArgument "${1}" "${2}" ;;
 
                     "--zram-swap" )
                         shift
                         _ASK_TO_EXECUTE_POST_SETUPS=false
-                        GetArgsForZRAMSwap "$1" "$2" || return 1
+                        GetArgsForZRAMSwap "${1}" "${2}" || return 1
                         IsHostMemorySufficientForZRAMSwap || return 1
                         _EXECUTE_POST_SETUP_ZRAM_SWAP=true
-                        ShiftInputIfOptionHasArgument "$1" "$2" ;;
+                        ShiftInputIfOptionHasArgument "${1}" "${2}" ;;
 
                     "--uninstall-post-setup" )
                         _EXECUTE_POST_SETUP_UNINSTALL=true ;;
 
                     # <remarks> Else </remarks>
                     * )
-                        PrintStatementInvalidOption "$1"
+                        PrintStatementInvalidOption "${1}"
                         return 1 ;;
                 esac
 
@@ -394,17 +394,17 @@
 
         function PrintStatementInvalidArgument
         {
-            echo -e "$_PREFIX_ERROR Invalid argument '$1'."
+            echo -e "${_PREFIX_ERROR} Invalid argument '${1}'."
             return 0
         }
 
         function PrintStatementInvalidOption
         {
-            if [[ -z "$1" ]]; then
+            if [[ -z "${1}" ]]; then
                 echo -e "$_OUTPUT_INVALID_OPTION"
             fi
 
-            echo -e "$_PREFIX_ERROR Invalid option '$1'."
+            echo -e "${_PREFIX_ERROR} Invalid option '${1}'."
             return 0
         }
 
diff --git a/etc/set-hooks b/etc/set-hooks
--- a/etc/set-hooks
+++ b/etc/set-hooks
@@ -7,7 +7,7 @@
 # Maintainer(s):    Alex Portell <github.com/portellam>
 #
 
-DOMAIN_NAME="$1"
+DOMAIN_NAME="${1}"
 HOOKS_BASE_DIR="/etc/libvirt/hooks"
 DOMAIN_NAME_BASE_DIR="$HOOKS_BASE_DIR/qemu.d/$DOMAIN_NAME"
 BEGIN_DIR="$DOMAIN_NAME_BASE_DIR/started/begin/"
@@ -41,19 +41,19 @@ function GetHooks
 
 function SetHooksForDomain
 {
-    if [[ -z "$1" ]]; then
+    if [[ -z "${1}" ]]; then
         return 0
     fi
 
-    if ! ln -s "$BEGIN_DIR/$1" "$HOOKS_BASE_DIR/$1" &> /dev/null \
-        || ! ln -s "$END_DIR/$1" "$HOOKS_BASE_DIR/$1" &> /dev/null; then
-        echo -e "An error occured: Failed to set symlinks for hook '$1'."
+    if ! ln -s "$BEGIN_DIR/${1}" "$HOOKS_BASE_DIR/${1}" &> /dev/null \
+        || ! ln -s "$END_DIR/${1}" "$HOOKS_BASE_DIR/${1}" &> /dev/null; then
+        echo -e "An error occured: Failed to set symlinks for hook '${1}'."
         return 1
     fi
 
-    if ! chmod +x "$BEGIN_DIR/$1" &> /dev/null \
-        || ! chmod +x "$END_DIR/$1" &> /dev/null; then
-        echo -e "An error occured: Failed to set file permissions for hook '$1'."
+    if ! chmod +x "$BEGIN_DIR/${1}" &> /dev/null \
+        || ! chmod +x "$END_DIR/${1}" &> /dev/null; then
+        echo -e "An error occured: Failed to set file permissions for hook '${1}'."
         return 1
     fi
 
