Finished updating vars for vfiolib-pre and post-setup. Placed setters at end of each source.

diff --git a/bin/vfiolib-common b/bin/vfiolib-common
--- a/bin/vfiolib-common
+++ b/bin/vfiolib-common
@@ -36,7 +36,7 @@
                 SetExitCode
 
                 if "$IS_VERBOSE"; then
-                    ( return "$_LAST_EXIT_CODE" )
+                    ( return "${_LAST_EXIT_CODE}" )
                     PrintSuffixPassOrFail
                     echo -en "Testing connection to DNS...\t"
                 fi
@@ -48,15 +48,15 @@
                 SetExitCode
 
                 if "$IS_VERBOSE"; then
-                    ( return "$_LAST_EXIT_CODE" )
+                    ( return "${_LAST_EXIT_CODE}" )
                     PrintSuffixPassOrFail
                 fi
 
-                if [[ "$_LAST_EXIT_CODE" -ne 0 ]]; then
+                if [[ "${_LAST_EXIT_CODE}" -ne 0 ]]; then
                     echo -e "Failed to ping Internet/DNS servers. Check network settings or firewall, and try again."
                 fi
 
-                return "$_LAST_EXIT_CODE"
+                return "${_LAST_EXIT_CODE}"
             }
 
             function GetLinuxDistro
@@ -70,7 +70,7 @@
                     elif [[ "$OS_WITH_DNF_OR_YUM" =~ .*${_OPERATING_SYSTEM}.* ]]; then
                         _PACKAGE_MANAGER="dnf"
 
-                        if command -v "$_PACKAGE_MANAGER"; then
+                        if command -v "${_PACKAGE_MANAGER}"; then
                             return 0
                         fi
 
@@ -92,7 +92,7 @@
                         _PACKAGE_MANAGER=""
                     fi
 
-                    if ! command -v "$_PACKAGE_MANAGER" &> /dev/null; then
+                    if ! command -v "${_PACKAGE_MANAGER}" &> /dev/null; then
                         return 1
                     fi
 
@@ -112,7 +112,7 @@
                     return 1
                 fi
 
-                if [[ -z "$_OPERATING_SYSTEM" ]]; then
+                if [[ -z "${_OPERATING_SYSTEM}" ]]; then
                     echo -e "${_PREFIX_ERROR} Failed to parse operating system."
                     return 1
                 fi
@@ -138,39 +138,46 @@
 
             function SetParameters
             {
-                # <summary>
+                if [[ ! -z "${_ARE_COMMON_PARAMS_SET}" ]] \
+                    && "${_ARE_COMMON_PARAMS_SET}"; then
+                    return 0
+                fi
+
+                declare -g _ARE_COMMON_PARAMS_SET=true
+
+                # <remarks>
                 # Color coding
                 # Reference URL: 'https://www.shellhacks.com/bash-colors'
-                # </summary>
+                # </remarks>
                 declare -g _SET_COLOR_GREEN='\033[0;32m'
                 declare -g _SET_COLOR_RED='\033[0;31m'
                 declare -g _SET_COLOR_YELLOW='\033[0;33m'
                 declare -g _RESET_COLOR='\033[0m'
 
-                # <summary> Append output </summary>
-                declare -g _PREFIX_NOTE="${_SET_COLOR_YELLOW}Note:$_RESET_COLOR"
-                declare -g _PREFIX_ERROR="${_SET_COLOR_YELLOW}An error occurred:$_RESET_COLOR"
-                declare -g _PREFIX_FAIL="${_SET_COLOR_RED}Failure:$_RESET_COLOR"
-                declare -g _PREFIX_PASS="${_SET_COLOR_GREEN}Success:$_RESET_COLOR"
-                declare -g _SUFFIX_FAIL="${_SET_COLOR_RED}[Failure]$_RESET_COLOR"
-                declare -g _SUFFIX_PASS="${_SET_COLOR_GREEN}[Success]$_RESET_COLOR"
-                declare -g _SUFFIX_SKIP="${_SET_COLOR_YELLOW}[Skipped]$_RESET_COLOR"
-                declare -g _SUFFIX_WORK="${_SET_COLOR_YELLOW}[Working]$_RESET_COLOR"
+                # <remarks> Append output </remarks>
+                declare -g _PREFIX_NOTE="${_SET_COLOR_YELLOW}Note:${_RESET_COLOR}"
+                declare -g _PREFIX_ERROR="${_SET_COLOR_YELLOW}An error occurred:${_RESET_COLOR}"
+                declare -g _PREFIX_FAIL="${_SET_COLOR_RED}Failure:${_RESET_COLOR}"
+                declare -g _PREFIX_PASS="${_SET_COLOR_GREEN}Success:${_RESET_COLOR}"
+                declare -g _SUFFIX_FAIL="${_SET_COLOR_RED}[Failure]${_RESET_COLOR}"
+                declare -g _SUFFIX_PASS="${_SET_COLOR_GREEN}[Success]${_RESET_COLOR}"
+                declare -g _SUFFIX_SKIP="${_SET_COLOR_YELLOW}[Skipped]${_RESET_COLOR}"
+                declare -g _SUFFIX_WORK="${_SET_COLOR_YELLOW}[Working]${_RESET_COLOR}"
 
                 # <remarks> File templates. </remarks>
                 declare -g _PREFIX_COMMENT="#"              # <note> Added this var, to prevent IDE from showing visual errors when a string contains a comment variable. </note>
 
-                declare -ag _DISCLAIMER_FILE_CONTENTS=(
-                    "$_PREFIX_COMMENT Generated by 'portellam/deploy-vfio-main'"
-                    "$_PREFIX_COMMENT WARNING: Any modifications to this file will be modified by 'deploy-vfio-main'"
-                    "$_PREFIX_COMMENT"
+                declare -ga _DISCLAIMER_FILE_CONTENTS=(
+                    "${_PREFIX_COMMENT} Generated by 'portellam/deploy-vfio-main'"
+                    "${_PREFIX_COMMENT} WARNING: Any modifications to this file will be modified by 'deploy-vfio-main'"
+                    "${_PREFIX_COMMENT}"
                 )
 
-                declare -ag _VFIO_DISCLAIMER_FILE_CONTENTS=(
+                declare -ga _VFIO_DISCLAIMER_FILE_CONTENTS=(
                     "${_DISCLAIMER_FILE_CONTENTS[@]}"
-                    "$_PREFIX_COMMENT Run lspci to view hardware information."
-                    "$_PREFIX_COMMENT You must run update-initramfs(8) to effect this change."
-                    "$_PREFIX_COMMENT"
+                    "${_PREFIX_COMMENT} Run lspci to view hardware information."
+                    "${_PREFIX_COMMENT} You must run update-initramfs(8) to effect this change."
+                    "${_PREFIX_COMMENT}"
                 )
 
                 # <remarks> Memory </remarks>
@@ -180,7 +187,7 @@
                 declare -gi _MIN_MEMORY=8
 
                 # <remarks> System validation </remarks>
-                declare -g _OUTPUT_INVALID_PACKAGE_MANAGER="${_PREFIX_ERROR} Command '$_PACKAGE_MANAGER' is not supported."
+                declare -g _OUTPUT_INVALID_PACKAGE_MANAGER="${_PREFIX_ERROR} Command '${_PACKAGE_MANAGER}' is not supported."
                 declare -gl _PACKAGE_MANAGER
                 declare -gl _OPERATING_SYSTEM="$( lsb_release -is )"
             }
@@ -199,7 +206,7 @@
                 local -n REFERENCE="${1}"
 
                 for VALUE in "${REFERENCE[@]}"; do
-                    [ ! -z "$VALUE" ] || return 1
+                    [ ! -z "${VALUE}" ] || return 1
                 done
 
                 return 0
@@ -244,15 +251,15 @@
             {
                 SetExitCode
 
-                case "$_LAST_EXIT_CODE" in
+                case "${_LAST_EXIT_CODE}" in
                     0 )
-                        echo -en "$_PREFIX_PASS" ;;
+                        echo -en "${_PREFIX_PASS}" ;;
 
                     255 )
-                        echo -en "$_PREFIX_SKIP" ;;
+                        echo -en "${_PREFIX_SKIP}" ;;
 
                     * )
-                        echo -en "$_PREFIX_FAIL" ;;
+                        echo -en "${_PREFIX_FAIL}" ;;
                 esac
 
                 if [[ -z "${1}" ]]; then
@@ -261,7 +268,7 @@
                     echo -e " ${1}"
                 fi
 
-                return "$_LAST_EXIT_CODE"
+                return "${_LAST_EXIT_CODE}"
             }
 
             function PrintSuffixPassOrFail
@@ -272,18 +279,18 @@
                     echo -en "${1}\t"
                 fi
 
-                case "$_LAST_EXIT_CODE" in
+                case "${_LAST_EXIT_CODE}" in
                     0 )
-                        echo -e "$_SUFFIX_PASS" ;;
+                        echo -e "${_SUFFIX_PASS}" ;;
 
                     255 )
-                        echo -e "$_SUFFIX_SKIP" ;;
+                        echo -e "${_SUFFIX_SKIP}" ;;
 
                     * )
-                        echo -e "$_SUFFIX_FAIL" ;;
+                        echo -e "${_SUFFIX_FAIL}" ;;
                 esac
 
-                return "$_LAST_EXIT_CODE"
+                return "${_LAST_EXIT_CODE}"
             }
 
             function PrintSuffixWait
@@ -292,7 +299,7 @@
                     echo -en "${1}\t"
                 fi
 
-                echo -e "$_SUFFIX_WORK"
+                echo -e "${_SUFFIX_WORK}"
                 return 0
             }
 
@@ -301,7 +308,7 @@
         {
             _AVAILABLE_MEMORY=$(( _INT_MAX_MEMORY - _MIN_MEMORY ))
 
-            if [[ "$_AVAILABLE_MEMORY" -le 0 ]]; then
+            if [[ "${_AVAILABLE_MEMORY}" -le 0 ]]; then
                 return 1
             fi
 
@@ -312,12 +319,12 @@
         function FindPackage
         {
             if [[ -z "${1}" ]] \
-                || [[ -z "$_PACKAGE_MANAGER" ]]; then
+                || [[ -z "${_PACKAGE_MANAGER}" ]]; then
                 echo -e "${_PREFIX_ERROR} Input values are empty."
                 return 1
             fi
 
-            case "$_PACKAGE_MANAGER" in
+            case "${_PACKAGE_MANAGER}" in
                 "apt" )
                     apt list "${1}" ;;
 
@@ -340,30 +347,30 @@
                     zypper se "${1}" ;;
 
                 * )
-                    echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
+                    echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
                     return 1 ;;
             esac
 
             SetExitCode
 
-            if [[ "$_LAST_EXIT_CODE" -ne 0 ]]; then
-                case "$_PACKAGE_MANAGER" in
+            if [[ "${_LAST_EXIT_CODE}" -ne 0 ]]; then
+                case "${_PACKAGE_MANAGER}" in
                     *" "* )
-                        echo -e "${_PREFIX_ERROR} Packages '$_PACKAGE_MANAGER' were not found." ;;
+                        echo -e "${_PREFIX_ERROR} Packages '${_PACKAGE_MANAGER}' were not found." ;;
 
                     * )
-                        echo -e "${_PREFIX_ERROR} Package '$_PACKAGE_MANAGER' was not found." ;;
+                        echo -e "${_PREFIX_ERROR} Package '${_PACKAGE_MANAGER}' was not found." ;;
                 esac
 
                 return 1
             fi
 
-            return "$_LAST_EXIT_CODE"
+            return "${_LAST_EXIT_CODE}"
         }
 
         function InstallPackage
         {
-            if [[ -z "$_PACKAGE_MANAGER" ]] \
+            if [[ -z "${_PACKAGE_MANAGER}" ]] \
                 || [[ -z "${1}" ]]; then
                 echo -e "${_PREFIX_ERROR} Input values are empty."
                 return 1
@@ -377,9 +384,9 @@
             fi
 
             # <remarks> Auto-update and auto-install selected packages </remarks>
-            case "$_PACKAGE_MANAGER" in
+            case "${_PACKAGE_MANAGER}" in
                 "apt" )
-                    if "$DO_REINSTALL"; then
+                    if "${DO_REINSTALL}"; then
                         OPTION="--reinstall -o Dpkg::Options::=--force-confmiss"
                     fi
 
@@ -404,7 +411,7 @@
                     zypper refresh && zypper in "${1}" ;;
 
                 * )
-                    echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
+                    echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
                     false ;;
             esac
 
@@ -414,7 +421,7 @@
 
         function IsInstalledPackage
         {
-            if [[ -z "$_PACKAGE_MANAGER" ]] \
+            if [[ -z "${_PACKAGE_MANAGER}" ]] \
                 || [[ -z "${1}" ]]; then
                 echo -e "${_PREFIX_ERROR} Input values are empty."
                 return 1
@@ -423,21 +430,21 @@
             local GET_COMMAND=""
 
             # <remarks> Check if package is not installed </remarks>
-            case "$_PACKAGE_MANAGER" in
+            case "${_PACKAGE_MANAGER}" in
                 "apt" )
                     GET_COMMAND="sudo dpkg -s" ;;
 
                 * )
-                    echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
+                    echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
                     return 1 ;;
             esac
 
             local -i COUNT_DELIM=$( echo "${1}" | wc -w )
-            local GET_PACKAGE='echo "${1}" | cut -d ' ' -f "$COUNT_DELIM"'
+            local GET_PACKAGE='echo "${1}" | cut -d ' ' -f "${COUNT_DELIM}"'
 
-            while [[ ! -z "$PACKAGE" ]]; do
-                local PACKAGE=$( eval "$GET_PACKAGE" )
-                eval "$GET_COMMAND $PACKAGE" || return 1
+            while [[ ! -z "${PACKAGE}" ]]; do
+                local PACKAGE=$( eval "${GET_PACKAGE}" )
+                eval "${GET_COMMAND} ${PACKAGE}" || return 1
                 (( COUNT_DELIM-- ))
             done
 
@@ -456,14 +463,14 @@
 
         function UninstallPackage
         {
-            if [[ -z "$_PACKAGE_MANAGER" ]] \
+            if [[ -z "${_PACKAGE_MANAGER}" ]] \
                 || [[ -z "${1}" ]]; then
                 echo -e "${_PREFIX_ERROR} Input values are empty."
                 return 1
             fi
 
             # <remarks> Uninstall selected packages </remarks>
-            case "$_PACKAGE_MANAGER" in
+            case "${_PACKAGE_MANAGER}" in
                 "apt" )
                     apt uninstall "${1}" ;;
 
@@ -486,7 +493,7 @@
                     zypper remove "${1}" ;;
 
                 * )
-                    echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
+                    echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
                     false ;;
             esac
 
@@ -529,7 +536,7 @@
             # <remarks> Clone new GitHub repository. </remarks>
             elif [[ -d "${1}${3}" ]]; then
                 for COUNT in $( seq 0 2 ); do
-                    if ! "$DO_AUTO_ANSWER_YES"; then
+                    if ! "${DO_AUTO_ANSWER_YES}"; then
                         read -r -p "Clone repo '${2}'? [Y/n]: " ANSWER
                     else
                         ANSWER="Y"
@@ -561,3 +568,7 @@
             fi
         }
 # </functions>
+
+# <main>
+    SetParameters
+# </main>
diff --git a/bin/vfiolib-post-setup b/bin/vfiolib-post-setup
--- a/bin/vfiolib-post-setup
+++ b/bin/vfiolib-post-setup
@@ -20,7 +20,7 @@
 			function Main
 			{
 				while [[ "${?}" -ne 1 ]]; do
-					if "$_ASK_TO_EXECUTE_POST_SETUPS"; then
+					if "${_ASK_TO_EXECUTE_POST_SETUPS}"; then
 						LibvirtHooks
 						GuestAudioLoopback
 						AllocateRAMToSwap
@@ -28,19 +28,19 @@
 						break
 					fi
 
-					if "$_EXECUTE_POST_SETUP_STATIC_LIBVIRT_HOOKS"; then
+					if "${_EXECUTE_POST_SETUP_STATIC_LIBVIRT_HOOKS}"; then
 						LibvirtHooks
 					fi
 
-					if "$_EXECUTE_POST_SETUP_AUDIO_LOOPBACK"; then
+					if "${_EXECUTE_POST_SETUP_AUDIO_LOOPBACK}"; then
 						GuestAudioLoopback
 					fi
 
-					if "$_EXECUTE_POST_SETUP_ZRAM_SWAP"; then
+					if "${_EXECUTE_POST_SETUP_ZRAM_SWAP}"; then
 						AllocateRAMToSwap
 					fi
 
-					if "$_EXECUTE_POST_SETUP_AUTO_XORG"; then
+					if "${_EXECUTE_POST_SETUP_AUTO_XORG}"; then
 						SetVideoOutput
 					fi
 
@@ -60,10 +60,20 @@
         # <summary> Global setters </summary>
             function SetParameters
             {
-                declare -g _GIT_PATH="$HOME/source/"
-                sudo mkdir -p "$_GIT_PATH" &> /dev/null
+				if [[ ! -z "${_ARE_POST_SETUP_PARAMS_SET}" ]] \
+                    && "${_ARE_POST_SETUP_PARAMS_SET}"; then
+                    return 0
+                fi
 
-                # <remarks> Flags </remarks>
+                declare -g _ARE_POST_SETUP_PARAMS_SET=true
+
+                declare -g _GIT_PATH="${HOME}/source/"
+
+				if [[ ! -d "${_GIT_PATH}" ]]; then
+	                sudo mkdir -p "${_GIT_PATH}" &> /dev/null
+				fi
+
+                # <remarks> Execution Flags </remarks>
                 declare -g _IS_AUDIO_CAPTURE_SETUP=false
             }
 
@@ -76,7 +86,7 @@
             {
                 function Get
                 {
-                    UpdateOrCloneGitRepo "$_GIT_PATH" "$FULL_REPO" "$USER_NAME" "$_EXECUTE_POST_SETUP_ZRAM_SWAP" || return 1
+                    UpdateOrCloneGitRepo "${_GIT_PATH}" "${FULL_REPO}" "${USER_NAME}" "${_EXECUTE_POST_SETUP_ZRAM_SWAP}" || return 1
                     return 0
                 }
 
@@ -84,18 +94,18 @@
                 {
                     local -r SCRIPT_NAME="install.sh"
 
-                    if ! cd "$_GIT_PATH$FULL_REPO"; then
+                    if ! cd "${_GIT_PATH}${FULL_REPO}"; then
                         echo -e "${_PREFIX_ERROR} Failed to find build directory."
                         return 1
                     fi
 
-                    if [[ ! -e "$SCRIPT_NAME" ]]; then
-                        echo -e "${_PREFIX_ERROR} Failed to find script '$SCRIPT_NAME'."
+                    if [[ ! -e "${SCRIPT_NAME}" ]]; then
+                        echo -e "${_PREFIX_ERROR} Failed to find script '${SCRIPT_NAME}'."
                         return 1
                     fi
 
-                    if ! echo "i" | sudo bash "$SCRIPT_NAME" &> /dev/null; then
-                        echo -e "${_PREFIX_ERROR} Failed to execute script '$SCRIPT_NAME'."
+                    if ! echo "i" | sudo bash "${SCRIPT_NAME}" &> /dev/null; then
+                        echo -e "${_PREFIX_ERROR} Failed to execute script '${SCRIPT_NAME}'."
                         return 1
                     fi
 
@@ -122,41 +132,41 @@
 
                     local -r FILE="/etc/default/zram-swap"
                     local -r LINE_TO_MATCH="_zram_fraction="
-                    local FRACTION="$_ARGS_FOR_ZRAM_SWAP_FRACTION"
+                    local FRACTION="${_ARGS_FOR_ZRAM_SWAP_FRACTION}"
 
-                    if ! "$_HAS_ARG_ZRAM_SWAP_DEFAULTS" \
-                        && ! "$_HAS_ARG_ZRAM_SWAP_SET_FRACTION"; then
-                        AskToContinue "$FRACTION" || return "${?}"
+                    if ! "${_HAS_ARG_ZRAM_SWAP_DEFAULTS}" \
+                        && ! "${_HAS_ARG_ZRAM_SWAP_SET_FRACTION}"; then
+                        AskToContinue "${FRACTION}" || return "${?}"
                     fi
 
-                    if "$_HAS_ARG_ZRAM_SWAP_DEFAULTS" \
-                        && ! "$_HAS_ARG_ZRAM_SWAP_SET_FRACTION"; then
+                    if "${_HAS_ARG_ZRAM_SWAP_DEFAULTS}" \
+                        && ! "${_HAS_ARG_ZRAM_SWAP_SET_FRACTION}"; then
                         local -i ZRAM_SWAP_AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY / 2 ))
-                        local -i DENOMINATOR=$( printf "%.0f" $( echo "scale=2;$_INT_MAX_MEMORY/$ZRAM_SWAP_AVAILABLE_MEMORY" | bc ) )
+                        local -i DENOMINATOR=$( printf "%.0f" $( echo "scale=2;${_INT_MAX_MEMORY}/${ZRAM_SWAP_AVAILABLE_MEMORY}" | bc ) )
 
                         # <remarks> Round down to nearest even number. </remarks>
-                        if [[ $( expr $DENOMINATOR % 2 ) -eq 1 ]]; then
+                        if [[ $( expr ${DENOMINATOR} % 2 ) -eq 1 ]]; then
                             (( DENOMINATOR-- ))
                         fi
 
                         # <remarks> Is fraction positive non-zero and not equal to one. </remarks>
-                        if [[ "$DENOMINATOR" -le 0 ]]; then
+                        if [[ "${DENOMINATOR}" -le 0 ]]; then
                             echo -e "${_PREFIX_ERROR} Denominator is negative or zero."
                         fi
 
-                        FRACTION="1/$DENOMINATOR"
+                        FRACTION="1/${DENOMINATOR}"
                     fi
 
-                    if ! sed -i '/'${LINE_TO_MATCH}'"*"/c\'${LINE_TO_MATCH}'"'$FRACTION'"' "${FILE}"; then
+                    if ! sed -i '/'${LINE_TO_MATCH}'"*"/c\'${LINE_TO_MATCH}'"'${FRACTION}'"' "${FILE}"; then
                         echo -e "${_PREFIX_ERROR} Failed to write output to zram-swap file."
                         return 1
                     fi
 
-                    if ! "$_HAS_ARG_ZRAM_SWAP_FORCE" \
+                    if ! "${_HAS_ARG_ZRAM_SWAP_FORCE}" \
                         && sudo swapon -v | grep zram &> /dev/null \
                         && sudo swapon -v | grep zram &> /dev/null \
                         && ! sudo swapon -v | grep zram | grep 0B &> /dev/null; then
-                        echo -e "$_PREFIX_NOTE zram-swap device(s) already in use. Restart system to save changes."
+                        echo -e "${_PREFIX_NOTE} zram-swap device(s) already in use. Restart system to save changes."
                         return 0
                     fi
 
@@ -186,10 +196,10 @@
 
                 local -r USER_NAME="foundObjects"
                 local -r REPO_NAME="zram-swap"
-                local -r FULL_REPO="$USER_NAME/$REPO_NAME"
+                local -r FULL_REPO="${USER_NAME}/${REPO_NAME}"
                 local HAS_SKIPPED=false
 
-                if ! "$_EXECUTE_POST_SETUP_ZRAM_SWAP"; then
+                if ! "${_EXECUTE_POST_SETUP_ZRAM_SWAP}"; then
                     echo
 
                     if ! AskToExecuteOrSkip "Install zram-swap?"; then
@@ -197,7 +207,7 @@
                     fi
                 fi
 
-                if ! "$HAS_SKIPPED" \
+                if ! "${HAS_SKIPPED}" \
                     && ( ! IsHostMemorySufficientForZRAMSwap \
                     || ! Get \
                     || ! Install \
@@ -205,12 +215,12 @@
                     false
                 fi
 
-                if "$HAS_SKIPPED"; then
+                if "${HAS_SKIPPED}"; then
                     ( return 255 )
                 fi
 
                 PrintSuffixPassOrFail "Allocating RAM to swap..."
-                return "$_LAST_EXIT_CODE"
+                return "${_LAST_EXIT_CODE}"
             }
 
             function GetZRAMSwapSize
@@ -231,18 +241,18 @@
                         return 1 ;;
                 esac
 
-                if ! [[ "$NUMERATOR" =~ ^[0-9]+$ ]] \
-                    || ! [[ "$DENOMINATOR" =~ ^[0-9]+$ ]]; then
+                if ! [[ "${NUMERATOR}" =~ ^[0-9]+$ ]] \
+                    || ! [[ "${DENOMINATOR}" =~ ^[0-9]+$ ]]; then
                     echo -e "${_PREFIX_ERROR} Values are not numbers."
                     return 1
                 fi
 
-                if [[ "$NUMERATOR" -lt "$DENOMINATOR" ]] || [[ "$DENOMINATOR" -gt 1 ]]; then
+                if [[ "${NUMERATOR}" -lt "${DENOMINATOR}" ]] || [[ "${DENOMINATOR}" -gt 1 ]]; then
                     declare -g _ARGS_FOR_ZRAM_SWAP_FRACTION="${1}"
                     _HAS_ARG_ZRAM_SWAP_SET_FRACTION=true
                     return 0
 
-                elif [[ "$DENOMINATOR" -eq 0 ]]; then
+                elif [[ "${DENOMINATOR}" -eq 0 ]]; then
                     return 1
 
                 else
@@ -254,7 +264,7 @@
 
             function IsHostMemorySufficientForZRAMSwap
             {
-                if "$_IS_HUGEPAGES_SETUP"; then
+                if "${_IS_HUGEPAGES_SETUP}"; then
                     _AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY - _HUGEPAGES_ALLOCATED_MEMORY ))
                 fi
 
@@ -281,7 +291,7 @@
 				local DEPENDENCIES=""
 
 				# <remarks> Install JACK and PipeWire. </remarks>
-				case "$_PACKAGE_MANAGER" in
+				case "${_PACKAGE_MANAGER}" in
 					"apt" )
 						DEPENDENCIES+="pipewire pipewire-jack " ;;
 
@@ -289,13 +299,13 @@
 						DEPENDENCIES+="pipewire pipewire-jack " ;;
 
 					* )
-						echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
+						echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
 						return 1 ;;
 				esac
 
 				# <remarks> Include PulseAudio (and QEMU driver if available). </remarks>
 				if IsInstalledCommand "pulseaudio" &> /dev/null; then
-					case "$_PACKAGE_MANAGER" in
+					case "${_PACKAGE_MANAGER}" in
 						"apt" )
 							DEPENDENCIES+="pipewire-pulse " ;;
 
@@ -303,13 +313,13 @@
 							DEPENDENCIES+="pipewire-pulse qemu-audio-pa " ;;
 
 						* )
-							echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
+							echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
 							return 1 ;;
 					esac
 
 				# <remarks> Fallback to factory driver. </remarks>
 				else
-					case "$_PACKAGE_MANAGER" in
+					case "${_PACKAGE_MANAGER}" in
 						"apt" )
 							DEPENDENCIES+="pipewire-alsa " ;;
 
@@ -317,18 +327,18 @@
 							DEPENDENCIES+="pipewire-alsa " ;;
 
 						* )
-							echo -e "$_OUTPUT_INVALID_PACKAGE_MANAGER"
+							echo -e "${_OUTPUT_INVALID_PACKAGE_MANAGER}"
 							return 1 ;;
 					esac
 				fi
 
-				IsInstalledPackage "$DEPENDENCIES" &> /dev/null || InstallPackage "$DEPENDENCIES" &> /dev/null
+				IsInstalledPackage "${DEPENDENCIES}" &> /dev/null || InstallPackage "${DEPENDENCIES}" &> /dev/null
 				return "${?}"
 			}
 
 			Main
 			PrintSuffixPassOrFail "Installing audio drivers..." && _IS_AUDIO_CAPTURE_SETUP=true
-			return "$_LAST_EXIT_CODE"
+			return "${_LAST_EXIT_CODE}"
 		}
 
 		# <summary>
@@ -344,7 +354,7 @@
 					return 1
 				fi
 
-				if ! sudo cp "$_AUDIO_LOOPBACK_SRC_PATH" "$_AUDIO_LOOPBACK_DEST_PATH"; then
+				if ! sudo cp "${_AUDIO_LOOPBACK_SRC_PATH}" "${_AUDIO_LOOPBACK_DEST_PATH}"; then
 					echo -e "${_PREFIX_ERROR} Failed to copy file."
 					return 1
 				fi
@@ -354,12 +364,12 @@
 					return 1
 				fi
 
-				if ! sudo systemctl start "$_AUDIO_LOOPBACK_FILENAME"; then
+				if ! sudo systemctl start "${_AUDIO_LOOPBACK_FILENAME}"; then
 					echo -e "${_PREFIX_ERROR} Failed to start audio loopback service."
 					return 1
 				fi
 
-				if ! sudo systemctl enable "$_AUDIO_LOOPBACK_FILENAME"; then
+				if ! sudo systemctl enable "${_AUDIO_LOOPBACK_FILENAME}"; then
 					echo -e "${_PREFIX_ERROR} Failed to enable audio loopback service."
 					return 1
 				fi
@@ -369,7 +379,7 @@
 
 			local HAS_SKIPPED=false
 
-			if ! "$_EXECUTE_POST_SETUP_AUDIO_LOOPBACK"; then
+			if ! "${_EXECUTE_POST_SETUP_AUDIO_LOOPBACK}"; then
 				echo
 
 				if ! AskToExecuteOrSkip "Install zram-swap?"; then
@@ -377,14 +387,14 @@
 				fi
 			fi
 
-			if ! "$HAS_SKIPPED"; then
+			if ! "${HAS_SKIPPED}"; then
 				Main
 			else
 				( return 255 )
 			fi
 
 			PrintSuffixPassOrFail "Creating audio loopback..."
-			return "$_LAST_EXIT_CODE"
+			return "${_LAST_EXIT_CODE}"
 		}
 
 		# <summary>
@@ -394,45 +404,45 @@
 		{
 			function Main
 			{
-				if ! sudo cp "$_LIBVIRT_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo cp "$_LIBVIRT_HOOK_CFSCPU_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_CFSCPU_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo cp "$_LIBVIRT_HOOK_DDCUTIL_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_DDCUTIL_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo cp "$_LIBVIRT_HOOK_ISOLCPU_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo cp "$_LIBVIRT_HOOK_NOSLEEP_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_NOSLEEP_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo cp "$_LIBVIRT_HOOK_NOSLEEP_SERVICE_SRC_PATH" "$_LIBVIRT_HOOK_NOSLEEP_SERVICE_DEST_PATH" &> /dev/null \
-					|| ! sudo cp "$_LIBVIRT_HOOK_UPDATE_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_UPDATE_HOOK_DEST_PATH" &> /dev/null; then
+				if ! sudo cp "${_LIBVIRT_HOOK_SRC_PATH}" "${_LIBVIRT_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo cp "${_LIBVIRT_HOOK_CFSCPU_HOOK_SRC_PATH}" "${_LIBVIRT_HOOK_CFSCPU_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo cp "${_LIBVIRT_HOOK_DDCUTIL_HOOK_SRC_PATH}" "${_LIBVIRT_HOOK_DDCUTIL_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo cp "${_LIBVIRT_HOOK_ISOLCPU_HOOK_SRC_PATH}" "${_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo cp "${_LIBVIRT_HOOK_NOSLEEP_HOOK_SRC_PATH}" "${_LIBVIRT_HOOK_NOSLEEP_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo cp "${_LIBVIRT_HOOK_NOSLEEP_SERVICE_SRC_PATH}" "${_LIBVIRT_HOOK_NOSLEEP_SERVICE_DEST_PATH}" &> /dev/null \
+					|| ! sudo cp "${_LIBVIRT_HOOK_UPDATE_HOOK_SRC_PATH}" "${_LIBVIRT_HOOK_UPDATE_HOOK_DEST_PATH}" &> /dev/null; then
 					echo -e "${_PREFIX_ERROR} Failed to copy file(s)."
 					return 1
 				fi
 
-				if ! sudo chmod +x "$_LIBVIRT_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo chmod +x "$_LIBVIRT_HOOK_CFSCPU_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo chmod +x "$_LIBVIRT_HOOK_DDCUTIL_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo chmod +x "$_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo chmod +x "$_LIBVIRT_HOOK_NOSLEEP_HOOK_DEST_PATH" &> /dev/null \
-					|| ! sudo chmod +x "$_LIBVIRT_HOOK_UPDATE_HOOK_DEST_PATH" &> /dev/null; then
+				if ! sudo chmod +x "${_LIBVIRT_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo chmod +x "${_LIBVIRT_HOOK_CFSCPU_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo chmod +x "${_LIBVIRT_HOOK_DDCUTIL_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo chmod +x "${_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo chmod +x "${_LIBVIRT_HOOK_NOSLEEP_HOOK_DEST_PATH}" &> /dev/null \
+					|| ! sudo chmod +x "${_LIBVIRT_HOOK_UPDATE_HOOK_DEST_PATH}" &> /dev/null; then
 					echo -e "${_PREFIX_ERROR} Failed to set file permissions."
 					return 1
 				fi
 
-				if ! "$_HAS_EXECUTED_PRE_SETUP_STATIC_ISOLCPU"; then
-					if ! sudo cp "$_LIBVIRT_HOOK_ISOLCPU_HOOK_SRC_PATH" "$_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH" &> /dev/null; then
+				if ! "${_HAS_EXECUTED_PRE_SETUP_STATIC_ISOLCPU}"; then
+					if ! sudo cp "${_LIBVIRT_HOOK_ISOLCPU_HOOK_SRC_PATH}" "${_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH}" &> /dev/null; then
 						echo -e "${_PREFIX_ERROR} Failed to copy file(s)."
 						return 1
 					fi
 
-					if ! sudo chmod +x "$_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH" &> /dev/null; then
+					if ! sudo chmod +x "${_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH}" &> /dev/null; then
 						echo -e "${_PREFIX_ERROR} Failed to set file permissions."
 						return 1
 					fi
 				fi
 
-				if ! sudo echo -e "\n\n# <sources>" >> "$_LIBVIRT_HOOK_DEST_PATH" \
-                    || ! sudo echo -e "" >> "$_LIBVIRT_HOOK_DEST_PATH" \
-					|| ( ! "$_HAS_EXECUTED_PRE_SETUP_STATIC_ISOLCPU" && ! sudo echo -e "source \"$_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH\"" >> "$_LIBVIRT_HOOK_DEST_PATH" ) \
-					|| ! sudo echo -e "source \"$_LIBVIRT_HOOK_NOSLEEP_HOOK_DEST_PATH\"" >> "$_LIBVIRT_HOOK_DEST_PATH" \
-					|| ! sudo echo -e "source \"$_LIBVIRT_HOOK_UPDATE_HOOK_DEST_PATH\"" >> "$_LIBVIRT_HOOK_DEST_PATH" \
-                    || ! sudo echo -e "# </sources>" >> "$_LIBVIRT_HOOK_DEST_PATH"; then
+				if ! sudo echo -e "\n\n# <sources>" >> "${_LIBVIRT_HOOK_DEST_PATH}" \
+                    || ! sudo echo -e "" >> "${_LIBVIRT_HOOK_DEST_PATH}" \
+					|| ( ! "${_HAS_EXECUTED_PRE_SETUP_STATIC_ISOLCPU}" && ! sudo echo -e "source \"${_LIBVIRT_HOOK_ISOLCPU_HOOK_DEST_PATH}\"" >> "${_LIBVIRT_HOOK_DEST_PATH}" ) \
+					|| ! sudo echo -e "source \"${_LIBVIRT_HOOK_NOSLEEP_HOOK_DEST_PATH}\"" >> "${_LIBVIRT_HOOK_DEST_PATH}" \
+					|| ! sudo echo -e "source \"${_LIBVIRT_HOOK_UPDATE_HOOK_DEST_PATH}\"" >> "${_LIBVIRT_HOOK_DEST_PATH}" \
+                    || ! sudo echo -e "# </sources>" >> "${_LIBVIRT_HOOK_DEST_PATH}"; then
 					echo -e "${_PREFIX_ERROR} Failed to append filenames as sources to Libvirt hooks file."
 					return 1
 				fi
@@ -448,7 +458,7 @@
 
 			local HAS_SKIPPED=false
 
-			if ! "$_EXECUTE_POST_SETUP_STATIC_LIBVIRT_HOOKS"; then
+			if ! "${_EXECUTE_POST_SETUP_STATIC_LIBVIRT_HOOKS}"; then
 				echo
 
 				if ! AskToExecuteOrSkip "Install Libvirt hooks?"; then
@@ -456,14 +466,14 @@
 				fi
 			fi
 
-			if ! "$HAS_SKIPPED"; then
+			if ! "${HAS_SKIPPED}"; then
 				Main
 			else
 				( return 255 )
 			fi
 
 			PrintSuffixPassOrFail "Installing Libvirt hooks..."
-			return "$_LAST_EXIT_CODE"
+			return "${_LAST_EXIT_CODE}"
 		}
 
 		# <summary>
@@ -477,7 +487,7 @@
 		{
 			function Get
 			{
-				UpdateOrCloneGitRepo "$_GIT_PATH" "$FULL_REPO" "$USER_NAME" "$_EXECUTE_POST_SETUP_AUTO_XORG" || return 1
+				UpdateOrCloneGitRepo "${_GIT_PATH}" "${FULL_REPO}" "${USER_NAME}" "${_EXECUTE_POST_SETUP_AUTO_XORG}" || return 1
 				return 0
 			}
 
@@ -504,18 +514,18 @@
 			{
 				local -r SCRIPT_NAME="installer.bash"
 
-				if ! cd "$_GIT_PATH$FULL_REPO"; then
+				if ! cd "${_GIT_PATH}${FULL_REPO}"; then
 					echo -e "${_PREFIX_ERROR} Failed to find build directory."
 					return 1
 				fi
 
-				if [[ ! -e "$SCRIPT_NAME" ]]; then
-					echo -e "${_PREFIX_ERROR} Failed to find script '$SCRIPT_NAME'."
+				if [[ ! -e "${SCRIPT_NAME}" ]]; then
+					echo -e "${_PREFIX_ERROR} Failed to find script '${SCRIPT_NAME}'."
 					return 1
 				fi
 
-				if ! sudo bash $SCRIPT_NAME $_ARGS_FOR_AUTO_XORG &> /dev/null; then
-					echo -e "${_PREFIX_ERROR} Failed to execute script '$SCRIPT_NAME'."
+				if ! sudo bash ${SCRIPT_NAME} ${_ARGS_FOR_AUTO_XORG} &> /dev/null; then
+					echo -e "${_PREFIX_ERROR} Failed to execute script '${SCRIPT_NAME}'."
 					return 1
 				fi
 
@@ -524,28 +534,28 @@
 
 			local -r USER_NAME="portellam"
 			local -r REPO_NAME="auto-Xorg"
-			local -r FULL_REPO="$USER_NAME/$REPO_NAME"
+			local -r FULL_REPO="${USER_NAME}/${REPO_NAME}"
 			local HAS_SKIPPED=false
 
-			if ! "$_EXECUTE_POST_SETUP_AUTO_XORG"; then
+			if ! "${_EXECUTE_POST_SETUP_AUTO_XORG}"; then
 				echo
 
-				if ! AskToExecuteOrSkip "Install $REPO_NAME?"; then
+				if ! AskToExecuteOrSkip "Install ${REPO_NAME}?"; then
 					HAS_SKIPPED=true
 				fi
 			fi
 
-			if ! "$HAS_SKIPPED"; then
+			if ! "${HAS_SKIPPED}"; then
 				Get
 
-				if ! "$_HAS_ARG_AUTO_XORG_PREFERRED_VENDOR" \
-					&& ! "$_HAS_ARG_AUTO_XORG_SORT_ORDER" \
+				if ! "${_HAS_ARG_AUTO_XORG_PREFERRED_VENDOR}" \
+					&& ! "${_HAS_ARG_AUTO_XORG_SORT_ORDER}" \
 					&& AskToExecuteOrSkip "Add arguments?"; then
 					local -i COUNT_OF_VALID_ARGS=2
 					echo
 					GetArgs
 
-					for _COUNT in $( seq 1 "$COUNT_OF_VALID_ARGS" ); do
+					for _COUNT in $( seq 1 "${COUNT_OF_VALID_ARGS}" ); do
 						read -r -p "Enter argument (to skip, leave blank): " ANSWER
 						GetArgsForAutoXorg "${ANSWER}" || return 1
 
@@ -558,11 +568,15 @@
 				Install
 			fi
 
-			if "$HAS_SKIPPED"; then
+			if "${HAS_SKIPPED}"; then
 				( return 255 )
 			fi
 
-			PrintSuffixPassOrFail "Installing $REPO_NAME...\t"
-			return "$_LAST_EXIT_CODE"
+			PrintSuffixPassOrFail "Installing ${REPO_NAME}...\t"
+			return "${_LAST_EXIT_CODE}"
 		}
 # </functions>
+
+# <main>
+    SetParameters
+# </main>
diff --git a/bin/vfiolib-usage b/bin/vfiolib-usage
--- a/bin/vfiolib-usage
+++ b/bin/vfiolib-usage
@@ -21,8 +21,8 @@
     # <summary> Public </summary>
         function ExecuteUsage
         {
-            if ! GetOption "${@}"; then
-                GetHelp
+            if ! GetOption "${@}" \
+                && GetHelp; then
                 return "${?}"
             fi
 
@@ -32,15 +32,21 @@
         # <summary> Global setters </summary>               # TODO: evaluate these params and move to respective sources accordingly.
             function SetParameters
             {
-                SetParseParameters
+                if [[ ! -z "${_ARE_USAGE_PARAMS_SET}" ]] \
+                    && "${_ARE_USAGE_PARAMS_SET}"; then
+                    return 0
+                fi
 
+                declare -g _ARE_USAGE_PARAMS_SET=true
+
+                # <remarks> Arguments </remarks
                 declare -g _ARGS_FOR_AUTO_XORG=""
 
-                # <remarks> Statements </remarks
-                declare -g _OUTPUT_INVALIDANSWER="${_PREFIX_ERROR} Failed to answer."
+                # <remarks> Output statements </remarks
+                declare -g _OUTPUT_INVALID_ANSWER="${_PREFIX_ERROR} Failed to answer."
                 declare -g _OUTPUT_INVALID_OPTION="${_PREFIX_ERROR} Invalid option."
 
-                # <remarks> Flags </remarks
+                # <remarks> Execution Flags </remarks
                 declare -g _ASK_TO_EXECUTE_POST_SETUPS=true
                 declare -g _ASK_TO_EXECUTE_PRE_SETUP_ALL=true
                 declare -g _ASK_TO_EXECUTE_VFIO_SETUP=true
@@ -85,14 +91,14 @@
                 while [[ ! -z "${1}" ]]; do
                     case "${1}" in
                         "first" | "last" )
-                            if "$_HAS_ARG_AUTO_XORG_SORT_ORDER"; then
+                            if "${_HAS_ARG_AUTO_XORG_SORT_ORDER}"; then
                                 return 1
                             fi
 
                             _HAS_ARG_AUTO_XORG_SORT_ORDER=true ;;
 
                         "amd" | "intel" | "nvidia" | "other" )
-                            if "$_HAS_ARG_AUTO_XORG_PREFERRED_VENDOR"; then
+                            if "${_HAS_ARG_AUTO_XORG_PREFERRED_VENDOR}"; then
                                 return 1
                             fi
 
@@ -120,15 +126,15 @@
                 local -i COUNT_DELIM=$( echo "${1}" | grep -o "," | wc -l )
                 (( COUNT_DELIM++ ))
 
-                while [[ "$COUNT_DELIM" -gt 0 ]] \
-                    && ! "$_HAS_ARG_PARSE_IOMMU_SELECT_ALL"; do
-                    local ARG=$( echo "${1}" | cut -d ',' -f "$COUNT_DELIM" )
+                while [[ "${COUNT_DELIM}" -gt 0 ]] \
+                    && ! "${_HAS_ARG_PARSE_IOMMU_SELECT_ALL}"; do
+                    local ARG=$( echo "${1}" | cut -d ',' -f "${COUNT_DELIM}" )
 
-                    if [[ ! -z "$ARG" ]] \
+                    if [[ ! -z "${ARG}" ]] \
                         && ( ! "${_DO_PARSE_DATABASE_FROM_FILE}" \
                             || ( "${_DO_PARSE_DATABASE_FROM_FILE}" \
-                            && [[ "$ARG" != "${_DATABASE_FILE}" ]] )); then
-                        case "$ARG" in
+                            && [[ "${ARG}" != "${_DATABASE_FILE}" ]] )); then
+                        case "${ARG}" in
                             "all" )
                                 _HAS_ARG_PARSE_IOMMU_SELECT_ALL=true
                                 AddValidIOMMUGroupsParseList || return 1 ;;
@@ -140,7 +146,7 @@
 
                             * )
                                 _HAS_ARG_PARSE_IOMMU_SELECT_SOME=true
-                                AddSomeIOMMUGroupsParseList "$ARG" || return 1 ;;
+                                AddSomeIOMMUGroupsParseList "${ARG}" || return 1 ;;
                         esac
                     fi
 
@@ -270,7 +276,7 @@
                         return 1
                     fi
 
-                    for _COUNT in $( seq 0 "$ARGS_COUNT" ); do
+                    for _COUNT in $( seq 0 "${ARGS_COUNT}" ); do
                         shift
                     done
                 done
@@ -401,7 +407,7 @@
         function PrintStatementInvalidOption
         {
             if [[ -z "${1}" ]]; then
-                echo -e "$_OUTPUT_INVALID_OPTION"
+                echo -e "${_OUTPUT_INVALID_OPTION}"
             fi
 
             echo -e "${_PREFIX_ERROR} Invalid option '${1}'."
@@ -499,5 +505,8 @@
             unset IFS
             return 0
         }
-
 # </functions>
+
+# <main>
+    SetParameters
+# </main>
