Finished sources.

diff --git a/bin/vfiolib-pre-setup b/bin/vfiolib-pre-setup
--- a/bin/vfiolib-pre-setup
+++ b/bin/vfiolib-pre-setup
@@ -521,8 +521,8 @@
                     echo -e "${_PREFIX_ERROR} Failed to write to file '${_QEMU_DEST_PATH}'."
                 fi
 
-                if ! sudo echo -e "${FILE_2_CONTENTS[*]}" >> "$_APPARMOR_QEMU_DEST_PATH"; then
-                    echo -e "${_PREFIX_ERROR} Failed to write to file '$_APPARMOR_QEMU_DEST_PATH'."
+                if ! sudo echo -e "${FILE_2_CONTENTS[*]}" >> "${_APPARMOR_QEMU_DEST_PATH}"; then
+                    echo -e "${_PREFIX_ERROR} Failed to write to file '${_APPARMOR_QEMU_DEST_PATH}'."
                 fi
 
                 return 0
