zram-swap: tied usage to business functions.

diff --git a/bin/vfiolib-extras b/bin/vfiolib-extras
--- a/bin/vfiolib-extras
+++ b/bin/vfiolib-extras
@@ -54,28 +54,35 @@
 		{
 			local -r _FILE="/etc/default/zram-swap"
 			local -r _LINE_TO_MATCH="_zram_fraction="
-			local -i _ZRAM_SWAP_AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY / 2 ))
-			local -i _DENOMINATOR=$( printf "%.0f" $( echo "scale=2;$_INT_MAX_MEMORY/$_ZRAM_SWAP_AVAILABLE_MEMORY" | bc ) )
+            local _FRACTION=""
 
-			# <remarks> Round down to nearest even number. </remarks>
-			if [[ $( expr $_DENOMINATOR % 2 ) -eq 1 ]]; then
-				(( _DENOMINATOR-- ))
-			fi
+            if ! "$_HAS_ARG_ZRAM_SWAP_SET_FRACTION"; then
+                local -i _ZRAM_SWAP_AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY / 2 ))
+                local -i _DENOMINATOR=$( printf "%.0f" $( echo "scale=2;$_INT_MAX_MEMORY/$_ZRAM_SWAP_AVAILABLE_MEMORY" | bc ) )
 
-			# <remarks> Is fraction positive non-zero and not equal to one. </remarks>
-			if [[ "$_DENOMINATOR" -le 0 ]]; then
-				echo -e "$_PREFIX_ERROR Denominator is negative or zero."
-			fi
+                # <remarks> Round down to nearest even number. </remarks>
+                if [[ $( expr $_DENOMINATOR % 2 ) -eq 1 ]]; then
+                    (( _DENOMINATOR-- ))
+                fi
 
-			local _FRACTION="1/$_DENOMINATOR"
+                # <remarks> Is fraction positive non-zero and not equal to one. </remarks>
+                if [[ "$_DENOMINATOR" -le 0 ]]; then
+                    echo -e "$_PREFIX_ERROR Denominator is negative or zero."
+                fi
+
+                _FRACTION="1/$_DENOMINATOR"
+            fi
+
+            _FRACTION="$_ARGS_FOR_ZRAM_SWAP_FRACTION"
 
 			if ! sed -i '/'$_LINE_TO_MATCH'"*"/c\'$_LINE_TO_MATCH'"'$_FRACTION'"' "$_FILE"; then
 				echo -e "$_PREFIX_ERROR Failed to write output to zram-swap file."
 				return 1
 			fi
 
-			if sudo swapon -v | grep zram &> /dev/null\
-				&& sudo swapon -v | grep zram &> /dev/null\
+			if ! "$_ARGS_FOR_ZRAM_SWAP_FORCE" \
+                && sudo swapon -v | grep zram &> /dev/null \
+				&& sudo swapon -v | grep zram &> /dev/null \
 				&& ! sudo swapon -v | grep zram | grep 0B &> /dev/null; then
 				echo -e "$_PREFIX_NOTE zram-swap device(s) already in use. Restart system to save changes."
 				return 0
