Fixed ZRAMSWAP function. Added func.

diff --git a/vfiolib/vfiolib-extras b/vfiolib/vfiolib-extras
--- a/vfiolib/vfiolib-extras
+++ b/vfiolib/vfiolib-extras
@@ -9,16 +9,14 @@
 
 # <remarks> Using </remarks>
 # <code>
-    source vfiolib-calcss
+    source vfiolib-calcs
     source vfiolib-iommu
 # </code>
 
 # <params>
-    declare -g _THIS_HOME_PATH=$( getent passwd "$( whoami )" | cut -d: -f6 )
-    declare -g _GIT_PATH="${_THIS_HOME_PATH}/source/"
-    declare -g _FILES_PATH="${_THIS_HOME_PATH}/Downloads/"
+    declare -g _GIT_PATH="$USER/source/"
 
-    # <remarks> Flag progress of setups </remarks>
+    # <remarks> Flags </remarks>
     declare -g _IS_AUDIO_CAPTURE_SETUP=false
     declare -g _IS_SCREAM_SETUP=false
 # </params>
@@ -32,79 +30,74 @@
     {
         function Install
         {
-            # <params>
-            local _USER_NAME="foundObjects"
-            local _REPO_NAME="zram-swap"
-            local _FULL_REPO="$_USER_NAME/$_REPO_NAME"
-            local _SCRIPT_NAME="install.sh"
-            # </params>
+            local -r _USER_NAME="foundObjects"
+            local -r _REPO_NAME="zram-swap"
+            local -r _FULL_REPO="$_USER_NAME/$_REPO_NAME"
+            local -r _SCRIPT_NAME="install.sh"
 
-            GetScriptDir || return 1
             echo
-            UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" || return 1
+            UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" "$_EXECUTE_ZRAM_SWAP" || return 1
             cd "$_GIT_PATH$_FULL_REPO" || return 1
-            [ -e "$_SCRIPT_NAME" ] || return 1
-            sudo bash "$_SCRIPT_NAME" || return 1
-            GetScriptDir || return 1
+
+            if [[ -z "$_SCRIPT_NAME" ]]; then
+                echo -e "$_PREFIX_ERROR Failed to find script '$_SCRIPT_NAME'."
+                return 1
+            fi
+
+            if ! sudo bash "$_SCRIPT_NAME"; then
+                echo -e "$_PREFIX_ERROR Failed to execute script '$_SCRIPT_NAME'."
+                return 1
+            fi
+
             return 0
         }
 
         function Modify
         {
-            # <params>
-            local _FILE_1="/etc/default/zram-swap"
-            local str_match_line1="_zram_fraction="
-            local var_find_zram_swap='swapon -v | grep zram'
-            local var_disable_zram_swap='swapoff /dev/zram*'
-            local var_enable_all_swap='swapon -a'
-            local var_restart_daemon='systemctl restart zram-swap'
-            declare -a arr_file_contents=( $( cat "${_FILE_1}" ) )
-            # </params>
-
-            # <remarks> Replace matching line with comment of line </remarks>
-            for _KEY in ${!arr_file_contents[@]}; do
-                if [[ "${arr_file_contents[$_KEY]}" == *"${str_match_line1}"* ]]; then
-                    arr_file_contents[$_KEY]="#${arr_file_contents[$_KEY]}"
-                fi
-            done
-
-            if ! IsNum "${_INT_MAX_MEMORY}"; then
-                local _OUTPUT_could_not_parse_memory="$_PREFIX_ERROR Could not parse system memory."
-                echo -e "${_OUTPUT_could_not_parse_memory}"
-                return 1
-            fi
-
-            if IsNum "${int_alloc_mem_hugepages}"; then
-                local -i int_usable_mem=$(( ( _INT_MAX_MEMORY - int_alloc_mem_hugepages ) / 2 ))
-            else
-                local -i int_usable_mem=$(( _INT_MAX_MEMORY / 2 ))
-            fi
-
-            local -i int_denominator=$( printf "%.0f" $( echo "scale=2;${_INT_MAX_MEMORY}/${int_usable_mem}" | bc ) )
+            local -r _FILE="/etc/default/zram-swap"
+            local -r _LINE_TO_MATCH="_zram_fraction="
+            local -ir _ZRAM_SWAP_AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY / 2 ))
+            local -ir _DENOMINATOR=$( printf "%.0f" $( echo "scale=2;$_INT_MAX_MEMORY/$_ZRAM_SWAP_AVAILABLE_MEMORY" | bc ) )
 
             # <remarks> Round down to nearest even number. </remarks>
-            if [[ $( expr $int_denominator % 2 ) -eq 1 ]]; then
-                (( int_denominator-- ))
+            if [[ $( expr $_DENOMINATOR % 2 ) -eq 1 ]]; then
+                (( _DENOMINATOR-- ))
             fi
 
             # <remarks> Is fraction positive non-zero and not equal to one. </remarks>
-            if [[ "${int_denominator}" -gt 1 ]]; then
-                local str_fraction="1/${int_denominator}"
-
-                arr_file_contents+=(
-                    ""
-                    "#"
-                    "# Generated by '${str_full_repo_name}'"
-                    "#"
-                    "# WARNING: Any modifications to this file will be modified by '${str_repo_name}'"
-                    "${str_match_line1}\"${str_fraction}\""
-                )
+            if [[ "$_DENOMINATOR" -le 0 ]]; then
+                echo -e "$_PREFIX_ERROR Denominator is negative or zero."
             fi
 
-            OverwriteFile "arr_file_contents" "${_FILE_1}" || return 1
-            eval "${var_find_zram_swap}" &> /dev/null && eval "${var_disable_zram_swap}" &> /dev/null
-            eval "${var_restart_daemon}" || return 1
-            eval "${var_enable_all_swap}" || return 1
+            local -r _FRACTION="1/$_DENOMINATOR"
+
+            if ! sed -i "/$_LINE_TO_MATCH\"*\"/c\$_LINE_TO_MATCH\"$_FRACTION\"" "$_FILE"; then
+                echo -e "$_PREFIX_ERROR Failed to write output to zram-swap file."
+                return 1
+            fi
+
+            if sudo swapon -v | grep zram \
+                && ! sudo swapon -v | grep zram | grep 0B; then
+                echo -e "$_PREFIX_NOTE zram-swap device(s) already in use. Restart system to save changes."
+                return 0
+            fi
+
+            if sudo swapon -v | grep zram \
+                && ! sudo swapoff /dev/zram*; then
+                echo -e "$_PREFIX_ERROR Failed to disable zram-swap device(s)."
+                return 1
+            fi
+
+            if ! sudo systemctl restart zram-swap; then
+                echo -e "$_PREFIX_ERROR Failed to restart zram-swap service."
+                return 1
+            fi
+
+            if ! sudo swapon -a; then
+                echo -e "$_PREFIX_ERROR Failed to enable zram-swap device."
+                return 1
+            fi
+
             return 0
         }
 
@@ -159,7 +152,6 @@
         ModifyQEMU || return 1
         return 0
     }
-
 
     # <summary>
     # Install necessary depenencies to setup an audio capture from guest emulated audio device to host audio backend.
@@ -229,7 +221,7 @@
 
         local _OUTPUT="Installing audio drivers..."
         Main &> /dev/null
-        PrintPassOrFail "${_OUTPUT}" && _IS_AUDIO_CAPTURE_SETUP=true || _IS_AUDIO_CAPTURE_SETUP=false
+        PrintPassOrFail "Installing audio drivers..." && _IS_AUDIO_CAPTURE_SETUP=true || _IS_AUDIO_CAPTURE_SETUP=false
         return "$_LAST_EXIT_CODE"
     }
 
@@ -579,5 +571,72 @@
     {
         # TODO
         return 1
+    }
+
+    function UpdateOrCloneGitRepo
+    {
+        local _AUTO_ANSWER_YES=false
+
+        if [[ "$4" == true ]]; then
+            _AUTO_ANSWER_YES=true
+        fi
+
+        if [[ "$3" == "" ]] \
+            || [[ "$2" == "" ]] \
+            || [[ "$1" == "" ]]; then
+            echo -e "$_PREFIX_ERROR Input values are empty."
+            return 1
+        fi
+
+        if [[ ! -d "$1$2" ]] \
+            && sudo mkdir -p "$1$3"; then
+            echo -e "$_PREFIX_ERROR Failed to create directory '$1$3'."
+            return 1
+        fi
+
+        # <remarks> Update existing GitHub repository. </remarks>
+        if [[ -d "$1$2" ]]; then
+            cd "$1$2"
+
+            if ! git pull &> /dev/null; then
+                echo -e "$_PREFIX_ERROR Failed to update repository."
+                return 1
+            fi
+
+            return 0
+
+        # <remarks> Clone new GitHub repository. </remarks>
+        elif [[ -d "$1$3" ]]; then
+            for _TRIES_COUNT in $( seq 0 2 ); do
+                if ! "$_AUTO_ANSWER_YES"; then
+                    read -r -p "Clone repo '$2'? [Y/n]: " _ANSWER
+                else
+                    _ANSWER="Y"
+                fi
+
+                case "$_ANSWER" in
+                    [Yy]* )
+                        cd "$1$3"
+
+                        if ! git clone "https://github.com/$2" &> /dev/null; then
+                            echo -e "$_PREFIX_ERROR Failed to download repository."
+                            return 1
+                        fi
+
+                        return 0 ;;
+
+                    [Nn]* )
+                        break ;;
+
+                    * )
+                        echo "Please answer Y/n." ;;
+                esac
+            done
+
+            return 1
+
+        else
+            return 1
+        fi
     }
 # </code>
