Working for the man

diff --git a/vfiolib/vfiolib-essentials b/vfiolib/vfiolib-essentials
--- a/vfiolib/vfiolib-essentials
+++ b/vfiolib/vfiolib-essentials
@@ -1,8 +1,8 @@
 #!/bin/bash sh
 
 #
-# Filename:         vfiolib-utils
-# Description:      Recommended pre-installation setup.
+# Filename:         vfiolib-essentials
+# Description:      Recommended pre-installation setups.
 # Author(s):        Alex Portell <github.com/portellam>
 # Maintainer(s):    Alex Portell <github.com/portellam>
 #
@@ -16,29 +16,11 @@
 
 # <remarks> Using </remarks>
 # <code>
-    source vfiolib-calc
+    source vfiolib-calcs
     source vfiolib-iommu
 # </code>
 
 # <params>
-    # <remarks> File templates. </remarks>
-    declare -g _DISCLAIMER_FILE_CONTENTS=(
-        "#### Generated by 'portellam/deploy-vfio'"
-        "# WARNING: Any modifications to this file will be modified by 'deploy-vfio'"
-        "#"
-    )
-
-    declare -g _VFIO_DISCLAIMER_FILE_CONTENTS=(
-        "${_DISCLAIMER_FILE_CONTENTS[@]}"
-        "# Run lspci to view hardware information."
-        "# You must run update-initramfs(8) to effect this change."
-        "#"
-    )
-
-    # <remarks> Evaluations </remarks>
-    declare -g _GET_FIRST_VALID_USER='getent passwd {1000..60000} | cut -d ":" -f 1' &> /dev/null
-    declare -g _FIRST_USER=$( eval "${_GET_FIRST_VALID_USER}" ) &> /dev/null
-
     # <remarks> Flag progress of setups </remarks>
     declare -g _IS_EVDEV_SETUP=false
     declare -g _IS_HUGEPAGES_SETUP=false
@@ -347,187 +329,122 @@
     {
         function Main
         {
-            declare -a arr_file1_evdev_cgroups=( )
-            declare -a arr_file1_default_cgroups=(
+            local -a _FILE_1_CONTENTS _FILE_1_CONTENTS_EVDEV_CGROUPS _FILE_2_CONTENTS
+            local -ar _FILE_1_CONTENTS_DEFAULT_CGROUPS=(
                 "        \"/dev/null\", \"/dev/full\", \"/dev/zero\","
                 "        \"/dev/random\", \"/dev/urandom\","
                 "        \"/dev/ptmx\", \"/dev/KVM\","
                 "        \"/dev/rtc\", \"/dev/hpet\""
             )
-
-            declare -a arr_file1_contents arr_file1_current arr_file2_contents arr_file2_current
-            local str_backup1="https://github.com/libvirt/libvirt/blob/master/src/qemu/qemu.conf.in"
-            # local str_backup2=""
-            local str_daemon1="libvirtd"
-            local str_daemon1_packages="qemu"
-            local str_file1="/etc/libvirt/qemu.conf"
-            local str_file2="/etc/apparmor.d/local/abstractions/libvirt-qemu"
-
-            # <remarks> Check if Libvirt is installed. </remarks>
-            IsInstalledPackage "${str_daemon1_packages}" &> /dev/null || InstallPackage "${str_daemon1_packages}" || return "$?"
-
-            # <remarks> Save file before work. </remarks>
-            BackupFile "${str_file1}" || return "$?"
-            BackupFile "${str_file2}" || return "$?"
-
-             # <remarks> Grab original system files. </remarks>
-            if SetInternetStatus && $_IS_CONNECTED_TO_INTERNET; then
-                curl "${str_backup_file1}" -o "${str_orig_file1}"
-                # curl "${str_backup_file2}" -o "${str_orig_file2}"
-            fi
-
-            # <remarks> Check if system files are unmodified. </remarks>
-            local bool_is_file1_original=true
-            local bool_is_file2_original=true
-
-            # TODO: delete lines the exist within range of the disclaimer and and end cap.
-
-            for var_line in ${_DISCLAIMER_FILE_CONTENTS[@]}; do
-                FindLineInFile "${str_file1}" "${var_line}" || bool_is_file1_original=false
-            done
-
-            for var_line in ${_DISCLAIMER_FILE_CONTENTS[@]}; do
-                FindLineInFile "${str_file2}" "${var_line}" || bool_is_file2_original=false
-            done
-
-            # <remarks> Overwrite system file with a backup or original copy. </remarks>
-            if ! $bool_is_file1_original; then
-                if IsFile "${str_backup_file1}" &> /dev/null && ! AreEqualFiles "${str_backup_file1}" "${str_file2}"; then
-                    cp "${str_orig_file1}" "${str_file1}" || (
-                        RestoreFile "${str_file1}"
-                        return "$?"
-                    )
-                elif ! IsFile "${str_backup_file1}" &> /dev/null; then  # TODO: to be revised
-                    RestoreFile "${str_file1}" || return "$?"
-                else
-                    return 1
-                fi
-            fi
-
-            if ! $bool_is_file2_original; then
-                if IsFile "${str_backup_file2}" &> /dev/null && ! AreEqualFiles "${str_backup_file2}" "${str_file2}"; then
-                    cp "${str_orig_file2}" "${str_file2}" || (
-                        RestoreFile "${str_file2}"
-                        return "$?"
-                    )
-                elif ! IsFile "${str_backup_file2}" &> /dev/null; then  # TODO: to be revised
-                    RestoreFile "${str_file2}" || return "$?"
-                else
-                    return 1
-                fi
-            fi
-
             # <remarks> Format input for Evdev. </remarks>
-            if $_IS_EVDEV_SETUP; then
-                for var_device in ${_EVENT_DEVICES_LIST[@]}; do
-                    arr_file1_evdev_cgroups+=( "        \"/dev/input/by-id/${var_device}\"," )
+            if "$_IS_EVDEV_SETUP"; then
+                for _DEVICE in ${_EVENT_DEVICES_LIST[@]}; do
+                    _FILE_1_CONTENTS_EVDEV_CGROUPS+=( "        \"/dev/input/by-id/$_DEVICE\"," )
                 done
 
-                for var_device in ${_INPUT_DEVICES_LIST[@]}; do
-                    arr_file1_evdev_cgroups+=( "        \"/dev/input/by-id/${var_device}\"," )
+                for _DEVICE in ${_INPUT_DEVICES_LIST[@]}; do
+                    _FILE_1_CONTENTS_EVDEV_CGROUPS+=( "        \"/dev/input/by-id/$_DEVICE\"," )
                 done
             fi
 
             # <remarks> Preface file contents. </remarks>
-            arr_file1_contents=( "${_DISCLAIMER_FILE_CONTENTS[@]}" )
-            arr_file2_contents=( "${_DISCLAIMER_FILE_CONTENTS[@]}" )
-            arr_file1_contents+=(
+            _FILE_1_CONTENTS=( "${_DISCLAIMER_FILE_CONTENTS[@]}" )
+            _FILE_2_CONTENTS=( "${_DISCLAIMER_FILE_CONTENTS[@]}" )
+            _FILE_1_CONTENTS+=(
                 ""
                 "### User permissions ###"
             )
 
             # <remarks> Add user and group for Evdev. </remarks>
-            if IsString "${_FIRST_USER}" && ($_IS_EVDEV_SETUP || $_IS_SCREAM_SETUP); then
-                arr_file1_contents+=(
-                    "user = \"${_FIRST_USER}\""
+            if "$_IS_EVDEV_SETUP" \
+                || "$_IS_SCREAM_SETUP"; then
+                _FILE_1_CONTENTS+=(
+                    "user = \"$SUDO_USER\""
                     "group = \"user\""
                 )
             else
-                arr_file1_contents+=(
+                _FILE_1_CONTENTS+=(
                     "#user = \"user\""
                     "#group = \"user\""
                 )
 
-                ( return "${int_code_skipped_operation}" )
+                false
             fi
 
             # <remarks> Hugepages </remarks>
-            arr_file1_contents+=(
+            _FILE_1_CONTENTS+=(
                 ""
                 "### Hugepages ###"
             )
 
-            if $_IS_HUGEPAGES_SETUP; then
-                arr_file1_contents+=(
+            if "$_IS_HUGEPAGES_SETUP"; then
+                _FILE_1_CONTENTS+=(
                     "hugetlbfs_mount = \"/dev/hugepages\""
                 )
             else
-                arr_file1_contents+=(
+                _FILE_1_CONTENTS+=(
                     "#hugetlbfs_mount = \"/dev/hugepages\""
                 )
 
-                ( return "${int_code_skipped_operation}" )
+                false
             fi
 
             # <remarks> Add cgroups for Evdev. </remarks>
-            arr_file1_contents+=(
+            _FILE_1_CONTENTS+=(
                 ""
                 "### Devices ###"
                 "cgroup_device_acl = ["
             )
 
             if $_IS_EVDEV_SETUP; then
-                arr_file1_contents+=(
-                    "${arr_file1_evdev_cgroups[@]}"
-                    "${arr_file1_default_cgroups[@]}"
+                _FILE_1_CONTENTS+=(
+                    "${_FILE_1_CONTENTS_EVDEV_CGROUPS[@]}"
+                    "${_FILE_1_CONTENTS_DEFAULT_CGROUPS[@]}"
                     "]"
                 )
 
-                arr_file2_contents+=(
+                _FILE_2_CONTENTS+=(
                     ""
                     "# EVDEV"
                     "/dev/input/* rw,"
                     "/dev/input/by-id/* rw,"
                 )
             else
-                arr_file1_contents+=(
-                    "${arr_file1_default_cgroups[@]}"
+                _FILE_1_CONTENTS+=(
+                    "${_FILE_1_CONTENTS_DEFAULT_CGROUPS[@]}"
                     "]"
                 )
 
-                ( return "${int_code_skipped_operation}" )
+                false
             fi
 
             # <remarks> Adds NVRAM for EFI kernels in UEFI guest(s). </remarks>
-            arr_file1_contents+=(
+            _FILE_1_CONTENTS+=(
                 ""
                 "nvram = ["
-                "        \"/usr/share/OguestF/OguestF_CODE.fd:/usr/share/OguestF/OguestF_VARS.fd\","
-                "        \"/usr/share/OguestF/OguestF_CODE.secboot.fd:/usr/share/OguestF/OguestF_VARS.fd\","
-                "        \"/usr/share/AAguestF/AAguestF_CODE.fd:/usr/share/AAguestF/AAguestF_VARS.fd\","
-                "        \"/usr/share/AAguestF/AAguestF32_CODE.fd:/usr/share/AAguestF/AAguestF32_VARS.fd\""
+                "        \"/usr/share/OVMF/OVMF_CODE.fd:/usr/share/OVMF/OVMF_VARS.fd\","
+                "        \"/usr/share/OVMF/OVMF_CODE.secboot.fd:/usr/share/OVMF/OVMF_VARS.fd\","
+                "        \"/usr/share/AAVMF/AAVMF_CODE.fd:/usr/share/AAVMF/AAVMF_VARS.fd\","
+                "        \"/usr/share/AAVMF/AAVMF32_CODE.fd:/usr/share/AAVMF/AAVMF32_VARS.fd\""
                 "]"
             )
 
             # <remarks> Append changes to file(s). </remarks>
-            if ! IsFile "${str_file1}" &> /dev/null || ( ReadFile "arr_file1_current" "${str_file1}" &> /dev/null && IsArray "arr_file1_current" && ! AreEqualArrays "arr_file1_current" "arr_file1_contents" ); then
-                OverwriteFile "arr_file1_contents" "${str_file1}" || return "$?"
+            if ! echo -e "${_FILE_1_CONTENTS[@]}" >> "$_QEMU_FILE_PATH"; then
+                echo -e "$_PREFIX_ERROR Failed to write to file '$_QEMU_FILE_PATH'."
             fi
 
-            if ! IsFile "${str_file2}" &> /dev/null || ( ReadFile "arr_file2_current" "${str_file1}" &> /dev/null && IsArray "arr_file2_current" && ! AreEqualArrays "arr_file2_current" "arr_file2_contents" ); then
-                OverwriteFile "arr_file2_contents" "${str_file2}" || return "$?"
+            if ! echo -e "${_FILE_2_CONTENTS[@]}" >> "$_APPARMOR_QEMU_FILE_PATH"; then
+                echo -e "$_PREFIX_ERROR Failed to write to file '$_APPARMOR_QEMU_FILE_PATH'."
             fi
 
-            # <remarks> Libvirtd service </remarks>
-            IsActiveDaemon "${str_daemon1}" || (
-                systemctl enable "${str_daemon1}" || return 1
-            )
-            systemctl restart "${str_daemon1}"
-            return "$?"
+            return 0
         }
 
         echo
+        IFS=$'\n'
         Main
+        unset IFS
         PrintPassOrFail "Appending libvirt-qemu..."
         return "$_LAST_EXIT_CODE"
     }
