Men at work

diff --git a/vfiolib/vfiolib-calcs b/vfiolib/vfiolib-calcs
--- a/vfiolib/vfiolib-calcs
+++ b/vfiolib/vfiolib-calcs
@@ -16,9 +16,23 @@
 # <params>
     declare -g _IS_HUGEPAGES_COUNT_SET=false
     declare -g _IS_HUGEPAGES_SIZE_SET=false
+    declare -gi _AVAILABLE_MEMORY=0
+    declare -gir _MIN_MEMORY=8
 # </params>
 
 # <code>
+    function GetFreeMemory
+    {
+        _AVAILABLE_MEMORY=$(( _INT_MAX_MEMORY - _MIN_MEMORY ))
+        return 0
+    }
+
+    function GetMemoryAllocatedToHugepages
+    {
+        _HUGEPAGES_ALLOCATED_MEMORY=$(( $_HUGEPAGES_COUNT * $_HUGEPAGES_SIZE_IN_KBIT ))
+        return 0
+    }
+
     function GetHugepageByteSize
     {
         local -u _ANSWER="$1"
@@ -85,6 +99,8 @@
 
     function GetZramSwapSize
     {
+        IsHostMemorySufficientForZramSwap || return 1
+
         case "$1" in
             *"/"* )
                 local -i _NUMERATOR=$( echo $1 | cut -d '/' -f1 )
@@ -114,5 +130,35 @@
         fi
 
         return 1
+    }
+
+    function IsHostMemorySufficientForHugepages
+    {
+        GetFreeMemory
+
+        if [[ "$_AVAILABLE_MEMORY" -le 0 ]]; then
+            echo -e "$_PREFIX_ERROR Insufficient Host memory for Hugepages."
+            return 1
+        fi
+
+        return 0
+    }
+
+    function IsHostMemorySufficientForZramSwap
+    {
+        GetFreeMemory
+
+        if "$_IS_HUGEPAGES_SETUP"; then
+            GetMemoryAllocatedToHugepages || return 1
+            _AVAILABLE_MEMORY=$(( _AVAILABLE_MEMORY - _HUGEPAGES_ALLOCATED_MEMORY ))
+        fi
+
+        if [[ "$_AVAILABLE_MEMORY" -le 0 ]]; then
+            echo -e "$_PREFIX_ERROR Insufficient Host memory for zram-swap."
+            return 1
+        fi
+
+        return 0
+
     }
 # </code>
diff --git a/vfiolib/vfiolib-essentials b/vfiolib/vfiolib-essentials
--- a/vfiolib/vfiolib-essentials
+++ b/vfiolib/vfiolib-essentials
@@ -21,6 +21,8 @@
 # </code>
 
 # <params>
+    declare -gir _HUGEPAGES_ALLOCATED_MEMORY=0
+
     # <remarks> Flag progress of setups </remarks>
     declare -g _IS_EVDEV_SETUP=false
     declare -g _IS_HUGEPAGES_SETUP=false
@@ -44,7 +46,7 @@
     # <summary>
     # isolcpus: Allocate host CPU cores (and/or threads), to reduce host overhead, and improve both host and guest performance.
     # </summary
-    function AllocateCPU
+    function AllocateCPUToGuest
     {
         function AskToContinue
         {
@@ -96,7 +98,7 @@
                 # <remarks> Save thread sets to delimited list. </remarks>
                 local -i _FIRST_THREAD_SET="${_HOST_THREADS_DELIM_LIST[0]}"
                 local -i _LAST_THREAD_SET="${_HOST_THREADS_DELIM_LIST[-1]}"
-                local _THREAD_SET="${_FIRST_THREAD_SET}"
+                local _THREAD_SET="$_FIRST_THREAD_SET"
 
                 if [[ "$_FIRST_THREAD_SET" -ne "$_LAST_THREAD_SET" ]]; then
                     local _THREAD_SET="$_FIRST_THREAD_SET-$_LAST_THREAD_SET"
@@ -120,9 +122,9 @@
 
         function Main
         {
+            local -i _CORES_ALLOCATED_TO_HOST=1
             local -i _TOTAL_CORES_COUNT=$( cat /proc/cpuinfo | grep "cpu cores" | uniq | grep -o "[0-9]\+" )
             local -i _TOTAL_THREADS_COUNT=$( cat /proc/cpuinfo | grep "siblings" | uniq | grep -o "[0-9]\+" )
-            local -i _CORES_ALLOCATED_TO_HOST=1
 
             # <remarks> Set maximum number of cores allocated to host. </remarks>
             if [[ "$_SUM_CORES" -ge 4 ]]; then
@@ -133,6 +135,7 @@
                 _CORES_ALLOCATED_TO_HOST=1
 
             else
+                echo -e "$PREFIX_ERROR Insuc"
                 return 1
             fi
 
@@ -172,7 +175,7 @@
             # </remarks>
 
             # <remarks> Find CPU mask. </remarks>
-            local _GET_HEX_MASK='echo "obase=16; $_THREAD_decimal" | bc'
+            local -r _GET_HEX_MASK='echo "obase=16; $_THREAD_decimal" | bc'
             local -i _HOST_THREADS_HEX_MASK=0
             local -i _TOTAL_THREADS_HEX_MASK=0
 
@@ -197,7 +200,7 @@
         }
 
         if ! "$_EXECUTE_ISOLCPU_SETUP"; then
-            AskToContinue || return "$?"
+            AskToContinue || return 1
         fi
 
         Main "$@"
@@ -209,7 +212,7 @@
     # Hugepages: Allocate host memory (RAM) to 'hugepages'.
     # Eliminate the need to defragement memory, reduce host overhead, and improve both host and guest performance.
     # </summary
-    function AllocateRAM
+    function AllocateRAMToGuest
     {
         function AskForHugepageByteSize
         {
@@ -283,7 +286,8 @@
 
             AskForHugepageByteSize || return 1
             AskForHugepageCount || return 1
-            declare -gir _HUGEPAGES_ALLOCATED_MEMORY=$(( $_HUGEPAGES_COUNT * $_HUGEPAGES_SIZE_IN_KBIT ))
+            GetMemoryAllocatedToHugepages || return 1
+            IsHostMemorySufficientForHugepages || return 1
             declare -gr _OUTPUT_GRUB_CMDLINE_HUGEPAGES="default_hugepagesz=$_HUGEPAGES_BYTE_SUFFIX hugepagesz=$_HUGEPAGES_BYTE_SUFFIX hugepages=$_HUGEPAGES_COUNT"
             _IS_HUGEPAGES_SETUP=true
             return 0
@@ -295,30 +299,30 @@
         return "$_LAST_EXIT_CODE"
     }
 
-    function ExecuteUtilsSetups
+    function ExecuteEssentials
     {
-        AddUserToGroups || return "$?"
+        AddUserToGroups || return 1
 
         if "$_EXECUTE_ALL_UTILS_SETUPS"; then
-            AllocateCPU || return "$?"
-            AllocateRAM || return "$?"
-            VirtualKVM || return "$?"
+            AllocateCPUToGuest || return 1
+            AllocateRAMToGuest || return 1
+            VirtualKVM || return 1
             return 0
         fi
 
         if "$_EXECUTE_ISOLCPU_SETUP"; then
-            AllocateCPU || return "$?"
+            AllocateCPUToGuest || return 1
         fi
 
         if "$_EXECUTE_HUGEPAGES_SETUP"; then
-            AllocateRAM || return "$?"
+            AllocateRAMToGuest || return 1
         fi
 
         if "$_EXECUTE_EVDEV_SETUP"; then
-            VirtualKVM || return "$?"
+            VirtualKVM || return 1
         fi
 
-        ModifyQEMU || return "$?"
+        ModifyQEMU || return 1
         return 0
     }
 
@@ -495,8 +499,8 @@
         echo
 
         if ! "$_EXECUTE_EVDEV_SETUP"; then
-            echo -e "Evdev (Event Devices) is a method of creating a virtual KVM (Keyboard-Video-Mouse) switch between host and guest(s).\n${var_yellow}HOW-TO:${var_reset_color} Press 'L-CTRL' and 'R-CTRL' simultaneously.\n"
-            AskToContinue || return "$?"
+            echo -e "Evdev (Event Devices) is a method of creating a virtual KVM (Keyboard-Video-Mouse) switch between host and guest(s).\n${_SET_COLOR_YELLOW}HOW-TO:${_RESET_COLOR} Press 'L-CTRL' and 'R-CTRL' simultaneously.\n"
+            AskToContinue || return 1
         fi
 
         Main
diff --git a/vfiolib/vfiolib-extras b/vfiolib/vfiolib-extras
--- a/vfiolib/vfiolib-extras
+++ b/vfiolib/vfiolib-extras
@@ -25,17 +25,141 @@
 
 # <code>
     # <summary>
-    # auto-Xorg: System service to find and set a valid Host boot VGA device for Xorg.
+    # zramswap: Setup a swap partition in host memory.
+    # Reduce swapiness to existing host swap partition(s)/file(s), and reduce chances of memory exhaustion as host over-allocates memory.
     # </summary>
-    # <remarks>
-    # References:
-    #   https://github.com/portellam/auto-Xorg
-    # </remarks>
-    function AutoXorg
+    function AllocateRAMToSwap
     {
-        # TODO
-        return 1
+        function Install
+        {
+            # <params>
+            local _USER_NAME="foundObjects"
+            local _REPO_NAME="zram-swap"
+            local _FULL_REPO="$_USER_NAME/$_REPO_NAME"
+            local _SCRIPT_NAME="install.sh"
+            # </params>
+
+            GetScriptDir || return 1
+            echo
+            UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" || return 1
+            cd "$_GIT_PATH$_FULL_REPO" || return 1
+            [ -e "$_SCRIPT_NAME" ] || return 1
+            sudo bash "$_SCRIPT_NAME" || return 1
+            GetScriptDir || return 1
+            return 0
+        }
+
+        function Modify
+        {
+            # <params>
+            local str_file1="/etc/default/zram-swap"
+            local str_match_line1="_zram_fraction="
+            local var_find_zram_swap='swapon -v | grep zram'
+            local var_disable_zram_swap='swapoff /dev/zram*'
+            local var_enable_all_swap='swapon -a'
+            local var_restart_daemon='systemctl restart zram-swap'
+            declare -a arr_file_contents=( $( cat "${str_file1}" ) )
+            # </params>
+
+            # <remarks> Replace matching line with comment of line </remarks>
+            for _KEY in ${!arr_file_contents[@]}; do
+                if [[ "${arr_file_contents[$_KEY]}" == *"${str_match_line1}"* ]]; then
+                    arr_file_contents[$_KEY]="#${arr_file_contents[$_KEY]}"
+                fi
+            done
+
+            if ! IsNum "${_INT_MAX_MEMORY}"; then
+                local _OUTPUT_could_not_parse_memory="$_PREFIX_ERROR Could not parse system memory."
+                echo -e "${_OUTPUT_could_not_parse_memory}"
+                return 1
+            fi
+
+            if IsNum "${int_alloc_mem_hugepages}"; then
+                local -i int_usable_mem=$(( ( _INT_MAX_MEMORY - int_alloc_mem_hugepages ) / 2 ))
+            else
+                local -i int_usable_mem=$(( _INT_MAX_MEMORY / 2 ))
+            fi
+
+            local -i int_denominator=$( printf "%.0f" $( echo "scale=2;${_INT_MAX_MEMORY}/${int_usable_mem}" | bc ) )
+
+            # <remarks> Round down to nearest even number. </remarks>
+            if [[ $( expr $int_denominator % 2 ) -eq 1 ]]; then
+                (( int_denominator-- ))
+            fi
+
+            # <remarks> Is fraction positive non-zero and not equal to one. </remarks>
+            if [[ "${int_denominator}" -gt 1 ]]; then
+                local str_fraction="1/${int_denominator}"
+
+                arr_file_contents+=(
+                    ""
+                    "#"
+                    "# Generated by '${str_full_repo_name}'"
+                    "#"
+                    "# WARNING: Any modifications to this file will be modified by '${str_repo_name}'"
+                    "${str_match_line1}\"${str_fraction}\""
+                )
+            fi
+
+            OverwriteFile "arr_file_contents" "${str_file1}" || return 1
+            eval "${var_find_zram_swap}" &> /dev/null && eval "${var_disable_zram_swap}" &> /dev/null
+            eval "${var_restart_daemon}" || return 1
+            eval "${var_enable_all_swap}" || return 1
+            return 0
+        }
+
+        if ! IsHostMemorySufficientForZramSwap \
+            || ! Install \
+            || ! Modify &> /dev/null; then
+            false
+        fi
+
+        PrintPassOrFail "Allocating RAM to swap..."
+        return "$_LAST_EXIT_CODE"
     }
+
+    function ExecuteExtras
+    {
+        GuestAudioCapture
+
+        if "$_EXECUTE_ALL_EXTRAS_SETUPS"; then
+            AllocateRAMToSwap
+            SetVideoOutput
+            LibvirtHooks
+            GuestAudioLoopback
+            GuestAudioStream
+            GuestVideoCapture
+            return 0
+        fi
+
+        if "$_EXECUTE_ZRAM_SWAP"; then
+            AllocateRAMToSwap || return 1
+        fi
+
+        if "$_EXECUTE_AUTO_XORG_SETUP"; then
+            SetVideoOutput || return 1
+        fi
+
+        if "$_EXECUTE_LIBVIRT_HOOKS"; then
+            LibvirtHooks || return 1
+        fi
+
+        if "$_EXECUTE_AUDIO_LOOPBACK_SETUP"; then
+            GuestAudioLoopback || return 1
+        fi
+
+        if "$_EXECUTE_SCREAM"; then
+            GuestAudioStream || return 1
+        fi
+
+        if "$_EXECUTE_LOOKING_GLASS"; then
+            GuestVideoCapture || return 1
+        fi
+
+        ModifyQEMU || return 1
+        return 0
+    }
+
 
     # <summary>
     # Install necessary depenencies to setup an audio capture from guest emulated audio device to host audio backend.
@@ -144,7 +268,7 @@
             # </params>
 
             if ! IsFile "${str_file1}" &> /dev/null || ( ReadFile "arr_file1_current" "${str_file1}" && IsArray "arr_file1_current" && ! AreEqualArrays "arr_file1_current" "arr_file1_contents" ); then
-                OverwriteFile "arr_file1_contents" "${str_dir1}${str_file1}" || return "$?"
+                OverwriteFile "arr_file1_contents" "${str_dir1}${str_file1}" || return 1
             fi
 
             systemctl daemon-reload || return 1
@@ -242,15 +366,15 @@
             # <remarks> Get dependencies. </remarks>
             if ! IsInstalledPackage "${str_dependencies}" &> /dev/null; then
                 echo
-                InstallPackage "${str_dependencies}" || return "$?"
+                InstallPackage "${str_dependencies}" || return 1
                 echo
             fi
 
             GetScriptDir
             echo
-            UpdateOrCloneGitRepo "${_GIT_PATH}" "${_FULL_REPO}" "${_USER_NAME}" || return "$?"
+            UpdateOrCloneGitRepo "${_GIT_PATH}" "${_FULL_REPO}" "${_USER_NAME}" || return 1
             GetScriptDir
-            cd "${_GIT_PATH}${_FULL_REPO}" || return "$?"
+            cd "${_GIT_PATH}${_FULL_REPO}" || return 1
             return 0
         }
 
@@ -310,11 +434,11 @@
             )
 
             if ! IsFile "${str_file1}" &> /dev/null || ( ReadFile "arr_file1_current" "${str_file1}" && IsArray "arr_file1_current" && ! AreEqualArrays "arr_file1_current" "arr_file1_contents" ); then
-                OverwriteFile "arr_file1_contents" "${str_dir1}${str_file1}" || return "$?"
+                OverwriteFile "arr_file1_contents" "${str_dir1}${str_file1}" || return 1
             fi
 
             if ! IsFile "${str_file2}" &> /dev/null || ( ReadFile "arr_file2_current" "${str_file2}" && IsArray "arr_file2_current" && ! AreEqualArrays "arr_file2_current" "arr_file2_contents" ); then
-                OverwriteFile "arr_file2_contents" "${str_dir2}${str_file2}" || return "$?"
+                OverwriteFile "arr_file2_contents" "${str_dir2}${str_file2}" || return 1
             fi
 
             systemctl daemon-reload || return 1
@@ -379,15 +503,15 @@
 
             if ! IsInstalledPackage "${str_dependencies}" &> /dev/null; then
                 echo
-                InstallPackage "${str_dependencies}" || return "$?"
+                InstallPackage "${str_dependencies}" || return 1
                 echo
             fi
 
             GetScriptDir
             echo
-            UpdateOrCloneGitRepo "${_GIT_PATH}" "${_FULL_REPO}" "${_USER_NAME}" || return "$?"
+            UpdateOrCloneGitRepo "${_GIT_PATH}" "${_FULL_REPO}" "${_USER_NAME}" || return 1
             GetScriptDir
-            cd "${_GIT_PATH}${_FULL_REPO}" || return "$?"
+            cd "${_GIT_PATH}${_FULL_REPO}" || return 1
             return 0
         }
 
@@ -440,7 +564,7 @@
             # </params>
 
             if ! IsFile "${str_file1}" &> /dev/null || ( ReadFile "arr_file1_current" "${str_file1}" && IsArray "arr_file1_current" && ! AreEqualArrays "arr_file1_current" "arr_file1_contents" ); then
-                OverwriteFile "arr_file1_contents" "${str_dir1}${str_file1}" || return "$?"
+                OverwriteFile "arr_file1_contents" "${str_dir1}${str_file1}" || return 1
             fi
 
             systemctl daemon-reload || return 1
@@ -455,92 +579,15 @@
     }
 
     # <summary>
-    # zramswap: Setup a swap partition in host memory.
-    # Reduce swapiness to existing host swap partition(s)/file(s), and reduce chances of memory exhaustion as host over-allocates memory.
+    # auto-Xorg: System service to find and set a valid Host boot VGA device for Xorg.
     # </summary>
-    function RAMSwapfile
+    # <remarks>
+    # References:
+    #   https://github.com/portellam/auto-Xorg
+    # </remarks>
+    function SetVideoOutput
     {
-        function Install
-        {
-            # <params>
-            local _USER_NAME="foundObjects"
-            local _REPO_NAME="zram-swap"
-            local _FULL_REPO="$_USER_NAME/$_REPO_NAME"
-            local _SCRIPT_NAME="install.sh"
-            # </params>
-
-            GetScriptDir || return "$?"
-            echo
-            UpdateOrCloneGitRepo "$_GIT_PATH" "$_FULL_REPO" "$_USER_NAME" || return "$?"
-            cd "$_GIT_PATH$_FULL_REPO" || return "$?"
-            [ -e "$_SCRIPT_NAME" ] || return "$?"
-            sudo bash "$_SCRIPT_NAME" || return 1
-            GetScriptDir || return "$?"
-            return 0
-        }
-
-        function Modify
-        {
-            # <params>
-            local str_file1="/etc/default/zram-swap"
-            local str_match_line1="_zram_fraction="
-            local var_find_zram_swap='swapon -v | grep zram'
-            local var_disable_zram_swap='swapoff /dev/zram*'
-            local var_enable_all_swap='swapon -a'
-            local var_restart_daemon='systemctl restart zram-swap'
-            declare -a arr_file_contents=( $( cat "${str_file1}" ) )
-            # </params>
-
-            # <remarks> Replace matching line with comment of line </remarks>
-            for _KEY in ${!arr_file_contents[@]}; do
-                if [[ "${arr_file_contents[$_KEY]}" == *"${str_match_line1}"* ]]; then
-                    arr_file_contents[$_KEY]="#${arr_file_contents[$_KEY]}"
-                fi
-            done
-
-            if ! IsNum "${_INT_MAX_MEMORY}"; then
-                local _OUTPUT_could_not_parse_memory="$_PREFIX_ERROR Could not parse system memory."
-                echo -e "${_OUTPUT_could_not_parse_memory}"
-                return 1
-            fi
-
-            if IsNum "${int_alloc_mem_hugepages}"; then
-                local -i int_usable_mem=$(( ( _INT_MAX_MEMORY - int_alloc_mem_hugepages ) / 2 ))
-            else
-                local -i int_usable_mem=$(( _INT_MAX_MEMORY / 2 ))
-            fi
-
-            local -i int_denominator=$( printf "%.0f" $( echo "scale=2;${_INT_MAX_MEMORY}/${int_usable_mem}" | bc ) )
-
-            # <remarks> Round down to nearest even number. </remarks>
-            if [[ $( expr $int_denominator % 2 ) -eq 1 ]]; then
-                (( int_denominator-- ))
-            fi
-
-            # <remarks> Is fraction positive non-zero and not equal to one. </remarks>
-            if [[ "${int_denominator}" -gt 1 ]]; then
-                local str_fraction="1/${int_denominator}"
-
-                arr_file_contents+=(
-                    ""
-                    "#"
-                    "# Generated by '${str_full_repo_name}'"
-                    "#"
-                    "# WARNING: Any modifications to this file will be modified by '${str_repo_name}'"
-                    "${str_match_line1}\"${str_fraction}\""
-                )
-            fi
-
-            OverwriteFile "arr_file_contents" "${str_file1}" || return "$?"
-            eval "${var_find_zram_swap}" &> /dev/null && eval "${var_disable_zram_swap}" &> /dev/null
-            eval "${var_restart_daemon}" || return "$?"
-            eval "${var_enable_all_swap}" || return "$?"
-            return 0
-        }
-
-        Install
-        Modify &> /dev/null
-        PrintPassOrFail "Allocating RAM to swap..."
-        return "$_LAST_EXIT_CODE"
+        # TODO
+        return 1
     }
 # </code>
