Relocated binaries and files.

diff --git a/vfiolib/vfiolib-files b/vfiolib/vfiolib-files
--- a/vfiolib/vfiolib-files
+++ b/vfiolib/vfiolib-files
@@ -9,171 +9,7 @@
 
 # <summary> Using </summary>
 # <code>
-    source bashlib-all
     source vfiolib-all
-# </code>
-
-# <remarks> Logic </remarks>
-# <code>
-    function GetBackups
-    {
-        if [ -z "$_APPARMOR_QEMU_BACKUP" ] \
-            || [ -z "$_CUSTOM_GRUB_FILE_BACKUP" ] \
-            || [ -z "$_INITRAMFS_MODULES_FILE_BACKUP" ] \
-            || [ -z "$_MODPROBE_BLACKLISTS_FILE_BACKUP" ] \
-            || [ -z "$_MODPROBE_VFIO_FILE_BACKUP" ] \
-            || [ -z "$_MODULES_FILE_BACKUP" ]; then
-            echo -e "An error occurred: Could not find backup files."
-            return 1
-        fi
-
-        if [ -z "$_GRUB_FILE_BACKUP_1" ]; then
-            GetBackupsForGRUB || return 1
-        fi
-
-        if [ -z "$_QEMU_FILE_BACKUP" ]; then
-            GetBackupsForQEMU || return 1
-        fi
-
-        return 0
-    }
-
-    function GetBackupsForGRUB
-    {
-        if [[ -e "$_GRUB_FILE_PATH_1" ]]; then
-            return 0
-        fi
-
-        if [[ -z "$_GRUB_FILE_PATH_2" && -z "$_GRUB_FILE_BACKUP_1" ]]; then
-            echo -e "An error occurred: Could not find GRUB source file."
-            return 1
-        fi
-
-        if [[ -z "$_GRUB_FILE_PATH_BACKUP" ]]; then
-            if ! [ sudo cp "$_GRUB_FILE_PATH_2 $_GRUB_FILE_BACKUP_1" ]; then
-                echo -e "An error occurred: Failed to backup GRUB source file."
-                return 1
-            fi
-        fi
-
-        return 0
-    }
-
-    function GetBackupsForQEMU
-    {
-        if [[ -e "$_QEMU_FILE_PATH" ]]; then
-            return 0
-        fi
-
-        if [[ -z "$_QEMU_FILE_BACKUP" ]]; then
-            echo -e "Could not find QEMU source file was not found. Attempting to download."
-
-            if ! [ command -v curl &> /dev/null ]; then
-                echo -e "An error occurred: Required command 'curl' is not installed."
-                return 1
-            fi
-
-            if ! [ curl -v "$_QEMU_FILE_URL" -o "$_QEMU_FILE_BACKUP" &> /dev/null ]; then
-                echo -e "An error occurred: Failed to backup QEMU source file."
-                return 1
-            fi
-        fi
-
-        if ! [ cp $_QEMU_FILE_BACKUP $_QEMU_FILE_PATH &> /dev/null ]; then
-            echo -e "Failed to restore QEMU backup file."
-            return 1
-        fi
-
-        return 0
-    }
-
-    function SetWorkingDirToBackupsFolder
-    {
-        if ! [ cd "$_BACKUPS_PATH" &> /dev/null ]; then
-            echo -e "An error occurred: Failed to set working directory."
-            return 1
-        fi
-
-        return 0
-    }
-
-    function CopyBackupsToPaths
-    {
-        GetBackups || return 1
-        SetBackups || return 1
-
-        if ! [ sudo cp -rv "$_APPARMOR_QEMU_BACKUP" "$_APPARMOR_QEMU_FILE_PATH" ] \
-            || [ ! sudo cp -rv "$_CUSTOM_GRUB_FILE_BACKUP" "$_CUSTOM_GRUB_FILE_PATH" ] \
-            || [ ! sudo cp -rv "$_INITRAMFS_MODULES_FILE_BACKUP" "$_INITRAMFS_MODULES_FILE_PATH" ] \
-            || [ ! sudo cp -rv "$_MODPROBE_BLACKLISTS_FILE_BACKUP" "$_MODPROBE_BLACKLISTS_FILE_PATH" ] \
-            || [ ! sudo cp -rv "$_MODPROBE_VFIO_FILE_BACKUP" "$_MODPROBE_VFIO_FILE_PATH" ] \
-            || [ ! sudo cp -rv "$_MODULES_FILE_BACKUP" "$_MODULES_FILE_PATH" ] \
-            || [ ! sudo cp -rv "$_QEMU_FILE_BACKUP" "$_QEMU_FILE_PATH" ]; then
-            echo -e "An error occurred: Failed to copy files."
-            return 1
-        fi
-
-        if ! [ sudo chown root: root "$_APPARMOR_QEMU_FILE_PATH" ] \
-            || ! [ sudo chown root: root "$_CUSTOM_GRUB_FILE_PATH" ] \
-            || ! [ sudo chown root: root "$_INITRAMFS_MODULES_FILE_PATH" ] \
-            || ! [ sudo chown root: root "$_MODPROBE_BLACKLISTS_FILE_PATH" ] \
-            || ! [ sudo chown root: root "$_MODPROBE_VFIO_FILE_PATH" ] \
-            || ! [ sudo chown root: root "$_MODULES_FILE_PATH" ] \
-            || ! [ sudo chown root: root "$_QEMU_FILE_PATH" ]; then
-            echo -e "An error occurred: Failed set permissions for files."
-            return 1
-        fi
-    }
-
-    function SetBackups
-    {
-        SetBackupsForGRUB || return 1
-        return 0
-    }
-
-    function SetBackupsForGRUB
-    {
-        if ! [ sudo cp "$_GRUB_FILE_BACKUP_1" "$_GRUB_FILE_BACKUP_2" &> /dev/null ]; then
-            echo -e "An error occurred: Failed to copy GRUB backup file."
-            return 1
-        fi
-
-        # <remarks> Overwrite target lines, lines that need to be set to defaults. </remarks>
-        local -r _LINE_GRUB_DISTRIBUTOR="GRUB_DISTRIBUTOR=\`lsb_release -i -s 2> /dev/null || echo "$( lsb_release -i -s )"\`"
-        local -r _LINE_GRUB_CMDLINE_DEFAULT="GRUB_CMDLINE_LINUX_DEFAULT=\"quiet\""
-        local -r _LINE_GRUB_CMDLINE="GRUB_CMDLINE_LINUX=\"\""
-
-        if ! [ sed -i 's/GRUB_DISTRIBUTOR=*/'"$_LINE_GRUB_DISTRIBUTOR" "$_GRUB_FILE_BACKUP_2" ] \
-            || ! [ sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=*/'"$_LINE_GRUB_CMDLINE_DEFAULT" "$_GRUB_FILE_BACKUP_2" ] \
-            || ! [ sed -i 's/GRUB_CMDLINE_LINUX=*/'"$_LINE_GRUB_CMDLINE" "$_GRUB_FILE_BACKUP_2" ]; then
-            echo -e "An error occurred: Failed to clear target lines of GRUB backup file."
-            return 1
-        fi
-
-        if ! [ -z $( grep "$_LINE_GRUB_DISTRIBUTOR" "$_GRUB_FILE_BACKUP_2" ) ] \
-            || ! [ -z $( grep "$_LINE_GRUB_DISTRIBUTOR" "$_GRUB_FILE_BACKUP_2" ) ] \
-            || ! [ -z $( grep "$_LINE_GRUB_DISTRIBUTOR" "$_GRUB_FILE_BACKUP_2" ) ]; then
-            echo -e "Failed to overwrite target lines of GRUB backup file."
-            return 1
-        fi
-
-        # <remarks> Note: this must be the second file (that is the overwritten copy) </remarks>
-        if ! [ sudo cp "$_GRUB_FILE_BACKUP_2" "$_GRUB_FILE_PATH_1" &> /dev/null ]; then
-            echo -e "Failed to restore GRUB backup file."
-            return 1
-        fi
-
-        return 0
-    }
-
-    function BackupsMain
-    {
-        SetWorkingDirToBackupsFolder || return 1
-        GetBackups || return 1
-        SetBackups || return 1
-        CopyBackupsToPaths || return 1
-        return 0
-    }
 # </code>
 
 # <params>
@@ -210,3 +46,166 @@
     declare -gr _QEMU_FILE_PATH="/etc/libvirt/qemu.conf"
     declare -gr _QEMU_FILE_URL="https://github.com/libvirt/libvirt/blob/master/src/qemu/qemu.conf.in"
 # </params>
+
+# <remarks> Logic </remarks>
+# <code>
+    function ExecuteBackups
+    {
+        SetWorkingDirToBackupsFolder || return 1
+        GetBackups || return 1
+        SetBackups || return 1
+        CopyBackupsToPaths || return 1
+        return 0
+    }
+
+    function GetBackups
+    {
+        if [ -z "$_APPARMOR_QEMU_BACKUP" ] \
+            || [ -z "$_CUSTOM_GRUB_FILE_BACKUP" ] \
+            || [ -z "$_INITRAMFS_MODULES_FILE_BACKUP" ] \
+            || [ -z "$_MODPROBE_BLACKLISTS_FILE_BACKUP" ] \
+            || [ -z "$_MODPROBE_VFIO_FILE_BACKUP" ] \
+            || [ -z "$_MODULES_FILE_BACKUP" ]; then
+            echo -e "$_PREFIX_ERROR Could not find backup files."
+            return 1
+        fi
+
+        if [ -z "$_GRUB_FILE_BACKUP_1" ]; then
+            GetBackupsForGRUB || return 1
+        fi
+
+        if [ -z "$_QEMU_FILE_BACKUP" ]; then
+            GetBackupsForQEMU || return 1
+        fi
+
+        return 0
+    }
+
+    function GetBackupsForGRUB
+    {
+        if [[ -e "$_GRUB_FILE_PATH_1" ]]; then
+            return 0
+        fi
+
+        if [[ -z "$_GRUB_FILE_PATH_2" && -z "$_GRUB_FILE_BACKUP_1" ]]; then
+            echo -e "$_PREFIX_ERROR Failed to find GRUB source file."
+            return 1
+        fi
+
+        if [[ -z "$_GRUB_FILE_PATH_BACKUP" ]]; then
+            if ! sudo cp "$_GRUB_FILE_PATH_2 $_GRUB_FILE_BACKUP_1"; then
+                echo -e "$_PREFIX_ERROR Failed to backup GRUB source file."
+                return 1
+            fi
+        fi
+
+        return 0
+    }
+
+    function GetBackupsForQEMU
+    {
+        if [[ -e "$_QEMU_FILE_PATH" ]]; then
+            return 0
+        fi
+
+        if [[ -z "$_QEMU_FILE_BACKUP" ]]; then
+            echo -e "$_PREFIX_ERROR Could not find QEMU source file. Attempting to download."
+
+            if ! [ command -v curl &> /dev/null ]; then
+                echo -e "$_PREFIX_ERROR Required command 'curl' is not installed."
+                return 1
+            fi
+
+            if ! [ curl -v "$_QEMU_FILE_URL" -o "$_QEMU_FILE_BACKUP" &> /dev/null ]; then
+                echo -e "$_PREFIX_ERROR Could not backup QEMU source file."
+                return 1
+            fi
+        fi
+
+        if ! [ sudo cp $_QEMU_FILE_BACKUP $_QEMU_FILE_PATH &> /dev/null ]; then
+            echo -e "$_PREFIX_ERROR Could not restore QEMU backup file."
+            return 1
+        fi
+
+        return 0
+    }
+
+    function SetWorkingDirToBackupsFolder
+    {
+        if ! [ cd "$_BACKUPS_PATH" &> /dev/null ]; then
+            echo -e "$_PREFIX_ERROR Could not set working directory."
+            return 1
+        fi
+
+        return 0
+    }
+
+    function CopyBackupsToPaths
+    {
+        GetBackups || return 1
+        SetBackups || return 1
+
+        if ! [ sudo cp -rv "$_APPARMOR_QEMU_BACKUP" "$_APPARMOR_QEMU_FILE_PATH" ] \
+            || [ ! sudo cp -rv "$_CUSTOM_GRUB_FILE_BACKUP" "$_CUSTOM_GRUB_FILE_PATH" ] \
+            || [ ! sudo cp -rv "$_INITRAMFS_MODULES_FILE_BACKUP" "$_INITRAMFS_MODULES_FILE_PATH" ] \
+            || [ ! sudo cp -rv "$_MODPROBE_BLACKLISTS_FILE_BACKUP" "$_MODPROBE_BLACKLISTS_FILE_PATH" ] \
+            || [ ! sudo cp -rv "$_MODPROBE_VFIO_FILE_BACKUP" "$_MODPROBE_VFIO_FILE_PATH" ] \
+            || [ ! sudo cp -rv "$_MODULES_FILE_BACKUP" "$_MODULES_FILE_PATH" ] \
+            || [ ! sudo cp -rv "$_QEMU_FILE_BACKUP" "$_QEMU_FILE_PATH" ]; then
+            echo -e "$_PREFIX_ERROR Could not copy files."
+            return 1
+        fi
+
+        if ! [ sudo chown root: root "$_APPARMOR_QEMU_FILE_PATH" ] \
+            || ! [ sudo chown root: root "$_CUSTOM_GRUB_FILE_PATH" ] \
+            || ! [ sudo chown root: root "$_INITRAMFS_MODULES_FILE_PATH" ] \
+            || ! [ sudo chown root: root "$_MODPROBE_BLACKLISTS_FILE_PATH" ] \
+            || ! [ sudo chown root: root "$_MODPROBE_VFIO_FILE_PATH" ] \
+            || ! [ sudo chown root: root "$_MODULES_FILE_PATH" ] \
+            || ! [ sudo chown root: root "$_QEMU_FILE_PATH" ]; then
+            echo -e "$_PREFIX_ERROR Could not set permissions for files."
+            return 1
+        fi
+    }
+
+    function SetBackups
+    {
+        SetBackupsForGRUB || return 1
+        return 0
+    }
+
+    function SetBackupsForGRUB
+    {
+        if ! sudo cp "$_GRUB_FILE_BACKUP_1" "$_GRUB_FILE_BACKUP_2" &> /dev/null; then
+            echo -e "$_PREFIX_ERROR Could not copy GRUB backup file."
+            return 1
+        fi
+
+        # <remarks> Overwrite target lines, lines that need to be set to defaults. </remarks>
+        local -r _LINE_GRUB_DISTRIBUTOR="GRUB_DISTRIBUTOR=\`lsb_release -i -s 2> /dev/null || echo "$( lsb_release -i -s )"\`"
+        local -r _LINE_GRUB_CMDLINE_DEFAULT="GRUB_CMDLINE_LINUX_DEFAULT=\"quiet\""
+        local -r _LINE_GRUB_CMDLINE="GRUB_CMDLINE_LINUX=\"\""
+
+        if ! [ sed -i 's/GRUB_DISTRIBUTOR=*/'"$_LINE_GRUB_DISTRIBUTOR" "$_GRUB_FILE_BACKUP_2" ] \
+            || ! [ sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=*/'"$_LINE_GRUB_CMDLINE_DEFAULT" "$_GRUB_FILE_BACKUP_2" ] \
+            || ! [ sed -i 's/GRUB_CMDLINE_LINUX=*/'"$_LINE_GRUB_CMDLINE" "$_GRUB_FILE_BACKUP_2" ]; then
+            echo -e "$_PREFIX_ERROR Could not clear target lines of GRUB backup file."
+            return 1
+        fi
+
+        if ! [ -z $( grep "$_LINE_GRUB_DISTRIBUTOR" "$_GRUB_FILE_BACKUP_2" ) ] \
+            || ! [ -z $( grep "$_LINE_GRUB_DISTRIBUTOR" "$_GRUB_FILE_BACKUP_2" ) ] \
+            || ! [ -z $( grep "$_LINE_GRUB_DISTRIBUTOR" "$_GRUB_FILE_BACKUP_2" ) ]; then
+            echo -e "$_PREFIX_ERROR Could not overwrite target lines of GRUB backup file."
+            return 1
+        fi
+
+        # <remarks> Note: this must be the second file (that is the overwritten copy) </remarks>
+        if ! [ sudo cp "$_GRUB_FILE_BACKUP_2" "$_GRUB_FILE_PATH_1" &> /dev/null ]; then
+            echo -e "$_PREFIX_ERROR Could not restore GRUB backup file."
+            return 1
+        fi
+
+        return 0
+    }
+# </code>
diff --git a/vfiolib/vfiolib-iommu b/vfiolib/vfiolib-iommu
--- a/vfiolib/vfiolib-iommu
+++ b/vfiolib/vfiolib-iommu
@@ -7,12 +7,22 @@
 # Maintainer(s):    Alex Portell <github.com/portellam>
 #
 
+# <params>
+    declare -ag _DRIVER_LISTs_VFIOPCI _PCISTUB_IOMMU_LIST _VFIOPCI_IOMMU_LIST _VGA_VFIOPCI_IOMMU_LIST _HWID_LIST_PCISTUB _HWID_LIST_VFIOPCI _HWID_LIST_VFIOPCI_with_VGA
+    declare -g bool_VFIO_has_IOMMU=false
+
+    # <remarks> Known kernel drivers to ignore; drivers that cause issues when binded to vfio-pci/pci-stub. </remarks>
+    declare -ag _DRIVER_LISTs_to_ignore=(
+        "snd_hda_intel"
+    )
+# </params>
+
 # <code>
     # <summary> Is Virtualization enabled on the current system. If true, pass. </summary>
     function IsEnabled_IOMMU
     {
         if ! compgen -G "/sys/kernel/iommu_groups/*/devices/*"; then
-            echo -e "$_PREFIX_ERROR System does not support Virtualization."
+            echo -e "$_PREFIX_FAIL System does not support Virtualization."
             return 1
         fi
     }
@@ -37,7 +47,7 @@
                 [ ${#_IOMMU_LIST[@]} -eq ${#arr_vendor_name[@]} ] || bool_are_inequal_lists=true
 
                 if $bool_are_inequal_lists; then
-                    echo -e $str_output_lists_inequal
+                    echo -e $_OUTPUT_lists_inequal
                     return 1
                 fi
 
@@ -58,7 +68,7 @@
                 IsString ${arr_vendor_name[@]} &> /dev/null || bool_is_empty_list=true
 
                 if $bool_is_empty_list; then
-                    echo -e $str_output_list_empty
+                    echo -e $_OUTPUT_list_empty
                     return 1
                 fi
 
@@ -85,7 +95,7 @@
 
                         # <remarks> If system is setup for VFIO, exit. </remarks>
                         "vfio-pci" )
-                            echo -e $str_output_is_setup_VFIO
+                            echo -e $_OUTPUT_is_setup_VFIO
                             return 1
                             ;;
                     esac
@@ -109,31 +119,31 @@
 
                     # <remarks> If parsing file and file does not exist, recursive call to parse internet. </remarks>
                     $str_opt_parse_file )
-                        str_output=$str_output_parse_file
+                        _OUTPUT=$_OUTPUT_parse_file
                         var_parse_all_ID+=" ${var_parse_args_file}"
                         var_parse_name_ID+=" ${var_parse_args_file}"
                         var_parse_slot_ID+=" ${var_parse_args_file}"
                         var_parse_quotes+=" ${var_parse_args_file}"
-                        # PrintWait "${str_output}"
+                        # PrintWait "${_OUTPUT}"
                         IsFile $str_filename_parse_IOMMU &> /dev/null
-                        return $?
+                        return "$?"
                         ;;
 
                     # <remarks> If internet is not available, exit. </remarks>
                     $str_opt_parse_internet )
-                        str_output=$str_output_parse_internet
+                        _OUTPUT=$_OUTPUT_parse_internet
                         local var_parse_all_ID+=" ${var_parse_args_online}"
                         local var_parse_name_ID+=" ${var_parse_args_online}"
                         local var_parse_slot_ID+=" ${var_parse_args_online}"
                         local var_parse_quotes+=" ${var_parse_args_online}"
-                        # PrintWait "${str_output}"
+                        # PrintWait "${_OUTPUT}"
                         GetInternetStatus &> /dev/null
-                        return $?
+                        return "$?"
                         ;;
 
-                    $str_output_parse_local | * )
-                        str_output=$str_output_parse_local
-                        # PrintWait "${str_output}"
+                    $_OUTPUT_parse_local | * )
+                        _OUTPUT=$_OUTPUT_parse_local
+                        # PrintWait "${_OUTPUT}"
                         ;;
                 esac
 
@@ -145,12 +155,12 @@
                 var_opt=$1
 
                 # <remarks> Output statements </remarks>
-                local str_output_lists_inequal="${var_prefix_error} System PCI lists' sizes are inequal."
-                local str_output_list_empty="${var_prefix_error} One or more system PCI lists are empty."
-                local str_output_parse_file="Parsing PCI from file..."
-                local str_output_parse_internet="Parsing PCI from Internet..."
-                local str_output_parse_local="Parsing PCI from system..."
-                local str_output_is_setup_VFIO="${var_prefix_error} Found existing VFIO setup."
+                local _OUTPUT_lists_inequal="$_PREFIX_FAIL System PCI lists' sizes are inequal."
+                local _OUTPUT_list_empty="$_PREFIX_FAIL One or more system PCI lists are empty."
+                local _OUTPUT_parse_file="Parsing PCI from file..."
+                local _OUTPUT_parse_internet="Parsing PCI from Internet..."
+                local _OUTPUT_parse_local="Parsing PCI from system..."
+                local _OUTPUT_is_setup_VFIO="$_PREFIX_FAIL Found existing VFIO setup."
 
                 # <remarks> Declare lists </remarks>
                 declare -ag arr_class arr_device_ID arr_device_name _DRIVER_LIST _HWID_LIST _IOMMU_LIST arr_slot_ID arr_vendor_ID arr_vendor_name
@@ -171,13 +181,13 @@
             # </params>
 
             # <remarks> Set commands for each parse type. </remarks>
-            Parse_IOMMU_Set_Operation || return $?
+            Parse_IOMMU_Set_Operation || return "$?"
 
             # <remarks> Get all devices from system. </remarks>
             declare -a arr_devices=( $( eval ${var_parse_slot_ID} | awk '{print $1}' ) )
-            Parse_IOMMU_Save_Lists || return $?
-            Parse_IOMMU_Are_Not_Empty_Lists || return $?
-            Parse_IOMMU_Are_Inequal_Lists_Sizes || return $?
+            Parse_IOMMU_Save_Lists || return "$?"
+            Parse_IOMMU_Are_Not_Empty_Lists || return "$?"
+            Parse_IOMMU_Are_Inequal_Lists_Sizes || return "$?"
 
             # <remarks> Save output to file. </remarks>
             if [[ $? -eq 0 && $var_opt != $str_opt_parse_file ]]; then
@@ -188,7 +198,7 @@
         }
 
         # <params>
-            local str_output=""
+            local _OUTPUT=""
 
             # <remarks> Set parse options </remarks>
             local str_opt_parse_file="FILE"
@@ -215,8 +225,8 @@
                 ;;
         esac
 
-        PrintPassOrFail "${str_output}"
-        return $int_exit_code
+        PrintPassOrFail "${_OUTPUT}"
+        return "$_LAST_EXIT_CODE"
     }
 
     # <summary> Select IOMMU groups for VFIO setup. </summary>
@@ -329,7 +339,7 @@
             for int_key in ${!_IOMMU_LIST[@]}; do
                 local str_slot_ID="${arr_slot_ID[$int_key]}"
                 local str_domain_ID=$( echo "${str_slot_ID}" | cut -d ':' -f 1 )
-                declare -i int_domain_ID="${str_domain_ID##*0}"
+                local -i int_domain_ID="${str_domain_ID##*0}"
                 local str_driver=""
                 local str_HWID=""
                 local var_IOMMU=""
@@ -367,7 +377,7 @@
             done
 
             if ! IsArray "_DRIVER_LISTs_VFIOPCI" &> /dev/null && ! IsArray "_DRIVER_LISTs_VFIOPCI_with_VGA" &> /dev/null && ! IsArray "_HWID_LIST_PCISTUB" &> /dev/null && ! IsArray "_HWID_LIST_VFIOPCI" &> /dev/null && ! IsArray "_DRIVER_LISTs_VFIOPCI_with_VGA" &> /dev/null; then
-                return $?
+                return "$?"
             fi
 
             return 0
@@ -404,11 +414,11 @@
 
             # NOTE: possibly breaking here, because I just revised the array functions (undeclared vars, should declare.)
 
-            TrimArray "_DRIVER_LISTs_VFIOPCI" || return $?
-            TrimArray "_DRIVER_LISTs_VFIOPCI_with_VGA" || return $?
-            TrimArray "_HWID_LIST_PCISTUB" || return $?
-            TrimArray "_HWID_LIST_VFIOPCI" || return $?
-            TrimArray "_HWID_LIST_VFIOPCI_with_VGA" || return $?
+            TrimArray "_DRIVER_LISTs_VFIOPCI" || return "$?"
+            TrimArray "_DRIVER_LISTs_VFIOPCI_with_VGA" || return "$?"
+            TrimArray "_HWID_LIST_PCISTUB" || return "$?"
+            TrimArray "_HWID_LIST_VFIOPCI" || return "$?"
+            TrimArray "_HWID_LIST_VFIOPCI_with_VGA" || return "$?"
 
             SortArray "_DRIVER_LISTs_VFIOPCI"
             SortArray "_DRIVER_LISTs_VFIOPCI_with_VGA"
@@ -427,13 +437,13 @@
         }
 
         # <params>
-        local str_output="Reviewing IOMMU groups..."
+        local _OUTPUT="Reviewing IOMMU groups..."
         local int_IOMMU_max=$( basename $( ls -1v /sys/kernel/iommu_groups/ | sort -hr | head -n1 ) )
         local var_get_IOMMU='seq 0 "${int_IOMMU_max}"'
         declare -a arr_this_IOMMU=( $( eval "${var_get_IOMMU}" ) )
         # </params>
 
-        # PrintWait "${str_output}"
+        # PrintWait "${_OUTPUT}"
 
         for var_IOMMU in ${arr_this_IOMMU[@]}; do
             local bool_IOMMU_has_external_domain=false
@@ -443,7 +453,7 @@
             local bool_IOMMU_has_VGA=false
 
             for int_key in ${!_IOMMU_LIST[@]}; do
-                declare -i int_IOMMU="${_IOMMU_LIST[$int_key]}"
+                local -i int_IOMMU="${_IOMMU_LIST[$int_key]}"
                 Select_IOMMU_Match_IOMMU_AndClass
             done
 
@@ -452,17 +462,7 @@
 
         # <remarks> Check if list is empty </remarks>
         IsArray "_VFIOPCI_IOMMU_LIST" &> /dev/null && bool_VFIO_has_IOMMU=true && Get_IOMMU_Lists && Set_IOMMU_Lists
-        PrintPassOrFail "${str_output}"
-        return $int_exit_code
+        PrintPassOrFail "${_OUTPUT}"
+        return "$_LAST_EXIT_CODE"
     }
 # </code>
-
-# <params>
-declare -ag _DRIVER_LISTs_VFIOPCI _PCISTUB_IOMMU_LIST _VFIOPCI_IOMMU_LIST _VGA_VFIOPCI_IOMMU_LIST _HWID_LIST_PCISTUB _HWID_LIST_VFIOPCI _HWID_LIST_VFIOPCI_with_VGA
-declare -g bool_VFIO_has_IOMMU=false
-
-    # <remarks> Known kernel drivers to ignore; drivers that cause issues when binded to vfio-pci/pci-stub. </remarks>
-    declare -ag _DRIVER_LISTs_to_ignore=(
-        "snd_hda_intel"
-    )
-# </params>
diff --git a/vfiolib/vfiolib-setup b/vfiolib/vfiolib-setup
--- a/vfiolib/vfiolib-setup
+++ b/vfiolib/vfiolib-setup
@@ -15,6 +15,10 @@
     source vfiolib-iommu
 # </code>
 
+# <params>
+    declare -gr _LINE_GRUB_CMDLINE="quiet iommu=1,pt amd_iommu=on intel_iommu=on video=efifb:off,vesafb:off acpi=force apm=power_off rd.driver.pre=vfio-pci pcie_aspm=off kvm.ignore_msrs=1"
+# </params>
+
 # <remarks> Logic </remarks>
 # <code>
     function ExcludeGivenVGAIOMMUGroup
@@ -68,12 +72,12 @@
 
     function ExecuteMultibootSetup
     {
-        if ! BackupsMain \
+        if ! ExecuteBackups \
             || ! GetParamsForSetup \
             || ! SetParamsForMultibootSetup \
             || ! WriteFilesForMultibootSetup \
             || ! ExecuteUpdateAfterSetup; then
-            echo -e "An error occurred: Multiboot setup has failed."
+            echo -e "$_PREFIX_FAIL Multiboot setup has failed."
             return 1
         fi
 
@@ -85,7 +89,7 @@
         local -r _PRINT_FAIL="An error occurred: Static setup has failed."
 
         if $_EXECUTE_GRUB_STATIC_SETUP \
-            && ( ! BackupsMain \
+            && ( ! ExecuteBackups \
             || ! GetParamsForSetup \
             || ! SetParamsForGRUBStaticSetup \
             || ! WriteFilesForGRUBStaticSetup \
@@ -95,7 +99,7 @@
         fi
 
         if ! $_EXECUTE_GRUB_STATIC_SETUP \
-            && ( ! BackupsMain \
+            && ( ! ExecuteBackups \
             || ! GetParamsForSetup \
             || ! SetParamsForNoGRUBStaticSetup \
             || ! WriteFilesForNoGRUBStaticSetup \
@@ -109,8 +113,8 @@
 
     function ExecuteUninstallSetup
     {
-        if ! BackupsMain || ! ExecuteUpdateAfterSetup; then
-            echo -e "An error occurred: Uninstall has failed."
+        if ! ExecuteBackups || ! ExecuteUpdateAfterSetup; then
+            echo -e "$_PREFIX_FAIL Uninstall has failed."
         fi
 
         return 0
@@ -120,7 +124,7 @@
     {
         if ! [ sudo update-grub ] \
             || ! [ sudo update-initramfs -u -k all ]; then
-            echo -e "An error occurred: Failed to update system configuration."
+            echo -e "$_PREFIX_FAIL Failed to update system configuration."
             return 1
         fi
 
@@ -134,7 +138,7 @@
                 && [[ "${_PCISTUB_HWID_LIST[@]}" -eq 0 ]] \
                 && [[ "${_VGA_VFIOPCI_DRIVER_LIST[@]}" -eq 0 ]] \
                 && [[ "${_VGA_VFIOPCI_HWID_LIST[@]}" -eq 0 ]] ); then
-            echo -e "An error occurred: Required parsed IOMMU group lists are empty."
+            echo -e "$_PREFIX_FAIL Required parsed IOMMU group lists are empty."
             return 1
         fi
 
@@ -173,11 +177,11 @@
 
         case true in
             $_EXECUTE_MULTIBOOT_SETUP )
-                ExecuteMultibootSetup || return $?
+                ExecuteMultibootSetup || return "$?"
                 ;;
 
             $_EXECUTE_STATIC_SETUP )
-                ExecuteStaticSetup || return $?
+                ExecuteStaticSetup || return "$?"
                 ;;
 
             $_EXECUTE_UNINSTALL_SETUP )
@@ -289,7 +293,7 @@
         GetParamsForVFIOSetup || return 1
 
         # <remarks> System configuration </remarks>
-        declare -ir _MAX_NUM_PARSE_KERNELS=3
+        local -ir _MAX_NUM_PARSE_KERNELS=3
         declare -ar _KERNELS_LIST=( $( ls -1 /boot/vmli* | cut -d 'z' -f 2 | sort -r | head -n $_MAX_NUM_PARSE_KERNELS ) )
         local _SYSTEM_DISK=$( df / | grep -iv 'filesystem' | cut -d '/' -f3 | cut -d ' ' -f1 )
         local _SYSTEM_DISTRO=$( lsb_release -i -s )
@@ -319,8 +323,8 @@
         _NO_VGA_HWID_DELIM="${_NO_VGA_HWID_DELIM::-1}"
         local _LINE_GRUB_CMDLINE_PREFIX=""
         _LINE_GRUB_CMDLINE_PREFIX+="$_LINE_GRUB_CMDLINE "
-        _LINE_GRUB_CMDLINE_PREFIX+="$str_output_allocate_cpu_GRUB "
-        _LINE_GRUB_CMDLINE_PREFIX+="$str_output_hugepages_GRUB "
+        _LINE_GRUB_CMDLINE_PREFIX+="$_OUTPUT_allocate_cpu_GRUB "
+        _LINE_GRUB_CMDLINE_PREFIX+="$_OUTPUT_hugepages_GRUB "
 
         # <remarks> Parse VGA VFIO IOMMU Groups. </remarks>
         for _IOMMU in ${_VGA_VFIOPCI_IOMMU_LIST[@]}; do
@@ -353,7 +357,7 @@
         done
 
         if ! [[ "${#_FILE_CONTENTS_LIST[@]}" -eq 0 ]]; then
-            echo -e "An error occurred: Multiboot setup output is empty."
+            echo -e "$_PREFIX_FAIL Multiboot setup output is empty."
             return 1
         fi
 
@@ -365,8 +369,8 @@
         IFS=$'\n'
         local _LINE_GRUB_CMDLINE_TEMP=""
         _LINE_GRUB_CMDLINE_TEMP+="$_LINE_GRUB_CMDLINE "
-        _LINE_GRUB_CMDLINE_TEMP+="$str_output_allocate_cpu_GRUB "
-        _LINE_GRUB_CMDLINE_TEMP+="$str_output_hugepages_GRUB "
+        _LINE_GRUB_CMDLINE_TEMP+="$_OUTPUT_allocate_cpu_GRUB "
+        _LINE_GRUB_CMDLINE_TEMP+="$_OUTPUT_hugepages_GRUB "
         _LINE_GRUB_CMDLINE_TEMP+="modprobe.blacklist=\"$_DRIVER_DELIM\" "
         _LINE_GRUB_CMDLINE_TEMP+="pci-stub.ids=\"$_STATIC_PCISTUB_HWID_DELIM\" "
         _LINE_GRUB_CMDLINE_TEMP+="vfio_pci.ids=\"$_HWID_DELIM\" "
@@ -381,7 +385,7 @@
             || ! [ sed -i 's/## REPLACE_THIS_LINE*/'"${_MODULES_LIST[*]}" "$_MODPROBE_VFIO_FILE_PATH" ] \
             || ! [ sed -i 's/options vfio_pci ids=*/vfio_pci_ids="'"$_HWID_DELIM\"" "$_MODPROBE_VFIO_FILE_PATH" ] \
             || ! [ sed -i 's/vfio_pci ids=*/vfio_pci_ids="'"$_HWID_DELIM\"" "$_MODULES_FILE_PATH" ]; then
-            echo -e "An error occurred: Failed to overwrite target lines of files."
+            echo -e "$_PREFIX_FAIL Failed to overwrite target lines of files."
             return 1
         fi
 
@@ -390,17 +394,17 @@
 
     function WriteFilesForNoGRUBStaticSetup
     {
-        BackupsMain || return 1
+        ExecuteBackups || return 1
         IFS=$'\n'
         local _LINE_GRUB_CMDLINE_TEMP=""
         _LINE_GRUB_CMDLINE_TEMP+="$_LINE_GRUB_CMDLINE "
-        _LINE_GRUB_CMDLINE_TEMP+="$str_output_allocate_cpu_GRUB "
-        _LINE_GRUB_CMDLINE_TEMP+="$str_output_hugepages_GRUB "
+        _LINE_GRUB_CMDLINE_TEMP+="$_OUTPUT_allocate_cpu_GRUB "
+        _LINE_GRUB_CMDLINE_TEMP+="$_OUTPUT_hugepages_GRUB "
         _LINE_GRUB_CMDLINE_TEMP="${_LINE_GRUB_CMDLINE_TEMP::-1}"
         local -r _LINE_GRUB_CMDLINE_DEFAULT="GRUB_CMDLINE_LINUX_DEFAULT=\"$_LINE_GRUB_CMDLINE_TEMP\""
 
         if ! [ sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=*/'"$_LINE_GRUB_CMDLINE_DEFAULT" "$_GRUB_FILE_PATH" ]; then
-            echo -e "An error occurred: Failed to overwrite target lines of files."
+            echo -e "$_PREFIX_FAIL Failed to overwrite target lines of files."
             return 1
         fi
 
@@ -409,18 +413,14 @@
 
     function WriteFilesForMultibootSetup
     {
-        BackupsMain || return 1
+        ExecuteBackups || return 1
         IFS=$'\n'
 
         if ! [ echo -e "${_FILE_CONTENTS_LIST[*]}" "$_CUSTOM_GRUB_FILE_PATH" ]; then
-            echo -e "An error occurred: Failed to overwrite target lines of files."
+            echo -e "$_PREFIX_FAIL Failed to overwrite target lines of files."
             return 1
         fi
 
         return 0
     }
 # </code>
-
-# <params>
-    declare -gr _LINE_GRUB_CMDLINE="quiet iommu=1,pt amd_iommu=on intel_iommu=on video=efifb:off,vesafb:off acpi=force apm=power_off rd.driver.pre=vfio-pci pcie_aspm=off kvm.ignore_msrs=1"
-# </params>
diff --git a/vfiolib/vfiolib-usage b/vfiolib/vfiolib-usage
--- a/vfiolib/vfiolib-usage
+++ b/vfiolib/vfiolib-usage
@@ -24,19 +24,19 @@
 
             # <remarks> Pre-setup: Parse IOMMU </remarks>
             "-f" | "--file" )
-                GetSelect_IOMMU_Args $2 || return $?
-                IsFile $3 || return $?
+                GetSelect_IOMMU_Args $2 || return "$?"
+                IsFile $3 || return "$?"
                 str_filename_parse_IOMMU=$3
                 bool_parse_IOMMU_from_file=true
                 ;;
 
             "-i" | "--internal" )
-                GetSelect_IOMMU_Args $2 || return $?
+                GetSelect_IOMMU_Args $2 || return "$?"
                 bool_parse_IOMMU_from_local=true
                 ;;
 
             "-o" | "--online" )
-                GetSelect_IOMMU_Args $2 || return $?
+                GetSelect_IOMMU_Args $2 || return "$?"
                 bool_parse_IOMMU_from_internet=true
                 ;;
 
@@ -50,8 +50,8 @@
                 ;;
 
             "-h" | "--hugepages" )
-                GetHugepageByteSize $2 || GetHugepageCount $2 || return $?
-                GetHugepageByteSize $3 || GetHugepageCount $3 || return $?
+                GetHugepageByteSize $2 || GetHugepageCount $2 || return "$?"
+                GetHugepageByteSize $3 || GetHugepageCount $3 || return "$?"
                 bool_hugepages=true
                 ;;
 
@@ -65,8 +65,8 @@
 
             # <remarks> Main setup </remarks>
             "-m" | "--multiboot" )
-                GetArgsForStatic_VFIO $1 || return $?
-                GetArgsForStatic_VFIO $2 || return $?
+                GetArgsForStatic_VFIO $1 || return "$?"
+                GetArgsForStatic_VFIO $2 || return "$?"
                 _EXECUTE_MULTIBOOT_SETUP=true
                 ;;
 
@@ -100,7 +100,7 @@
                 ;;
 
             "-z" | "--zram-swap" )
-                GetZramSwapSize $1 || return $?
+                GetZramSwapSize $1 || return "$?"
                 GetZramSwapOverride $2
                 bool_zram_swap=true
                 ;;
@@ -114,7 +114,7 @@
                 ;;
 
             * )
-                echo -e "${var_prefix_warn} Invalid input."
+                echo -e "${$_PREFIX_FAIL} Invalid input."
                 return 1
                 ;;
         esac; shift; done
@@ -286,7 +286,7 @@
             *"/"* )
                 ;;
             * )
-                echo -e "${var_prefix_error} Not a fraction."
+                echo -e "$_PREFIX_FAIL Not a fraction."
                 return 1
                 ;;
         esac
@@ -295,7 +295,7 @@
         local var_denominator=$( echo $1 | cut -d '/' -f2 )
 
         if ! IsNum $var_numerator || ! IsNum $var_numerator; then
-            return $?
+            return "$?"
         fi
 
         if [[ $var_numerator -lt $var_denominator ]] || [[ $var_denominator -gt 1 ]]; then
@@ -304,9 +304,9 @@
             return 0
         elif [[ $var_denominator -eq 0 ]]; then
             IsNum ""
-            return $?
+            return "$?"
         else
-             echo -e "${var_prefix_error} Invalid fraction."
+             echo -e "$_PREFIX_FAIL Invalid fraction."
         fi
 
         return 1
@@ -318,7 +318,7 @@
     {
         for var_option in $@; do
             IsString $var_option &> /dev/null || return 0
-            GetOption $var_option || return $?
+            GetOption $var_option || return "$?"
         done
 
         return 0
@@ -328,11 +328,11 @@
 # <params>
     # <remarks> Get script directories </remarks
     GetScriptDir
-    declare -g str_files_dir="$( find . -name files | uniq | head -n1 | cut -c2- )/"
+    declare -g _FILES_PATH="$( find . -name files | uniq | head -n1 | cut -c2- )/"
     declare -g str_filename_parse_IOMMU=""
 
     # <remarks> Toggles </remarks
-    declare -g bool_is_connected_to_Internet=false
+    declare -g _IS_CONNECTED_TO_INTERNET=false
 
     # <remarks> Usage toggles </remarks
     declare -g bool_alloc_cpu=false
