Brought over changes from src_auto_xorg to src_libvirt_hooks

diff --git a/deploy-vfio.d/bin/src_libvirt_hooks b/deploy-vfio.d/bin/src_libvirt_hooks
--- a/deploy-vfio.d/bin/src_libvirt_hooks
+++ b/deploy-vfio.d/bin/src_libvirt_hooks
@@ -2,7 +2,7 @@
 
 #
 # Filename:       src_libvirt_hooks
-# Description:    Logic to update and install Libvirt hooks.
+# Description:    Logic to update and install Libvirt Hooks.
 # Author(s):      Alex Portell <github.com/portellam>
 # Maintainer(s):  Alex Portell <github.com/portellam>
 #
@@ -10,9 +10,7 @@
 #
 # TODO:
 # - [ ] test.
-# - [x] develop.
 #
-
 
 #
 # sources
@@ -33,7 +31,7 @@
   #         If false, return 1.
   #         If any exception occurs, return 2.
   #
-    function does_libvirt_hooks_repo_exist
+    function src_libvirt_hooks_does_repo_exist
     {
       local -r str_repo_name="Libvirt Hooks"
       local -r str_warn="Could not determine if ${str_repo_name} repository exists."
@@ -45,7 +43,7 @@
 
       if ! is_bool "${bool_do_force_download_repo}"; then
         log_invalid_parameter "bool_do_force_download_repo"
-        log_warn "${str_warn}"
+        print_and_log_warn "${str_warn}"
         return 2
       fi
 
@@ -57,12 +55,12 @@
       local -ir int_return_code="${?}"
 
       if ! change_directory "${str_last_dir}"; then
-        log_warn "${str_warn}"
+        print_and_log_warn "${str_warn}"
         return 2
       fi
 
       if [[ "${int_return_code}" -ne 0 ]]; then
-        log_warn "${str_warn}"
+        print_and_log_warn "${str_warn}"
         return "${int_return_code}"
       fi
 
@@ -72,22 +70,34 @@
 
   #
   # DESC:   Execute Libvirt Hooks installer.
-  # $1:     the command line arguments
+  # $*:     the command line arguments as a string.
   # RETURN: If execution is successful, return 0.
   #         If false, return 1.
-    function execute_libvirt_hooks_installer
+  #
+    function src_libvirt_hooks_execute_installer
     {
-      if ! does_libvirt_hooks_repo_exist; then
+      local -r str_repo_name="Libvirt Hooks"
+      local -r str_warn="Could not execute ${str_repo_name} installer."
+
+      if ! src_libvirt_hooks_does_repo_exist "false"; then
+        print_and_log_warn "${str_warn}"
+        return 1
+      fi
+
+      local -a arr_arguments="$@"
+      local str_arguments
+
+      if ! get_delimited_string_from_array "arr_arguments" "str_arguments" " "; then
+        print_and_log_warn "${str_warn}"
         return 1
       fi
 
       if ! go_to_parent_path \
         || ! change_directory "libvirt-hooks"; then
+        print_and_log_warn "${str_warn}"
         return 2
       fi
 
-      local -r str_repo_name="Libvirt Hooks"
-      local -r str_arguments="${*}"
       log_work "Executing ${str_repo_name} installer...\n"
       sudo bash installer.bash "${str_arguments}"
 
@@ -96,7 +106,7 @@
       echo
 
       if [[ "${int_code}" -ne 0 ]]; then
-        print_and_log_warn "Could not execute ${str_repo_name} installer."
+        print_and_log_warn "${str_warn}"
         return "${int_code}"
       fi
 
@@ -105,22 +115,130 @@
     }
 
   #
-  # DESC:   Install Libvirt Hooks.
+  # DESC:   Install of Libvirt Hooks.
+  # $*:     the command line arguments as a string.
   # RETURN: If install is successful, return 0.
   #         If false, return 1.
   #
-    function install_libvirt_hooks
+    function src_libvirt_hooks_install
     {
+      local -r str_arguments="${*}"
       local -r str_repo_name="Libvirt Hooks"
 
       print_and_log_work "Installing ${str_repo_name}..."
 
-      if ! execute_libvirt_hooks_installer "--install"; then
+      if ! src_libvirt_hooks_execute_installer "--install ${str_arguments}"; then
         print_and_log_fail "Could not install ${str_repo_name}."
         return 1
       fi
 
-      print_and_log_pass "Installed ${str_repo_name}."
+      print_and_log_pass "Installed ${str_repo_name}"
+      return 0
+    }
+
+  #
+  # DESC:   Prompt to install Libvirt Hooks.
+  # $*:     the command line arguments as a string.
+  # RETURN: If uninstall is successful, return 0.
+  #         If uninstall has failed, return 1.
+  #         If uninstall is skipped, return 2.
+  #
+    function src_libvirt_hooks_install_prompt
+    {
+      local -r str_repo_name="Libvirt Hooks"
+
+      if ! ask_yes_no_question "Install ${str_repo_name}?"; then
+        print_and_log_output "Skipped install of ${str_repo_name}."
+        return 2
+      fi
+
+      if ! src_libvirt_hooks_install "${str_arguments}"; then
+        return 1
+      fi
+
+      return 0
+    }
+
+  #
+  # DESC:   Main execution.
+  # $1:     do skip.
+  # $2:     do force install.
+  # $3:     do force uninstall.
+  # $3:     do force update.
+  # RETURN: If successful, return 0.
+  #         If not, return 1.
+  #         If any exceptions occur, return 2.
+  #
+    function src_libvirt_hooks_main
+    {
+      local -r str_repo_name="Libvirt Hooks"
+      local -r bool_do_force_update="${4}"
+
+      if ! is_bool "${bool_do_force_update}"; then
+        log_invalid_parameter "bool_do_force_update"
+        return 2
+      fi
+
+      local -r bool_do_force_uninstall="${3}"
+
+      if ! is_bool "${bool_do_force_uninstall}"; then
+        log_invalid_parameter "bool_do_force_uninstall"
+        return 2
+      fi
+
+      local -r bool_do_force_install="${2}"
+
+      if ! is_bool "${bool_do_force_install}l"; then
+        log_invalid_parameter "bool_do_force_install"
+        return 2
+      fi
+
+      local -r bool_do_force_skip="${1}"
+
+      if ! is_bool "${bool_do_force_skip}"; then
+        log_invalid_parameter "bool_do_force_skip"
+        return 2
+      fi
+
+      if "${bool_do_force_skip}"; then
+        print_and_log_output "Skipped ${str_repo_name}."
+        return 0
+      fi
+
+      if "${bool_do_force_update}"; then
+        if ! src_libvirt_hooks_does_repo_exist "true"; then
+          return 1
+        fi
+      fi
+
+      if "${bool_do_force_install}"; then
+        if ! src_libvirt_hooks_install; then
+          return 1
+        fi
+
+        return 0
+      fi
+
+      if "${bool_do_force_uninstall}"; then
+        if ! src_libvirt_hooks_uninstall; then
+          return 1
+        fi
+
+        return 0
+      fi
+
+      if ! src_libvirt_hooks_does_repo_exist "false"; then
+        return 1
+      fi
+
+      if ! src_libvirt_hooks_install_prompt "${str_arguments}"; then
+        return 1
+      fi
+
+      if ! src_libvirt_hooks_uninstall_prompt; then
+        return 1
+      fi
+
       return 0
     }
 
@@ -129,17 +247,39 @@
   # RETURN: If uninstall is successful, return 0.
   #         If false, return 1.
   #
-    function uninstall_libvirt_hooks
+    function src_libvirt_hooks_uninstall
     {
       local -r str_repo_name="Libvirt Hooks"
 
       print_and_log_work "Uninstalling ${str_repo_name}..."
 
-      if ! execute_libvirt_hooks_installer "--uninstall"; then
+      if ! src_libvirt_hooks_execute_installer "--uninstall"; then
         print_and_log_fail "Could not uninstall ${str_repo_name}."
         return 1
       fi
 
       print_and_log_pass "Uninstalled ${str_repo_name}"
+      return 0
+    }
+
+  #
+  # DESC:   Prompt to uninstall Libvirt Hooks.
+  # RETURN: If uninstall is successful, return 0.
+  #         If uninstall has failed, return 1.
+  #         If uninstall is skipped, return 2.
+  #
+    function src_libvirt_hooks_uninstall_prompt
+    {
+      local -r str_repo_name="Libvirt Hooks"
+
+      if ! ask_yes_no_question "Uninstall ${str_repo_name}?"; then
+        print_and_log_output "Skipped uninstall of ${str_repo_name}."
+        return 2
+      fi
+
+      if ! src_libvirt_hooks_uninstall; then
+        return 1
+      fi
+
       return 0
     }
