Brought over changes from src_auto_xorg to src_looking_glass.

diff --git a/deploy-vfio.d/bin/src_looking_glass b/deploy-vfio.d/bin/src_looking_glass
--- a/deploy-vfio.d/bin/src_looking_glass
+++ b/deploy-vfio.d/bin/src_looking_glass
@@ -9,10 +9,9 @@
 
 #
 # TODO:
-# - [ ] develop.
 # - [ ] test.
+# - [ ] develop.
 #
-
 
 #
 # sources
@@ -22,7 +21,6 @@
 
   source "${SRC_STR_SCRIPT_BIN_DIR}src_print"
   source "${SRC_STR_SCRIPT_BIN_DIR}src_git"
-  source "${SRC_STR_SCRIPT_BIN_DIR}src_compatibility"
 
 #
 # logic
@@ -32,7 +30,7 @@
   # RETURN: If dependencies are installed, return 0.
   #         If false, return 1.
   #
-    function are_looking_glass_dependencies_installed
+    function src_looking_glass_are_dependencies_installed
     {
       local -r str_pass="Installed required build dependencies."
 
@@ -80,12 +78,56 @@
     }
 
   #
+  # DESC:   Checks if git repo exists.
+  # $1:     do force download repo.
+  # RETURN: If repo exists, return 0.
+  #         If false, return 1.
+  #         If any exception occurs, return 2.
+  #
+    function src_looking_glass_does_repo_exist
+    {
+      local -r str_repo_name="Looking Glass"
+      local -r str_warn="Could not determine if ${str_repo_name} repository exists."
+
+      log_work "Determining if ${str_repo_name} repository exists..."
+
+      local -r str_last_dir="$( pwd )"
+      local -r bool_do_force_download="${1}"
+
+      if ! is_bool "${bool_do_force_download_repo}"; then
+        log_invalid_parameter "bool_do_force_download_repo"
+        print_and_log_warn "${str_warn}"
+        return 2
+      fi
+
+      does_this_git_repo_exist \
+        "${str_repo_name}" \
+        "github.com/gnif/LookingGlass" \
+        "${bool_do_force_download}"
+
+      local -ir int_return_code="${?}"
+
+      if ! change_directory "${str_last_dir}"; then
+        print_and_log_warn "${str_warn}"
+        return 2
+      fi
+
+      if [[ "${int_return_code}" -ne 0 ]]; then
+        print_and_log_warn "${str_warn}"
+        return "${int_return_code}"
+      fi
+
+      log_pass "${str_repo_name} repository exists."
+      return 0
+    }
+
+  #
   # DESC:   Execute cmake. If any dependency fails, disable and try again.
   # $1:     the argument for cmake as a string
   # RETURN: If cmake execute, return 0.
   #         If false, return 1.
   #
-    function execute_cmake
+    function src_looking_glass_execute_cmake
     {
       local -r str_pass="Execute 'cmake' successful."
       local -r str_warn="Execute 'cmake' failed."
@@ -172,74 +214,73 @@
     }
 
   #
-  # DESC:   Checks if git repo exists.
-  # $1:     do force download repo.
-  # RETURN: If repo exists, return 0.
+  # DESC:   Execute Looking Glass installer.
+  # $*:     the command line arguments as a string.
+  # RETURN: If execution is successful, return 0.
   #         If false, return 1.
-  #         If any exception occurs, return 2.
   #
-    function does_looking_glass_repo_exist
+    function src_looking_glass_execute_installer
     {
       local -r str_repo_name="Looking Glass"
-      local -r str_warn="Could not determine if ${str_repo_name} repository exists."
+      local -r str_warn="Could not execute ${str_repo_name} installer."
 
-      log_work "Determining if ${str_repo_name} repository exists..."
+      if ! src_looking_glass_does_repo_exist "false"; then
+        print_and_log_warn "${str_warn}"
+        return 1
+      fi
 
-      local -r str_last_dir="$( pwd )"
-      local -r bool_do_force_download="${1}"
+      local -a arr_arguments="$@"
+      local str_arguments
 
-      if ! is_bool "${bool_do_force_download_repo}"; then
-        log_invalid_parameter "bool_do_force_download_repo"
+      if ! get_delimited_string_from_array "arr_arguments" "str_arguments" " "; then
+        print_and_log_warn "${str_warn}"
+        return 1
+      fi
+
+      if ! go_to_parent_path \
+        || ! change_directory "looking-glass"; then
         print_and_log_warn "${str_warn}"
         return 2
       fi
 
-      does_this_git_repo_exist \
-        "${str_repo_name}" \
-        "github.com/gnif/LookingGlass" \
-        "${bool_do_force_download}"
+      log_work "Executing ${str_repo_name} installer...\n"
+      sudo bash installer.bash "${str_arguments}"
 
-      local -ir int_return_code="${?}"
+      local -i int_code="${?}"
 
-      if ! change_directory "${str_last_dir}"; then
+      echo
+
+      if [[ "${int_code}" -ne 0 ]]; then
         print_and_log_warn "${str_warn}"
-        return 2
+        return "${int_code}"
       fi
 
-      if [[ "${int_return_code}" -ne 0 ]]; then
-        print_and_log_warn "${str_warn}"
-        return "${int_return_code}"
-      fi
-
-      log_pass "${str_repo_name} repository exists."
+      log_pass "Executed ${str_repo_name} installer."
       return 0
     }
 
   #
-  # DESC:   Install Looking Glass.
+  # DESC:   Install of Looking Glass.
   # RETURN: If install is successful, return 0.
   #         If false, return 1.
-  #         If any exceptions occur, return 2.
   #
-    function install_looking_glass
+    function src_looking_glass_install
     {
       local -r str_repo_name="Looking Glass"
-      local -r str_fail="Could not install ${str_repo_name}."
+      local -r str_warn="Could not install ${str_repo_name}."
 
-      print_and_log_work "Installing ${str_repo_name}..."
-
-      local -r str_arguments="${*}"
-
-      if ! does_looking_glass_repo_exist; then
-        print_and_log_fail "${str_fail}"
-        return 2
+      if ! src_looking_glass_does_repo_exist "false"; then
+        print_and_log_warn "${str_warn}"
+        return 1
       fi
 
       if ! go_to_parent_path \
         || ! change_directory "LookingGlass"; then
-        print_and_log_fail "${str_fail}"
+        print_and_log_warn "${str_warn}"
         return 2
       fi
+
+      print_and_log_work "Installing ${str_repo_name}..."
 
       local -r str_build_dir="client/build"
 
@@ -283,6 +324,158 @@
 
       print_and_log_output "For usage on how to run ${str_repo_name}, execute: " \
         "'looking-glass-client --help"
+
+      return 0
+
+      print_and_log_pass "Installed ${str_repo_name}"
+      return 0
+    }
+
+  #
+  # DESC:   Prompt to install Looking Glass.
+  # RETURN: If uninstall is successful, return 0.
+  #         If uninstall has failed, return 1.
+  #         If uninstall is skipped, return 2.
+  #
+    function src_looking_glass_install_prompt
+    {
+      local -r str_repo_name="Looking Glass"
+
+      if ! ask_yes_no_question "Install ${str_repo_name}?"; then
+        print_and_log_output "Skipped install of ${str_repo_name}."
+        return 2
+      fi
+
+      if ! src_looking_glass_install; then
+        return 1
+      fi
+
+      return 0
+    }
+
+  #
+  # DESC:   Main execution.
+  # $1:     do skip.
+  # $2:     do force install.
+  # $3:     do force uninstall.
+  # $3:     do force update.
+  # RETURN: If successful, return 0.
+  #         If not, return 1.
+  #         If any exceptions occur, return 2.
+  #
+    function src_looking_glass_main
+    {
+      local -r str_repo_name="Looking Glass"
+      local -r bool_do_force_update="${4}"
+
+      if ! is_bool "${bool_do_force_update}"; then
+        log_invalid_parameter "bool_do_force_update"
+        return 2
+      fi
+
+      local -r bool_do_force_uninstall="${3}"
+
+      if ! is_bool "${bool_do_force_uninstall}"; then
+        log_invalid_parameter "bool_do_force_uninstall"
+        return 2
+      fi
+
+      local -r bool_do_force_install="${2}"
+
+      if ! is_bool "${bool_do_force_install}l"; then
+        log_invalid_parameter "bool_do_force_install"
+        return 2
+      fi
+
+      local -r bool_do_force_skip="${1}"
+
+      if ! is_bool "${bool_do_force_skip}"; then
+        log_invalid_parameter "bool_do_force_skip"
+        return 2
+      fi
+
+      if "${bool_do_force_skip}"; then
+        print_and_log_output "Skipped ${str_repo_name}."
+        return 0
+      fi
+
+      if "${bool_do_force_update}"; then
+        if ! src_looking_glass_does_repo_exist "true"; then
+          return 1
+        fi
+      fi
+
+      if "${bool_do_force_install}"; then
+        if ! src_looking_glass_install; then
+          return 1
+        fi
+
+        return 0
+      fi
+
+      if "${bool_do_force_uninstall}"; then
+        if ! src_looking_glass_uninstall; then
+          return 1
+        fi
+
+        return 0
+      fi
+
+      if ! src_looking_glass_does_repo_exist "false"; then
+        return 1
+      fi
+
+      if ! src_looking_glass_install_prompt "${str_arguments}"; then
+        return 1
+      fi
+
+      if ! src_looking_glass_uninstall_prompt; then
+        return 1
+      fi
+
+      return 0
+    }
+
+  # TODO: develop!
+  #
+  # DESC:   Uninstall Looking Glass.
+  # RETURN: If uninstall is successful, return 0.
+  #         If false, return 1.
+  #
+    function src_looking_glass_uninstall
+    {
+      return 1
+      local -r str_repo_name="Looking Glass"
+
+      print_and_log_work "Uninstalling ${str_repo_name}..."
+
+      if false; then
+        print_and_log_fail "Could not uninstall ${str_repo_name}."
+        return 1
+      fi
+
+      print_and_log_pass "Uninstalled ${str_repo_name}"
+      return 0
+    }
+
+  #
+  # DESC:   Prompt to uninstall Looking Glass.
+  # RETURN: If uninstall is successful, return 0.
+  #         If uninstall has failed, return 1.
+  #         If uninstall is skipped, return 2.
+  #
+    function src_looking_glass_uninstall_prompt
+    {
+      local -r str_repo_name="Looking Glass"
+
+      if ! ask_yes_no_question "Uninstall ${str_repo_name}?"; then
+        print_and_log_output "Skipped uninstall of ${str_repo_name}."
+        return 2
+      fi
+
+      if ! src_looking_glass_uninstall; then
+        return 1
+      fi
 
       return 0
     }
