Update src_test_file

diff --git a/deploy-vfio.d/bin/src_test_file b/deploy-vfio.d/bin/src_test_file
--- a/deploy-vfio.d/bin/src_test_file
+++ b/deploy-vfio.d/bin/src_test_file
@@ -8,6 +8,19 @@
 #
 
 #
+# NOTES:
+# - to concatonate strings across multiple lines, "re-declare" the string and use '+='
+#   - example:    str_name="the_string_value_on_line1"
+#                 str_name+="line2"
+#   - the prior written way will not work: str_name="the_string_value_on_line1"\
+#                                                   "line2"
+# - print formatting:
+#   - added work output
+#
+#
+
+
+#
 # sets
 #
   #set -e    # stop script on external program returns non-zero code.
@@ -43,19 +56,27 @@
   #
   # DESC:   prompt prefixes
   #
-    STR_PREFIX_PROMPT="${STR_SCRIPT_NAME}: "
+    declare -gr SRC_PRINT_STR_PREFIX_PROMPT="${STR_SCRIPT_NAME}: "
 
-    STR_PREFIX_ERROR="${STR_PREFIX_PROMPT}${STR_SET_COLOR_YELLOW}An error occurred: "
-    STR_PREFIX_ERROR+="${STR_RESET_COLOR} "
+    declare -g SRC_PRINT_STR_PREFIX_ERROR="${SRC_PRINT_STR_PREFIX_PROMPT}"
+    SRC_PRINT_STR_PREFIX_ERROR+="${STR_SET_COLOR_YELLOW}An error occurred: "
+    declare -r SRC_PRINT_STR_PREFIX_ERROR+="${SRC_PRINT_STR_RESET_COLOR} "
 
-    STR_PREFIX_FAIL="${STR_PREFIX_PROMPT}${STR_SET_COLOR_RED}Failure:"
-    STR_PREFIX_FAIL+="${STR_RESET_COLOR} "
+    declare -g SRC_PRINT_STR_PREFIX_FAIL="${SRC_PRINT_STR_PREFIX_PROMPT}"
+    SRC_PRINT_STR_PREFIX_FAIL+="${STR_SET_COLOR_RED}Failure: "
+    declare -r SRC_PRINT_STR_PREFIX_FAIL+="${SRC_PRINT_STR_RESET_COLOR} "
 
-    STR_PREFIX_PASS="${STR_PREFIX_PROMPT}${STR_SET_COLOR_GREEN}Success:"
-    STR_PREFIX_PASS+="${STR_RESET_COLOR} "
+    declare -g SRC_PRINT_STR_PREFIX_PASS="${SRC_PRINT_STR_PREFIX_PROMPT}"
+    SRC_PRINT_STR_PREFIX_PASS+="${STR_SET_COLOR_GREEN}Success: "
+    declare -r SRC_PRINT_STR_PREFIX_PASS+="${SRC_PRINT_STR_RESET_COLOR} "
 
-    STR_PREFIX_SKIP="${STR_PREFIX_PROMPT}${STR_SET_COLOR_YELLOW}Skipped:"
-    STR_PREFIX_FAIL+="${STR_RESET_COLOR} "
+    declare -g SRC_PRINT_STR_PREFIX_SKIP="${SRC_PRINT_STR_PREFIX_PROMPT}"
+    SRC_PRINT_STR_PREFIX_SKIP+="${STR_SET_COLOR_YELLOW}Skipped: "
+    declare -r SRC_PRINT_STR_PREFIX_SKIP+="${SRC_PRINT_STR_RESET_COLOR} "
+
+    declare -g SRC_PRINT_STR_PREFIX_WORK="${SRC_PRINT_STR_PREFIX_PROMPT}"
+    SRC_PRINT_STR_PREFIX_WORK+="${STR_SET_COLOR_YELLOW}Working: "
+    declare -r SRC_PRINT_STR_PREFIX_WORK+="${SRC_PRINT_STR_RESET_COLOR} "
 
 #
 # datatype logic
@@ -80,51 +101,6 @@
       fi
 
       print_output_to_log "Valid bool."
-      return 0
-    }
-
-  #
-  # DESC:   Is input an integer.
-  # $1:     the input as an int.
-  # RETURN: If true, return 0.
-  #         If false, return 1.
-  #         If an exception occurs, return 2.
-  #
-    function is_int
-    {
-      if  ! is_string "${1}"; then
-        return 2
-      fi
-
-      if  ! [[ "${1}" =~ ^[0-9]+$ ]] \
-        && ! [[ "${1}" =~ ^[-][0-9]+$ ]]; then
-        print_error_to_log "Invalid integer."
-        return 1
-      fi
-
-      print_output_to_log "Valid integer."
-      return 0
-    }
-
-  #
-  # DESC:   Is input variable a reference.
-  # $1:     the input as a string.
-  # RETURN: If true, return 0.
-  #         If false, return 1.
-  #         If an exception occurs, return 2.
-  #
-    function is_reference
-    {
-      if  ! is_variable "${1}"; then
-        return 2
-      fi
-
-      if  [[ $( declare -p "${1}" 2>/dev/null ) != *"-n"* ]]; then
-        print_error_to_log "Variable is not a reference."
-        return 1
-      fi
-
-      print_output_to_log "Variable is a reference."
       return 0
     }
 
@@ -159,11 +135,13 @@
     {
       local str_output=""
 
-      if ! is_string "${1}"; then
+      if is_string "${1}" &> /dev/null; then                                          # NOTE: added mute because called function is changed.
         str_output="${1} "
       fi
 
-      for int_count in $( seq 0 2 ); do
+      local -i int_max_tries=2
+
+      for int_count in $( seq 0 "${int_max_tries}" ); do
         local str_answer=""
         echo -en "${str_output}[Y/n]: "
         read -r -p "" str_answer
@@ -176,11 +154,11 @@
             return 255 ;;
 
           * )
-            echo "Please answer 'Y' or 'N'." ;;
+            echo "Invalid answer. Please answer 'Y' or 'N'." ;;
         esac
       done
 
-      echo "Invalid answer."
+      echo "Exceeded number of tries."
       return 1
     }
 
@@ -196,12 +174,14 @@
   #
     function do_ping_address
     {
-      local -r str_log="Pinging..."
+      print_output_to_log "$0: $FUNCNAME"
+
+      local -r str_log="Pinging address."
       local -r str_address="${1}"
 
-      print_output_to_log "${str_log}"
+      print_work_to_log "${str_log}"
 
-      if  ! is_string "${str_address}"; then
+      if  ! is_string "${str_address}" &> /dev/null; then
         print_fail_to_log "${str_log}"
         return 2
       fi
@@ -225,9 +205,9 @@
   #
     function do_ping_internet
     {
-      local -r str_log="Checking connection to Internet..."
+      local -r str_log="Checking connection to Internet."
 
-      print_output_to_log "${str_log}"
+      print_work_to_log "${str_log}"
 
       if  ! do_ping_address "8.8.8.8" \
         && ! do_ping_address "8.8.4.4"; then
@@ -254,12 +234,12 @@
   #
     function is_connected_to_internet
     {
-      local -r str_log="Conntecting to Internet..."
+      local -r str_log="Conntecting to Internet."
       local bool_do_ignore="${1}"
 
-      print_output_to_log "${str_log}"
+      print_work_to_log "${str_log}"
 
-      if  ! is_bool "${bool_do_ignore}"; then
+      if  ! is_bool "${bool_do_ignore}" &> /dev/null; then
         print_fail_to_log "${str_log}"
         return 2
       fi
@@ -341,5 +321,17 @@
     {
       local -ir int_return_code="${?}"
       echo -e "${STR_PREFIX_SKIP}${1}" >&1
+      return "${int_return_code}"
+    }
+
+  #
+  # DESC:   Print working.
+  # $1:     line of text as a string.
+  # RETURN: Always return code from previous scope.
+  #
+    function print_work_to_log
+    {
+      local -ir int_return_code="${?}"
+      echo -e "${STR_PREFIX_WORK}${1}" >&1
       return "${int_return_code}"
     }
