Updated hooks.

diff --git a/etc/cfscpu b/etc/cfscpu
--- a/etc/cfscpu
+++ b/etc/cfscpu
@@ -24,43 +24,43 @@
 # </remarks>
 
 # <remarks> Ranges from 20 (lowest priority) to -20 (highest priority). </remarks>
-_TARGET_NICE="-1"
-_DOMAIN_NAME="$1"
-_HOOK_NAME="cfscpu"
-_PREFIX_PROMPT="libvirt-qemu $_HOOK_NAME:"
+TARGET_NICE="-1"
+DOMAIN_NAME="$1"
+HOOK_NAME="cfscpu"
+PREFIX_PROMPT="libvirt-qemu $HOOK_NAME:"
 
-function Get_vCPU_Path
+function GetVCPUPath
 {
-    if ls /sys/fs/cgroup/cpu/machine.slice/machine-qemu*$_DOMAIN_NAME.scope/libvirt/vcpu* 1> /dev/null 2>&1; then
-        echo "$_PREFIX_PROMPT Found vCPU paths in Libvirt subdirectory." > /dev/kmsg
-        _VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/machine-qemu*$_DOMAIN_NAME.scope/libvirt/vcpu*"
+    if ls /sys/fs/cgroup/cpu/machine.slice/machine-qemu*$DOMAIN_NAME.scope/libvirt/vcpu* 1> /dev/null 2>&1; then
+        echo "$PREFIX_PROMPT Found vCPU paths in Libvirt subdirectory." > /dev/kmsg
+        VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/machine-qemu*$DOMAIN_NAME.scope/libvirt/vcpu*"
     else
-        echo "$_PREFIX_PROMPT Failed to find vCPU paths in Libvirt subdirectory. Found vCPU directory." > /dev/kmsg
-        _VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/machine-qemu*$_DOMAIN_NAME.scope/vcpu*"
+        echo "$PREFIX_PROMPT Failed to find vCPU paths in Libvirt subdirectory. Found vCPU directory." > /dev/kmsg
+        VCPU_PATH="/sys/fs/cgroup/cpu/machine.slice/machine-qemu*$DOMAIN_NAME.scope/vcpu*"
     fi
 
     return 0
 }
 
-function Prioritize_vCPU_ForDomain
+function PrioritizeVCPUForDomain
 {
     if ! SetNiceLevelForDomain; then
-        echo "$_PREFIX_PROMPT Failed to prioritize vCPU threads of Libvirt domain '$_DOMAIN_NAME'" > /dev/kmsg
+        echo "$PREFIX_PROMPT Failed to prioritize vCPU threads of Libvirt domain '$DOMAIN_NAME'" > /dev/kmsg
         return 1
     fi
 
-    echo "$_PREFIX_PROMPT Prioritized vCPU threads of Libvirt domain '$_DOMAIN_NAME'" > /dev/kmsg
+    echo "$PREFIX_PROMPT Prioritized vCPU threads of Libvirt domain '$DOMAIN_NAME'" > /dev/kmsg
     return 0
 }
 
 function SetNiceLevelForDomain
 {
-    for _VCPU_GROUP in $_VCPU_PATH; do
-        echo "$_PREFIX_PROMPT Setting nice level of $_TARGET_NICE to vCPU group '$( basename $_VCPU_GROUP ).'" > /dev/kmsg
+    for VCPU_GROUP in $VCPU_PATH; do
+        echo "$PREFIX_PROMPT Setting nice level of $TARGET_NICE to vCPU group '$( basename $VCPU_GROUP ).'" > /dev/kmsg
 
-        for _PID in $( cat $_VCPU_GROUP/tasks ); do
-            if ! renice -n "$_TARGET_NICE" -p "$_PID" 2> /dev/null; then
-                echo "$_PREFIX_PROMPT An error occured: Failed to set nice level for PID '$_PID'"
+        for PID in $( cat $VCPU_GROUP/tasks ); do
+            if ! renice -n "$TARGET_NICE" -p "$PID" 2> /dev/null; then
+                echo "$PREFIX_PROMPT An error occured: Failed to set nice level for PID '$PID'"
                 return 1
             fi
         done
@@ -69,7 +69,7 @@ function SetNiceLevelForDomain
     return 0
 }
 
-if [[ ! -z "$_DOMAIN" ]]; then
-    Get_vCPU_Path
-    Prioritize_vCPU_ForDomain
+if [[ ! -z "$DOMAIN_NAME" ]]; then
+    GetVCPUPath
+    PrioritizeVCPUForDomain
 fi
diff --git a/etc/ddcutil b/etc/ddcutil
--- a/etc/ddcutil
+++ b/etc/ddcutil
@@ -19,28 +19,28 @@
 # Make sure you specify the right settings for your setup below or it won't work.
 # </remarks>
 
-_HOOK_NAME="ddcutil"
-_PREFIX_PROMPT="libvirt-qemu $_HOOK_NAME:"
-_OPERATION="$2"
-_SUBOPERATION="$3"
+HOOK_NAME="ddcutil"
+PREFIX_PROMPT="libvirt-qemu $HOOK_NAME:"
+OPERATION="$2"
+SUBOPERATION="$3"
 
 # <remarks> The display shown in `ddcutil detect` </remarks>
-_DOMAIN_DISPLAY="0"
+DOMAIN_DISPLAY="0"
 
 # <remarks> Video input values (without 0x, but with leading zeroes, if any. See `ddcutil capabilities`) </remarks>
-_DOMAIN_VIDEO_INPUT="12"
-_HOST_VIDEO_INPUT="0f"
-_VIDEO_INPUT=""
+DOMAIN_VIDEO_INPUT="12"
+HOST_VIDEO_INPUT="0f"
+VIDEO_INPUT=""
 
 function GetVideoInput
 {
-	case "$_OPERATION/$_SUBOPERATION" in
+	case "$OPERATION/$SUBOPERATION" in
 		"started/begin" )
-			_VIDEO_INPUT="$_DOMAIN_VIDEO_INPUT"
+			VIDEO_INPUT="$DOMAIN_VIDEO_INPUT"
 			return 0 ;;
 
 		"stopped/end" )
-			_VIDEO_INPUT="$_HOST_VIDEO_INPUT"
+			VIDEO_INPUT="$HOST_VIDEO_INPUT"
 			return 0 ;;
 	esac
 
@@ -49,12 +49,12 @@ function GetVideoInput
 
 function SetVideoOutput
 {
-    if [[ "$( ddcutil -d "$_DOMAIN_DISPLAY" getvcp 60 --terse | awk '{print $4}' )" == "x$_VIDEO_INPUT" ]]; then
+    if [[ "$( ddcutil -d "$DOMAIN_DISPLAY" getvcp 60 --terse | awk '{print $4}' )" == "x$VIDEO_INPUT" ]]; then
         return 0
     fi
 
-	if ! ddcutil -d "$_DOMAIN_DISPLAY" setvcp 60 "0x$_VIDEO_INPUT"; then
-        echo "$_PREFIX_PROMPT An error occured: Failed to switch video input."
+	if ! ddcutil -d "$DOMAIN_DISPLAY" setvcp 60 "0x$VIDEO_INPUT"; then
+        echo "$PREFIX_PROMPT An error occured: Failed to switch video input."
 		return 1
 	fi
 
diff --git a/etc/nosleep b/etc/nosleep
--- a/etc/nosleep
+++ b/etc/nosleep
@@ -8,34 +8,34 @@
 # Maintainer(s):    Alex Portell <github.com/portellam>
 #
 
-_HOOK_NAME="nosleep"
-_PREFIX_PROMPT="libvirt-qemu $_HOOK_NAME:"
-_DOMAIN_NAME="$1"
-_OPERATION="$2"
+HOOK_NAME="nosleep"
+PREFIX_PROMPT="libvirt-qemu $HOOK_NAME:"
+DOMAIN_NAME="$1"
+OPERATION="$2"
 
 function StartNosleepService
 {
-    if ! systemctl start libvirt-nosleep@"$_DOMAIN_NAME" &> /dev/null; then
-        echo "$_PREFIX_PROMPT An error occured: Failed to start Nosleep service for Libvirt domain '$_DOMAIN_NAME'." >&2
+    if ! systemctl start libvirt-nosleep@"$DOMAIN_NAME" &> /dev/null; then
+        echo "$PREFIX_PROMPT An error occured: Failed to start Nosleep service for Libvirt domain '$DOMAIN_NAME'." >&2
         return 1
     fi
 
-    echo "$_PREFIX_PROMPT Started Nosleep service for Libvirt domain '$_DOMAIN_NAME'."
+    echo "$PREFIX_PROMPT Started Nosleep service for Libvirt domain '$DOMAIN_NAME'."
     return 0
 }
 
 function StopNosleepService
 {
-    if ! systemctl stop libvirt-nosleep@"$_DOMAIN_NAME" &> /dev/null; then
-        echo "$_PREFIX_PROMPT An error occured: Failed to stop Nosleep service for Libvirt domain '$_DOMAIN_NAME'." >&2
+    if ! systemctl stop libvirt-nosleep@"$DOMAIN_NAME" &> /dev/null; then
+        echo "$PREFIX_PROMPT An error occured: Failed to stop Nosleep service for Libvirt domain '$DOMAIN_NAME'." >&2
         return 1
     fi
 
-    echo "$_PREFIX_PROMPT Stopped Nosleep service for Libvirt domain '$_DOMAIN_NAME'."
+    echo "$PREFIX_PROMPT Stopped Nosleep service for Libvirt domain '$DOMAIN_NAME'."
     return 0
 }
 
-case "$_OPERATION" in
+case "$OPERATION" in
     "prepare")
         StartNosleepService ;;
     "release")
