Fixed hooks.

diff --git a/etc/ddcutil b/etc/ddcutil
--- a/etc/ddcutil
+++ b/etc/ddcutil
@@ -19,6 +19,8 @@
 # Make sure you specify the right settings for your setup below or it won't work.
 # </remarks>
 
+_HOOK_NAME="ddcutil"
+_PREFIX_PROMPT="libvirt-qemu $_HOOK_NAME:"
 _OPERATION="$2"
 _SUBOPERATION="$3"
 
@@ -47,12 +49,16 @@ function GetVideoInput
 
 function SetVideoOutput
 {
-	if [[ "$( ddcutil -d "$_DOMAIN_DISPLAY" getvcp 60 --terse | awk '{print $4}' )" != "x$_VIDEO_INPUT" ]] \
-		&& ddcutil -d "$_DOMAIN_DISPLAY" setvcp 60 "0x$_VIDEO_INPUT"; then
-		return 0
+    if [[ "$( ddcutil -d "$_DOMAIN_DISPLAY" getvcp 60 --terse | awk '{print $4}' )" == "x$_VIDEO_INPUT" ]]; then
+        return 0
+    fi
+
+	if ! ddcutil -d "$_DOMAIN_DISPLAY" setvcp 60 "0x$_VIDEO_INPUT"; then
+        echo "$_PREFIX_PROMPT An error occured: Failed to switch video input."
+		return 1
 	fi
 
-	return 1
+	return 0
 }
 
 if GetVideoInput; then
diff --git a/etc/nosleep b/etc/nosleep
--- a/etc/nosleep
+++ b/etc/nosleep
@@ -8,12 +8,36 @@
 # Maintainer(s):    Alex Portell <github.com/portellam>
 #
 
+_HOOK_NAME="nosleep"
+_PREFIX_PROMPT="libvirt-qemu $_HOOK_NAME:"
 _DOMAIN_NAME="$1"
 _OPERATION="$2"
 
+function StartNosleepService
+{
+    if ! systemctl start libvirt-nosleep@"$_DOMAIN_NAME" &> /dev/null; then
+        echo "$_PREFIX_PROMPT An error occured: Failed to start Nosleep service for Libvirt domain '$_DOMAIN_NAME'."
+        return 1
+    fi
+
+    echo "$_PREFIX_PROMPT Started Nosleep service for Libvirt domain '$_DOMAIN_NAME'."
+    return 0
+}
+
+function StopNosleepService
+{
+    if ! systemctl start libvirt-nosleep@"$_DOMAIN_NAME" &> /dev/null; then
+        echo "$_PREFIX_PROMPT An error occured: Failed to stop Nosleep service for Libvirt domain '$_DOMAIN_NAME'."
+        return 1
+    fi
+
+    echo "$_PREFIX_PROMPT Stopped Nosleep service for Libvirt domain '$_DOMAIN_NAME'."
+    return 0
+}
+
 case "$_OPERATION" in
     "prepare")
-        systemctl start libvirt-nosleep@"$_DOMAIN_NAME" ;;
+        StartNosleepService ;;
     "release")
-        systemctl stop libvirt-nosleep@"$_DOMAIN_NAME" ;;
+        StopNosleepService ;;
 esac
