Added hugepages hook from VFIO-tools. Updated set-hooks for new hook and added functionality.

diff --git a/etc/set-hooks b/etc/set-hooks
--- a/etc/set-hooks
+++ b/etc/set-hooks
@@ -15,8 +15,21 @@ BEGIN_DIR="${DOMAIN_NAME_BASE_DIR}/started/begin/"
 END_DIR="${DOMAIN_NAME_BASE_DIR}/stopped/end/"
 
 # <remarks> Add domain-specific hooks here. </remarks>
-HOOK_NAME_1="ddcutil"
-HOOK_NAME_2="cfscpu"
+HOOK_NAME_1="cfscpu"
+HOOK_NAME_2="ddcutil"
+HOOK_NAME_3="hugepages"
+
+declare -a START_HOOKS_LIST=(
+    "${HOOK_NAME_1}"
+    "${HOOK_NAME_2}"
+    "${HOOK_NAME_3}"
+)
+
+declare -a STOP_HOOKS_LIST=(
+    "${HOOK_NAME_1}"
+    "${HOOK_NAME_2}"
+    # NOTE: no stop hook for hook #3
+)
 
 function GetPathsForDomain
 {
@@ -40,21 +53,61 @@ function GetHooks
     return 0
 }
 
-function SetHooksForDomain
+function SetStartHookForDomain
+{
+    if [[ -z "${1}" ]] \
+        || [[ ! -e "${BEGIN_DIR}/${1}" ]]; then
+        return 0
+    fi
+
+    if ! ln -s "${BEGIN_DIR}/${1}" "${HOOKS_BASE_DIR}/${1}" &> /dev/null; then
+        echo -e "${PREFIX_ERROR} Failed to set symlinks for start hook '${1}'."
+        return 1
+    fi
+
+    if ! chmod +x "${BEGIN_DIR}/${1}" &> /dev/null; then
+        echo -e "${PREFIX_ERROR} Failed to set file permissions for start hook '${1}'."
+        return 1
+    fi
+
+    return 0
+}
+
+function SetStopHookForDomain
+{
+    if [[ -z "${1}" ]] \
+        || [[ ! -e "${END_DIR}/${1}" ]]; then
+        return 0
+    fi
+
+    if ! ln -s "${END_DIR}/${1}" "${HOOKS_BASE_DIR}/${1}" &> /dev/null; then
+        echo -e "${PREFIX_ERROR} Failed to set symlinks for stop hook '${1}'."
+        return 1
+    fi
+
+    if ! chmod +x "${END_DIR}/${1}" &> /dev/null; then
+        echo -e "${PREFIX_ERROR} Failed to set file permissions for stop hook '${1}'."
+        return 1
+    fi
+
+    return 0
+}
+
+function UnsetHookForDomain
 {
     if [[ -z "${1}" ]]; then
         return 0
     fi
 
-    if ! ln -s "${BEGIN_DIR}/${1}" "${HOOKS_BASE_DIR}/${1}" &> /dev/null \
-        || ! ln -s "${END_DIR}/${1}" "${HOOKS_BASE_DIR}/${1}" &> /dev/null; then
-        echo -e "${PREFIX_ERROR} Failed to set symlinks for hook '${1}'."
+    if [[ ! -e "${BEGIN_DIR}/${1}" ]] \
+        && ! rm -rf "${BEGIN_DIR}/${1}" &> /dev/null; then
+        echo -e "${PREFIX_ERROR} Failed to unset symlinks for start hook '${1}'."
         return 1
     fi
 
-    if ! chmod +x "${BEGIN_DIR}/${1}" &> /dev/null \
-        || ! chmod +x "${END_DIR}/${1}" &> /dev/null; then
-        echo -e "${PREFIX_ERROR} Failed to set file permissions for hook '${1}'."
+    if [[ ! -z "${END_DIR}/${1}" ]] \
+        && ! rm -rf "${END_DIR}/${1}" &> /dev/null; then
+        echo -e "${PREFIX_ERROR} Failed to unset symlinks for stop hook '${1}'."
         return 1
     fi
 
@@ -66,6 +119,11 @@ if [[ ! -z "${DOMAIN_NAME}" ]] \
     && GetHooks; then
 
     # <remarks> Call domain-specific hooks here. </remarks>
-    SetHooksForDomain "${HOOK_NAME_1}"
-    SetHooksForDomain "${HOOK_NAME_2}"
+    for HOOK in ${START_HOOKS_LIST[@]}; do
+        SetStartHookForDomain "${HOOK}" || UnsetHookForDomain "${HOOK}"
+    done
+
+    for HOOK in ${STOP_HOOKS_LIST[@]}; do
+        SetStopHookForDomain "${HOOK}" || UnsetHookForDomain "${HOOK}"
+    done
 fi
