Redone input parameters. Amended loggers and comments. Removed globals.

diff --git a/deploy-vfio.d/bin.new/src_iommu_device_getters b/deploy-vfio.d/bin.new/src_iommu_device_getters
--- a/deploy-vfio.d/bin.new/src_iommu_device_getters
+++ b/deploy-vfio.d/bin.new/src_iommu_device_getters
@@ -10,6 +10,7 @@
 #
 # TODO:
 # - [ ] test.
+# - [x] develop.
 #
 
 #
@@ -22,33 +23,12 @@
   source "${SRC_STR_SCRIPT_BIN_DIR}src_iommu_device_validation"
 
 #
-# setter logic
-#
-  #
-  # DESC: globals
-  #
-    function set_globals
-    {
-      log_stdout "${0}: ${FUNCNAME}"
-
-      if [[ "${SRC_IOMMU_PARSE_BOOL_SET_GLOBALS}" == true ]]; then
-        return 0
-      fi
-
-      declare -g SRC_IOMMU_PARSE_BOOL_SET_GLOBALS=true
-
-      declare -gr SRC_IOMMU_PARSE_STR_GET_DEVICES_FOR_IOMMU_GROUP=$( \
-        ls "/sys/kernel/iommu_groups/"'${int_iommu_group_id}'"/devices" \
-      )
-    }
-
-#
 # logic
 #
   #
   # DESC:   Get device class.
-  # $1:     the device info as a string.
-  # $2:     the reference variable.
+  # $1:     the device slot ID as a string.
+  # $2:     the device class as a string reference.
   # RETURN: If device class is found, return 0.
   #         If not, return 1.
   #
@@ -56,16 +36,36 @@
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      local -r str_device="${1}"
-      local -n ref="${2}"
+      local -r str_device_slot_id="${1}"
+      local -n ref_str_device_class="${2}"
 
-      ref="$( lspci -ms ${str_device} | cut --delimiter '"' --fields 2 )"
+      if ! is_string "${ref_str_device_class}"; then
+        log_invalid_parameter "ref_str_device_class"
+        return 2
+      fi
+
+      if ! is_string "${str_device_slot_id}"; then
+        log_invalid_parameter "str_device_slot_id"
+        return 2
+      fi
+
+      ref_str_device_class="$( \
+        lspci -ms ${str_device_slot_id} | cut --delimiter '"' --fields 2 \
+      )"
+
+      if ! is_string "${ref_str_device_class}"; then
+        log_stderr "Could not find device class."
+        return 1
+      fi
+
+      log_stdout "Found device class."
+      return 0
     }
 
   #
   # DESC:   Get the device driver.
-  # $1:     the device info as a string.
-  # $2:     the reference variable.
+  # $1:     the device slot ID as a string.
+  # $2:     the device driver as a string reference.
   # $3:     the reference of dictionary of device drivers from XML file.
   # RETURN: If device driver is found, return 0.
   #         If not, return 1.
@@ -74,56 +74,56 @@
     {
       log_stdout "${0}: ${FUNCNAME}"
 
+      local str_device_slot_id="${1}"
+      local -n ref_str_device_driver="${2}"
+      local -n ref_dict_device_slot_id_and_driver="${3}"
       local bool_do_parse_from_xml_file=false
 
-      if ! is_dict "${3}" &> /dev/null; then
-        bool_do_parse_from_xml_file=false
+      if ! is_string "${ref_str_device_driver}"; then
+        log_invalid_parameter "ref_str_device_driver"
+        return 2
+      fi
 
-        log_stderr "Missing dictionary of device drivers from XML file."\
-          "Parsing from internal database."
+      if ! is_string "${str_device_slot_id}"; then
+        log_invalid_parameter "str_device_slot_id"
+        return 2
+      fi
+
+      if ! is_dict "${ref_dict_device_slot_id_and_driver}"; then
+        bool_do_parse_from_xml_file=false
+        log_invalid_parameter "ref_dict_device_slot_id_and_driver."
+        log_stdout "Not parsing from XML file."
       else
         bool_do_parse_from_xml_file=true
-
-        print_output_to_log "Parsing from XML file."
+        log_stdout "Parsing from XML file."
       fi
 
-      if ! is_string "${2}"; then
-        log_stderr "Invalid reference."
-        return 1
-      fi
-
-      if ! is_string "${1}"; then
-        log_stderr "Invalid device."
-        return 1
-      fi
-
-      local -r str_device="${1}"
-      local -n ref="${2}"
-      local -n ref_array_device_drivers_from_xml_file="${3}"
-
-      if "${bool_do_parse_from_xml_file}"; then
-        ref="${ref_array_device_drivers_from_xml_file["${str_device}"]}"
-
-        if ! dict_contains_key "ref_array_device_drivers_from_xml_file" \
-          "${str_device}" &> /dev/null; then
-          print_error_to_log "Could not find device driver from XML file."
-          return 1
-        fi
-
-      else
-        ref="$( \
-          lspci -ks "${str_device}" | grep --ignore-case "driver" | \
-          awk 'END {print $5}' \
+      if ! "${bool_do_parse_from_xml_file}"; then
+        ref_str_device_driver="$( \
+          lspci -ks "${str_device_slot_id}" | grep --ignore-case "driver" | \
+            awk 'END {print $5}' \
         )"
+
+        log_stdout "Found device driver."
+        return 0
       fi
 
+      ref_str_device_driver="${ref_dict_device_slot_id_and_driver["${str_device}"]}"
+
+      if ! dict_contains_key "ref_dict_device_slot_id_and_driver" \
+          "${str_device_slot_id}"; then
+        log_stderr "Could not find device driver from XML file."
+        return 1
+      fi
+
+      log_stdout "Found device driver from XML file."
       return 0
     }
 
   #
   # DESC:   Get device hardware ID.
-  # $1:     the device info as a string.
-  # $2:     the reference variable.
+  # $1:     the device slot ID as a string.
+  # $2:     the device hardware ID as a string reference.
   # RETURN: If device hardware ID is found, return 0.
   #         If not, return 1.
   #
@@ -131,16 +131,36 @@
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      local -r str_device="${1}"
-      local -n ref="${2}"
+      local -r str_device_slot_id="${1}"
+      local -n ref_str_device_hardware_id="${2}"
 
-      ref="$( lspci -ns ${str_device} | cut --delimiter ' ' --fields 3 )"
+      if ! is_string "${ref_str_device_hardware_id}"; then
+        log_invalid_parameter "ref_str_device_hardware_id"
+        return 2
+      fi
+
+      if ! is_string "${str_device_slot_id}"; then
+        log_invalid_parameter "str_device_slot_id"
+        return 2
+      fi
+
+      ref_str_device_hardware_id="$( \
+        lspci -ns ${str_device_slot_id} | cut --delimiter ' ' --fields 3 \
+      )"
+
+      if ! is_string "${ref_str_device_hardware_id}"; then
+        log_stderr "Could not find device hardware ID."
+        return 1
+      fi
+
+      log_stdout "Found device hardware ID."
+      return 0
     }
 
   #
   # DESC:   Get device name.
-  # $1:     the device info as a string.
-  # $2:     the reference variable.
+  # $1:     the device slot ID as a string.
+  # $2:     the device name as a string reference.
   # RETURN: If device name is found, return 0.
   #         If not, return 1.
   #
@@ -148,16 +168,36 @@
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      local -r str_device="${1}"
-      local -n ref="${2}"
+      local -r str_device_slot_id="${1}"
+      local -n ref_str_device_name="${2}"
 
-      ref="$( lspci -ms ${str_device}  | cut --delimiter '"' --fields 6 )"
+      if ! is_string "${ref_str_device_name}"; then
+        log_invalid_parameter "ref_str_device_name"
+        return 2
+      fi
+
+      if ! is_string "${str_device_slot_id}"; then
+        log_invalid_parameter "str_device_slot_id"
+        return 2
+      fi
+
+      ref_str_device_name="$( \
+        lspci -ms ${str_device_slot_id}  | cut --delimiter '"' --fields 6 \
+      )"
+
+      if ! is_string "${ref_str_device_hardware_id}"; then
+        log_stderr "Could not find device name."
+        return 1
+      fi
+
+      log_stdout "Found device name."
+      return 0
     }
 
   #
   # DESC:   Get device vendor.
-  # $1:     the device info as a string.
-  # $2:     the reference variable.
+  # $1:     the device slot ID as a string.
+  # $2:     the device vendor as a string reference.
   # RETURN: If device vendor is found, return 0.
   #         If not, return 1.
   #
@@ -165,10 +205,30 @@
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      local -r str_device="${1}"
-      local -n ref="${2}"
+      local -r str_device_slot_id="${1}"
+      local -n ref_str_device_vendor="${2}"
 
-      ref="$( lspci -ms ${str_device} | cut --delimiter '"' --fields 4 )"
+      if ! is_string "${ref_str_device_vendor}"; then
+        log_invalid_parameter "ref_str_device_vendor"
+        return 2
+      fi
+
+      if ! is_string "${str_device_slot_id}"; then
+        log_invalid_parameter "str_device_slot_id"
+        return 2
+      fi
+
+      ref_str_device_vendor="$( \
+        lspci -ms ${str_device_slot_id}  | cut --delimiter '"' --fields 4 \
+      )"
+
+      if ! is_string "${ref_str_device_vendor}"; then
+        log_stderr "Could not find device vendor."
+        return 1
+      fi
+
+      log_stdout "Found device vendor."
+      return 0
     }
 
   #
@@ -180,83 +240,91 @@
   # RETURN: If drivers and/or hardware IDs are found, return 0.
   #         If not, return 1.
   #
-    function get_device_dictionaries_for_selection
+    function get_device_arrays_for_iommu_groups
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      if ! is_array "${4}" &> /dev/null; then
-        log_stderr "Missing reference of device 'vfio-pci' HWID array."
-        return 1
+      local -n ref_arr_iommu_group_id="${1}"
+      local -n ref_arr_device_driver="${2}"
+      local -n ref_arr_stub_hardware_id="${3}"
+      local -n ref_arr_vfio_hardware_id="${4}"
+
+      if ! is_array "${ref_arr_vfio_hardware_id}"; then
+        log_invalid_parameter "${ref_arr_vfio_hardware_id}"
+        return 2
       fi
 
-      if ! is_array "${3}" &> /dev/null; then
-        log_stderr "Missing reference of device 'pci-stub' HWID array."
-        return 1
+      if ! is_array "${ref_arr_stub_hardware_id}"; then
+        log_invalid_parameter "${ref_arr_stub_hardware_id}"
+        return 2
       fi
 
-      if ! is_array "${2}" &> /dev/null; then
-        log_stderr "Missing reference of device driver array."
-        return 1
+      if ! is_array "${ref_arr_device_driver}"; then
+        log_invalid_parameter "${ref_arr_device_driver}"
+        return 2
       fi
 
-      if ! is_array "${1}" &> /dev/null; then
-        log_stderr "Missing reference of IOMMU group ID array."
-        return 1
+      if ! is_array "${ref_arr_iommu_group_id}"; then
+        log_invalid_parameter "${ref_arr_iommu_group_id}"
+        return 2
       fi
 
-      local -n ref="${1}"
-      local -n ref_array_driver="${2}"
-      local -n ref_array_stub_hwid="${3}"
-      local -n ref_array_vfio_hwid="${4}"
-
-      for int_iommu_group_id in ${ref[@]}; do
-        local -a arr_device_list="$( \
-          eval "${SRC_IOMMU_PARSE_STR_GET_DEVICES_FOR_IOMMU_GROUP}" \
+      for int_iommu_group_id in ${ref_arr_iommu_group_id[@]}; do
+        local -a arr_device_slot_id="$( \
+          ls "/sys/kernel/iommu_groups/${int_iommu_group_id}/devices" \
         )"
 
-        for str_device in ${arr_device_list[@]}; do
-          local str_driver=""
-          local str_hwid=""
+        for str_device_slot_id in ${arr_device_slot_id[@]}; do
+          local str_device_driver=""
+          local str_device_hardware_id=""
 
-          get_device_driver       "${str_device}" "str_driver"
-          get_device_hardware_id  "${str_device}" "str_hwid"
+          get_device_driver       "${str_device_slot_id}" "str_device_driver"
+          get_device_hardware_id  "${str_device_slot_id}" "str_device_hardware_id"
 
-          if [[ ! -z "${str_driver}" ]] \
-            && is_device_not_excluded "${str_device}"; then
-            ref_array_driver+=( "${str_driver}" )
+          if is_string "${str_device_slot_id}" \
+            && is_device_not_excluded "${str_device_slot_id}"; then
+            ref_arr_device_driver+=( "${str_device_driver}" )
           fi
 
-          if [[ ! -z "${str_hwid}" ]]; then
-            if is_device_for_pci_stub "${str_device}"; then
-              ref_array_stub_hwid+=( "${str_hwid}" )
+          if is_string "${str_device_hardware_id}"; then
+            if is_device_for_pci_stub "${str_device_slot_id}"; then
+              ref_arr_stub_hardware_id+=( "${str_device_hardware_id}" )
             else
-              ref_array_vfio_hwid+=( "${str_hwid}" )
+              ref_arr_vfio_hardware_id+=( "${str_device_hardware_id}" )
             fi
           fi
         done
       done
 
-      ref_array_driver=( $( sort --unique <<<"${ref_array_driver[*]}" ) )
-      ref_array_stub_hwid=( $( sort --unique <<<"${ref_array_stub_hwid[*]}" ) )
-      ref_array_vfio_hwid=( $( sort --unique <<<"${ref_array_vfio_hwid[*]}" ) )
+      ref_arr_device_driver=( $( sort --unique <<<"${ref_arr_device_driver[*]}" ) )
 
-      if is_enum_not_empty "ref_array_driver"; then
-        return 0
-      fi
+      ref_arr_stub_hardware_id=( \
+        $( sort --unique <<<"${ref_arr_stub_hardware_id[*]}" ) \
+      )
 
-      if is_enum_not_empty "ref_array_stub_hwid" \
-        || is_enum_not_empty "ref_array_vfio_hwid"; then
-        print_error_to_log "No drivers or hardware IDs found for selection."
+      ref_arr_vfio_hardware_id=( \
+        $( sort --unique <<<"${ref_arr_vfio_hardware_id[*]}" ) \
+      )
+
+      if ! is_enum_not_empty "ref_arr_device_driver"; then
+        log_stdout "Could not find device drivers."
         return 1
       fi
 
+      if ! is_enum_not_empty "ref_arr_stub_hardware_id" \
+        && ! is_enum_not_empty "ref_arr_vfio_hardware_id"; then
+        log_stderr "Could not find device hardware IDs."
+        return 1
+      fi
+
+      log_stdout "Found device drivers and hardware IDs."
       return 0
     }
 
   #
   # DESC:   Get name for fist VGA device in IOMMU group.
   # $1:     the IOMMU group ID as an int.
-  # $2:     the reference of the device name as a string.
+  # $2:     the device name as a string reference.
   # RETURN: If the device name is found, return 0.
   #         If not, return 1.
   #
@@ -264,38 +332,44 @@
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      if [[ -z "${2}" ]] \
-        || ! is_int "${1}" &> /dev/null; then
-        return 1
-      fi
-
       local -ir int_iommu_group_id="${1}"
       local -n ref_str_device_name="${2}"
 
-      local -ar arr_device_list="$( \
-        eval "${SRC_IOMMU_PARSE_STR_GET_DEVICES_FOR_IOMMU_GROUP}" \
+      if ! is_string "${ref_str_device_name}"; then
+        log_invalid_parameter "${ref_str_device_name}"
+        return 2
+      fi
+
+      if ! is_int "${int_iommu_group_id}"; then
+        log_invalid_parameter "${int_iommu_group_id}"
+        return 2
+      fi
+
+      local -ar arr_device_slot_id="$( \
+        ls "/sys/kernel/iommu_groups/${int_iommu_group_id}/devices" \
       )"
 
-      local str_name=""
-
-      for str_device in ${arr_device_list[@]}; do
-        if ! is_device_vga "${str_device}"; then
+      for str_device_slot_id in ${arr_device_slot_id[@]}; do
+        if ! is_device_vga "${str_device_slot_id}"; then
           continue
         fi
 
-        if get_device_name "${str_device}" "ref_str_device_name"; then
+        if get_device_name "${str_device_slot_id}" "ref_str_device_name"; then
           break
         fi
       done
 
-      if [[ -z "${str_name}" ]]; then
-        print_error_to_log "Could not find device name of any VGA device in "\
-          "IOMMU group ${int_iommu_group_id}."
+      if ! is_string "${ref_str_device_name}"; then
+        log_stderr "Could not find device name of any VGA device in IOMMU group "\
+          "${int_iommu_group_id}."
 
         return 1
       fi
 
-      ref_str_device_name="${str_name}"
+      log_stdout "Found device name of any VGA device in IOMMU group "\
+        "${int_iommu_group_id}."
+
+      return 0
     }
 
 #
