Added param for saving IFS. Renamed params given new notation.

diff --git a/deploy-vfio.d/bin.new/src_print b/deploy-vfio.d/bin.new/src_print
--- a/deploy-vfio.d/bin.new/src_print
+++ b/deploy-vfio.d/bin.new/src_print
@@ -22,41 +22,52 @@
   #
     function set_globals
     {
-      if [[ "${BOOL_SRC_PRINT_SET_GLOBALS}" == true ]]; then
+      if [[ "${SRC_PRINT_BOOL_SET_GLOBALS}" == true ]]; then
         return 0
       fi
 
-      declare -g BOOL_SRC_PRINT_SET_GLOBALS=true
+      declare -g SRC_PRINT_BOOL_SET_GLOBALS=true
+
+      declare -g SRC_PRINT_SAVEIFS="${IFS}"
 
       #
       # DESC:   vanity
       #
-        declare -gr STR_SCRIPT_NAME="deploy-vfio"
+        declare -gr SRC_PRINT_STR_SCRIPT_NAME="deploy-vfio"
 
       #
       # DESC:   color coding
       #
-        declare -gr STR_SET_COLOR_GREEN='\033[0;32m'
-        declare -gr STR_SET_COLOR_RED='\033[0;31m'
-        declare -gr STR_SET_COLOR_YELLOW='\033[0;33m'
-        declare -gr STR_RESET_COLOR='\033[0m'
+        declare -gr SRC_PRINT_STR_SET_COLOR_GREEN='\033[0;32m'
+        declare -gr SRC_PRINT_STR_SET_COLOR_RED='\033[0;31m'
+        declare -gr SRC_PRINT_STR_SET_COLOR_YELLOW='\033[0;33m'
+        declare -gr SRC_PRINT_STR_RESET_COLOR='\033[0m'
 
       #
       # DESC:   font handling
       #
-        declare -gr STR_SET_BOLD='\e[1m'
-        declare -gr STR_SET_ITALIC='\e[3m'
-        declare -gr STR_SET_UNDERLINE='\e[4m'
-        declare -gr STR_RESET_TEXT='\e[0m'
+        declare -gr SRC_PRINT_STR_SET_BOLD='\e[1m'
+        declare -gr SRC_PRINT_STR_SET_ITALIC='\e[3m'
+        declare -gr SRC_PRINT_STR_SET_UNDERLINE='\e[4m'
+        declare -gr SRC_PRINT_STR_RESET_TEXT='\e[0m'
 
       #
       # DESC:   prompt prefixes
       #
-        declare -gr STR_PREFIX_PROMPT="${STR_SCRIPT_NAME}: "
-        declare -gr STR_PREFIX_NOTE="${STR_PREFIX_PROMPT}${STR_SET_COLOR_YELLOW}Note:${STR_RESET_COLOR} "
-        declare -gr STR_PREFIX_ERROR="${STR_PREFIX_PROMPT}${STR_SET_COLOR_YELLOW}An error occurred:${STR_RESET_COLOR} "
-        declare -gr STR_PREFIX_FAIL="${STR_PREFIX_PROMPT}${STR_SET_COLOR_RED}Failure:${STR_RESET_COLOR} "
-        declare -gr STR_PREFIX_PASS="${STR_PREFIX_PROMPT}${STR_SET_COLOR_GREEN}Success:${STR_RESET_COLOR} "
+        declare -gr SRC_PRINT_STR_PREFIX_PROMPT="${SRC_PRINT_STR_SCRIPT_NAME}: "
+
+        declare -gr STR_PREFIX_NOTE="${STR_PREFIX_PROMPT}" + \
+          "${SRC_PRINT_STR_SET_COLOR_YELLOW}Note:${SRC_PRINT_STR_RESET_COLOR} "
+
+        declare -gr SRC_PRINT_STR_PREFIX_ERROR="${STR_PREFIX_PROMPT}" + \
+          "${SRC_PRINT_STR_SET_COLOR_YELLOW}An error occurred:" + \
+          "${SRC_PRINT_STR_RESET_COLOR} "
+
+        declare -gr SRC_PRINT_STR_PREFIX_FAIL="${STR_PREFIX_PROMPT}" + \
+          "${SRC_PRINT_STR_SET_COLOR_RED}Failure:${SRC_PRINT_STR_RESET_COLOR} "
+
+        declare -gr SRC_PRINT_STR_PREFIX_PASS="${STR_PREFIX_PROMPT}" + \
+          "${SRC_PRINT_STR_SET_COLOR_GREEN}Success:${SRC_PRINT_STR_RESET_COLOR} "
     }
 
 #
@@ -87,7 +98,7 @@
   #
     function print_error_to_log
     {
-       echo -e "${STR_PREFIX_ERROR}${1}" >&2
+       echo -e "${SRC_PRINT_STR_PREFIX_ERROR}${1}" >&2
     }
 
   #
@@ -97,7 +108,7 @@
   #
     function print_fail_to_log
     {
-      echo -e "${STR_PREFIX_FAIL}${1}" >&2
+      echo -e "${SRC_PRINT_STR_PREFIX_FAIL}${1}" >&2
     }
 
   #
@@ -107,7 +118,7 @@
   #
     function print_output_to_log
     {
-      echo -e "${STR_PREFIX_PROMPT}${1}" >&1
+      echo -e "${SRC_PRINT_STR_PREFIX_PROMPT}${1}" >&1
     }
 
   #
@@ -117,7 +128,7 @@
   #
     function print_note
     {
-      echo -e "${STR_PREFIX_NOTE}${1}"
+      echo -e "${SRC_PRINT_STR_PREFIX_NOTE}${1}"
     }
 
   #
@@ -150,7 +161,7 @@
   #
     function print_pass_to_log
     {
-      echo -e "${STR_PREFIX_PASS}${1}" >&1
+      echo -e "${SRC_PRINT_STR_PREFIX_PASS}${1}" >&1
     }
 
   #
@@ -159,7 +170,7 @@
   #
     function reset_ifs
     {
-      IFS="${SAVEIFS}"
+      IFS="${SRC_PRINT_SAVEIFS}"
     }
 
   #
