Migrated logic from usage. Added return codes and comments.

diff --git a/deploy-vfio.d/bin.new/src_print b/deploy-vfio.d/bin.new/src_print
--- a/deploy-vfio.d/bin.new/src_print
+++ b/deploy-vfio.d/bin.new/src_print
@@ -85,7 +85,7 @@
 #
   #
   # DESC:   Trap error code and run logic before exit.
-  # RETURN: Always return 1.
+  # RETURN: Always exit 1.
   #
     function catch_error
     {
@@ -96,12 +96,13 @@
 
   #
   # DESC:   Trap exit code and run logic before exit.
-  # RETURN: Always return 1.
+  # RETURN: Always return 0.
   #
     function catch_exit
     {
       print_pass_or_fail_to_log
       reset_ifs
+      return 0
     }
 
   #
@@ -112,6 +113,8 @@
     {
       echo -e "${SRC_PRINT_STR_PREFIX_PROMPT}One or more errors have occurred."\
         "Please view the logfile to troubleshoot ('${SRC_PRINT_STR_LOG_FILE}')." >&2
+
+      return 0
     }
 
   #
@@ -122,6 +125,7 @@
     {
       logger --stderr "${1}" 2>> "${SRC_PRINT_STR_LOG_FILE}"
       echo -e "" >&2
+      return 0
     }
 
   #
@@ -131,6 +135,102 @@
     function log_stdout
     {
       logger "${1}" 2>> "${SRC_PRINT_STR_LOG_FILE}"
+      return 0
+    }
+
+  #
+  # DESC:   Print help.
+  # $1:     the argument as a string.
+  # RETURN: Always return 0.
+  #
+    function print_help
+    {
+      echo -e "Try 'sudo bash ${SRC_PRINT_STR_SCRIPT_NAME} --help' for usage."
+      return 0
+    }
+
+  #
+  # DESC:   Print conflicting options output.
+  # $1:     the argument as a string.
+  # RETURN: Always exit 1.
+  #
+    function print_conflicting_options
+    {
+      print_error_to_log "Conflicting option(s)."
+      print_help
+      exit 1
+    }
+
+  #
+  # DESC:   Print duplicate argument output.
+  # $1:     the argument as a string.
+  # RETURN: Always exit 1.
+  #
+    function print_duplicate_argument
+    {
+      local -r str_output="Duplicate argument"
+
+      if ! is_string "${1}"; then
+        print_error_to_log "${str_output}."
+      fi
+
+      print_error_to_log "${str_output}'${1}'."
+      return 1
+    }
+
+  #
+  # DESC:   Print duplicate option output.
+  # $1:     the option as a string.
+  # RETURN: Always exit 1.
+  #
+    function print_duplicate_option
+    {
+      local -r str_output="Duplicate option"
+
+      if ! is_string "${1}"; then
+        print_error_to_log "${str_output}."
+      fi
+
+      print_error_to_log "${str_output}'${1}'."
+      return 1
+    }
+
+  #
+  # DESC:   Print invalid argument output.
+  # $1:     the argument as a string.
+  # RETURN: Always exit 1.
+  #
+    function print_invalid_argument
+    {
+      local -r str_output="Invalid argument"
+
+      if ! is_string "${1}"; then
+        print_error_to_log "${str_output}."
+      else
+        print_error_to_log "${str_output} '${1}'."
+      fi
+
+      print_help
+      exit 1
+    }
+
+  #
+  # DESC:   Print invalid option output.
+  # $1:     the option as a string.
+  # RETURN: Always exit 1.
+  #
+    function print_invalid_option
+    {
+      local -r str_output="Invalid option"
+
+      if ! is_string "${1}"; then
+        print_error_to_log "${str_output}."
+      else
+        print_error_to_log "${str_output} '${1}'."
+      fi
+
+      print_help
+      exit 1
     }
 
   #
@@ -178,10 +278,11 @@
 
   #
   # DESC:   Print and log error.
-  # $1:     line of text as a string
+  # $1:     line of text as a string.
   # RETURN: Return incoming return code.
   #         If 0, output success.
-  #         If 255, output skipped. If else, output failure.
+  #         If 255, output skipped.
+  #         If else, output failure.
   #
     function print_pass_or_fail_to_log
     {
@@ -202,7 +303,7 @@
 
   #
   # DESC:   Print and log success.
-  # $1:     line of text as a string
+  # $1:     line of text as a string.
   # RETURN: Always return 0.
   #
     function print_pass_to_log
