Refactored print outs to log only.

diff --git a/deploy-vfio.d/bin.new/src_auto_xorg b/deploy-vfio.d/bin.new/src_auto_xorg
--- a/deploy-vfio.d/bin.new/src_auto_xorg
+++ b/deploy-vfio.d/bin.new/src_auto_xorg
@@ -26,7 +26,8 @@
 #
   #
   # DESC:   Checks if git repo exists.
-  # RETURN: If repo exists, return 0. If false, return 1.
+  # RETURN: If repo exists, return 0.
+  #         If false, return 1.
   #
     function does_auto_xorg_repo_exist
     {
@@ -39,18 +40,21 @@
 
   #
   # DESC:   Execute Auto X.Org.
-  # $1:     the command line arguments
-  # RETURN: If execution is successful, return 0. If false, return 1.
+  # $*:     the command line arguments as a string.
+  # RETURN: If execution is successful, return 0.
+  #         If false, return 1.
   #
     function execute_auto_xorg
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      does_auto_xorg_repo_exist || return 1
+      if ! does_auto_xorg_repo_exist; then
+        return 1
+      fi
 
       local -r str_arguments="${*}"
 
-      print_output_to_log "Executing Auto X.Org...\n"
+      log_stdout "Executing Auto X.Org...\n"
       sudo bash auto-xorg "${str_arguments}"
 
       local -i int_code="${?}"
@@ -58,30 +62,32 @@
       echo
 
       if [[ "${int_code}" -ne 0 ]]; then
-        print_output_to_log "Execution failed."
+        log_stderr "Execution failed."
         return "${int_code}"
       fi
 
-      print_output_to_log "Execution successful."
+      log_stdout "Execution successful."
       return 0
     }
 
   #
   # DESC:   Execute Auto X.Org installer.
-  # $1:     the command line arguments
+  # $*:     the command line arguments as a string.
   # RETURN: If execution is successful, return 0. If false, return 1.
   #
     function execute_auto_xorg_installer
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      does_auto_xorg_repo_exist || return 1
+      if ! does_auto_xorg_repo_exist; then
+        return 1
+      fi
 
       local -r str_arguments="${*}"
       local -r str_project_path="${STR_GIT_STR_REPO_PARENT_PATH}/auto-xorg"
 
       cd "${str_project_path}"
-      print_output_to_log "Executing Auto X.Org installer...\n"
+      log_stdout "Executing Auto X.Org installer...\n"
       sudo bash installer.bash "${str_arguments}"
 
       local -i int_code="${?}"
@@ -89,34 +95,53 @@
       echo
 
       if [[ "${int_code}" -ne 0 ]]; then
-        print_output_to_log "Execution failed."
+        log_stderr "Execution failed."
         return "${int_code}"
       fi
 
-      print_output_to_log "Execution successful."
+      log_stdout "Execution successful."
       return 0
     }
 
   #
-  # DESC:   Basic install of Auto X.Org, no added arguments.
-  # RETURN: If install is successful, return 0. If false, return 1.
+  # DESC:   Install of Auto X.Org, no added arguments.
+  # $*:     the command line arguments as a string.
+  # RETURN: If install is successful, return 0.
+  #         If false, return 1.
   #
-    function basic_install_auto_xorg
+    function install_auto_xorg
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      execute_auto_xorg_installer "--install"
-      return "${?}"
+      local -r str_arguments="${*}"
+
+      print_output_to_log "Installing Auto X.Org..."
+
+      if ! execute_auto_xorg_installer "--install ${str_arguments}"; then
+        print_output_to_log "Failed."
+        return 1
+      fi
+
+      print_output_to_log "Successful."
+      return 0
     }
 
   #
   # DESC:   Uninstall Auto X.Org.
-  # RETURN: If uninstall is successful, return 0. If false, return 1.
+  # RETURN: If uninstall is successful, return 0.
+  #         If false, return 1.
   #
     function uninstall_auto_xorg
     {
       log_stdout "${0}: ${FUNCNAME}"
 
-      execute_auto_xorg_installer "--uninstall"
-      return "${?}"
+      print_output_to_log "Uninstalling Auto X.Org..."
+
+      if ! execute_auto_xorg_installer "--uninstall"; then
+        print_output_to_log "Failed."
+        return 1
+      fi
+
+      print_output_to_log "Successful."
+      return 0
     }
diff --git a/deploy-vfio.d/bin.new/src_iommu_group_validation b/deploy-vfio.d/bin.new/src_iommu_group_validation
--- a/deploy-vfio.d/bin.new/src_iommu_group_validation
+++ b/deploy-vfio.d/bin.new/src_iommu_group_validation
@@ -90,26 +90,26 @@
       log_stdout "${0}: ${FUNCNAME}"
 
       if ! is_array "${4}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for with VGA"\
+        log_stderr "Missing reference of array of IOMMU groups for with VGA"\
           "for VFIO."
 
         return 1
       fi
 
       if ! is_array "${3}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for VFIO."
+        log_stderr "Missing reference of array of IOMMU groups for VFIO."
         return 1
       fi
 
       if ! is_array "${2}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups with VGA for "\
+        log_stderr "Missing reference of array of IOMMU groups with VGA for "\
           "Host machine."
 
         return 1
       fi
 
       if ! is_array "${1}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for Host "\
+        log_stderr "Missing reference of array of IOMMU groups for Host "\
           "machine."
 
         return 1
@@ -142,26 +142,26 @@
       log_stdout "${0}: ${FUNCNAME}"
 
       if ! is_array "${5}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for with VGA"\
+        log_stderr "Missing reference of array of IOMMU groups for with VGA"\
           "for VFIO."
 
         return 1
       fi
 
       if ! is_array "${4}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for VFIO."
+        log_stderr "Missing reference of array of IOMMU groups for VFIO."
         return 1
       fi
 
       if ! is_array "${3}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups with VGA for "\
+        log_stderr "Missing reference of array of IOMMU groups with VGA for "\
           "Host machine."
 
         return 1
       fi
 
       if ! is_array "${2}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for Host "\
+        log_stderr "Missing reference of array of IOMMU groups for Host "\
           "machine."
 
         return 1
@@ -199,11 +199,11 @@
       log_stdout "${0}: ${FUNCNAME}"
 
       if ! is_array "${3}" &> /dev/null; then
-        print_error_to_log "Missing reference of IOMMU groups with VGA array."
+        log_stderr "Missing reference of IOMMU groups with VGA array."
       fi
 
       if ! is_array "${2}" &> /dev/null; then
-        print_error_to_log "Missing reference of IOMMU groups array."
+        log_stderr "Missing reference of IOMMU groups array."
       fi
 
       if ! is_iommu_group_id_valid "${1}"; then
@@ -238,26 +238,26 @@
       log_stdout "${0}: ${FUNCNAME}"
 
       if ! is_array "${5}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for with VGA"\
+        log_stderr "Missing reference of array of IOMMU groups for with VGA"\
           "for VFIO."
 
         return 1
       fi
 
       if ! is_array "${4}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for VFIO."
+        log_stderr "Missing reference of array of IOMMU groups for VFIO."
         return 1
       fi
 
       if ! is_array "${3}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups with VGA for "\
+        log_stderr "Missing reference of array of IOMMU groups with VGA for "\
           "Host machine."
 
         return 1
       fi
 
       if ! is_array "${2}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for Host "\
+        log_stderr "Missing reference of array of IOMMU groups for Host "\
           "machine."
 
         return 1
@@ -303,26 +303,26 @@
       log_stdout "${0}: ${FUNCNAME}"
 
       if ! is_array "${5}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for with VGA"\
+        log_stderr "Missing reference of array of IOMMU groups for with VGA"\
           "for VFIO."
 
         return 1
       fi
 
       if ! is_array "${4}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for VFIO."
+        log_stderr "Missing reference of array of IOMMU groups for VFIO."
         return 1
       fi
 
       if ! is_array "${3}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups with VGA for "\
+        log_stderr "Missing reference of array of IOMMU groups with VGA for "\
           "Host machine."
 
         return 1
       fi
 
       if ! is_array "${2}" &> /dev/null; then
-        print_error_to_log "Missing reference of array of IOMMU groups for Host "\
+        log_stderr "Missing reference of array of IOMMU groups for Host "\
           "machine."
 
         return 1
@@ -335,11 +335,13 @@
       for this_iommu_group_id in \
         ${SRC_IOMMU_GROUP_VALIDATION_ARR_IOMMU_GROUP_ID[@]}; do
         if [[ "${this_iommu_group_id}" -ne "${iommu_group_id}" ]]; then
-          if ! add_iommu_group_to_either_with_or_without_vga_array "${1}" "${2}" "${3}"; then
+          if ! add_iommu_group_to_either_with_or_without_vga_array "${1}" "${2}" \
+            "${3}"; then
             return 1
           fi
         else
-          if ! add_iommu_group_to_either_with_or_without_vga_array "${1}" "${4}" "${5}"; then
+          if ! add_iommu_group_to_either_with_or_without_vga_array "${1}" "${4}" \
+            "${5}"; then
             return 1
           fi
         fi
@@ -437,7 +439,7 @@
       log_stdout "${0}: ${FUNCNAME}"
 
       if ! is_enum "${2}" &> /dev/null; then
-        print_error_to_log "Missing reference to array of IOMMU group IDs."
+        log_stderr "Missing reference to array of IOMMU group IDs."
         return 1
       fi
 
@@ -551,7 +553,7 @@
       log_stdout "${0}: ${FUNCNAME}"
 
       if ! is_array "${1}" &> /dev/null; then
-        print_error_to_log "Missing array for IOMMU group IDs."
+        log_stderr "Missing array for IOMMU group IDs."
         return 1
       fi
 
