Added vars functions.

diff --git a/bashlib/bin/bashlib-vars b/bashlib/bin/bashlib-vars
--- a/bashlib/bin/bashlib-vars
+++ b/bashlib/bin/bashlib-vars
@@ -13,6 +13,36 @@
 # </code>
 
 # <code>
+    # <summary> Find line in array. </summary>
+    # <paramref name=$1> string: the name of the array </paramref>
+    # <param name=$2> string: the line </param>
+    # <returns> exit code </returns>
+    function FindLineInArray
+    {
+        IsString $2 || return $?
+        IsArray $1 || return $?
+
+        # <params>
+        local readonly var_command='declare -a arr=( ${'$1'[@]} )'
+        # </params>
+
+        eval "${var_command}" || return 1
+
+        # if [[ -z $( echo "${arr[@]}" | grep -iF $2 ) ]]; then
+        #     return 1
+        # fi
+
+        # return 0
+
+        for var_element in "${arr[@]}"; do
+            if [[ "${var_element}" == $2 ]]; then
+                return 0
+            fi
+        done
+
+        return 1
+    }
+
     # <summary> Check if the array is empty. </summary>
     # <paramref name=$1> string: name of the array </paramref>
     # <returns> exit code </returns>
@@ -137,6 +167,37 @@
 
         echo
         eval "${var_print_array}" || return 1
+        return 0
+    }
+
+    # <summary> Replace line in an array. </summary>
+    # <paramref name=$1> string: the name of the array </paramref>
+    # <param name=$2> string: the line </param>
+    # <param name=$3> string: the new line </param>
+    # <returns> exit code </returns>
+    function ReplaceLineInArray
+    {
+        IsString $3 || return $?
+        FindLineInArray $1 $2 || return $?
+
+        # <params>
+        local readonly var_get_param='declare arr_replace_line=( ${!'$1'[@]} )'
+        local readonly var_set_param="$1"'=( "${arr_replace_line[@]}" )'
+        # </params>
+
+        eval "${var_get_param}" || return 1
+
+        for int_key in "${!arr_replace_line[@]}"; do
+            local var_line="${arr_replace_line[$int_key]}"
+
+            case "${var_line}" in
+                $2* )
+                    arr_replace_line[$int_key]="$3"
+                    ;;
+            esac
+        done
+
+        eval "${var_set_param}" || return 1
         return 0
     }
 # </code>
